/** Continuous candidate biology -> sensing -> choice -> execution -> learning. */
import {advanceBiology,defaultConstitution,initialBiology,emptyPhysicalInput,senseBiology,physicalChallenges,lattice,type BiologyState,type Constitution,type BiologyLaw,type PhysicalInput,type SensorPolicy} from './biologicalDynamics';
import {biologicalChoice,type Ground} from './biologicalChoice';
import {canonicalEncode,list,text,unsigned} from '../substrate/canonicalEncoding';
import {decodeReceiving} from './receivingCodecs';
import {dataItems,dataUnsigned} from '../campaign2/canonicalData';
export const INTEGRATION_VERSION='biological-integration/0.1-candidate';
export const ACTIONS=['drug','meal','drink','sleep','relax','work','alternative','withhold'] as const;
export type Action=typeof ACTIONS[number];
export const DOMAINS=['pleasure','withdrawal','hunger','thirst','sleep','pain','stress','harm'] as const;
export type Domain=typeof DOMAINS[number];
export const INTEGRATION_LAWS=['Full','Latest','NoLearning','NoControl','NoAdaptation','NoRecovery','KnownAccess','NoReliefLearning','CueHabituation','BaselinePleasure'] as const;
export type IntegrationLaw=typeof INTEGRATION_LAWS[number];
export interface BiologicalFrame {available:Action[];cue:boolean;practice:Action|null;adoptProtection:boolean;adoptWork:boolean;reminder:boolean;support:boolean;load:number;interference:boolean;sensor:SensorPolicy;receipt:boolean;external:PhysicalInput;}
export interface IntegrationConfig {constitution:Constitution;initial:BiologyState;worldLaw:BiologyLaw;catalog:Record<Action,PhysicalInput>;competence:number;controlThreshold:number;protectionImportance:number;workImportance:number;}
export function biologicalConfig():IntegrationConfig {const constitution=defaultConstitution(),catalog=Object.fromEntries(ACTIONS.map(a=>[a,emptyPhysicalInput()])) as Record<Action,PhysicalInput>;
 catalog.drug={...emptyPhysicalInput(),injury:30,intoxicant:160,stimuli:[{channel:'reward',exposure:'drug',dose:600,direction:1}]};catalog.meal={...emptyPhysicalInput(),fuel:600,stimuli:[{channel:'reward',exposure:'meal',dose:100,direction:1}]};catalog.drink={...emptyPhysicalInput(),water:650};catalog.sleep={...emptyPhysicalInput(),asleep:true};catalog.relax={...emptyPhysicalInput(),stimuli:[{channel:'stress',exposure:'relax',dose:350,direction:-1}]};catalog.alternative={...emptyPhysicalInput(),stimuli:[{channel:'reward',exposure:'alternative',dose:250,direction:1}]};return {constitution,initial:initialBiology(constitution),worldLaw:'Full',catalog,competence:850,controlThreshold:300,protectionImportance:900,workImportance:400};}
const clone=<T>(v:T):T=>structuredClone(v),clamp=(v:number)=>Math.max(0,Math.min(1000,v)),mul=(a:number,b:number)=>lattice(BigInt(a)*BigInt(b),1000n);
type View=ReturnType<typeof senseBiology>;
type Sample={at:number;action:Action;cue:boolean;outcomes:Record<Domain,number|null>};
function observation(body:BiologyState,c:Constitution,policy:SensorPolicy,law:IntegrationLaw):View {const view=senseBiology(body,c,policy);if(law!=='BaselinePleasure'&&view.pleasure!==null){const gap=Math.max(0,body.channels.reward.level-Math.min(1000,c.channels.reward.baseline+body.channels.reward.displacement));view.pleasure=Math.floor(gap/policy.resolution)*policy.resolution;}return view;}
function experienced(before:View,after:View):Record<Domain,number|null>{const diff=(k:keyof View)=>before[k]===null||after[k]===null?null:Math.max(0,before[k]!-after[k]!);const pain=before.pain===null||after.pain===null?null:Math.max(0,after.pain-before.pain),intox=before.intoxication===null||after.intoxication===null?null:Math.max(0,after.intoxication-before.intoxication);return {pleasure:after.pleasure,withdrawal:diff('withdrawalReward'),hunger:diff('hunger'),thirst:diff('thirst'),sleep:diff('sleepiness'),pain:diff('pain'),stress:diff('stress'),harm:pain===null||intox===null?null:Math.max(pain,intox)};}
function estimates(history:Sample[],action:Action,law:IntegrationLaw){return Object.fromEntries(DOMAINS.map(domain=>{const xs=history.filter(s=>s.action===action&&s.outcomes[domain]!==null).map(s=>s.outcomes[domain]!);return [domain,!xs.length?null:law==='Latest'?xs.at(-1)!:lattice(BigInt(xs.reduce((a,b)=>a+b,0)),BigInt(xs.length))];})) as Record<Domain,number|null>;}
function mergeInput(a:PhysicalInput,b:PhysicalInput):PhysicalInput {const stimuli=clone(a.stimuli);for(const x of b.stimuli){const old=stimuli.find(y=>y.channel===x.channel&&y.exposure===x.exposure);if(old)throw Error('BIO_INTEGRATION_EXPOSURE_COLLISION');stimuli.push(clone(x));}return {fuel:clamp(a.fuel+b.fuel),water:clamp(a.water+b.water),injury:clamp(a.injury+b.injury),intoxicant:clamp(a.intoxicant+b.intoxicant),asleep:a.asleep||b.asleep,stimuli};}
export function createBiologicalRun(law:IntegrationLaw,frames:readonly BiologicalFrame[],config=biologicalConfig(),seed=7){
 if(!INTEGRATION_LAWS.includes(law)||!Array.isArray(frames)||frames.length<12||frames.length>96)throw Error('BIO_INTEGRATION_PROFILE');const originals=clone(frames),c=clone(config);
 for(const f of originals){if(!Array.isArray(f.available)||new Set(f.available).size!==f.available.length||f.available.some(a=>!ACTIONS.includes(a))||f.practice!==null&&!ACTIONS.includes(f.practice)||!Number.isInteger(f.load)||f.load<0||f.load>1000||['cue','adoptProtection','adoptWork','reminder','support','interference','receipt'].some(k=>typeof f[k as keyof BiologicalFrame]!=='boolean'))throw Error('BIO_INTEGRATION_FRAME');advanceBiology(c.initial,c.constitution,f.external,c.worldLaw);senseBiology(c.initial,c.constitution,f.sensor);}
 for(const a of ACTIONS)advanceBiology(c.initial,c.constitution,c.catalog[a],c.worldLaw);for(const n of [c.competence,c.controlThreshold,c.protectionImportance,c.workImportance])if(!Number.isInteger(n)||n<0||n>1000)throw Error('BIO_INTEGRATION_CONFIG');
 if(law==='NoAdaptation')for(const p of Object.values(c.constitution.channels)){p.toleranceGain=0;p.sensitizationGain=0;p.displacementGain=0;}
 type Row={at:number;before:View;after:View|null;protection:boolean;work:boolean;maintained:boolean;control:number|null;inhibited:boolean;beliefs:Record<Action,Record<Domain,number|null>>;habit:Record<Action,number>;affect:{pleasure:number|null;distress:number|null;threat:number|null};grounds:Ground[];choice:Awaited<ReturnType<typeof biologicalChoice>>;intent:Action|null;expression:string;receipt:Record<Domain,number|null>|null;errors:Partial<Record<Domain,number>>};
 let state=clone(c.initial),history:Sample[]=[],rows:Row[]=[],world:{at:number;state:BiologyState;terms:Record<string,unknown>;executed:Action|null;challenge:number}[]=[],protection=false,work=false,maintained=false,at=0,busy=false;
 const observerView=()=>clone({at,history,protection,work,maintained,rows}),snapshot=()=>clone({...observerView(),state,world}),save=()=>canonicalEncode(list([text(INTEGRATION_VERSION),text(law),text(JSON.stringify(config)),text(JSON.stringify(originals)),unsigned(seed),unsigned(at),text(JSON.stringify(snapshot()))]));
 return Object.freeze({observerView,snapshot,save,async step(fault?:'after-choice'|'before-commit'){
  if(busy)throw Error('BIO_INTEGRATION_CONCURRENT');if(at===originals.length)return false;busy=true;try{
   const f=originals[at],tick=at+1,before=observation(state,c.constitution,f.sensor,law),nextProtection=protection||f.adoptProtection,nextWork=work||f.adoptWork,nextMaintained=(nextProtection||nextWork)&&(f.reminder||maintained&&f.support),beliefs=Object.fromEntries(ACTIONS.map(a=>[a,estimates(history,a,law)])) as Record<Action,Record<Domain,number|null>>,habit=Object.fromEntries(ACTIONS.map(a=>[a,history.filter(s=>s.action===a&&s.cue===f.cue).reduce((h,s)=>lattice(BigInt(h+((s.outcomes.pleasure??0)>0||(s.outcomes.withdrawal??0)>0?1000:0)),2n),0)])) as Record<Action,number>;
   const known=[before.sleepiness,before.stress,before.intoxication,before.arousal].every(x=>x!==null),control=known?clamp(1000-lattice(BigInt(before.sleepiness!+before.stress!+before.intoxication!+Math.abs(before.arousal!-500)),2n)-f.load):null,inhibited=law!=='NoControl'&&nextProtection&&nextMaintained&&control!==null&&control>=c.controlThreshold;
   const options=f.available.filter(a=>f.practice?a===f.practice:(!(a==='drug'&&inhibited)&&(a==='work'||a==='withhold'||law==='KnownAccess'||habit[a]>=500||DOMAINS.some(d=>(beliefs[a][d]??0)>0))));
   const grounds:Ground[]=[];const add=(option:Action,domain:string,strength:number)=>{if(strength)grounds.push({option,domain,strength:Math.max(-1000,Math.min(1000,strength))});};
   for(const a of options){if(f.practice){add(a,'practice',1000);continue;}const b=beliefs[a],cueCount=history.filter(s=>s.action===a&&s.cue===f.cue).length,reward=law==='CueHabituation'?lattice(BigInt(b.pleasure??0)*4n,BigInt(4+cueCount)):b.pleasure??0;add(a,'pleasure',reward);
    for(const [domain,pressure] of [['withdrawal',before.withdrawalReward],['hunger',before.hunger],['thirst',before.thirst],['sleep',before.sleepiness],['pain',before.pain],['stress',before.stress]] as const)if(pressure!==null&&!(domain==='withdrawal'&&law==='NoReliefLearning'))add(a,domain,mul(pressure,b[domain]??0));
    if(nextProtection&&nextMaintained){add(a,'protection',-mul(c.protectionImportance,b.harm??0));if(a==='withhold')add(a,'protective-goal',c.protectionImportance);}if(a==='work'&&nextWork&&nextMaintained)add(a,'work-goal',c.workImportance);
   }
   if(grounds.length>32)throw Error('BIO_INTEGRATION_GROUND_LIMIT');const choice=await biologicalChoice(options,grounds,tick,seed),intent=choice.chosen as Action|null,expression=JSON.stringify({at:tick,intent,choice,grounds});if(fault==='after-choice')throw Error('BIO_INTEGRATION_INJECTED');
   const challenge=physicalChallenges(state,c.constitution).execution,executed=intent&&!f.interference&&challenge<c.competence?intent:null,input=mergeInput(executed?c.catalog[executed]:emptyPhysicalInput(),f.external),transition=advanceBiology(state,c.constitution,input,law==='NoRecovery'?'NoRecovery':c.worldLaw),after=observation(transition.state,c.constitution,f.sensor,law),receipt=intent&&f.receipt?experienced(before,after):null,errors:Partial<Record<Domain,number>>={};
   if(intent&&receipt)for(const d of DOMAINS)if(receipt[d]!==null&&beliefs[intent][d]!==null)errors[d]=receipt[d]!-beliefs[intent][d]!;
   const nextHistory=clone(history);if(intent&&receipt&&law!=='NoLearning')nextHistory.push({at:tick,action:intent,cue:f.cue,outcomes:{...receipt,...(law==='NoReliefLearning'?{withdrawal:null}:{})}});
   const vulnerability=before.pain===null?null:clamp(500+lattice(BigInt(before.pain),2n)),threat=beliefs.drug.harm===null||vulnerability===null?null:mul(mul(beliefs.drug.harm,c.protectionImportance*(nextProtection?1:0)),vulnerability),distress=before.withdrawalReward===null||before.stress===null||before.pain===null?null:Math.max(before.withdrawalReward,before.stress,before.pain);
   const row:Row={at:tick,before,after:f.receipt?after:null,protection:nextProtection,work:nextWork,maintained:nextMaintained,control,inhibited,beliefs,habit,affect:{pleasure:before.pleasure,distress,threat},grounds,choice,intent,expression,receipt,errors};
   if(fault==='before-commit')throw Error('BIO_INTEGRATION_INJECTED');state=transition.state;history=nextHistory;rows=[...rows,row];world=[...world,{at:tick,state:clone(state),terms:transition.terms,executed,challenge}];at=tick;protection=nextProtection;work=nextWork;maintained=nextMaintained;return true;
  }finally{busy=false;}
 }});
}
export async function restoreBiologicalRun(law:IntegrationLaw,frames:readonly BiologicalFrame[],saved:Uint8Array,config=biologicalConfig(),seed=7){const v=dataItems(decodeReceiving(saved),'list');if(v.length!==7)throw Error('BIO_INTEGRATION_SAVE');const count=dataUnsigned(v[5]);if(count>BigInt(frames.length))throw Error('BIO_INTEGRATION_PREFIX');const run=createBiologicalRun(law,frames,config,seed);for(let i=0n;i<count;i++)await run.step();const actual=run.save();if(actual.length!==saved.length||!actual.every((b,i)=>b===saved[i]))throw Error('BIO_INTEGRATION_MISMATCH');return run;}
