import {it,expect} from 'vitest';
import {createAffectRetrievalRun as create,restoreAffectRetrievalRun as restore,affectRetrievalGain,LAWS,type Law} from '../campaign3/affectRetrieval';
import {affectRetrievalCases as cases} from './affectRetrievalFixtures';
async function run(name:keyof ReturnType<typeof cases>='high',law:Law='UncontrolledGain'){const r=create(law,cases()[name]);while(await r.step()){}return r;}
it('actual completed affect reverses the published winner with identical prior memory and history',async()=>{const a=(await run()).snapshot(),b=(await run('low')).snapshot(),x=a.rows[3],y=b.rows[3];expect(a.rows.slice(0,2)).toEqual(b.rows.slice(0,2));expect(x.memoryBefore).toEqual(y.memoryBefore);expect(x.historyBefore).toEqual(y.historyBefore);expect(x.historyBefore).toEqual([{id:1,times:[2]},{id:2,times:[3]}]);expect(x.selected).toBe(1);expect(y.selected).toBe(2);expect(x.gain).toBe('2/1');expect(y.gain).toBe('1/1');expect(x.scores[0].score).toBe('7/12');expect(y.scores[0].score).toBe('11/24');expect(a.memory).toEqual(b.memory);});
it('NoFeedback removes winner change while preserving completed affect and memory',async()=>{const a=(await run()).snapshot(),b=(await run('high','NoFeedback')).snapshot();expect(a.rows[2].affectAfter).toEqual(b.rows[2].affectAfter);expect(a.memory).toEqual(b.memory);expect(b.rows[3].selected).toBe(2);});
it('candidate gains remain distinct; full control removes uncontrolled but not exposure response',async()=>{expect((await run('controlled')).snapshot().rows[3].selected).toBe(2);expect((await run('controlled','ExposureGain')).snapshot().rows[3].selected).toBe(1);expect((await run('high','HalfGain')).snapshot().rows[3].gain).toBe('3/2');});
it('current affect and current report cannot alter retrieval using prior completed output',async()=>{const a=(await run()).snapshot(),b=(await run('currentContext')).snapshot(),c=(await run('currentReport')).snapshot();expect(a.rows[3].selected).toBe(b.rows[3].selected);expect(a.rows[3].priorAffect).toEqual(b.rows[3].priorAffect);expect(a.rows[3].selected).toBe(c.rows[3].selected);expect((await run('lateAffect')).snapshot().rows[3].selected).toBe(2);expect(()=>affectRetrievalGain({at:4,status:'Known',exposure:'1/1',uncontrolled:'1/1'},4,'UncontrolledGain')).toThrow('AR_PRIOR_ONLY');});
it('unknown factors use explicit unavailable baseline and do not imply known zero',async()=>{for(const name of ['unknownControl','unknownBelief','deniedContext'] as const){const r=(await run(name)).snapshot();expect(r.rows[2].affectAfter!.status).toBe('Unavailable');expect(r.rows[3].gain).toBe('1/1');expect(r.rows[3].selected).toBe(2);}expect((await run('low')).snapshot().rows[2].affectAfter!.status).toBe('Known');});
it('hidden truth and denied report changes preserve whole safe state for all laws',async()=>{for(const law of LAWS){expect((await run('high',law)).observerView()).toEqual((await run('hidden',law)).observerView());expect((await run('deniedReport',law)).observerView()).toEqual((await run('deniedReportChanged',law)).observerView());}});
it('affect cannot manufacture a cue or association; actual publication alone updates history',async()=>{const a=(await run('absentCue')).snapshot(),b=(await run('emptyGraph')).snapshot();expect(a.rows[3].selected).toBeNull();expect(a.history).toEqual([{id:1,times:[2]},{id:2,times:[3]}]);expect(b.rows[3].selected).toBe(2);expect((await run()).snapshot().history).toEqual([{id:1,times:[2,4]},{id:2,times:[3]}]);});
it('all candidate laws restore every whole prefix and successor exactly',async()=>{for(const law of LAWS){const r=create(law,cases().high);for(let i=0;i<=4;i++){const q=await restore(law,cases().high,i,r.save());expect(q.save()).toEqual(r.save());expect(await q.step()).toBe(await r.step());expect(q.save()).toEqual(r.save());}}},60000);
it('faults and overlap preserve committed history and one-use publication retry',async()=>{for(const fault of ['after-publication','before-commit'] as const){const r=create('UncontrolledGain',cases().high);await r.step();await r.step();await r.step();const before=r.save();await expect(r.step(fault)).rejects.toThrow('AR_INJECTED');expect(r.save()).toEqual(before);const q=await restore('UncontrolledGain',cases().high,3,before),pending=r.step();await expect(r.step()).rejects.toThrow('AR_CONCURRENT');await pending;await q.step();expect(r.save()).toEqual(q.save());}});
it('strict copied sources and full save commitments reject forgery',async()=>{const f=cases().high,r=create('UncontrolledGain',f);f[0].display=false;await r.step();expect(r.snapshot().memory[0].display).toBe(true);const bad=cases().high;Object.defineProperty(bad[0],'report',{get(){throw Error('GETTER_RAN');}});expect(()=>create('UncontrolledGain',bad)).toThrow('AR_DATA');const saved=r.save();saved[saved.length-1]^=1;await expect(restore('UncontrolledGain',cases().high,1,saved)).rejects.toThrow('AR_SAVE_MISMATCH');await expect(restore('UncontrolledGain',cases().hidden,1,r.save())).rejects.toThrow('AR_SAVE_MISMATCH');});
