import {describe,it,expect} from 'vitest';
import {ExactRational as Q} from '../substrate/exactMath';
import {assessContrastiveAttribution,type AttributionTrial} from '../campaign3/contrastiveAttribution';
import {adoptMaintenanceGoal,settleMaintenanceGoal} from '../campaign3/bodilyMaintenanceGoal';
import {qualifyGoalOutcome} from '../campaign3/goalOutcomeQualification';
const interval=(a:bigint,b:bigint)=>({lower:Q.of(a),upper:Q.of(b)});
describe('source grouping and historical concern expressibility witnesses',()=>{
 it('SGR-A: identical individual observation multiset admits different verdicts under different pairings',()=>{const before=interval(20n,21n),high=interval(30n,31n),low=interval(20n,21n),motion:AttributionTrial['motion'][]=[[[0,0],[1,0]],[[0,0],[0,0]],[[0,0],[1,0]],[[0,0],[0,0]]];const make=(after:AttributionTrial['after'][])=>motion.map((m,i)=>({motion:m,before,after:after[i]}));const a=[high,low,high,low],b=[low,high,low,high];const bag=(xs:AttributionTrial['after'][])=>xs.map(x=>`${x!.lower.numerator}/${x!.lower.denominator}:${x!.upper.numerator}/${x!.upper.denominator}`).sort();expect(bag(a)).toEqual(bag(b));expect(assessContrastiveAttribution(make(a)).kind).toBe('Supported');expect(assessContrastiveAttribution(make(b)).kind).toBe('Unavailable');});
 it('SGR-B: later current-goal recomputation loses the lawful consequence-time qualification',()=>{const bounds=interval(0n,100n),domains=new Map([['alpha',{kind:'MetricInterval' as const,bounds}]]),goals=adoptMaintenanceGoal([],{character:'a',goal:'maintain',signal:'alpha',desired:interval(30n,40n),adoptedAt:0n,activeFrom:0n,expiresAt:100n},new Map([['alpha',bounds]]));const input={state:goals,character:'a',goal:'maintain',signal:'alpha',now:20n,before:interval(20n,21n),after:interval(30n,31n),domains};const historical=qualifyGoalOutcome(input),later=settleMaintenanceGoal(goals,'a','maintain',40n,'Withdraw',new Map([['alpha',bounds]]));expect(historical.kind).toBe('Qualifies');expect(qualifyGoalOutcome({...input,state:later,now:60n})).toMatchObject({kind:'QualificationUnavailable',assessment:{reason:'Withdrawn'}});expect(historical).toMatchObject({kind:'Qualifies',assessment:{at:20n,concern:{status:'Open'}}});});
});
