import {it,expect} from 'vitest';
import {ExactRational as Q} from '../substrate/exactMath';
import {prepareAttributionProduction as prepare,produceAttributionResult as produce,closeAttributionProduction,type AttributionProductionContext} from '../campaign3/attributionProduction';
import type {prepareFocalPositionPairAttributionUse,AttributionField,PositionPairTrial} from '../campaign3/retainedAttributionUse';
import type {AttributionTrial} from '../campaign3/contrastiveAttribution';
const context=():AttributionProductionContext=>({observer:'observer/a',character:'character/a',at:20n,focal:{observer:'observer/a',consequence:90n,sourceAt:16n}});
function operands(missing=false):Parameters<typeof prepareFocalPositionPairAttributionUse>{
 const memory:{id:bigint;kind:'EventContinuant'|'Interoceptive';acquiredAt:bigint;units:{key:string;views:Uint8Array[];useProtection:boolean}[]}[]=[],trials:PositionPairTrial[]=[];
 for(let i=0;i<4;i++){const base=i*4,stroke=i%2===0,ids=[1,2,3,4].map(x=>BigInt(base+x));for(let j=0;j<4;j++)memory.push({id:ids[j],kind:j<2?'EventContinuant':'Interoceptive',acquiredAt:BigInt(base+j+1),units:[{key:'child',views:[new Uint8Array(j<2?[base+j+1,j===1&&stroke?1:0,0]:j===2?[missing&&i===0?255:20,21]:stroke?[30,31]:[20,21])],useProtection:false}]});const address=(j:number)=>({address:{acquisition:ids[j],unit:'child'},view:0});trials.push({motion:{kind:'RetainedPositionPair',start:address(0),end:address(1)},before:{kind:'Retained',...address(2)},after:{kind:'Retained',...address(3)}});}
 const project=<K extends AttributionField>(b:Uint8Array,k:K):AttributionTrial[K]=>{if(k==='motion')throw Error('interval');return (b[0]===255?null:{lower:Q.of(BigInt(b[0])),upper:Q.of(BigInt(b[1]))}) as AttributionTrial[K];};
 return [{memory,now:20n,admitted:memory.map(a=>({acquisition:a.id,unit:'child'})),trials,focalTrial:0},project,b=>({at:BigInt(b[0]),position:[b[1],b[2]]})];
}
it('AP-A: actual supported calculation produces one narrow result and only the focal consumed end child',()=>{let calls=0;const args=operands(),before=structuredClone(args[0]),r=produce(prepare(context(),()=>args),()=>{calls++;return 100n;});expect(calls).toBe(1);expect(args[0]).toEqual(before);if(r.kind!=='Result')throw Error('result');expect(r.result).toMatchObject({resultId:100n,disposition:'Supported',targets:[{acquisition:2n,unit:'child'}]});expect(r.result.consumed).toHaveLength(16);expect(Object.keys(r.result).sort()).toEqual(['resultId','observer','character','consequence','at','transformationVersion','disposition','consumed','targets'].sort());});
it('AP-B: missing focal does no work or allocation; present incomplete grouping has its own unavailable result',()=>{let calls=0;expect(produce(prepare({...context(),focal:null},()=>{calls++;return operands();}),()=>{calls++;return 1n;})).toEqual({kind:'NoConsequence'});expect(calls).toBe(0);const r=produce(prepare(context(),()=>null),()=>5n);expect(r).toMatchObject({kind:'Result',result:{resultId:5n,disposition:'Unavailable',consumed:[],targets:[]}});});
it('AP-C: actual unavailable preserves partial semantic consumption without a target',()=>{const r=produce(prepare(context(),()=>operands(true)),()=>100n);if(r.kind!=='Result')throw Error('result');expect(r.result.disposition).toBe('Unavailable');expect(r.result.targets).toEqual([]);expect(r.result.consumed.map(c=>c.acquisition)).toEqual([1n,2n,3n]);});
it('AP-D: stationary focal cannot borrow the two stroke trials’ support',()=>{const args=operands();args[0]={...args[0],focalTrial:1};const r=produce(prepare(context(),()=>args),()=>100n);expect(r).toMatchObject({kind:'Result',result:{disposition:'Unavailable',targets:[]}});});
it('AP-E: foreign/current/future focal and wrong evaluation instant reject before result allocation',()=>{let calls=0;for(const focal of [{observer:'foreign',consequence:1n,sourceAt:1n},{observer:'observer/a',consequence:1n,sourceAt:20n},{observer:'observer/a',consequence:-1n,sourceAt:1n}])expect(()=>prepare({...context(),focal},()=>{calls++;return operands();})).toThrow();expect(calls).toBe(0);const args=operands();args[0]={...args[0],now:19n};expect(()=>prepare(context(),()=>args)).toThrow('INSTANT');});
it('AP-F: frozen result and one-use capabilities exclude mutation, forgery, replay and failed allocation retry',()=>{const c=context(),args=operands(),v=prepare(c,()=>args);Object.assign(c,{character:'changed'});Object.assign(args[0].trials[0].motion.end.address,{acquisition:6n});expect(()=>produce({...v},()=>1n)).toThrow('VIEW');const r=produce(v,()=>100n);expect(r).toMatchObject({kind:'Result',result:{character:'character/a',targets:[{acquisition:2n,unit:'child'}]}});expect(()=>produce(v,()=>101n)).toThrow('VIEW');const bad=prepare(context(),()=>null);expect(()=>produce(bad,()=>-1n)).toThrow('ALLOCATION');expect(()=>produce(bad,()=>1n)).toThrow('VIEW');const closed=prepare(context(),()=>null);closeAttributionProduction(closed);expect(()=>produce(closed,()=>1n)).toThrow('VIEW');});
