import {biologicalConfig,type BiologicalFrame,type Action} from '../campaign3/biologicalIntegration';
import {emptyPhysicalInput} from '../campaign3/biologicalDynamics';
export function biologicalFrames(length=48):BiologicalFrame[]{return Array.from({length},(_,i)=>({available:['drug','alternative','work','withhold'] as Action[],cue:true,practice:i<8?'drug':null,adoptProtection:i===24,adoptWork:i===24,reminder:i===24,support:true,load:i>=32&&i<40?800:0,interference:false,sensor:{resolution:10,denied:[]},receipt:true,external:emptyPhysicalInput()}));}
export function addictionConfig(){const c=biologicalConfig();c.constitution.fuelDrain=0;c.constitution.waterDrain=0;c.constitution.sleepAccumulation=0;c.constitution.nightDrive=0;c.constitution.healing=30;c.constitution.clearance=160;c.constitution.channels.reward={...c.constitution.channels.reward,decay:850,toleranceGain:250,toleranceRecovery:10,displacementGain:180,displacementRecovery:12,satiationGain:150,satiationRecovery:100};c.catalog.drug.injury=20;c.catalog.drug.intoxicant=100;return c;}
export function biologicalScenarios(){
 const main=biologicalFrames(),config=addictionConfig(),scenario=(frames=main,c=config)=>({frames:structuredClone(frames),config:structuredClone(c)}),out:Record<string,ReturnType<typeof scenario>>={main:scenario(),noLoad:scenario(main.map(f=>({...f,load:0}))),noCue:scenario(main.map((f,i)=>({...f,cue:i<8}))),noFeedback:scenario(main.map(f=>({...f,receipt:false}))),interference:scenario(main.map((f,i)=>({...f,interference:i>=8}))),recovery:scenario(biologicalFrames(96).map((f,i)=>({...f,load:0,available:i>=24?['work','withhold'] as Action[]:f.available}))),alternative:scenario(main.map((f,i)=>({...f,practice:i===18||i===20?'alternative':f.practice,available:i>=24?['alternative','work','withhold'] as Action[]:f.available}))),unavailable:scenario(main.map((f,i)=>({...f,available:i>=24?['alternative','work','withhold'] as Action[]:f.available})))};
 const c=biologicalConfig();c.initial.fuel=100;c.initial.water=100;c.initial.sleepDebt=700;c.initial.channels.stress.level=900;c.constitution.channels.stress.decay=50;const practice:Action[]=['meal','drink','sleep','relax','alternative','drug'];const frames=biologicalFrames(24).map((f,i)=>({...f,available:['meal','drink','sleep','relax','alternative','work','withhold'] as Action[],practice:i<5?practice[i]:null,adoptWork:i===5,reminder:i===5}));out.resources=scenario(frames,c);
 for(const [name,edit] of [['noHunger',(x:typeof c)=>{x.initial.fuel=1000;x.constitution.fuelDrain=0;}],['noThirst',(x:typeof c)=>{x.initial.water=1000;x.constitution.waterDrain=0;}],['rested',(x:typeof c)=>{x.initial.sleepDebt=0;x.constitution.sleepAccumulation=0;x.constitution.nightDrive=0;}],['calm',(x:typeof c)=>{x.initial.channels.stress.level=0;}],['highArousal',(x:typeof c)=>{x.initial.channels.arousal.level=1000;x.constitution.channels.arousal.decay=0;}],['injury',(x:typeof c)=>{x.initial.damage=900;x.constitution.healing=0;x.competence=300;}],['intoxicated',(x:typeof c)=>{x.initial.burden=900;x.constitution.clearance=0;x.competence=300;}]] as const){const changed=structuredClone(c);edit(changed);out[name]=scenario(frames,changed);}
 const network=structuredClone(c);network.constitution.network=[{from:'stress',to:'arousal',weight:300}];out.network=scenario(frames,network);const independent=structuredClone(network);independent.worldLaw='IndependentAxes';out.independent=scenario(frames,independent);
 const probeFrames=main.map((f,i)=>({...f,load:i>=32&&i<40?600:0,receipt:i<24}));out.controlProbe=scenario(probeFrames);
 const tired=structuredClone(config);tired.initial.sleepDebt=600;out.tiredControl=scenario(probeFrames,tired);
 const stressed=structuredClone(config);stressed.constitution.channels.stress.decay=0;out.stressControl=scenario(probeFrames.map((f,i)=>({...f,external:i===30?{...emptyPhysicalInput(),stimuli:[{channel:'stress',exposure:'threat',dose:600,direction:1}]}:f.external})),stressed);
 const activated=structuredClone(config);activated.constitution.channels.arousal.decay=0;out.arousalControl=scenario(probeFrames.map((f,i)=>({...f,external:i===30?{...emptyPhysicalInput(),stimuli:[{channel:'arousal',exposure:'stimulant',dose:500,direction:1}]}:f.external})),activated);
 const intox=structuredClone(config);intox.constitution.clearance=0;out.intoxicantControl=scenario(probeFrames.map((f,i)=>({...f,external:i===30?{...emptyPhysicalInput(),intoxicant:600}:f.external})),intox);
 const falseConfig=structuredClone(config);falseConfig.catalog.drug={...emptyPhysicalInput()};const falseFrames=biologicalFrames(16);out.noEffect=scenario(falseFrames,falseConfig);out.falsePleasure=scenario(falseFrames.map(f=>({...f,consequenceSensor:{resolution:10,denied:[],bias:{pleasure:500}}})),falseConfig);
 return out;
}
