import {describe,it,expect,vi} from 'vitest';
import * as schedulerModule from '../substrate/scheduler';
import * as runtimeModule from '../campaign2/adaptationRuntime';
import * as traceModule from '../substrate/trace';
import * as taskModule from '../campaign2/taskExecution';
import {canonicalEncode as enc,list,unsigned,signed,text,typedIdentifier} from '../substrate/canonicalEncoding';
import {AuthoritativeState} from '../substrate/state';
import {governedContentDefinitionId} from '../substrate/contentDefinitionId';
import {semanticReferentFromAuthoredContent} from '../substrate/referentOrigin';
import {taskModelReviewSource,type TaskSpecimen} from '../campaign2/taskModelReview';
import {taskRecord as r,decodeTask as decode} from '../campaign2/taskCodecs';
import {prepareTaskModel,createTaskRun,restoreTaskRun} from '../campaign2/taskFactory';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key} from '../campaign2/canonicalData';
const id=(n:number,s:string)=>typedIdentifier(n,text(s)),ref=(s:string)=>semanticReferentFromAuthoredContent(governedContentDefinitionId(s));
const C=ref('character/bridge-subject');
function fixture(times:number[]=[],adopted=['a','b'],D=0){const state=new AuthoritativeState([{path:{rootStateTypeId:268n,fieldId:1n,selectors:[{kind:'mapKey' as const,key:id(1000,'observer/bridge-subject')}]},value:r(267,[C])},...(D?[{path:{rootStateTypeId:302n,fieldId:3n,selectors:[{kind:'mapKey' as const,key:r(294,[C,id(1029,'variable/fixture-regulation')])}]},value:r(299,[signed(D)])}]:[]),...adopted.map(n=>({path:{rootStateTypeId:373n,fieldId:1n,selectors:[{kind:'mapKey' as const,key:r(371,[C,ref('content/task-'+n)])}]},value:r(372,[unsigned(1)])}))]);return {initialState:enc(state.canonicalValue()),orderedInputs:enc(list(times.map(t=>list([signed(t),unsigned(110),id(1001,'event/regulatory-diagnostic-probe'),r(333,[id(1027,'definition/regulatory-diagnostic-probe')]),list([])])))),runSeed:new Uint8Array(32)};}
function statuses(run:Awaited<ReturnType<typeof createTaskRun>>){return items(decode(run.snapshot().state),'set').map(v=>f(rec(v,151n),2n)).filter(v=>typeof v!=='boolean'&&v.kind==='record'&&v.schema.typeId===372n).map(v=>f(rec(v,372n),1n));}
describe('task-commitment/0.2-candidate runtime',()=>{
 for(const a of [false,true])for(const p of [false,true])for(const F of [false,true])for(const R of [false,true])for(const B of [false,true])for(const P of [false,true])it(`task fixed slots a=${a} p=${p} F=${F} R=${R} B=${B} P=${P}`,async()=>{const run=await createTaskRun(await prepareTaskModel(taskModelReviewSource('coincident',a,p,F,R,B,P)),fixture([4]));await run.settleNextInstant();expect(statuses(run)).toEqual([unsigned(a&&p?2:1),unsigned(a&&p?2:1)]);expect(items(decode(run.snapshot().trace),'list')).toHaveLength(13);await run.settleNextInstant();expect(statuses(run)).toEqual([unsigned(a&&p?2:3),unsigned(a&&p?2:3)]);expect(items(decode(run.snapshot().trace),'list')).toHaveLength(17);expect(f(rec(f(rec(decode(run.save()),132n),6n),131n),1n)).toEqual(unsigned(9));},20000);
 for(const specimen of ['overlapping','coincident','recurrence'] as TaskSpecimen[])it('private clocks terminate adopted tasks: '+specimen,async()=>{const run=await createTaskRun(await prepareTaskModel(taskModelReviewSource(specimen)),fixture());let count=0;while(await run.settleNextInstant())count++;expect(count).toBe(specimen==='coincident'?1:2);expect(statuses(run)).toEqual([unsigned(3),unsigned(3)]);expect(items(decode(run.snapshot().outputs),'list')).toEqual([]);expect(f(rec(f(rec(decode(run.save()),132n),6n),131n),1n)).toEqual(unsigned(0));},20000);
 it('one safe measurement satisfies two overlapping adopted tasks; later clocks preserve terminals',async()=>{const source=taskModelReviewSource(),data=fixture([4]),run=await createTaskRun(await prepareTaskModel(source),data);await run.settleNextInstant();expect(statuses(run)).toEqual([unsigned(2),unsigned(2)]);expect(items(decode(run.snapshot().trace),'list')).toHaveLength(13);const restored=await restoreTaskRun(source,{initialState:data.initialState,orderedInputs:data.orderedInputs,save:run.save()});while(await run.settleNextInstant()){await restored.settleNextInstant();expect(restored.save()).toEqual(run.save());}expect(statuses(run)).toEqual([unsigned(2),unsigned(2)]);},30000);
 it('unadopted tasks remain absent while both private clocks still execute',async()=>{const run=await createTaskRun(await prepareTaskModel(taskModelReviewSource()),fixture([],[]));while(await run.settleNextInstant()){}expect(statuses(run)).toEqual([]);expect(items(decode(run.snapshot().trace),'list')).toHaveLength(2);},20000);
 it('deadline excludes measurement for old instance and admits recurrent next instance',async()=>{const run=await createTaskRun(await prepareTaskModel(taskModelReviewSource('recurrence')),fixture([4]));await run.settleNextInstant();expect(statuses(run)).toEqual([unsigned(3),unsigned(2)]);},20000);
 it('suppressed M1 runs empty S padding; clocks still expire both commitments',async()=>{const run=await createTaskRun(await prepareTaskModel(taskModelReviewSource('coincident',true,false)),fixture([4]));await run.settleNextInstant();expect(statuses(run)).toEqual([unsigned(1),unsigned(1)]);await run.settleNextInstant();expect(statuses(run)).toEqual([unsigned(3),unsigned(3)]);},20000);
});
it.each([[-10,2,1],[-11,1,1],[10,2,2],[11,1,2]])('task exact inclusive interval D=%s',async(D,A,B)=>{const run=await createTaskRun(await prepareTaskModel(taskModelReviewSource()),fixture([4],['a','b'],D));await run.settleNextInstant();expect(statuses(run)).toEqual([unsigned(A),unsigned(B)]);},20000);
it('task forged association fails before any projection or prior access',async()=>{const original=taskModule.createTaskExecution;let checked=false;const spy=vi.spyOn(taskModule,'createTaskExecution').mockImplementation((...args)=>{const engine=original(...args);return {...engine,preflight(event,state){const reads=vi.spyOn(AuthoritativeState.prototype,'read');try{expect(()=>engine.preflight({...event,eventId:event.eventId+1000n},state)).toThrow('association');expect(reads).not.toHaveBeenCalled();checked=true;}finally{reads.mockRestore();}return engine.preflight(event,state);}};});try{const run=await createTaskRun(await prepareTaskModel(taskModelReviewSource()),fixture([4]));await run.settleNextInstant();expect(checked).toBe(true);}finally{spy.mockRestore();}},20000);
it('all three subject projections precede every phase-140 prior; task outputs stay empty',async()=>{const Original=schedulerModule.DeterministicScheduler;let checked=false;const spy=vi.spyOn(schedulerModule,'DeterministicScheduler').mockImplementation(function(config:schedulerModule.SchedulerConfiguration<AuthoritativeState>){const a=config.adaptationSettlement!;return new Original({...config,adaptationSettlement:{...a,prepare(events,state,instant){const roots:bigint[]=[],read=AuthoritativeState.prototype.read,reads=vi.spyOn(AuthoritativeState.prototype,'read').mockImplementation(function(this:AuthoritativeState,path){roots.push(path.rootStateTypeId);return read.call(this,path);});let batch;try{batch=a.prepare(events,state,instant);expect(roots.filter(r=>r===268n).length).toBeGreaterThanOrEqual(3);expect(roots.every(r=>r===268n)).toBe(true);checked=true;}finally{reads.mockRestore();}return batch;}}});} as never);try{const run=await createTaskRun(await prepareTaskModel(taskModelReviewSource()),fixture([4]));await run.settleNextInstant();expect(checked).toBe(true);const traces=items(decode(run.snapshot().trace),'list').map(v=>rec(v,160n)).filter(v=>key(f(v,7n))===key(id(1001,'event/task-measurement-settlement')));expect(traces).toHaveLength(1);expect(f(traces[0],13n)).toEqual(list([]));}finally{spy.mockRestore();}},20000);
it.each(['missing-S','duplicate-S','mismatched-parent','premature-finish','skip','duplicate-execution','trace-failure'] as const)('task whole-instant rollback: %s',async mode=>{
 const Original=schedulerModule.DeterministicScheduler;let captured:schedulerModule.DeterministicScheduler<AuthoritativeState>|undefined,runtime:ReturnType<typeof runtimeModule.createAdaptationRuntime>|undefined;
 const originalRuntime=runtimeModule.createAdaptationRuntime,capture=vi.spyOn(runtimeModule,'createAdaptationRuntime').mockImplementation((...args)=>runtime=originalRuntime(...args));
 const spy=vi.spyOn(schedulerModule,'DeterministicScheduler').mockImplementation(function(config:schedulerModule.SchedulerConfiguration<AuthoritativeState>){const a=config.adaptationSettlement!;captured=new Original({...config,adaptationSettlement:{...a,prepare(events,state,instant){const s=events.find(e=>key(e.eventTypeId)===key(id(1001,'event/task-measurement-settlement')))!;
  const altered=mode==='missing-S'?events.filter(e=>e!==s):mode==='duplicate-S'?[...events,s]:mode==='mismatched-parent'?events.map(e=>e===s?{...e,causalParentEventIds:[999n]}:e):events;
  const batch=a.prepare(altered,state,instant);if(mode==='premature-finish')batch.finish();return {...batch,async execute(context){if(mode==='skip')return {nextState:context.state,outputs:[],emittedEvents:[],traceContributions:[]};const result=await batch.execute(context);if(mode==='duplicate-execution')await batch.execute(context);return result;}};
 }}});return captured;} as never);
 const originalTrace=traceModule.traceRecordValue,trace=vi.spyOn(traceModule,'traceRecordValue').mockImplementation(t=>{if(mode==='trace-failure'&&key(t.event.eventTypeId)===key(id(1001,'event/task-measurement-settlement')))throw Error('after all task patches');return originalTrace(t);});
 try{const run=await createTaskRun(await prepareTaskModel(taskModelReviewSource()),fixture([4])),before=captured!.exportQuiescentSnapshot(),facts=runtime!.taskPendingFacts();await expect(run.settleNextInstant()).rejects.toThrow();const after=captured!.exportQuiescentSnapshot();expect(enc(after.state.canonicalValue())).toEqual(enc(before.state.canonicalValue()));for(const k of ['queue','allocators','outputs','committedTrace','clock'] as const)expect(after[k]).toEqual(before[k]);expect(runtime!.taskPendingFacts()).toEqual(facts);expect(runtime!.memoryPendingFacts()).toEqual([]);expect(runtime!.predictionPendingFacts()).toEqual([]);
 }finally{trace.mockRestore();spy.mockRestore();capture.mockRestore();}
},20000);
