import {describe,it,expect} from 'vitest';
import {canonicalEncode,bytesToHex,text,type CanonicalValue} from '../substrate/canonicalEncoding';
import {perceptualReferentIdValue} from '../semanticBinding/semanticCodecs';
import {retainCanonicalSignificantChildren as retain,type CanonicalSignificantAcquisition} from '../campaign3/canonicalChildKeys';
const file=(n:bigint)=>perceptualReferentIdValue({observerId:'observer/long-enough-to-exceed-the-placeholder-text-bound',observerTrackSequence:n});
const memory=(keys:CanonicalValue[]):CanonicalSignificantAcquisition[]=>[{id:1n,kind:'EventContinuant',acquiredAt:1n,units:keys.map(key=>({key,views:[new Uint8Array([1])],useProtection:false,outcomeSignificanceDirections:[]}))}];
const capacity={EventContinuant:1,Interoceptive:0},key=(v:CanonicalValue)=>bytesToHex(canonicalEncode(v));
describe('canonical child keys survive placeholder adaptation',()=>{
 it('CK-A: long actual SEM file keys round-trip without truncation or persisted labels',()=>{const k=file(900n);expect(key(k).length).toBeGreaterThan(64);const r=retain(memory([k]),2n,capacity);expect(r.acquisitions[0].units[0].key).toEqual(k);expect(r.losses).toEqual([]);});
 it('CK-B: canonical byte order, not numeric ordinal or rendered text, determines a tie',()=>{const keys=[file(812n),file(900n)],ordered=[...keys].sort((a,b)=>key(a)<key(b)?-1:1);expect(ordered[0]).toEqual(file(900n));const r=retain(memory(keys),2n,capacity);expect(r.acquisitions[0].units[0].key).toEqual(ordered[0]);expect(r.losses[0].unit).toEqual(ordered[1]);const textResult=retain(memory([text('aa'),text('z')]),2n,capacity);expect(textResult.acquisitions[0].units[0].key).toEqual(text('z'));});
 it('CK-C: permutations and fresh tables preserve exact output; decoded keys are detached',()=>{const keys=[file(812n),file(900n)],a=memory(keys),before=structuredClone(a),r=retain(a,2n,capacity);expect(retain(memory([...keys].reverse()),2n,capacity)).toEqual(r);expect(a).toEqual(before);const k=r.acquisitions[0].units[0].key;if(typeof k==='boolean'||k.kind!=='record')throw Error('record');(k.fields as Map<bigint,CanonicalValue>).set(2n,text('changed'));expect(a).toEqual(before);expect(retain(a,2n,capacity).acquisitions[0].units[0].key).toEqual(file(900n));});
 it('CK-D: identity preservation does not replace significance or acquisition age ranking',()=>{const m=memory([file(812n),file(900n)]);const units=m[0].units.map((u,i)=>({...u,outcomeSignificanceDirections:i===0?['MovingCloser' as const]:[]}));expect(retain([{...m[0],units}],2n,capacity).acquisitions[0].units[0].key).toEqual(file(812n));});
 it('CK-E: repeated keys in one acquisition reject and large construction keys fail closed',()=>{expect(()=>retain(memory([file(1n),file(1n)]),2n,capacity)).toThrow('duplicate unit');expect(()=>retain(memory([text('a'.repeat(4097))]),2n,capacity)).toThrow('CANONICAL_CHILD_KEY_DOMAIN');});
 it('CK-F: the same child in distinct acquisitions does not create shared mutable output keys',()=>{const a=memory([file(900n)])[0],r=retain([a,{...a,id:2n}],2n,{EventContinuant:2,Interoceptive:0}),first=r.acquisitions[0].units[0].key;if(typeof first==='boolean'||first.kind!=='record')throw Error('record');(first.fields as Map<bigint,CanonicalValue>).set(2n,text('changed'));expect(r.acquisitions[1].units[0].key).toEqual(file(900n));});
});
