import {describe,it,expect} from 'vitest';
import {canonicalEncode,bytesToHex} from '../substrate/canonicalEncoding';
import {ExactRational as Q} from '../substrate/exactMath';
import {perceptualReferentIdValue} from '../semanticBinding/semanticCodecs';
import {recallCanonicalEventAcquisitions as recall,type CanonicalEventRecallInput} from '../campaign3/canonicalEventRecall';
const q=(n:number,d=1)=>Q.of(BigInt(n),BigInt(d)),file=(n:bigint)=>perceptualReferentIdValue({observerId:'observer/a',observerTrackSequence:n});
const calibration=()=>({beta:q(1,2),scale:1000n,lambda:q(1),exponent:1,omegaB:q(0),omegaA:q(1),k:1});
const input=():CanonicalEventRecallInput=>({cue:{kind:'Present',key:file(900n)},memory:[{id:812n,acquiredAt:1n,units:[{key:file(812n),views:[new Uint8Array([1])]}]},{id:900n,acquiredAt:1n,units:[{key:file(900n),views:[new Uint8Array([2])]}]}],graph:{keys:[],weights:[]},presentations:new Map(),now:2n,calibration:calibration()});
describe('canonical event recall composes existing kernels',()=>{
 it('CER-A: actual matching episodic content recalls with no graph membership',()=>{const r=recall(input());expect(r.recalled.map(a=>a.id)).toEqual([900n]);expect(r.recalled[0].units[0].key).toEqual(file(900n));const isolated=recall({...input(),graph:{keys:[file(900n)],weights:[[q(0)]]}});expect(isolated.recalled).toEqual(r.recalled);expect(isolated.scores).toEqual(r.scores);});
 it('CER-B: a graph-only cue can mediate access but never creates an episode',()=>{const r=recall({...input(),cue:{kind:'Present',key:file(9n)},graph:{keys:[file(900n),file(9n)],weights:[[q(0),q(1,2)],[q(0),q(0)]]}});expect(r.recalled.map(a=>a.id)).toEqual([900n]);expect(r.recalled.some(a=>a.units.some(u=>bytesToHex(canonicalEncode(u.key))===bytesToHex(canonicalEncode(file(9n)))))).toBe(false);expect(recall({...input(),memory:[],cue:{kind:'Present',key:file(9n)},graph:{keys:[file(9n)],weights:[[q(0)]]}}).recalled).toEqual([]);});
 it('CER-C: absent cue reads neither memory nor graph/history and zero slots recall nothing',()=>{const absent={cue:{kind:'Absent' as const},now:2n,calibration:calibration(),get memory():never{throw Error('memory read');},get graph():never{throw Error('graph read');},get presentations():never{throw Error('history read');}};expect(recall(absent)).toEqual({disposition:'UnavailableCue',access:[],scores:[],recalled:[]});expect(recall({...input(),calibration:{...calibration(),k:0}}).recalled).toEqual([]);});
 it('CER-D: canonical acquisition tie order is preserved, not decimal rendering',()=>{const a=input(),memory=a.memory.map(m=>({...m,units:[{key:file(900n),views:[new Uint8Array([1])]}]}));expect(recall({...a,memory}).recalled[0].id).toBe(900n);expect(recall({...a,memory:[...memory].reverse()})).toEqual(recall({...a,memory}));});
 it('CER-E: only retained targets and nonfuture actual history are admitted',()=>{expect(()=>recall({...input(),presentations:new Map([[3n,[1n]]])})).toThrow('CANONICAL_EVENT_HISTORY');expect(()=>recall({...input(),presentations:new Map([[900n,[3n]]])})).toThrow('future');expect(()=>recall({...input(),memory:[...input().memory,{...input().memory[0]}]})).toThrow('duplicate acquisition');});
 it('CER-F: recall preserves source state and returns detached content without protection metadata',()=>{const a=input(),before=structuredClone(a.memory),r=recall(a);r.recalled[0].units[0].views[0][0]=99;expect(a.memory).toEqual(before);expect(Object.keys(r.recalled[0]).sort()).toEqual(['acquiredAt','id','units']);expect(Object.keys(r.recalled[0].units[0]).sort()).toEqual(['key','views']);});
});
