import {describe,it,expect} from 'vitest';
import {canonicalEncode} from '../substrate/canonicalEncoding';
import {decodeAttention} from '../campaign3/attentionCodecs';
import {selectCanonicalVisual} from '../campaign3/canonicalVisualSelection';
import {selectedReferences,consumeSelected} from '../campaign3/attentionSelection';
import {attentionFixture} from './attentionFixtures';
describe('actual canonical visual selection completion',()=>{
 it('CVS-A: one audit occurrence and a referencing selected view use the same actual allocation',()=>{const f=attentionFixture();let n=7n;const r=selectCanonicalVisual({kind:'Experience',experience:f.experience,claims:f.claims},2,()=>n++);expect(n).toBe(8n);expect(r.selectionId).toBe(7n);expect(r.audit.schema.typeId).toBe(532n);expect(r.selected.fields.get(1n)).toEqual(r.audit.fields.get(1n));for(const v of [r.audit,r.selected])expect(canonicalEncode(decodeAttention(canonicalEncode(v)))).toEqual(canonicalEncode(v));const refs=selectedReferences(r.view);expect(refs).toHaveLength(4);expect(consumeSelected(r.view,refs)).toHaveLength(4);expect(()=>selectedReferences(r.view)).toThrow();});
 it('CVS-B: zero capacity and missing roles still produce their own completed selection',()=>{const f=attentionFixture();for(const [capacity,claims]of [[0,f.claims],[2,[]]] as const){let calls=0;const r=selectCanonicalVisual({kind:'Experience',experience:claims.length?f.experience:{...f.experience,perceivedBindings:f.experience.perceivedBindings.map(b=>({...b,eventRoleEvidence:{kind:'unresolved' as const}}))},claims},capacity,()=>BigInt(calls++));expect(calls).toBe(1);expect(r.selected.fields.get(4n)).toMatchObject({kind:'list',items:[]});expect(consumeSelected(r.view,[])).toEqual([]);}});
 it('CVS-C: no detections cite the actual observation without a fake experience',()=>{const r=selectCanonicalVisual({kind:'NoDetection',observation:{observerId:'observer/a',observationId:8n,occurredAt:2n,detections:[]}},1,()=>9n);expect(r.audit.fields.get(4n)).toMatchObject({kind:'record',fields:new Map([[1n,{kind:'unsigned',value:2n}],[3n,{kind:'typedIdentifier',namespaceId:1115n,payload:{kind:'unsigned',value:8n}}]])});expect(r.audit.fields.get(6n)).toMatchObject({kind:'list',items:[]});expect(consumeSelected(r.view,[])).toEqual([]);});
 it('CVS-D: malformed capacity, time and positive-as-empty cannot consume an occurrence',()=>{let calls=0;const empty={kind:'NoDetection' as const,observation:{observerId:'observer/a',observationId:8n,occurredAt:2n,detections:[]}};for(const [s,c] of [[empty,3],[{...empty,observation:{...empty.observation,occurredAt:0n}},1],[{...empty,observation:{...empty.observation,detections:[{}]}},1]] as const)expect(()=>selectCanonicalVisual(s,c as 1,()=>BigInt(calls++))).toThrow();expect(calls).toBe(0);expect(()=>selectCanonicalVisual(empty,1,()=>-1n)).toThrow('VISUAL_SELECTION_ALLOCATION');});
 it('CVS-E: audit, canonical view and one-use capability are detached projections',()=>{const f=attentionFixture(),r=selectCanonicalVisual({kind:'Experience',experience:f.experience,claims:f.claims},1,()=>7n),before=canonicalEncode(r.selected),refs=selectedReferences(r.view);const id=r.audit.fields.get(1n);if(typeof id==='boolean'||id?.kind!=='typedIdentifier'||typeof id.payload==='boolean'||id.payload.kind!=='unsigned')throw Error('id');Reflect.set(id.payload,'value',99n);expect(canonicalEncode(r.selected)).toEqual(before);(r.selected.fields as Map<bigint,unknown>).clear();expect(consumeSelected(r.view,refs)).toHaveLength(2);});
});
