import {it,expect} from 'vitest';
import {canonicalEncode as enc,list,record,unsigned as u} from '../substrate/canonicalEncoding';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key} from '../campaign2/canonicalData';
import {applyStatePatch} from '../substrate/state';
import {STAGES,eventId,path,owner,chosenReappraisalPublicRecipe} from '../campaign3/chosenReappraisalPublicModel';
import {parseChosenReappraisalSave} from '../campaign3/chosenReappraisalPublicCodecs';
import {prepareChosenReappraisalPublicModel,createChosenReappraisalPublicRun,restoreChosenReappraisalPublicRun} from '../campaign3/chosenReappraisalPublicFactory';
import {createChosenReappraisalRun} from '../campaign3/chosenReappraisal';
import {chosenFrames} from './chosenReappraisalFixtures';
import {nativeCase,nativeRun,nativeRuntime,nativeRows,publicInput,restoreInput} from './chosenReappraisalPublicFixtures';
it('twelve native phases preserve component choice, execution, learning and frame exactly',async()=>{
 const c=nativeCase('Balanced','BenefitRelative',1),s=await nativeRuntime(c),component=await createChosenReappraisalRun('BenefitRelative',chosenFrames(),1);while(await s.runtime.settle()){}while(await component.step()){}
 expect(nativeRows(s.runtime.snapshot().outputs,c.law)).toEqual(component.snapshot().rows);expect(s.runtime.snapshot().randomAddresses).toEqual(component.snapshot().addresses);
 const ts=s.runtime.snapshot().trace.map(v=>rec(v,160n));expect(ts.length).toBe(96);for(let i=0;i<8;i++)expect(ts.slice(i*12,i*12+12).map(t=>f(rec(f(t,4n),130n),3n))).toEqual(STAGES.map(([,p])=>u(p)));
},600000);
it('goals, knowledge and frame reject every foreign writer',async()=>{const s=await nativeRuntime(nativeCase('SafetyOnly'));for(let i=0;i<4;i++)await s.runtime.settle();for(const [root,authorized]of [[1462,'context'],[1029,'learn'],[1031,'frame']] as const)for(const writer of ['context','learn','frame']){if(writer===authorized)continue;const p=path(root),prior=s.runtime.snapshot().state.read(p).value!;expect(()=>applyStatePatch(s.runtime.snapshot().state,{operations:[{kind:'set',path:p,expected:{presence:true,value:prior},newValue:prior}]},owner(writer),s.model.authority)).toThrow();}},600000);
it('closed model, initial state, original source, seed and opaque handle admission',async()=>{const c=nativeCase(),h=await prepareChosenReappraisalPublicModel(c.source);await expect(createChosenReappraisalPublicRun({} as any,publicInput(c))).rejects.toThrow();await expect(prepareChosenReappraisalPublicModel({...c.source,registry:enc(list([]))})).rejects.toThrow();for(const input of [{...publicInput(c),runSeed:new Uint8Array(31)},{...publicInput(c),runSeed:Uint8Array.from({length:32},(_,i)=>i)},{...publicInput(c),initialState:enc(list([]))},{...publicInput(c),orderedInputs:enc(list([]))}])await expect(createChosenReappraisalPublicRun(h,input)).rejects.toThrow();},600000);
it('restore checks whole native save and rejects forged trace or foreign model',async()=>{const c=nativeCase(),a=await nativeRun(c);await a.settleNextInstant();const save=a.save(),parsed=parseChosenReappraisalSave(save),fields=new Map(parsed.fields);fields.set(11n,list([]));await expect(restoreChosenReappraisalPublicRun(c.source,restoreInput(c,enc(record(parsed.schema,fields))))).rejects.toThrow();await expect(restoreChosenReappraisalPublicRun(chosenReappraisalPublicRecipe('NoReappraisal'),restoreInput(c,save))).rejects.toThrow();const b=await restoreChosenReappraisalPublicRun(c.source,restoreInput(c,save));expect(b.save()).toEqual(save);await a.settleNextInstant();await b.settleNextInstant();expect(b.save()).toEqual(a.save());},600000);
for(const stage of [...STAGES.map(([n])=>n),'commit'])it('native Failed rollback at reached '+stage,async()=>{const s=await nativeRuntime(nativeCase('Balanced','BenefitRelative',1));for(let i=0;i<3;i++)await s.runtime.settle();const before=s.runtime.snapshot(),project=(v:typeof before)=>({...v,status:undefined,state:enc(v.state.canonicalValue())});let reached=false;await expect(s.runtime.settleForConformance({onBoundary(b,e){if(stage==='commit'?b==='before-commit':b==='after-trace-validation'&&e&&key(e.eventTypeId)===key(eventId(stage))){reached=true;throw Error('injected');}}})).rejects.toThrow();expect(reached).toBe(true);expect(s.runtime.snapshot().status).toBe('Failed');expect(project(s.runtime.snapshot())).toEqual(project(before));await expect(s.runtime.settle()).rejects.toThrow();},600000);
it('quiescent publication rejects in-flight reads and concurrent calls',async()=>{const s=await nativeRuntime(),first=s.runtime.settle();expect(()=>s.runtime.save()).toThrow();expect(()=>s.runtime.snapshot()).toThrow();await expect(s.runtime.settle()).rejects.toThrow();expect(()=>s.runtime.save()).toThrow();await first;expect(s.runtime.save().length).toBeGreaterThan(0);},600000);
it('whole-wrapper barrier spans commit through RNG ledger publication microtask',async()=>{const s=await nativeRuntime(),reads:string[]=[];const pending=s.runtime.settleForConformance({onBoundary(b){if(b==='before-commit')queueMicrotask(()=>{for(const get of [()=>s.runtime.save(),()=>s.runtime.snapshot()]){try{get();reads.push('ACCEPTED');}catch(e){reads.push(String(e));}}});}});await expect(s.runtime.settle()).rejects.toThrow('not quiescent');await pending;expect(reads).toHaveLength(2);expect(reads.every(s=>s.includes('not quiescent'))).toBe(true);},600000);
it('caller bytes cannot mutate admitted source, inputs or published output',async()=>{const c=nativeCase(),a=await nativeRun(c),b=await nativeRun();c.source.parameters.fill(0);c.orderedInputs.fill(0);c.runSeed.fill(7);await a.settleNextInstant();await b.settleNextInstant();expect(a.save()).toEqual(b.save());const output=a.observerView();output.fill(0);expect(a.observerView()).not.toEqual(output);},600000);
it('safe output is invariant under hidden truth and denied versus absent catalogue',async()=>{for(const [a,b]of [['Balanced','HiddenTruth'],['DeniedCatalogue','AbsentCatalogue']] as const){const x=await nativeRun(nativeCase(a)),y=await nativeRun(nativeCase(b));while(await x.settleNextInstant())await y.settleNextInstant();expect(x.observerView()).toEqual(y.observerView());expect(x.runIdentity()).not.toEqual(y.runIdentity());}},600000);
