import {it,expect} from 'vitest';
import {ExactRational as Q} from '../substrate/exactMath';
import {text,typedIdentifier,canonicalEncode} from '../substrate/canonicalEncoding';
import {createLocalReserveSource} from '../campaign3/localReserveSource';
import {createTrialPanelSource} from '../campaign3/trialPanelSource';
import {createWindowMarkerManager} from '../campaign3/windowMarkerTransaction';
import {createWindowPanelManager} from '../campaign3/windowPanelTransaction';
import {observeGeneralSourceOpportunity} from '../campaign3/generalSourceOpportunity';
import {produceBodyFormationEvidence as produce} from '../campaign3/bodyFormationEvidence';
import {selectContextualBody as select,consumeContextualBody as consume,closeContextualBody as close,type ContextualBodyView} from '../campaign3/contextualBodySelection';
const observer=typedIdentifier(1000,text('observer/a')),limits={maxSignals:1,maxViewsPerSignal:1,maxBytesPerSignal:4096,capacity:1};
function source(visible=true,available=true,multiple=false){const body=createLocalReserveSource(['A','B','C'].map(k=>({key:'local-reserve/'+k,capacity:Q.of(100n),rate:Q.of(0n),amount:Q.of(0n),anchoredAt:0n})),['A','B','C',...(multiple?['A-alt']:[])].map(k=>({channel:'channel/'+k,physical:'local-reserve/'+(k==='A-alt'?'A':k),signal:'interoceptive-signal/'+(k==='A-alt'?'A':k),width:Q.of(k==='A-alt'?2n:1n),available,permitted:true}))),panel=createTrialPanelSource([{at:1n,glyph:0,stage:'Before',visible,permitted:true}]);let n=0n;const r=observeGeneralSourceOpportunity(body,panel,undefined,createWindowPanelManager('observer/a'),createWindowMarkerManager('observer/a'),observer,1n,'Current',{bodyChannels:multiple?['channel/A','channel/A-alt']:['channel/A'],panel:true,visual:false},()=>n++);return {...r.body!,context:r.context};}
it('CB-A: selected context is the actual shared-source companion, without a second identity',()=>{const s=source();let calls=0;const r=select(s,limits,()=>{calls++;return 90n;}),v=consume(r.view);expect(calls).toBe(1);expect(v.selectionId).toBe(90n);expect(v.context).toEqual(s.context);expect(v.groups[0].samples.map(canonicalEncode)).toEqual(s.samples.map(canonicalEncode));expect(Object.keys(v).sort()).toEqual(['at','context','groups','observer','opportunityId','selection','selectionId']);});
it('CB-B: wrong context experience/event/support/time/observer rejects before allocation',()=>{const s=source();let calls=0;const c=s.context!;const changes=[{...c,experience:999n},{...c,context:{...c.context,observerEventSequence:99n}},{...c,panel:{...c.panel,observation:99n}},{...c,panel:{...c.panel,sample:{...c.panel.sample,at:2n}}},{...c,context:{...c.context,observerId:'observer/b'}}];for(const context of changes)expect(()=>select({...s,context},limits,()=>BigInt(calls++))).toThrow();expect(calls).toBe(0);expect(()=>select({...s,staged:null},limits,()=>90n)).toThrow();const staged=s.staged;if(!staged)throw Error('fixture');expect(()=>select({...s,staged:{...staged,experience:{...staged.experience,transformationVersion:'unaccepted-source'}}},limits,()=>90n)).toThrow();});
it('CB-C: selected context is detached, one-use and absent when unsensed',()=>{const s=source(),r=select(s,limits,()=>90n);if(s.context!.panel.sample.kind!=='Present')throw Error('fixture');(s.context!.panel.sample as {stage:string}).stage='After';expect(consume(r.view).context!.panel.sample).toMatchObject({stage:'Before'});expect(()=>consume(r.view)).toThrow();expect(()=>consume({} as ContextualBodyView)).toThrow();const c=select(source(),limits,()=>91n);close(c.view);expect(()=>consume(c.view)).toThrow();expect(consume(select(source(false),limits,()=>92n).view).context).toBeUndefined();});
it('CB-D: context alone and capacity zero cannot fabricate a retained signal group',()=>{for(const [available,capacity]of [[false,1],[true,0]] as const){const v=consume(select(source(true,available),{...limits,capacity},()=>90n).view);expect(v.context).toBeDefined();expect(v.groups).toEqual([]);}});
it('CB-E: undeclared context fields and executable properties never reach retained evidence',()=>{const s=source(),c=s.context!;let reads=0,allocations=0;for(const context of [{...c,world:'forbidden'},{...c,panel:{...c.panel,truth:'forbidden'}},{...c,panel:{...c.panel,sample:{...c.panel.sample,get stage(){reads++;return 'Before' as const;}}}}])expect(()=>select({...s,context},limits,()=>BigInt(allocations++))).toThrow('SHAPE');expect(reads).toBe(0);expect(allocations).toBe(0);});

it('BF-A: selected signal views produce one later identity and preserve the actual source',()=>{const s=source(true,true,true),a=select(s,{...limits,maxViewsPerSignal:2},()=>90n);let calls=0;const r=produce(a.view,()=>{calls++;return 100n;});expect(calls).toBe(1);if(r.kind!=='Formation')throw Error('formation');expect(r.evidence).toMatchObject({acquisitionId:100n,sourceSelectionId:90n,at:1n});expect(r.evidence.content.children).toHaveLength(1);expect(r.evidence.content.children[0].views).toHaveLength(2);expect(r.evidence.content.children[0].views.map(v=>canonicalEncode(v.sample))).toEqual(s.samples.map(canonicalEncode));expect(r.evidence.content.children[0].views[0].sample).toEqual(s.samples[0]);expect(r.evidence.content.children[0].views[0].context).toEqual(s.context);expect(Object.keys(r.evidence).sort()).toEqual(['acquisitionId','at','content','observer','sourceSelectionId','transformationVersion']);});
it('BF-B: zero capacity and missing body evidence allocate no acquisition despite context',()=>{for(const [available,capacity]of [[false,1],[true,0]] as const){let calls=0;const s=source(true,available),a=select(s,{...limits,capacity},()=>90n);expect(produce(a.view,()=>{calls++;return 100n;})).toEqual({kind:'NoFormation',selectionId:90n});expect(calls).toBe(0);}});
it('BF-C: raw observation, forged token and replay cannot produce evidence',()=>{const s=source();expect(()=>produce(s as unknown as ContextualBodyView,()=>100n)).toThrow();expect(()=>produce({} as ContextualBodyView,()=>100n)).toThrow();const a=select(s,limits,()=>90n);produce(a.view,()=>100n);expect(()=>produce(a.view,()=>101n)).toThrow();});
it('BF-D: failed allocation consumes no persistent source and evidence is detached',()=>{const s=source(),before=s.samples.map(canonicalEncode),a=select(s,limits,()=>90n);expect(()=>produce(a.view,()=>-1n)).toThrow('ALLOCATION');expect(()=>produce(a.view,()=>100n)).toThrow();expect(s.samples.map(canonicalEncode)).toEqual(before);const r=produce(select(s,limits,()=>90n).view,()=>100n);if(r.kind!=='Formation')throw Error('formation');const c=r.evidence.content.children[0].views[0].context!;(c.context as {observerEventSequence:bigint}).observerEventSequence=99n;expect(s.context!.context.observerEventSequence).toBe(0n);});
