import {it,expect,vi} from 'vitest';
import {createCrossContextRun as create,crossContextSummary as summary} from '../campaign3/crossContextIdentity';
import {crossContextCases as cases} from './crossContextIdentityFixtures';
import {expectedStanding} from './crossContextReceiving';
vi.setConfig({testTimeout:120000});
it('independent millionth fold preserves opposing evidence and exact rounding',()=>{expect(expectedStanding([])).toBe('0/1');expect(expectedStanding(['7/18'])).toBe('388889/1388889');expect(expectedStanding(['7/18','-7/18'])).toBe('0/1');expect(expectedStanding(['1/2000000'])).toBe('0/1');expect(expectedStanding(['3/2000000'])).toBe('1/500001');});
it('same-context receiving uses its actual contributing subset including zero',async()=>{for(const seed of [0,1,7]){const r=create('SeparateContext',cases().sameContextProbe,seed);while(await r.step()){}const rows=summary(r.observerView());expect(rows[4].used).toBe(expectedStanding(rows.slice(0,4).filter(x=>x.context==='Custody').map(x=>x.contribution)));}});
it('missing probe meaning removes a nonzero receiving modifier without deleting history',async()=>{const a=create('SharedMeaning',cases().main,0),b=create('SharedMeaning',cases().noProbeMeaning,0),n=create('NoFeedback',cases().main,0);for(const r of [a,b,n])while(await r.step()){}const x=summary(a.observerView()),y=summary(b.observerView()),z=summary(n.observerView());expect(x[4].used).not.toBe('0/1');expect(y.slice(0,4)).toEqual(x.slice(0,4));expect(y[4].used).toBe('0/1');expect(y[4].strength).toBe(x[4].strength);expect(y[4].probabilities).toEqual(z[4].probabilities);expect(y[4].chosen).toBe(z[4].chosen);});
it('reversing current meaning redirects standing but preserves original expressions',async()=>{const a=create('SharedMeaning',cases().main,0),b=create('SharedMeaning',cases().reversedProbe,0);for(const r of [a,b])while(await r.step()){}const x=summary(a.observerView()),y=summary(b.observerView());expect(y.slice(0,4)).toEqual(x.slice(0,4));expect(y[4].used).toBe(x[4].used);expect(y[4].probabilities).toEqual([...x[4].probabilities].reverse());});
