import {it,expect,vi} from 'vitest';
vi.setConfig({testTimeout:180000});
import {createCrossContextRun as create,restoreCrossContextRun as restore,crossContextSummary as summary,LAWS,type Law,CONTEXTS} from '../campaign3/crossContextIdentity';
import {dataItems as items,dataKey as key} from '../campaign2/canonicalData';
import {crossContextCases as cases} from './crossContextIdentityFixtures';
async function run(name:keyof ReturnType<typeof cases>='main',law:Law='SharedMeaning',seed=7){const r=create(law,cases()[name],seed);while(await r.step()){}return r;}
it('actual disjoint context sources retain different effects, motives and action order',async()=>{const r=summary((await run()).observerView());expect(r.map(x=>x.context)).toEqual(['Custody','Disclosure','Custody','Disclosure','Appointment']);expect(new Set(Object.values(CONTEXTS).flatMap(x=>[...x.actions])).size).toBe(6);expect(new Set(Object.values(CONTEXTS).map(x=>x.predicate)).size).toBe(3);expect(CONTEXTS.Custody.expected).toEqual([true,false]);expect(CONTEXTS.Disclosure.expected).toEqual([false,true]);expect(r.slice(0,4).every(x=>x.expression&&x.addresses.length>0)).toBe(true);});
it('shared and context-local histories have identical acquisition but distinct held-out use',async()=>{for(let seed=0;seed<8;seed++){const a=summary((await run('main','SharedMeaning',seed)).observerView()),b=summary((await run('main','SeparateContext',seed)).observerView()),c=summary((await run('main','NoFeedback',seed)).observerView());expect(a.slice(0,4)).toEqual(b.slice(0,4));expect(a.slice(0,4)).toEqual(c.slice(0,4));expect(b[4].used).toBe('0/1');expect(c[4].used).toBe('0/1');expect(b[4].probabilities).toEqual(c[4].probabilities);expect(a[4].used).toBe(a[3].strength);}});
it('local history is restricted to the previously visited context, including cancellation',async()=>{const a=summary((await run('sameContextProbe','SeparateContext')).observerView());expect(a[4].context).toBe('Custody');expect(a.filter(x=>x.context==='Custody'&&x.at<5).map(x=>x.contribution)).toEqual(['7/18','-7/18']);expect(a[4].used).toBe('0/1');});
it('hidden execution differences leave complete character history and choice unchanged',async()=>{for(const law of LAWS){const a=await run('main',law),b=await run('hidden',law);expect(key(a.observerView())).toBe(key(b.observerView()));expect(key(a.snapshot())).not.toBe(key(b.snapshot()));}});
it('triviality and pressure are excluded by threshold while Frequency retains its different claim',async()=>{for(const name of ['trivial','pressured'] as const){const a=summary((await run(name)).observerView()),b=summary((await run(name,'Frequency')).observerView());expect(a.slice(0,4).every(x=>x.contribution==='0/1')).toBe(true);expect(b.slice(0,4).every(x=>x.contribution!=='0/1')).toBe(true);}});
it('withheld, uninterpretable and unaccepted choices never become evidence in any law',async()=>{for(const law of LAWS)for(const name of ['withheld','absentMeaning','unaccepted'] as const){const a=summary((await run(name,law)).observerView());expect(a.every(x=>x.strength==='0/1')).toBe(true);}});
it('opposite admitted meaning reverses evidence without changing acquisition choice or authorship',async()=>{const a=summary((await run()).observerView()),b=summary((await run('opposite')).observerView());for(let i=0;i<4;i++){expect(a[i].chosen).toBe(b[i].chosen);expect(a[i].authorship).toBe(b[i].authorship);expect(a[i].alignment===b[i].alignment).toBe(false);expect(b[i].contribution).toBe(a[i].contribution.startsWith('-')?a[i].contribution.slice(1):'-'+a[i].contribution);}});
it('graded small significance contributes while threshold does not, and Refold reproduces the full view',async()=>{expect(summary((await run('partial')).observerView())[3].strength).toBe('0/1');expect(summary((await run('partial','Graded')).observerView()).slice(0,4).every(x=>x.contribution!=='0/1')).toBe(true);expect(key((await run()).observerView())).toBe(key((await run('main','Refold')).observerView()));});
it('current interpretation changes receiving use, never the old expression or qualification',async()=>{const a=await run(),b=await run('noProbeMeaning'),c=await run('reversedProbe');const ar=items(items(a.observerView(),'list')[2],'list');for(const r of [b,c])expect(items(items(r.observerView(),'list')[2],'list').slice(0,4).map(key)).toEqual(ar.slice(0,4).map(key));expect(summary(b.observerView())[4].used).toBe('0/1');expect(summary(c.observerView())[4].used).toBe(summary(a.observerView())[4].used);});
it('every complete prefix and successor restores with immutable prior rows',async()=>{for(const law of LAWS){const r=create(law,cases().main);for(let i=0;i<=5;i++){const before=summary(r.observerView()),s=await restore(law,cases().main,7,i,r.save());expect(s.save()).toEqual(r.save());expect(await s.step()).toBe(await r.step());expect(s.save()).toEqual(r.save());expect(summary(r.observerView()).slice(0,i)).toEqual(before);}}},300000);
it('choice and precommit failures roll back; concurrent steps cannot cross a transaction',async()=>{for(const fault of ['after-choice','before-commit'] as const){const r=create('SharedMeaning',cases().main);await r.step();const save=r.save();await expect(r.step(fault)).rejects.toThrow('CCI_INJECTED');expect(r.save()).toEqual(save);const s=await restore('SharedMeaning',cases().main,7,1,save),pending=r.step();await expect(r.step()).rejects.toThrow('CCI_CONCURRENT');await pending;await s.step();expect(r.save()).toEqual(s.save());}});
it('inputs are copied, getters rejected without executing, and original/model/seed/bytes are bound',async()=>{const f=cases().main,r=create('SharedMeaning',f);f[0].contrary=true;await r.step();const s=create('SharedMeaning',cases().main);await s.step();expect(r.save()).toEqual(s.save());const bad=cases().main;Object.defineProperty(bad[0],'accepted',{get(){throw Error('GETTER_EXECUTED');}});expect(()=>create('SharedMeaning',bad)).toThrow('CCI_DATA');const bytes=r.save();bytes[bytes.length-1]^=1;await expect(restore('SharedMeaning',cases().main,7,1,bytes)).rejects.toThrow('CCI_SAVE_MISMATCH');await expect(restore('NoFeedback',cases().main,7,1,r.save())).rejects.toThrow('CCI_SAVE_MISMATCH');await expect(restore('SharedMeaning',cases().main,8,1,r.save())).rejects.toThrow('CCI_SAVE_MISMATCH');await expect(restore('SharedMeaning',cases().opposite,7,1,r.save())).rejects.toThrow('CCI_SAVE_MISMATCH');});
