import {it,expect,vi} from 'vitest';
import {createDomainRun as create,restoreDomainRun as restore} from '../campaign3/crossContextDomains';
import {createCrossContextRun} from '../campaign3/crossContextIdentity';
import {dataItems as items,dataKey as key} from '../campaign2/canonicalData';
import {domainCases as cases} from './crossContextDomainsFixtures';
vi.setConfig({testTimeout:180000});
it('publication is rejected for the complete pending domain transaction',async()=>{const x=cases().main,r=create('SharedMeaning',x.frames,x.sources,7),pending=r.step();for(const read of [r.save,r.snapshot,r.identityView,()=>r.recipientView(1)])expect(read).toThrow('CCD_BUSY');await pending;expect(r.snapshot().prefix).toBe(1);});
async function run(name='main'){const x=cases()[name],r=create('SharedMeaning',x.frames,x.sources,7);while(await r.step()){}return r;}
it('actual attempts enact parcel transfer, disclosure and attendance under one actor',async()=>{const r=await run(),s=r.snapshot(),receipts=s.receipts.map(x=>items(x,'list'));expect(s.world.parcels[0].owner).toBe('Beneficiary');expect(s.world.parcels[2].owner).toBe('Actor');expect(s.world.location).toBe('WithBeneficiary');expect(receipts.map(x=>(x[4] as {value:string}).value)).toEqual(['return-parcel','conceal-hazard','keep-parcel','disclose-hazard','attend-appointment']);expect(receipts[1][8]).toBe(false);expect(receipts[3][8]).toBe(true);expect(items(items(r.recipientView(1),'list')[2],'list')).toHaveLength(1);expect(items(items(r.recipientView(2),'list')[2],'list')).toHaveLength(0);});
it('the original cognitive component remains byte-identical',async()=>{const x=cases().main,a=create('SharedMeaning',x.frames,x.sources,7),b=createCrossContextRun('SharedMeaning',x.frames,7);for(let i=0;i<5;i++){await a.step();await b.step();expect(key(a.identityView())).toBe(key(b.observerView()));}});
it('hidden truth changes neither identity nor either recipient view',async()=>{const a=await run(),b=await run('hidden');expect(key(a.identityView())).toBe(key(b.identityView()));for(const i of [1,2] as const)expect(key(a.recipientView(i))).toBe(key(b.recipientView(i)));expect(a.snapshot().world.hazard).not.toBe(b.snapshot().world.hazard);});
it('failed transport and denied execution preserve expression but prevent their actual effects',async()=>{const a=await run(),b=await run('failedDelivery'),c=await run('deniedExecution');for(const r of [b,c]){expect(key(r.identityView())).toBe(key(a.identityView()));expect(items(items(r.recipientView(1),'list')[2],'list')).toHaveLength(0);}expect(b.snapshot().world.parcels[0].owner).toBe('Beneficiary');expect(c.snapshot().world.parcels.every(x=>x.owner==='Actor')).toBe(true);expect(c.snapshot().world.location).toBe('Away');});
it('false private evidence is transmitted as a false assertion, while unknown transmits nothing',async()=>{const a=await run('falseDisplay'),b=await run('noPrivateEvidence');expect(items(items(a.recipientView(1),'list')[2],'list')[0]).toMatchObject({kind:'rational',numerator:0n});expect(items(items(b.recipientView(1),'list')[2],'list')).toHaveLength(0);expect(a.snapshot().world.hazard).toBe(true);});
it('access selects private recipient learning without rewriting identity',async()=>{const a=await run(),b=await run('noRecipients'),c=await run('otherRecipient');for(const r of [b,c])expect(key(r.identityView())).toBe(key(a.identityView()));expect(items(items(b.recipientView(1),'list')[2],'list')).toHaveLength(0);expect(items(items(c.recipientView(1),'list')[2],'list')).toHaveLength(0);expect(items(items(c.recipientView(2),'list')[2],'list')).toHaveLength(1);});
it('complete domain prefixes and successors replay exactly',async()=>{const x=cases().main,r=create('SharedMeaning',x.frames,x.sources,7);for(let i=0;i<=5;i++){const s=await restore('SharedMeaning',x.frames,x.sources,7,i,r.save());expect(s.save()).toEqual(r.save());expect(await s.step()).toBe(await r.step());expect(s.save()).toEqual(r.save());}},300000);
it('faults restore cognition and every domain before retry, and reject overlapping work',async()=>{const x=cases().main;for(const fault of ['after-identity','after-world','before-commit'] as const){const r=create('SharedMeaning',x.frames,x.sources,7);await r.step();const before=r.save();await expect(r.step(fault)).rejects.toThrow('CCD_INJECTED');expect(r.save()).toEqual(before);const s=await restore('SharedMeaning',x.frames,x.sources,7,1,before),pending=r.step();await expect(r.step()).rejects.toThrow('CCD_CONCURRENT');await pending;await s.step();expect(r.save()).toEqual(s.save());}},300000);
it('copied source data and whole-original save binding reject mutation, getters and altered source',async()=>{const x=cases().main,r=create('SharedMeaning',x.frames,x.sources,7);x.sources[1].display=false;while(await r.step()){}expect(key(r.recipientView(1))).toBe(key((await run()).recipientView(1)));const bad=cases().main;Object.defineProperty(bad.sources[0],'truth',{get(){throw Error('GETTER_EXECUTED');}});expect(()=>create('SharedMeaning',bad.frames,bad.sources,7)).toThrow('CCD_DATA');const other=cases().hidden;await expect(restore('SharedMeaning',other.frames,other.sources,7,5,r.save())).rejects.toThrow('CCD_SAVE_MISMATCH');});
