import {beforeAll,describe,it,expect} from 'vitest';
import receipt from '../../docs/planning/DEFINING_MEMORY_TRAINING_REV1.json';
import {canonicalEncode as enc,list,unsigned as u,signed} from '../substrate/canonicalEncoding';
import {AuthoritativeState,type StatePatch} from '../substrate/state';
import {dataRecord as rec,dataField as f,dataItems as items,dataIdentity as identity,dataText as txt} from '../campaign2/canonicalData';
import {admitDefiningContinuationProgram as admit} from '../campaign3/definingContinuationProgram';
import {definingMeaningCases} from '../campaign3/definingMeaning';
import {createDefiningLifecycleModel} from '../campaign3/definingLifecycleModel';
import {compileDefiningLifecycleState,definingLifecyclePath} from '../campaign3/definingLifecycleState';
import {compileGeneralModelCandidate} from '../campaign3/generalModelCandidate';
import {buildGeneralDeclarationPacket} from '../campaign3/generalDeclarations';
import {definingLifecycleRecord as r,decodeDefiningLifecycle} from '../campaign3/definingLifecycleCodecs';
const spec={...definingMeaningCases()[0],now:400 as const},program=admit(spec),unhex=(s:string)=>Uint8Array.from(s.match(/../g)!.map(x=>parseInt(x,16)));
let baseModel:Awaited<ReturnType<typeof compileGeneralModelCandidate>>['model'];
let run:Awaited<ReturnType<typeof createDefiningLifecycleModel>>,binding:ReturnType<typeof compileDefiningLifecycleState>;
const prefixes:Uint8Array[]=[],times:bigint[]=[];let acquired:ReturnType<Awaited<ReturnType<typeof createDefiningLifecycleModel>>['runtime']['snapshot']>;
const image=(r:typeof run)=>{const s=r.runtime.snapshot();return enc(list([s.state.canonicalValue(),list(s.outputs),list(s.committedTrace)]));};
beforeAll(async()=>{const predecessor=await compileGeneralModelCandidate(buildGeneralDeclarationPacket('credit-significance-first'));baseModel=predecessor.model;binding=compileDefiningLifecycleState(baseModel,program);run=await createDefiningLifecycleModel(program);prefixes.push(image(run));while(true){const result=await run.runtime.settleNextInstant();if(!result)break;times.push(result.dueAt);prefixes.push(image(run));if(result.dueAt===37n)acquired=run.runtime.snapshot();}},240000);
describe('native defining lifecycle development',()=>{
 it('reproduces the acquired GA37 partition and outputs while adding a distinct adopted goal',()=>{expect(enc(binding.legacy(acquired.state).canonicalValue())).toEqual(unhex(receipt.snapshots[0].state));expect(enc(list(acquired.outputs))).toEqual(unhex(receipt.snapshots[0].outputs));const goal=rec(acquired.state.read(definingLifecyclePath(1485)).value!,1485n);expect(f(goal,2n)).toBe(true);expect(f(goal,3n)).toEqual(signed(37));expect(f(goal,4n)).toEqual(signed(38));expect(f(rec(acquired.state.read(definingLifecyclePath(1486)).value!,1486n),1n)).toEqual(u(0));});
 it('settles report and inherited task/goal deadlines in one original scheduler through400',()=>{expect(times).toEqual([1n,2n,3n,4n,5n,6n,16n,17n,18n,19n,20n,21n,22n,23n,33n,34n,35n,36n,37n,43n,100n,400n]);const s=run.runtime.snapshot();expect(s.queue).toEqual([]);expect(f(rec(s.state.read(definingLifecyclePath(1486)).value!,1486n),1n)).toEqual(u(2));const task=s.state.entries().find(e=>e.path.rootStateTypeId===373n)!;expect(f(rec(task.value,372n),1n)).not.toEqual(u(1));const goal=s.state.entries().find(e=>e.path.rootStateTypeId===633n)!;expect(f(rec(items(f(rec(goal.value,560n),1n),'list')[0],559n),3n)).toEqual(u(3));expect(prefixes).toHaveLength(23);});
 it('emits closed canonical native traces with exact owner reads, paths and mutation authority',()=>{
  const traces=run.runtime.snapshot().committedTrace.map(v=>rec(decodeDefiningLifecycle(enc(v)),160n)),own=traces.filter(t=>txt(identity(f(t,7n)).payload).startsWith('event/defining-'));expect(own).toHaveLength(3);
  for(const [stage,root,count,authority] of [['adopt',1485,1,'defining-interpretation-goal'],['report',1486,2,'defining-admitted-report']] as const){const trace=own.find(t=>txt(identity(f(t,7n)).payload)==='event/defining-'+stage)!;expect(items(f(trace,11n),'list')).toHaveLength(count);const diffs=items(f(trace,17n),'list');expect(diffs).toHaveLength(1);const diff=rec(diffs[0],148n);expect(f(rec(f(diff,1n),140n),1n)).toEqual(u(root));expect(txt(identity(f(diff,6n)).payload)).toBe('authority/'+authority);}
  const horizon=own.find(t=>txt(identity(f(t,7n)).payload)==='event/defining-horizon')!;expect(items(f(horizon,11n),'list')).toHaveLength(0);expect(items(f(horizon,17n),'list')).toHaveLength(0);
 });
 it('fresh empty-S0 execution repeats every complete native lifecycle prefix',async()=>{const fresh=await createDefiningLifecycleModel(program);expect(image(fresh)).toEqual(prefixes[0]);let i=1;while(await fresh.runtime.settleNextInstant())expect(image(fresh)).toEqual(prefixes[i++]);expect(i).toBe(prefixes.length);},240000);
 it('enforces disjoint mutation authorities and exact root values without altering prior state',()=>{const s0=binding.model.initial.build(),goal=binding.transition('defining-adopt',binding.source('defining-adopt'),s0,37n);expect(()=>binding.model.state.applyStagePatch('defining-report',s0,goal.patch)).toThrow();expect(()=>binding.model.state.applyStagePatch('ordinary-memory-use',s0,goal.patch)).toThrow();const p:StatePatch={operations:[{kind:'set',path:definingLifecyclePath(1486),expected:{presence:true,value:s0.read(definingLifecyclePath(1486)).value!},newValue:r(1486,[u(2),signed(43)])}]};expect(()=>binding.model.state.applyStagePatch('defining-report',s0,p)).toThrow();expect(f(rec(s0.read(definingLifecyclePath(1485)).value!,1485n),2n)).toBe(false);expect(()=>binding.model.state.validateState(new AuthoritativeState(binding.legacy(s0).entries()))).toThrow();});
 it('rejects duplicate or mismatched source transitions and unsettled lifecycle at quiescence',()=>{const s0=binding.model.initial.build();expect(()=>binding.transition('defining-report',binding.source('defining-report'),s0,43n)).toThrow();const next=binding.model.state.applyStagePatch('defining-adopt',s0,binding.transition('defining-adopt',binding.source('defining-adopt'),s0,37n).patch).state;expect(()=>binding.transition('defining-adopt',binding.source('defining-adopt'),next,37n)).toThrow();expect(()=>binding.transition('defining-report',r(1487,[u(2),signed(43),u(2)]),next,43n)).toThrow();expect(()=>binding.model.validateQuiescent(acquired.state,43n)).toThrow();});
 it('admitted goal/report variants preserve unknown/missing and reject foreign source values',()=>{
  for(const goal of ['High','Low','Wide','Absent'] as const)for(const report of ['original','contrary','missing'] as const){const b=compileDefiningLifecycleState(baseModel,admit({...spec,goal,report})),s0=b.model.initial.build();const g=b.transition('defining-adopt',b.source('defining-adopt'),s0,37n),s1=b.model.state.applyStagePatch('defining-adopt',s0,g.patch).state,delivery=b.transition('defining-report',b.source('defining-report'),s1,43n),s2=b.model.state.applyStagePatch('defining-report',s1,delivery.patch).state;
   const goalRow=rec(s2.read(definingLifecyclePath(1485)).value!,1485n),reportRow=rec(s2.read(definingLifecyclePath(1486)).value!,1486n);expect(goalRow.fields.has(6n)).toBe(goal!=='Absent');expect(f(reportRow,1n)).toEqual(u(report==='missing'?1:2));expect(reportRow.fields.has(3n)).toBe(report!=='missing');expect(enc(binding.legacy(s2).canonicalValue())).toEqual(enc(baseModel.initial.build().canonicalValue()));
  }
 });
 it('a reached adoption fault rolls back both partitions, queue, allocators, outputs and trace and leaves Failed',async()=>{const fresh=await createDefiningLifecycleModel(program);while(fresh.runtime.snapshot().clock<36n)await fresh.runtime.settleNextInstant();const prior=fresh.runtime.snapshot();let hit=false;await expect(fresh.runtime.settleNextInstantForConformance({onBoundary:(boundary)=>{if(boundary==='after-invariant-validation'){hit=true;throw Error('defining adoption fault');}}})).rejects.toThrow('defining adoption fault');expect(hit).toBe(true);const after=fresh.runtime.snapshot();expect(enc(after.state.canonicalValue())).toEqual(enc(prior.state.canonicalValue()));expect(after.queue).toEqual(prior.queue);expect(after.allocators).toEqual(prior.allocators);expect(after.outputs).toEqual(prior.outputs);expect(after.committedTrace).toEqual(prior.committedTrace);expect(after.status).toBe('Failed');await expect(fresh.runtime.settleNextInstant()).rejects.toThrow();},240000);
});
