import {describe,it,expect} from 'vitest';
import {applyQualifiedSignificance as apply,fragmentSignificantChildren as fragment,sharedSignificanceBitControl as bit,type SignificantAcquisition,type SignificanceDirection} from '../campaign3/directionalSignificanceState';
const memory=():SignificantAcquisition[]=>[{id:812n,kind:'EventContinuant',acquiredAt:1n,units:['alpha','beta'].map(key=>({key,views:[new Uint8Array([42])],useProtection:false,outcomeSignificanceDirections:[]}))}];
const owner=(m=memory())=>({observer:'observer/a',character:'character/a',memory:m});
const target={acquisition:812n,unit:'alpha'};
const credit=(direction:SignificanceDirection)=>({observer:'observer/a',character:'character/a',direction,targets:[target]});
describe('directional significance supplied-credit algebra',()=>{
 it('DS-A: exact four states and the shared-bit reduction',()=>{const none=memory(),closer=apply(owner(),[credit('MovingCloser')],2n),farther=apply(owner(),[credit('MovingFarther')],2n),both=apply(owner(),[credit('MovingFarther'),credit('MovingCloser')],2n);expect([none,closer,farther,both].map(s=>s[0].units[0].outcomeSignificanceDirections)).toEqual([[],['MovingCloser'],['MovingFarther'],['MovingCloser','MovingFarther']]);expect(bit(closer[0].units[0].outcomeSignificanceDirections)).toBe(bit(farther[0].units[0].outcomeSignificanceDirections));});
 it('DS-B: repetition, duplicate targets and credit order are idempotent',()=>{const one=apply(owner(),[credit('MovingCloser')],2n);expect(apply(owner(one),Array(10).fill({...credit('MovingCloser'),targets:[target,target]}),3n)).toEqual(one);expect(apply(owner(),[credit('MovingCloser'),credit('MovingFarther')],2n)).toEqual(apply(owner(),[credit('MovingFarther'),credit('MovingCloser')],2n));});
 it('DS-C: credit is child-local and independent of use, time and content',()=>{const before=memory(),after=apply(owner(before),[credit('MovingFarther')],2n);expect(after[0].units[1].outcomeSignificanceDirections).toEqual([]);expect(after[0].units[0].useProtection).toBe(false);expect(after[0].acquiredAt).toBe(1n);expect(after[0].units[0].views).toEqual(before[0].units[0].views);expect(before[0].units[0].outcomeSignificanceDirections).toEqual([]);});
 it('DS-D: loss removes significance and later credit cannot restore lost child',()=>{const prior=apply(owner(),[credit('MovingFarther')],2n),remaining=fragment(prior,[target],{EventContinuant:1,Interoceptive:0},3n).acquisitions;expect(remaining[0].units.map(u=>u.key)).toEqual(['beta']);expect(()=>apply(owner(remaining),[credit('MovingCloser')],4n)).toThrow('unknown loss');const fresh=memory().map(a=>({...a,id:900n}));expect(fresh[0].units[0].outcomeSignificanceDirections).toEqual([]);});
 it('DS-E: partial survivors preserve both significance and independently earned use',()=>{const prior=apply(owner(),[credit('MovingCloser')],2n);prior[0].units[0].useProtection=true;const kept=fragment(prior,[{acquisition:812n,unit:'beta'}],{EventContinuant:1,Interoceptive:0},3n);expect(kept.acquisitions[0].units[0]).toMatchObject({useProtection:true,outcomeSignificanceDirections:['MovingCloser']});expect(fragment(prior,[target,{acquisition:812n,unit:'beta'}],{EventContinuant:0,Interoceptive:0},3n).acquisitions).toEqual([]);});
 it('DS-F: a later invalid credit exposes no partially modified caller state',()=>{const m=memory(),before=structuredClone(m);expect(()=>apply(owner(m),[credit('MovingCloser'),{...credit('MovingFarther'),character:'foreign'}],2n)).toThrow('SUBJECT');expect(m).toEqual(before);});
 it('DS-G: invalid stored tags and nonqualifying directions reject',()=>{const m=memory().map(a=>({...a,units:a.units.map(u=>({...u,outcomeSignificanceDirections:['MovingCloser','MovingCloser'] as SignificanceDirection[]}))}));expect(()=>apply(owner(m),[],2n)).toThrow('STATE_TAGS');expect(()=>apply(owner(),[{...credit('MovingCloser'),direction:'SameDistance' as SignificanceDirection}],2n)).toThrow('CREDIT_DIRECTION');});
 it('DS-H: later evaluation time neither decays nor refreshes earned state',()=>{const m=apply(owner(),[credit('MovingFarther')],2n);expect(apply(owner(m),[],100n)).toEqual(m);m[0].units[0].views[0][0]=17;const copy=apply(owner(m),[],100n);copy[0].units[0].views[0][0]=18;expect(m[0].units[0].views[0][0]).toBe(17);});
});
