import {it,expect,vi} from 'vitest';
import {createCoercionRun as create,restoreCoercionRun as restore,expectation,TARGET,COERCERS,LAWS,type Law} from '../campaign3/enactedCoercion';
import {coercionCases as cases} from './enactedCoercionFixtures';
vi.setConfig({testTimeout:180000});
async function run(name='main',law:Law='Threshold',seed=7){const r=create(law,cases()[name],seed);while(await r.step()){}return r;}
it('all seeds preserve genuine first choices and learn only after actual refusal',async()=>{
 const first=[];for(let seed=0;seed<8;seed++){const r=await run('main','Threshold',seed),s=r.snapshot();first.push(s.rows[0].choice.chosen);for(const row of s.rows){expect(row.prior.every(e=>e.at<row.at&&e.holder===TARGET&&e.demander===row.demander)).toBe(true);expect(row.loss).toBe(row.executed==='refuse'?1000:0);expect(row.evidence!==null).toBe(row.executed==='refuse');if(row.at===1){expect(row.anticipatedCost).toBeNull();expect(row.pressure).toBe(0);}if(row.pressure===1000)expect(row.qualification).toEqual({status:'Constrained',contribution:'0/1'});}expect(s.resources).toBe(4000-s.rows.reduce((sum,x)=>sum+x.loss,0));}expect(first).toContain('refuse');expect(first).toContain('comply');
});
it('admitted evidence changes later probabilities without rewriting the original expression',async()=>{
 let changed=0;for(let seed=0;seed<8;seed++){const a=(await run('main','Threshold',seed)).snapshot(),b=(await run('withheld','Threshold',seed)).snapshot();expect(a.rows[0].expression).toEqual(b.rows[0].expression);expect(a.rows[0].qualification).toEqual(b.rows[0].qualification);expect(b.evidence).toEqual([]);if(JSON.stringify(a.rows.map(x=>x.choice.probabilities))!==JSON.stringify(b.rows.map(x=>x.choice.probabilities)))changed++;}expect(changed).toBeGreaterThan(0);
});
it('same admitted high reports conceal different physical power from all target state',async()=>{for(let seed=0;seed<8;seed++){const a=await run('explicitHigh','Threshold',seed),b=await run('hiddenPower','Threshold',seed);expect(a.targetView()).toEqual(b.targetView());expect(b.snapshot().resources).toBe(4000);}});
it('false zero and withheld evidence differ as known zero and unknown despite equal choices',async()=>{for(let seed=0;seed<8;seed++){const a=(await run('falseZero','Threshold',seed)).snapshot(),b=(await run('withheld','Threshold',seed)).snapshot();expect(a.rows.map(x=>x.choice)).toEqual(b.rows.map(x=>x.choice));if(a.evidence.length)expect(a.evidence.every(e=>e.cost===0)).toBe(true);expect(b.evidence).toEqual([]);}});
it('no opportunity does not become a negative sample; no-learning retains observations only in receipts',async()=>{const a=(await run('noDemand')).snapshot(),b=(await run('main','NoLearning')).snapshot();expect(a.evidence).toEqual([]);expect(a.rows.every(x=>x.choice.chosen===null&&x.evidence===null)).toBe(true);expect(b.evidence).toEqual([]);expect(b.rows.every(x=>x.anticipatedCost===null)).toBe(true);});
it('pressure qualification is independent of the pressure motive and later execution success',async()=>{for(let seed=0;seed<8;seed++){const a=create('Threshold',cases().main,seed),b=create('IgnorePressure',cases().main,seed),c=create('Threshold',cases().failedLater,seed);await a.step();await b.step();await c.step();await a.step();await b.step();await c.step();const x=a.snapshot().rows[1],y=b.snapshot().rows[1],z=c.snapshot().rows[1];expect(x.choice).toEqual(y.choice);expect(x.expression).toEqual(y.expression);expect(x.expression).toEqual(z.expression);expect(x.qualification).toEqual(z.qualification);expect(z.executed).toBeNull();if(x.pressure===1000){expect(x.qualification.contribution).toBe('0/1');expect(y.qualification.contribution).not.toBe('0/1');}}});
it('instruction cost below the threshold retains credit and graded qualification discounts it',async()=>{let witnesses=0;for(let seed=0;seed<8;seed++){const a=(await run('instruction','Threshold',seed)).snapshot(),b=(await run('instruction','Graded',seed)).snapshot();expect(a.rows.map(x=>x.choice)).toEqual(b.rows.map(x=>x.choice));for(let i=0;i<4;i++)if(a.rows[i].pressure===250){witnesses++;expect(a.rows[i].qualification.status).not.toBe('Constrained');expect(a.rows[i].qualification.contribution).not.toBe(b.rows[i].qualification.contribution);}}expect(witnesses).toBeGreaterThan(0);});
it('holder and demander continuity prevents pooling a foreign history',async()=>{const sample={at:1,holder:TARGET,demander:COERCERS[0],cost:1000};expect(expectation([sample],COERCERS[1],'Threshold')).toBeNull();expect(expectation([{...sample,holder:'foreign'}],COERCERS[0],'Threshold')).toBeNull();for(let seed=0;seed<8;seed++){const s=(await run('otherDemander','Threshold',seed)).snapshot();expect(s.rows[1].anticipatedCost).toBeNull();}});
it('mean, latest and no-pressure are retained alternatives',async()=>{const samples=[1000,0].map((cost,i)=>({at:i+1,holder:TARGET,demander:COERCERS[0],cost}));expect(expectation(samples,COERCERS[0],'Threshold')).toBe(500);expect(expectation(samples,COERCERS[0],'Latest')).toBe(0);const a=(await run('main','NoPressure')).snapshot();expect(a.rows.every(x=>x.pressure===0)).toBe(true);});
it('all candidate complete prefixes restore originals and replay the next transaction',async()=>{for(const law of LAWS){const r=create(law,cases().main,7);for(let prefix=0;prefix<=4;prefix++){const s=await restore(law,cases().main,7,prefix,r.save());expect(s.save()).toEqual(r.save());expect(await s.step()).toBe(await r.step());expect(s.save()).toEqual(r.save());}}},300000);
it('the complete pending transaction blocks publication and faults retry exactly',async()=>{for(const fault of ['after-choice','after-consequence','before-commit'] as const){const r=create('Threshold',cases().main,7);await r.step();const before=r.save(),p=r.step(fault);for(const read of [r.save,r.snapshot,r.targetView])expect(read).toThrow('EC_BUSY');await expect(r.step()).rejects.toThrow('EC_CONCURRENT');await expect(p).rejects.toThrow('EC_INJECTED');expect(r.save()).toEqual(before);const s=await restore('Threshold',cases().main,7,1,before);await r.step();await s.step();expect(s.save()).toEqual(r.save());}});
it('inputs are copied, accessor sources are rejected, and restore binds every original',async()=>{const f=cases().main,r=create('Threshold',f,7);f[0].penalty=0;await r.step();const s=create('Threshold',cases().main,7);await s.step();expect(s.save()).toEqual(r.save());await expect(restore('Threshold',f,7,1,r.save())).rejects.toThrow('EC_SAVE_MISMATCH');const bad=cases().main;Object.defineProperty(bad[0],'power',{get(){throw Error('GETTER_EXECUTED');}});expect(()=>create('Threshold',bad,7)).toThrow('EC_DATA');});
