import {describe,it,expect} from 'vitest';
import {ExactRational as Q} from '../substrate/exactMath';
import {encodingRaw,encodingBudget,residualAttention,associationCandidate,spreadingActivation,presentationAccessibility,rankAccessibleEpisodes} from '../campaign3/encodingAccessMath';
const q=(n:number,d=1)=>Q.of(BigInt(n),BigInt(d)),zero=q(0),one=q(1),eq=(a:Q,b:Q)=>expect(a.equals(b)).toBe(true),matrix=(n:number)=>Array.from({length:n},()=>Array.from({length:n},()=>zero));
describe('encoding-access-math/0.1-candidate',()=>{
 it('EAM-A: exact factor decomposition and zero attention',()=>{const f={base:q(3,10),role:one,attention:one,need:q(1,2),surprise:zero,alphaN:one,alphaS:one};eq(encodingRaw(f),q(9,20));eq(encodingRaw({...f,attention:zero}),zero);});
 it('EAM-B: unrelated footprint cannot dilute independent focal encoding',()=>{for(let n=0;n<31;n++){const z=encodingBudget(['a',...Array.from({length:n},(_,i)=>'extra'+i)],[one,...Array.from({length:n},()=>q(1,10))],'independent');eq(z[0],q(1,2));}});
 it('EAM-C: historical denominators do not imply a conserved budget; threshold is inclusive',()=>{const shared=encodingBudget(['a','b'],[one,one],'historical-shared',q(1,5));eq(shared[0],q(1,2));eq(shared[1],q(1,2));const hybrid=encodingBudget(['a','b'],[one,q(1,10)],'historical-hybrid',q(1,5),one);eq(hybrid[0],q(1,2));eq(hybrid[1],one);expect(encodingBudget([],[],'historical-shared',zero)).toEqual([]);eq(encodingBudget(['a'],[zero],'historical-shared',zero)[0],zero);eq(encodingBudget(['a'],[zero],'retired-flat')[0],one);});
 it('EAM-D: residual pool is shared only among positive supplied members',()=>{eq(residualAttention(q(1,5),0),zero);eq(residualAttention(q(1,5),1),q(1,5));eq(residualAttention(q(1,5),3),q(1,15));});
 it('EAM-E: decay, Hebbian addition and ties-to-even quantization remain separate',()=>{const w=[[zero,q(1,2)],[zero,zero]],p={scale:10n,eta:q(1,10),lambda:one,elapsed:one},r=associationCandidate(['a','b'],w,[one,one],p);eq(r.rows[0].exact[1],q(7,20));expect(r.rows[0].quantized[1]).toBe(4n);eq(r.values[0][1],q(2,5));const tiny=associationCandidate(['a','b'],matrix(2),[one,one],{...p,eta:q(1,20)});expect(tiny.rows[0].quantized[1]).toBe(0n);});
 it('EAM-F: overflowing rows conserve exact lattice mass with canonical remainder ties',()=>{const r=associationCandidate(['d','c','b','a'],matrix(4),[one,one,one,one],{scale:5n,eta:one,lambda:zero,elapsed:zero});expect(r.rows[0].mass).toEqual([0n,1n,2n,2n]);expect(r.rows.every(row=>row.mass.reduce((a,b)=>a+b,0n)===5n)).toBe(true);});
 it('EAM-G: every repeated candidate retains row budget and no self edges without changing inputs',()=>{let w=matrix(4);const untouched=w;for(let k=0;k<40;k++){w=associationCandidate(['a','b','c','d'],w,[one,q(1,2),q(1,3),q(1,4)],{scale:100n,eta:one,lambda:q(1,10),elapsed:one}).values;w.forEach((row,i)=>{eq(row[i],zero);expect(row.reduce((a,b)=>a.add(b),zero).compare(one)).toBeLessThanOrEqual(0);});}expect(untouched.every(row=>row.every(x=>x.equals(zero)))).toBe(true);});
 it('EAM-H: exact coupled solve and honest no-spreading alternative',()=>{const w=[[zero,q(1,2)],[q(1,4),zero]],r=spreadingActivation(['a','b'],w,[one,zero],q(1,2),10n);eq(r.exact[0],q(32,31));eq(r.exact[1],q(4,31));const local=spreadingActivation(['a','b'],w,[one,zero],zero,10n);eq(local.exact[1],zero);});
 it('EAM-I: quantization happens after solving, not on matrix coefficients',()=>{const r=spreadingActivation(['a','b'],[[zero,q(1,2)],[q(1,4),zero]],[one,zero],q(1,2),10n);eq(r.quantized[0],one);eq(r.quantized[1],q(1,10));expect(r.exact[0].equals(q(50,49))).toBe(false);});
 it('EAM-J: recency, repeated presentation and future-history exclusion',()=>{eq(presentationAccessibility([0n],2n,one,1),q(1,3));eq(presentationAccessibility([0n,2n],2n,one,1),q(4,3));eq(presentationAccessibility([0n],2n,one,2),q(1,9));expect(()=>presentationAccessibility([3n],2n,one,1)).toThrow();expect(()=>presentationAccessibility([2n,0n],2n,one,1)).toThrow();});
 it('EAM-K: averaged pull, canonical ties, K0 and read-only ranking',()=>{const episodes=[{key:'b',retainedKeys:['a','b'],presentations:[0n]},{key:'a',retainedKeys:['a'],presentations:[0n]}],activation=new Map([['a',one],['b',one]]),p={lambda:one,exponent:1,omegaB:one,omegaA:one,k:1};const r=rankAccessibleEpisodes(episodes,activation,2n,p);eq(r.scored[0].pull,one);expect(r.selected[0].key).toBe('a');expect(rankAccessibleEpisodes(episodes,activation,2n,{...p,k:0}).selected).toEqual([]);expect(episodes[0].presentations).toEqual([0n]);});
 it('EAM-L: rejects invalid domains even for empty inputs',()=>{expect(()=>encodingBudget(['a','a'],[one,one],'independent')).toThrow();expect(()=>encodingBudget(['a'],[],'independent')).toThrow();expect(()=>residualAttention(one,-1)).toThrow();expect(()=>associationCandidate(['a'],[[one]],[one],{scale:10n,eta:one,lambda:zero,elapsed:zero})).toThrow();expect(()=>associationCandidate(['a','b'],[[zero,q(1,3)],[zero,zero]],[one,one],{scale:10n,eta:one,lambda:zero,elapsed:zero})).toThrow();expect(()=>spreadingActivation([],[],[],one,10n)).toThrow();expect(()=>spreadingActivation(['a'],[],[one],zero,10n)).toThrow();expect(()=>rankAccessibleEpisodes([],new Map(),-1n,{lambda:one,exponent:1,omegaB:one,omegaA:one,k:0})).toThrow();expect(()=>rankAccessibleEpisodes([{key:'episode',retainedKeys:['missing'],presentations:[]}],new Map(),0n,{lambda:one,exponent:1,omegaB:one,omegaA:one,k:1})).toThrow();});
});
