import {describe,it,expect} from 'vitest';
import {reconcileFormationGovernance as settle,type FormationSource,type GovernanceEntry} from '../campaign3/formationGovernance';
const a:FormationSource={source:'source/2',character:'character/a',kind:'Interoceptive'},b:FormationSource={source:'source/1',character:'character/a',kind:'Interoceptive'},domain=[a,b];
const commit=(s:FormationSource,id:bigint,at=1n)=>({...s,acquisition:id,formedAt:at});
describe('bounded formation governance',()=>{
 it('FG-A: immediate loss preserves exact source history and no content',()=>{const rows=settle(domain,[],[commit(a,812n)],[],1n);expect(rows).toEqual([{...commit(a,812n),completeLoss:true}]);expect(Object.keys(rows[0]).sort()).toEqual(['acquisition','character','completeLoss','formedAt','kind','source']);expect(()=>settle(domain,rows,[commit(a,813n,2n)],[],2n)).toThrow();});
 it('FG-B: absence is no successful formation, not ordinal finalization or failed-attempt history',()=>{const rows=settle(domain,[],[commit(a,812n)],[],1n);expect(settle(domain,rows,[commit(b,813n,2n)],[],2n)).toHaveLength(2);expect(settle(domain,[],[],[],1n)).toEqual([]);});
 it('FG-C: fixed source universe excludes novel sources even when no successes exist',()=>{expect(()=>settle([a],[],[commit(b,1n)],[],1n)).toThrow();});
 it('FG-D: continuation and later loss retain metadata and prevent resurrection',()=>{const rows=settle(domain,[],[commit(a,1n)],[1n],1n),lost=settle(domain,rows,[],[],2n);expect(lost[0]).toEqual({...rows[0],completeLoss:true});expect(()=>settle(domain,lost,[],[1n],3n)).toThrow();expect(settle(domain,structuredClone(lost),[],[],3n)).toEqual(lost);});
 it('FG-E: subject/kind mismatch, reused identities and unknown survivors reject',()=>{for(const s of [{...a,character:'other'},{...a,kind:'EventContinuant' as const}])expect(()=>settle(domain,[],[commit(s,1n)],[],1n)).toThrow();expect(()=>settle(domain,[],[commit(a,1n),commit(b,1n)],[],1n)).toThrow();expect(()=>settle(domain,[],[],[1n],1n)).toThrow();});
 it('FG-F: extra payload fields are rejected and outputs detached immutable',()=>{const injected={...commit(a,1n),payload:new Uint8Array([42])};expect(()=>settle(domain,[],[injected],[],1n)).toThrow();const input=commit(a,1n),rows=settle(domain,[],[input],[],1n);input.source='changed';expect(rows[0].source).toBe(a.source);expect(Object.isFrozen(rows[0])).toBe(true);});
 it('FG-G: failed plan does not modify prior; canonical result ignores supplied row order',()=>{const prior=settle(domain,[],[commit(a,2n),commit(b,1n)],[1n,2n],1n);const before=structuredClone(prior);expect(()=>settle(domain,prior,[commit(a,3n,2n)],[],2n)).toThrow();expect(prior).toEqual(before);expect(settle(domain,[...prior].reverse(),[],[2n,1n],2n)).toEqual(prior);});
 it('FG-H: domain itself is bounded, unique and metadata-only',()=>{expect(()=>settle([a,a],[],[],[],1n)).toThrow();expect(()=>settle(Array.from({length:65},(_,i)=>({...a,source:String(i)})),[],[],[],1n)).toThrow();expect(()=>settle(domain,[],[commit(a,1n,2n)],[],1n)).toThrow();});
});
