import {describe,it,expect} from 'vitest';
import {prepareFormationSettlement as prepare,type FormationSettlementInput} from '../campaign3/formationSettlement';
const make=(capacity=1):FormationSettlementInput=>({priorProtocol:{domain:[],successes:[]},priorMemory:[],incoming:[{source:'s',character:'c',kind:'Interoceptive'}],formed:[{source:'s',character:'c',kind:'Interoceptive',acquisition:1n,formedAt:1n}],freshMemory:[{id:1n,kind:'Interoceptive',acquiredAt:1n,units:[{key:'alpha',views:[new Uint8Array([42])]},{key:'beta',views:[new Uint8Array([17])]}]}],now:1n,sourceLimit:2,capacity:{EventContinuant:0,Interoceptive:capacity}});
describe('actual memory owner result binding component',()=>{
 it('OJ-A: actual retention result determines partial and complete loss metadata',()=>{for(const cap of [0,1,2]){const tx=prepare(make(cap)),out=tx.finish(tx.resolveMemory());expect(out.memory.flatMap(a=>a.units)).toHaveLength(cap);expect(out.protocol.successes[0].completeLoss).toBe(cap===0);expect(Object.keys(out.protocol.successes[0]).sort()).toEqual(['acquisition','character','completeLoss','formedAt','kind','source']);}});
 it('OJ-B: copied and cross-transaction handles reject even with matching data',()=>{const a=prepare(make()),b=prepare(make()),token=a.resolveMemory();expect(()=>a.finish({...token})).toThrow('FORMATION_OWNER_RESULT_BINDING');expect(()=>b.finish(token)).toThrow('FORMATION_OWNER_RESULT_BINDING');expect(a.finish(token).memory).toHaveLength(1);});
 it('OJ-C: successful consumption, close and repeated resolve cannot replay a result',()=>{const tx=prepare(make()),token=tx.resolveMemory();expect(()=>tx.resolveMemory()).toThrow();tx.finish(token);expect(()=>tx.finish(token)).toThrow();const next=prepare(make()),stale=next.resolveMemory();next.close();expect(()=>next.finish(stale)).toThrow('FORMATION_OWNER_CLOSED');});
 it('OJ-D: empty admitted source enrolls without a successful formation',()=>{const x=make();const tx=prepare({...x,formed:[],freshMemory:[]});const out=tx.finish(tx.resolveMemory());expect(out.protocol.domain).toHaveLength(1);expect(out.protocol.successes).toEqual([]);expect(out.memory).toEqual([]);});
 it('OJ-E: altered time/kind or missing fresh acquisition rejects before result issuance',()=>{const x=make();for(const freshMemory of [[],[{...x.freshMemory[0],acquiredAt:0n}],[{...x.freshMemory[0],kind:'EventContinuant' as const}]])expect(()=>prepare({...x,freshMemory})).toThrow();});
 it('OJ-F: input mutation after preparation cannot change the result',()=>{const x=make(2),tx=prepare(x);x.freshMemory[0].units[0].views[0][0]=99;const out=tx.finish(tx.resolveMemory());expect(out.memory[0].units.find(u=>u.key==='alpha')!.views[0][0]).toBe(42);});
 it('OJ-G: prior content cannot contradict governance survival or original metadata',()=>{const tx=prepare(make()),out=tx.finish(tx.resolveMemory());const x={...make(),priorProtocol:out.protocol,priorMemory:out.memory,incoming:[],formed:[],freshMemory:[],now:2n};expect(()=>prepare({...x,priorMemory:[]})).toThrow();expect(()=>prepare({...x,priorMemory:[{...out.memory[0],acquiredAt:0n}]})).toThrow('FORMATION_OWNER_PRIOR_BINDING');});
});
