import {canonicalEncode as enc,list,set,signed,unsigned as u,type CanonicalValue} from '../substrate/canonicalEncoding';
import {griefRecord as r} from '../campaign3/griefCodecs';
export const initialState=enc(set([])),seed=new Uint8Array(32).fill(13);
export type Row={target:number;worldSupport:number;worldBlocked:boolean;worldResolved:boolean;worldPresent:boolean;support:number;opportunity:boolean;resolved:boolean;demand:boolean;blocked:boolean;present:boolean;partA:boolean;partB:boolean;accessA:boolean;accessB:boolean;cueA:boolean;cueB:boolean;alternative:boolean;currentDemand:boolean;returnOpportunity:boolean;returnClaim:number;worldReturn:number};
const row=(x:Partial<Row>={}):Row=>({target:1,worldSupport:2,worldBlocked:true,worldResolved:true,worldPresent:false,support:2,opportunity:true,resolved:true,demand:true,blocked:true,present:false,partA:true,partB:true,accessA:true,accessB:true,cueA:true,cueB:true,alternative:true,currentDemand:true,returnOpportunity:false,returnClaim:0,worldReturn:0,...x});
export function cases(){
 const probe=(x:Partial<Row>={})=>row({opportunity:false,accessA:false,accessB:false,...x});
 const main=[row(),row(),row({opportunity:false,returnOpportunity:true}),probe(),row({target:2,opportunity:false,returnOpportunity:true}),row({opportunity:false,returnOpportunity:true,returnClaim:2}),row({support:0,resolved:false}),probe()];
 const change=(fn:(r:Row,i:number)=>Row)=>main.map((r,i)=>fn({...r},i)),third=(x:Partial<Row>)=>change((r,i)=>i===2?{...r,...x}:r),sixth=(x:Partial<Row>)=>change((r,i)=>i===5?{...r,...x}:r);
 return {main,temporary:third({returnClaim:2}),uncertain:third({returnClaim:1}),noReport:third({returnOpportunity:false}),deniedReport:third({accessA:false,accessB:false}),noCorrection:sixth({returnOpportunity:false}),deniedCorrection:sixth({accessA:false,accessB:false}),foreignCorrection:sixth({target:2}),oneSupport:change((r,i)=>i===1?{...r,opportunity:false}:r),selfSufficient:change((r,i)=>i<2?{...r,blocked:false}:r),noHistory:change((r,i)=>i<2?{...r,opportunity:false}:r),witnessA:change(r=>({...r,partA:false})),present:change(r=>({...r,present:true})),noAlternative:change(r=>({...r,alternative:false})),noDemand:change(r=>({...r,currentDemand:false})),otherTarget:change((r,i)=>i===4?{...r,returnClaim:2}:r),missingCue:change(r=>({...r,cueA:false})),hiddenWorld:change(r=>({...r,worldSupport:0,worldBlocked:false,worldResolved:false,worldPresent:true,worldReturn:2})),hiddenReturn:change(r=>({...r,worldReturn:2})),denied:change((r,i)=>i===3?{...r,opportunity:true,support:0,resolved:false,returnOpportunity:true,returnClaim:2}:r),noA:change((r,i)=>i<6?{...r,accessA:false,cueA:false}:r),noB:change((r,i)=>i<6?{...r,accessB:false,cueB:false}:r)};
}
export const ordered=(rows:Row[])=>enc(list(rows.map((x,i)=>r(1279,[signed(i+1),u(x.target),u(x.worldSupport),x.worldBlocked,x.worldResolved,x.worldPresent,u(x.support),x.opportunity,x.resolved,x.demand,x.blocked,x.present,x.partA,x.partB,x.accessA,x.accessB,x.cueA,x.cueB,x.alternative,x.currentDemand,x.returnOpportunity,u(x.returnClaim),u(x.worldReturn)]))));
export const records=(xs:readonly CanonicalValue[],type:bigint)=>xs.filter(x=>typeof x!=='boolean'&&x.kind==='record'&&x.schema.typeId===type);
