import {it,expect} from 'vitest';
import {createUncertaintyRun as create,restoreUncertaintyRun as restore,projectReserveEvidence as sense,LAWS,type Law} from '../campaign3/interoceptiveUncertainty';
import {uncertaintyCases as cases} from './interoceptiveUncertaintyFixtures';
async function run(name:keyof ReturnType<typeof cases>='narrow',law:Law='UpperRisk',seed=7){const r=create(law,cases()[name],seed);while(await r.step()){}return r;}
it('every unbiased finite sensor bin contains actual truth including ties and endpoints',()=>{for(const width of [0,200,600])for(let actual=0;actual<=1000;actual++){const b=sense(actual,0,width,true)!;expect(b.lower).toBeLessThanOrEqual(actual);expect(b.upper).toBeGreaterThanOrEqual(actual);expect(b.lower).toBeGreaterThanOrEqual(0);expect(b.upper).toBeLessThanOrEqual(1000);}});
it('same truth and midpoint with different admitted quality changes next-step precaution',async()=>{const a=(await run()).snapshot().rows,b=(await run('wide')).snapshot().rows;expect(a[0].choice).toEqual(b[0].choice);expect(a[0].after).toEqual({lower:400,upper:600});expect(b[0].after).toEqual({lower:200,upper:800});expect(a[1].strength).toBe(400);expect(b[1].strength).toBe(800);expect(a[1].choice.probabilities).not.toEqual(b[1].choice.probabilities);});
it('both interval beliefs are uncertain and approximately correct under predeclared criteria',async()=>{for(const name of ['narrow','wide'] as const){const b=(await run(name)).snapshot().belief!;expect(b.upper-b.lower).toBeGreaterThan(0);expect(Math.abs((b.upper+b.lower)/2-550)).toBeLessThanOrEqual(100);expect(b.lower<=550&&550<=b.upper).toBe(true);}const b=(await run('biased')).snapshot().belief!;expect(b.lower>550).toBe(true);});
it('point/optimistic/midpoint competitors preserve distinct interpretations without confidence inflation',async()=>{const a=(await run('wide','MidpointRisk')).snapshot(),b=(await run('wide','PointBelief')).snapshot(),c=(await run('wide','LowerRisk')).snapshot();expect(a.belief).toEqual({lower:200,upper:800});expect(b.belief).toEqual({lower:500,upper:500});expect(a.rows[1].strength).toBe(200);expect(b.rows[1].strength).toBe(200);expect(c.rows[1].strength).toBe(0);expect((await run('wide','NoLearning')).snapshot().belief).toBeNull();});
it('duplicate intervals and missing evidence cannot manufacture precision',async()=>{const a=(await run()).snapshot(),b=(await run('duplicate')).snapshot();expect(a.belief).toEqual(b.belief);expect(a.rows.map(x=>x.prior)).toEqual(b.rows.map(x=>x.prior));expect(a.rows.map(x=>x.choice)).toEqual(b.rows.map(x=>x.choice));expect(a.rows[1].observation).toBeNull();});
it('whole safe view follows admitted evidence rather than hidden truth or denied settings',async()=>{for(const law of LAWS){expect((await run('narrow',law)).observerView()).toEqual((await run('hidden',law)).observerView());expect((await run('absent',law)).observerView()).toEqual((await run('deniedChanged',law)).observerView());}});
it('known no deficit is not unknown and correction affects only subsequent choice',async()=>{const n=(await run('neutral')).snapshot(),u=(await run('absent')).snapshot();expect(n.belief).not.toBeNull();expect(u.belief).toBeNull();expect(n.rows[1].strength).toBe(u.rows[1].strength);const a=(await run('biased')).snapshot(),b=(await run('corrected')).snapshot();expect(a.rows.slice(0,2)).toEqual(b.rows.slice(0,2));expect(a.rows[2].choice).toEqual(b.rows[2].choice);expect(a.rows[3].strength).not.toBe(b.rows[3].strength);});
it('every law restores all prefixes and one successor including terminal exactly',async()=>{for(const law of LAWS){const r=create(law,cases().wide);for(let i=0;i<=4;i++){const q=await restore(law,cases().wide,7,i,r.save());expect(q.save()).toEqual(r.save());expect(await q.step()).toBe(await r.step());expect(q.save()).toEqual(r.save());}}},60000);
it('faults and overlap preserve prior state and addressed retry results',async()=>{for(const fault of ['after-choice','before-commit'] as const){const r=create('UpperRisk',cases().wide);await r.step();const saved=r.save();await expect(r.step(fault)).rejects.toThrow('UNC_INJECTED');expect(r.save()).toEqual(saved);const q=await restore('UpperRisk',cases().wide,7,1,saved);const pending=r.step();await expect(r.step()).rejects.toThrow('UNC_CONCURRENT');await pending;await q.step();expect(r.save()).toEqual(q.save());}});
it('copied strict inputs and full save commitments reject mutation and forgery',async()=>{const f=cases().narrow,r=create('UpperRisk',f);f[0].bias=400;await r.step();expect(r.snapshot().belief).toEqual({lower:400,upper:600});const bad=cases().narrow;Object.defineProperty(bad[0],'width',{get(){throw Error('GETTER_RAN');}});expect(()=>create('UpperRisk',bad)).toThrow('UNC_DATA');const extra=[{...cases().wide[0],extra:true},...cases().wide.slice(1)];expect(()=>create('UpperRisk',extra)).toThrow('UNC_DATA');const save=r.save();save[save.length-1]^=1;await expect(restore('UpperRisk',cases().narrow,7,1,save)).rejects.toThrow('UNC_SAVE_MISMATCH');await expect(restore('UpperRisk',cases().hidden,7,1,r.save())).rejects.toThrow('UNC_SAVE_MISMATCH');});
