import {it,expect} from 'vitest';
import {createInterferenceExpectationRun as create,restoreInterferenceExpectationRun as restore,LAWS,type Law} from '../campaign3/interferenceExpectation';
import {interferenceFrames as frames} from './interferenceExpectationFixtures';
async function complete(name:Parameters<typeof frames>[0]='main',law:Law='AcrossEpisodeMean'){const f=await frames(name),r=create(law,f);while(await r.step()){}return r;}
it('three actual opportunities yield one equal-weight sample each and next-step appraisal',async()=>{const r=(await complete()).snapshot();expect(r.rows[0].expectation).toBeNull();expect(r.rows[1].expectation).toBeNull();expect(r.rows[2].expectation).toBe('1/1');expect(r.rows[5].expectation).toBe('1/1');expect(r.rows[6].expectation).toBe('2/3');expect(r.rows[6].affect).toEqual(['2/3','2/3']);expect(r.episodes).toHaveLength(3);},60000);
it('latest and episode-only competitors keep distinct prospective claims',async()=>{expect((await complete('main','LatestEpisode')).snapshot().rows[7].expectation).toBe('0/1');for(const law of ['EpisodeOnly','NoLearning'] as const)expect((await complete('main',law)).snapshot().rows.every(r=>r.expectation===null)).toBe(true);},60000);
it('known clear is zero; missing causal evidence, opportunity or context is unknown',async()=>{expect((await complete('clear')).snapshot().rows[7].expectation).toBe('0/1');for(const name of ['withheld','noOpportunity','noContext'] as const)expect((await complete(name)).snapshot().rows[7].expectation).toBeNull();},60000);
it('context and goal are separate from evidence and expectation',async()=>{expect((await complete('otherContext')).snapshot().rows[7].expectation).toBe('1/1');const a=(await complete()).snapshot(),b=(await complete('goalZero')).snapshot();expect(a.episodes).toEqual(b.episodes);expect(a.rows.map(r=>r.expectation)).toEqual(b.rows.map(r=>r.expectation));expect(b.rows[7].affect).toEqual(['0/1','0/1']);},60000);
it('hidden causes cannot alter whole component views',async()=>{const a=await frames(),b=await frames('hidden');expect(a).toEqual(b);for(const law of LAWS){const x=create(law,a),y=create(law,b);while(await x.step())await y.step();expect(x.observerView()).toEqual(y.observerView());}},60000);
it('duplicate and additional same-polarity reports do not create a fourth opportunity',async()=>{const a=(await complete()).snapshot(),b=(await complete('duplicate')).snapshot(),c=(await complete('repeat')).snapshot();expect(b.episodes).toEqual(a.episodes);expect(c.episodes).toHaveLength(3);expect(c.episodes[2].support).toHaveLength(2);expect(c.rows[7].expectation).toBe('2/3');},60000);
it('contrary correction updates one old episode only at the next probe',async()=>{const a=(await complete()).snapshot(),b=(await complete('correction')).snapshot();expect(b.rows.slice(0,7)).toEqual(a.rows.slice(0,7));expect(b.rows[7].expectation).toBe('1/2');expect(b.episodes).toHaveLength(3);},60000);
it('every component prefix restores and preserves old rows',async()=>{const f=await frames();for(const law of LAWS){const r=create(law,f);for(let i=0;i<=8;i++){const old=r.snapshot(),q=await restore(law,f,i,r.save());expect(q.save()).toEqual(r.save());expect(await q.step()).toBe(await r.step());expect(q.save()).toEqual(r.save());expect(r.snapshot().rows.slice(0,i)).toEqual(old.rows);}}},60000);
it('fault rollback and overlap reject without partial learning',async()=>{const f=await frames();for(const fault of ['after-evidence','before-commit'] as const){const r=create('AcrossEpisodeMean',f);await r.step();const saved=r.save();await expect(r.step(fault)).rejects.toThrow('IE_INJECTED');expect(r.save()).toEqual(saved);const q=await restore('AcrossEpisodeMean',f,1,saved),pending=r.step();await expect(r.step()).rejects.toThrow('IE_CONCURRENT');await pending;await q.step();expect(q.save()).toEqual(r.save());}},60000);
it('copies data, rejects accessor sources and corrupted or changed saves',async()=>{const f=await frames(),r=create('AcrossEpisodeMean',f);f[0].context='B';await r.step();expect(r.snapshot().episodes[0].context).toBe('A');const bad=await frames();Object.defineProperty(bad[0],'goal',{get(){throw Error('GETTER');}});expect(()=>create('AcrossEpisodeMean',bad)).toThrow('IE_DATA');const saved=r.save();saved[saved.length-1]^=1;await expect(restore('AcrossEpisodeMean',await frames(),1,saved)).rejects.toThrow('IE_SAVE_MISMATCH');await expect(restore('AcrossEpisodeMean',f,1,r.save())).rejects.toThrow('IE_SAVE_MISMATCH');},60000);

it('denied report content changes preserve complete admitted views and learned states',async()=>{const a=await frames('withheld'),b=await frames('withheldChanged');expect(a).toEqual(b);for(const law of LAWS){const x=create(law,a),y=create(law,b);while(await x.step())await y.step();expect(x.observerView()).toEqual(y.observerView());}},60000);
