import {it,expect} from 'vitest';
import {createLatentCauseRun as create,restoreLatentCauseRun as restore,LAWS,type Law} from '../campaign3/latentCause';
import {latentCauseCases as cases} from './latentCauseFixtures';
async function run(name:keyof ReturnType<typeof cases>='correction',law:Law='JointDiagnostics'){const r=create(law,cases()[name]);while(await r.step()){}return r;}
it('failure alone is ambiguous; independent diagnostics revise competing causes only later',async()=>{const r=(await run()).observerView();expect(r.rows.map(x=>x.inference.blockage)).toEqual([null,'1/2','1/4','1/10','1/2','9/10']);expect(r.rows.map(x=>x.inference.status)).toEqual(['Unknown','Ambiguous','Limitation','Limitation','Ambiguous','Obstruction']);expect(r.intent).toEqual({at:1,action:'AttemptDelivery'});});
it('stable diagnoses can be correct and hidden-cause changes can make them wrong without leaking',async()=>{const a=await run('limitation'),b=await run('hidden'),c=await run('obstruction');expect(a.observerView()).toEqual(b.observerView());expect(a.snapshot().world).not.toEqual(b.snapshot().world);expect(a.observerView().rows[5].inference.status).toBe('Limitation');expect(c.observerView().rows[5].inference.status).toBe('Obstruction');});
it('actual appraisal uses inferred cause and independent goal without changing knowledge',async()=>{const a=(await run()).observerView(),b=(await run('goalChange')).observerView();expect(a.evidence).toEqual(b.evidence);expect(a.rows.map(x=>x.inference)).toEqual(b.rows.map(x=>x.inference));expect(a.rows[3].affect).toEqual(['1/10','1/10']);expect(b.rows[3].affect).toEqual(['9/10','9/10']);});
it('meaningful simpler models preserve their different scope',async()=>{expect((await run('conflict')).observerView().rows[5].inference.status).toBe('Ambiguous');expect((await run('conflict','MotionOnly')).observerView().rows[5].inference.blockage).toBe('1/4');expect((await run('correction','OutcomeOnly')).observerView().rows[5].inference.blockage).toBe('1/2');expect((await run('correction','NoLearning')).observerView().rows.every(x=>x.inference.status==='Unknown')).toBe(true);});
it('absent evidence differs from false, success from failure, and current correction is not retroactive',async()=>{expect((await run('absent')).observerView().rows[5].inference.status).toBe('Ambiguous');expect((await run('unknownOutcome')).observerView().rows.every(x=>x.inference.status==='Unknown')).toBe(true);expect((await run('success')).observerView().rows[5].inference.status).toBe('NotFailure');expect((await run('late')).observerView().rows[5].inference.blockage).toBe('1/10');});
it('duplicate changed receipts and foreign episodes cannot correct the target',async()=>{for(const name of ['duplicate','foreign'] as const)expect((await run(name)).observerView().rows[5].inference.blockage).toBe('1/10');});
it('whole safe hidden and denied invariance holds for every model',async()=>{for(const law of LAWS){expect((await run('limitation',law)).observerView()).toEqual((await run('hidden',law)).observerView());expect((await run('denied',law)).observerView()).toEqual((await run('deniedChanged',law)).observerView());}});
it('all complete prefixes and successors restore, leaving earlier history fixed',async()=>{for(const law of LAWS){const r=create(law,cases().correction);for(let i=0;i<=6;i++){const before=r.observerView(),q=await restore(law,cases().correction,i,r.save());expect(q.save()).toEqual(r.save());expect(await q.step()).toBe(await r.step());expect(q.save()).toEqual(r.save());expect(r.observerView().rows.slice(0,i)).toEqual(before.rows);}}},60000);
it('faults and overlapping steps roll back all state and retry identically',async()=>{for(const fault of ['after-evidence','before-commit'] as const){const r=create('JointDiagnostics',cases().correction);await r.step();const saved=r.save();await expect(r.step(fault)).rejects.toThrow('LC_INJECTED');expect(r.save()).toEqual(saved);const q=await restore('JointDiagnostics',cases().correction,1,saved),pending=r.step();await expect(r.step()).rejects.toThrow('LC_CONCURRENT');await pending;await q.step();expect(r.save()).toEqual(q.save());}});
it('strict copied inputs and full save binding reject malformed or changed originals',async()=>{const f=cases().correction,r=create('JointDiagnostics',f);f[0].outcome=true;await r.step();expect(r.observerView().outcome).toBe(false);const bad=cases().correction;Object.defineProperty(bad[0],'motion',{get(){throw Error('GETTER');}});expect(()=>create('JointDiagnostics',bad)).toThrow('LC_DATA');const saved=r.save();saved[saved.length-1]^=1;await expect(restore('JointDiagnostics',cases().correction,1,saved)).rejects.toThrow('LC_SAVE_MISMATCH');await expect(restore('JointDiagnostics',cases().hidden,1,r.save())).rejects.toThrow('LC_SAVE_MISMATCH');});
