import {describe,it,expect} from 'vitest';
import {ExactRational as Q} from '../substrate/exactMath';
import {canonicalEncode,typedIdentifier,text,type CanonicalValue} from '../substrate/canonicalEncoding';
import {createLocalReserveSource,inspectLocalReserves,replenishLocalReserve} from '../campaign3/localReserveSource';
import {observeLocalReserveRecords,observeLocalReserveOpportunity,LOCAL_RESERVE_OBSERVATION_VERSION as version} from '../campaign3/localReserveObservation';
import {selectLocalReserveSignals,selectInteroceptiveSignals,consumeInteroceptiveSignals} from '../campaign3/interoceptiveSignalSelection';
import {admitLocalReserveSignalCue,admitBodySignalCue} from '../campaign3/bodySignalCue';
const q=(n:number)=>Q.of(BigInt(n)),observer=()=>typedIdentifier(1000,text('observer/a'));
function source(renamed=false,denied=false){return createLocalReserveSource(['A','B','C'].map(k=>({key:'local-reserve/'+(renamed?'renamed-':'')+k,capacity:q(100),rate:q(0),amount:q(k==='A'?0:20),anchoredAt:0n})),['A','B','C'].map(k=>({channel:'channel/'+k,physical:'local-reserve/'+(renamed?'renamed-':'')+k,signal:'interoceptive-signal/'+k,width:q(1),available:true,permitted:!denied})));}
function batch(s=source(),channels=['channel/A']){let n=0n;return {...observeLocalReserveRecords(s,observer(),2n,channels,()=>n++),opportunityId:9n};}
const field=(v:CanonicalValue,n:bigint)=>{if(typeof v==='boolean'||v.kind!=='record')throw Error('record');return v.fields.get(n)!;};
const limits={maxSignals:3,maxViewsPerSignal:3,maxBytesPerSignal:4096,capacity:0};
describe('actual local reserve canonical sample projection',()=>{
 it('LRO-A: requested actual zero sample owns one observation, with distinct producer version',()=>{const b=batch(),s=b.samples[0];expect(b.samples).toHaveLength(1);expect(field(s,6n)).toEqual(text(version));expect(field(field(s,5n),1n)).toMatchObject({kind:'rational',numerator:0n});expect(consumeInteroceptiveSignals(selectLocalReserveSignals(b,limits).view).groups).toEqual([]);expect(admitLocalReserveSignalCue(b,2n,true).cue).toEqual({kind:'Present',signals:['interoceptive-signal/A']});});
 it('LRO-B: old consumers reject new source, and exact new consumers reject old version substitution',()=>{const b=batch();expect(()=>selectInteroceptiveSignals(b,limits)).toThrow('wrong signal producer');expect(()=>admitBodySignalCue(b,2n,true)).toThrow();const altered=structuredClone(b);const s=altered.samples[0];if(typeof s==='boolean'||s.kind!=='record')throw Error('record');altered.samples[0]={...s,fields:new Map(s.fields).set(6n,text('embodied-level-observation/0.1-candidate'))};expect(()=>selectLocalReserveSignals(altered,limits)).toThrow('wrong signal producer');expect(()=>admitLocalReserveSignalCue(altered,2n,true)).toThrow();});
 it('LRO-C: hidden key renaming preserves bytes; requests are canonical and allocate only requested channels',()=>{const a=batch(source(),['channel/C','channel/A']),b=batch(source(true),['channel/A','channel/C']);expect(a.samples.map(canonicalEncode)).toEqual(b.samples.map(canonicalEncode));expect(a.declarations.map(d=>d.signal)).toEqual(['interoceptive-signal/A','interoceptive-signal/C']);expect(Object.keys(a).sort()).toEqual(['at','declarations','observer','opportunityId','samples']);});
 it('LRO-D: bad observer/channel requests reject before allocation; duplicate allocated observations reject',()=>{for(const channels of [[],['channel/A','channel/A'],['channel/unknown']]){let calls=0;expect(()=>observeLocalReserveRecords(source(),observer(),2n,channels,()=>{calls++;return 0n;})).toThrow();expect(calls).toBe(0);}let calls=0;expect(()=>observeLocalReserveRecords(source(),typedIdentifier(1002,text('not-observer')),2n,['channel/A'],()=>{calls++;return 0n;})).toThrow();expect(calls).toBe(0);expect(()=>observeLocalReserveRecords(source(),observer(),2n,['channel/A','channel/B'],()=>0n)).toThrow('LOCAL_OBSERVATION_ALLOCATION');});
 it('LRO-E: unavailable is explicit and unrequested future channel is not queried',()=>{const b=batch(source(false,true));expect(b.samples[0]).toMatchObject({kind:'record',schema:{typeId:463n}});expect(admitLocalReserveSignalCue(b,2n,true).cue).toEqual({kind:'Absent'});const futureB=replenishLocalReserve(source(),'local-reserve/B',5n,q(0));expect(()=>batch(futureB,['channel/A'])).not.toThrow();expect(()=>batch(futureB,['channel/B'])).toThrow();});
 it('LRO-F: observations do not mutate physical state and detach caller observer data',()=>{const s=source(),before=inspectLocalReserves(s),o=observer();const b=observeLocalReserveRecords(s,o,2n,['channel/A'],()=>0n),bytes=b.samples.map(canonicalEncode),observerBytes=canonicalEncode(b.observer);if(typeof o.payload==='boolean'||o.payload.kind!=='text')throw Error('text');(o.payload as {value:string}).value='observer/changed';expect(b.samples.map(canonicalEncode)).toEqual(bytes);expect(canonicalEncode(b.observer)).toEqual(observerBytes);expect(inspectLocalReserves(s)).toEqual(before);});
});
describe('body-only SEM opportunity reservation',()=>{
 it('LRO-G: all present views share one actual reservation in either lane',()=>{for(const lane of ['Current','Consequence'] as const){let n=0n;const b=observeLocalReserveOpportunity(source(),observer(),2n,['channel/A','channel/B','channel/C'],lane,()=>n++);expect(n).toBe(4n);expect(b.opportunityId).toBe(3n);expect(b.staged?.reservation.lane).toBe(lane);expect(b.staged?.stagedAtPhase).toBe(lane==='Current'?14n:124n);expect(b.staged?.experience.supportingObservationIds.map(s=>s.observationId)).toEqual([0n,1n,2n]);expect(b.staged?.experience.perceptualEventReferentIds).toEqual([]);}});
 it('LRO-H: all-unavailable observation has no fake experience, but can complete empty selection',()=>{let n=0n;const b=observeLocalReserveOpportunity(source(false,true),observer(),2n,['channel/A','channel/B'],'Current',()=>n++);expect(n).toBe(2n);expect(b.opportunityId).toBeNull();expect(b.staged).toBeNull();expect(consumeInteroceptiveSignals(selectLocalReserveSignals(b,limits).view)).toMatchObject({opportunityId:null,groups:[]});expect(admitLocalReserveSignalCue(b,2n,true)).toMatchObject({cue:{kind:'Absent'},provenance:{opportunityId:null,supportingObservationIds:[]}});});
 it('LRO-I: present samples cannot enter either gate with a null experience',()=>{const b={...batch(),opportunityId:null};expect(()=>selectLocalReserveSignals(b,limits)).toThrow('present sample requires experience');expect(()=>admitLocalReserveSignalCue(b,2n,true)).toThrow();expect(()=>admitLocalReserveSignalCue(b,2n,false)).toThrow();});
 it('LRO-J: invalid lane rejects before any observation allocation',()=>{let n=0n;expect(()=>observeLocalReserveOpportunity(source(),observer(),2n,['channel/A'],'Invalid' as 'Current',()=>n++)).toThrow('LOCAL_OBSERVATION_LANE');expect(n).toBe(0n);});
});
