import {it,expect,vi} from 'vitest';
import {createLongitudinalGoalRun as create,restoreLongitudinalGoalRun as restore,originalInputs,type Law,type GoalMode} from '../campaign3/longitudinalGoal';
import {longitudinalInputs,longitudinalScenario} from './longitudinalFixtures';
vi.setConfig({testTimeout:300000});
async function run(law:Law='FineStanding',mode:GoalMode='Maintained',keep=false){const r=await create(law,mode,0,keep);for(let i=0;i<9;i++)await r.step();return r;}
it('the source bytes are the unchanged native LONG scenario',()=>{expect(originalInputs()).toEqual(longitudinalInputs(longitudinalScenario()));});
it('an actually adopted goal and acquired standing survive actual recent episode expiry',async()=>{const r=await run(),s=r.snapshot(),before=s.rows[7],after=s.rows[8];expect(before.episodes).toBeGreaterThan(0);expect(after.episodes).toBe(0);expect(after.standing).toBe(before.standing);expect(after.standing).not.toBe('0/1');expect(after.goalsBefore[0]).toMatchObject({status:'Open',adoptedAt:'1',activeFrom:'2'});expect(after.choice.chosen).not.toBeNull();expect(before.choice.chosen).toBeNull();});
it('current goal changes leave every native source save and acquired history unchanged',async()=>{const a=await run(),b=await run('FineStanding','Withdrawn'),c=await run('FineStanding','Replaced');expect(a.nativeSave()).toEqual(b.nativeSave());expect(a.nativeSave()).toEqual(c.nativeSave());const [x,y,z]=[a,b,c].map(r=>r.snapshot().rows[8]);expect(y.goalsBefore[0].status).toBe('Withdrawn');expect(z.goalsBefore.map(g=>g.status)).toEqual(['Withdrawn','Open']);expect(x.choice.probabilities).not.toEqual(y.choice.probabilities);expect(x.choice.probabilities).not.toEqual(z.choice.probabilities);expect(x.standing).toBe(z.standing);});
it('NoFeedback preserves acquired biography and goal but removes its later reason modifier',async()=>{const a=await run(),b=await run('NoFeedback');expect(a.nativeSave()).toEqual(b.nativeSave());const x=a.snapshot().rows[8],y=b.snapshot().rows[8];expect(x.standing).toBe(y.standing);expect(y.usedStanding).toBe(0);expect(x.choice.probabilities).not.toEqual(y.choice.probabilities);const coarse=(await run('SeparateOwners')).snapshot().rows[8];expect(coarse.choice.probabilities).toEqual(y.choice.probabilities);});
it('keeping episodes is distinct from keeping a goal or standing; opportunity loss is not retirement',async()=>{const a=await run(),b=await run('FineStanding','Maintained',true),c=await run('GoalEqualsOpportunity');const [x,y,z]=[a,b,c].map(r=>r.snapshot().rows[8]);expect(y.episodes).toBeGreaterThan(0);expect(x.choice).toEqual(y.choice);expect(x.standing).toBe(y.standing);expect(z.goalsBefore[0].status).toBe('Withdrawn');expect(z.choice.probabilities).not.toEqual(x.choice.probabilities);});
it('publication is guarded across the native join and fault rollback reproduces original source',async()=>{for(const fault of ['after-source','after-choice','before-commit'] as const){const r=await create('SeparateOwners','Maintained');await r.step();const before=r.save(),source=r.nativeSave(),pending=r.step(fault);for(const read of [r.save,r.snapshot,r.nativeSave])expect(read).toThrow('LG_BUSY');await expect(r.step()).rejects.toThrow('LG_CONCURRENT');await expect(pending).rejects.toThrow('LG_INJECTED');expect(r.save()).toEqual(before);expect(r.nativeSave()).toEqual(source);await r.step();expect(r.snapshot().prefix).toBe(2);}});
it('joined restore binds source plus goal state and reproduces the gap successor',async()=>{const r=await create('SeparateOwners','Replaced');for(let i=0;i<8;i++)await r.step();const s=await restore('SeparateOwners','Replaced',0,false,8,r.save());await r.step();await s.step();expect(s.save()).toEqual(r.save());await expect(restore('NoFeedback','Replaced',0,false,8,s.save())).rejects.toThrow('LG_SAVE_MISMATCH');});
