import {it,expect} from 'vitest';
import {canonicalEncode as enc,list,map,rational as q,type CanonicalValue} from '../substrate/canonicalEncoding';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {longitudinalRecipe,compileLongitudinalModel,compileLongitudinalInputs,OBSERVER,ACTOR,STAGES,eventId,stageReads,path,type LongitudinalSettings} from '../campaign3/longitudinalModel';
import {prepareLongitudinalModel,createLongitudinalRun,restoreLongitudinalRun} from '../campaign3/longitudinalFactory';
import {createLongitudinalRuntime} from '../campaign3/longitudinalRuntime';
import {decodeLongitudinal as decode} from '../campaign3/longitudinalCodecs';
import {statePathValue,applyStatePatch} from '../substrate/state';
import {longitudinalInputs,longitudinalScenario,type LongitudinalInput} from './longitudinalFixtures';
const seed=new Uint8Array(32);
async function setup(settings:Partial<LongitudinalSettings>={},xs:readonly LongitudinalInput[]=longitudinalScenario()){const source=longitudinalRecipe(settings),model=await compileLongitudinalModel(source),initialState=enc(model.initial.canonicalValue()),orderedInputs=longitudinalInputs(xs),input=await compileLongitudinalInputs(model,initialState,orderedInputs,seed);return {source,model,initialState,orderedInputs,input};}
async function run(settings:Partial<LongitudinalSettings>={},xs:readonly LongitudinalInput[]=longitudinalScenario()){const x=await setup(settings,xs),run=await createLongitudinalRun(await prepareLongitudinalModel(x.source),{initialState:x.initialState,orderedInputs:x.orderedInputs,runSeed:seed}),views=new Map<bigint,ReturnType<typeof rec>>();while(await run.settleNextInstant())views.set(run.snapshot().clock,rec(decode(run.observerView(enc(OBSERVER))),881n));return {...x,run,views};}
const projection=(v:ReturnType<typeof rec>)=>[2n,3n,4n].map(n=>f(v,n));
const outputs=(x:Awaited<ReturnType<typeof run>>,type:bigint)=>items(decode(x.run.snapshot().outputs),'list').filter(v=>typeof v!=='boolean'&&v.kind==='record'&&v.schema.typeId===type).map(v=>rec(v,type));
const decisions=(x:Awaited<ReturnType<typeof run>>)=>outputs(x,409n).map(v=>rec(f(rec(f(v,4n),419n),2n),420n));
const effective=(d:ReturnType<typeof rec>)=>uint(f(d,8n))===1n?f(d,1n):f(d,2n);
it('acquires all three families publicly and retains learned state after actual episode expiry',async()=>{const x=await run(),v=x.views.get(8n)!,lost=x.views.get(14n)!;expect(f(v,2n)).not.toEqual(q(0,1));expect(f(rec(f(v,3n),784n),1n)).toEqual(q(1,2));expect(f(rec(f(v,4n),851n),1n)).toEqual({kind:'unsigned',value:2n});expect(projection(lost)).toEqual(projection(v));expect(items(f(rec(f(lost,5n),866n),1n),'list')).toHaveLength(0);expect(f(rec(f(lost,6n),869n),1n)).toBe(true);expect(outputs(x,426n).length).toBe(16);expect(outputs(x,398n).length).toBe(16);expect(items(f(outputs(x,398n)[0],3n),'list')).toHaveLength(2);},180000);
it('full and compact history match learned projections under both laws; episodic-only and shared-slot fail',async()=>{for(const law of [1,2]){const a=await run({law}),b=await run({representation:1,law});for(const [at,v]of a.views)expect(projection(v)).toEqual(projection(b.views.get(at)!));expect(decisions(a).map(effective)).toEqual(decisions(b).map(effective));expect(b.views.get(14n)!.fields.has(7n)).toBe(true);}const ep=await run({representation:3}),shared=await run({representation:4});expect(f(rec(f(ep.views.get(14n)!,4n),851n),1n)).toEqual({kind:'unsigned',value:0n});expect(f(shared.views.get(6n)!,2n)).toEqual(q(0,1));expect(f(rec(f(shared.views.get(6n)!,3n),784n),1n)).toEqual(q(0,1));},300000);
it('matches isolated family projections and preserves target-only interference and later relearning',async()=>{const xs=longitudinalScenario(),a=await run(),clean=await run({},xs.map(x=>x.at===16?{...x,interference:false}:x));for(const family of [1,2,3]){const b=await run({family});for(const [at,v]of a.views)expect(f(v,BigInt(family+1))).toEqual(f(b.views.get(at)!,BigInt(family+1)));}const v=a.views.get(16n)!,c=clean.views.get(16n)!;expect(f(v,2n)).toEqual(f(c,2n));expect(f(v,4n)).toEqual(f(c,4n));expect(f(v,3n)).not.toEqual(f(c,3n));expect(f(rec(f(a.views.get(17n)!,3n),784n),1n)).toEqual(q(1,2));},300000);
it('keeps fixed displays independent of truth and distinguishes absence, false claims and denied participation',async()=>{const xs=longitudinalScenario().slice(0,8).map(x=>x.kind===3?{...x,display:1}:x),a=await run({},xs),b=await run({},xs.map(x=>x.kind===3?{...x,physical:false}:x));expect(a.run.observerView(enc(OBSERVER))).toEqual(b.run.observerView(enc(OBSERVER)));const denied=await run({},xs.map(x=>x.kind===3?{...x,access:false}:x)),witness=await run({},xs.map(x=>x.kind===3?{...x,participant:false}:x));expect(f(denied.views.get(8n)!,4n)).toEqual(f(witness.views.get(8n)!,4n));const absent=await run({},[{at:1}]),negative=await run({},[{at:1,kind:4,physical:false}]);expect(absent.views.get(1n)!.fields.has(6n)).toBe(false);expect(f(rec(f(negative.views.get(1n)!,6n),869n),1n)).toBe(false);},240000);
it('standing changes effective later choice while the preserved predecessor fails that gate',async()=>{const xs=longitudinalScenario().slice(0,3),a=await run({},xs),off=await run({standing:false},xs);expect(effective(decisions(a)[2])).not.toEqual(effective(decisions(off)[2]));expect(outputs(a,426n)[0]).toEqual(outputs(off,426n)[0]);const old=await run({revision:1},xs),oldOff=await run({revision:1,standing:false},xs);expect(decisions(old).map(effective)).toEqual(decisions(oldOff).map(effective));},240000);
it('audits every declared read and sole owner, and restores an authenticated complete prefix',async()=>{const x=await setup({},longitudinalScenario().slice(0,3)),runtime=createLongitudinalRuntime(x.model,x.input);while(await runtime.settle()){}for(const [name]of STAGES){for(const t of runtime.snapshot().trace.map(v=>rec(v,160n)).filter(t=>key(f(t,7n))===key(eventId(name))))expect(items(f(t,11n),'list').map(v=>f(rec(v,147n),2n))).toEqual(stageReads(name,x.model.settings).map(statePathValue));}const state=runtime.snapshot().state,value=state.read(path(871)).value!;expect(()=>applyStatePatch(state,{operations:[{kind:'set',path:path(871),expected:{presence:true,value},newValue:value}]},OBSERVER,x.model.authority)).toThrow();const restored=await restoreLongitudinalRun(x.source,{initialState:x.initialState,orderedInputs:x.orderedInputs,save:runtime.save()});expect(restored.save()).toEqual(runtime.save());expect(()=>restored.observerView(enc(ACTOR))).toThrow();},180000);
it('rejects forged saves, injected learned state, malformed originals and getters',async()=>{const x=await run({},[{at:1,kind:1}]),save=x.run.save();for(const field of [8n,11n,12n]){const saved=rec(decode(save),132n),fields=new Map(saved.fields);fields.set(field,field===8n?map([]):list([]));await expect(restoreLongitudinalRun(x.source,{initialState:x.initialState,orderedInputs:x.orderedInputs,save:enc({...saved,fields})})).rejects.toThrow();}for(const xs of [[{at:0}],[{at:65}],[{at:1},{at:1}],Array.from({length:17},(_,i)=>({at:i+1}))])await expect(setup({},xs)).rejects.toThrow();const handle=await prepareLongitudinalModel(x.source);await expect(createLongitudinalRun(handle,{initialState:x.run.snapshot().state,orderedInputs:x.orderedInputs,runSeed:seed})).rejects.toThrow();let called=false;await expect(createLongitudinalRun(handle,{initialState:x.initialState,orderedInputs:x.orderedInputs,get runSeed(){called=true;return seed;}})).rejects.toThrow();expect(called).toBe(false);},180000);
it('rolls back every reached stage and commit, including actual practice/memory writes and RNG',async()=>{for(const name of [...STAGES.map(([n])=>n),'commit']){const x=await setup({},longitudinalScenario().slice(0,3)),runtime=createLongitudinalRuntime(x.model,x.input);await runtime.settle();await runtime.settle();const before=runtime.snapshot(),view=runtime.view(OBSERVER);let reached=false;await expect(runtime.settleForConformance({onBoundary(b,e){if(name==='commit'?b==='before-commit':b==='after-trace-validation'&&e!==undefined&&key(e.eventTypeId)===key(eventId(name))){reached=true;throw Error('longitudinal fault');}}})).rejects.toThrow();expect(reached).toBe(true);const after=runtime.snapshot();expect(after.status).toBe('Failed');expect(enc(after.state.canonicalValue())).toEqual(enc(before.state.canonicalValue()));for(const k of ['queue','allocators','outputs','trace']as const)expect(after[k]).toEqual(before[k]);expect(runtime.view(OBSERVER)).toEqual(view);}},300000);
