import {describe,it,expect} from 'vitest';
import {ExactRational as Q} from '../substrate/exactMath';
import {adoptMaintenanceGoal,settleMaintenanceGoal,settleMaintenanceGoalDeadline,readMaintenanceConcern} from '../campaign3/bodilyMaintenanceGoal';
const interval=(lo:bigint,hi:bigint)=>({lower:Q.of(lo),upper:Q.of(hi)}),domains=new Map([['signal/a',interval(0n,100n)]]);
const adopted=()=>adoptMaintenanceGoal([],{character:'character/a',goal:'goal/a',signal:'signal/a',desired:interval(30n,40n),adoptedAt:1n,activeFrom:1n,expiresAt:100n},domains);
describe('authenticated-deadline owner guard component',()=>{
 it('GD-A: an open goal expires exactly at its deadline and becomes explicitly unavailable',()=>{const prior=adopted(),r=settleMaintenanceGoalDeadline(prior,'character/a','goal/a',100n,domains);expect(r.kind).toBe('Expired');expect(r.state[0]).toMatchObject({status:'Expired',changedAt:100n});expect(prior[0].status).toBe('Open');expect(readMaintenanceConcern(r.state,'character/a','goal/a',100n,domains)).toEqual({kind:'Unavailable',reason:'Expired'});});
 it('GD-B: a withdrawn goal has equal component data at deadline, without rewriting its terminal history',()=>{const prior=settleMaintenanceGoal(adopted(),'character/a','goal/a',70n,'Withdraw',domains),r=settleMaintenanceGoalDeadline(prior,'character/a','goal/a',100n,domains);expect(r.kind).toBe('AlreadyWithdrawn');expect(r.state).toEqual(prior);expect(r.state).not.toBe(prior);expect(r.state[0].desired).not.toBe(prior[0].desired);expect(r.state[0].changedAt).toBe(70n);expect(()=>settleMaintenanceGoal(prior,'character/a','goal/a',100n,'Expire',domains)).toThrow('GOAL_LIFECYCLE_TARGET');});
 it('GD-C: wrong time, foreign target, missing target and repeated expiration reject',()=>{const prior=adopted();for(const at of [99n,101n])expect(()=>settleMaintenanceGoalDeadline(prior,'character/a','goal/a',at,domains)).toThrow('GOAL_DEADLINE_TIME');expect(()=>settleMaintenanceGoalDeadline(prior,'character/b','goal/a',100n,domains)).toThrow('GOAL_DEADLINE_TARGET');expect(()=>settleMaintenanceGoalDeadline([],'character/a','goal/a',100n,domains)).toThrow('GOAL_DEADLINE_TARGET');const r=settleMaintenanceGoalDeadline(prior,'character/a','goal/a',100n,domains);expect(()=>settleMaintenanceGoalDeadline(r.state,'character/a','goal/a',100n,domains)).toThrow('GOAL_DEADLINE_TARGET');});
});
