import {describe,it,expect} from 'vitest';
import {createMarkerTracker,createNineSweepMarkerTracker,applyMarkerSweep,markerTrackingSnapshot,type MarkerSweep} from '../campaign3/observedMarkerTracking';
import {createMarkerTransactionManager,createNineSweepMarkerTransactionManager as create,beginMarkerTransaction as begin,previewMarkerTransaction as preview,commitMarkerTransaction as commit,abortMarkerTransaction as abort,committedMarkerSnapshot as snapshot} from '../campaign3/transactionalMarkerTracking';
import {createPositionDisplaySource,createNineFramePositionDisplaySource,observePositionDisplay} from '../campaign3/positionDisplaySource';
const observer='observer/a',sweep=(i:number,missing=false,count=1):MarkerSweep=>({observerId:observer,observationId:BigInt(i*10),occurredAt:BigInt(i),detections:Array.from({length:count},(_,j)=>({detectionId:BigInt(i*10+j+1),...(missing?{}:{glyph:BigInt(j)})}))});
describe('explicit ninth cue sweep successor',()=>{
 it('N9-A: old constructor still rejects ninth; new one admits ninth and rejects tenth',()=>{const old=createMarkerTracker(observer),fresh=createNineSweepMarkerTracker(observer);for(let i=1;i<=8;i++){expect(applyMarkerSweep(fresh,sweep(i))).toEqual(applyMarkerSweep(old,sweep(i)));}expect(()=>applyMarkerSweep(old,sweep(9))).toThrow('horizon');const cue=applyMarkerSweep(fresh,sweep(9));expect(cue[0].continuityKind).toBe('ContinuesPriorTrack');expect(cue[0].perceptualReferentId.observerTrackSequence).toBe(0n);expect(()=>applyMarkerSweep(fresh,sweep(10))).toThrow('horizon');});
 it('N9-B: successor caps each sweep at three and therefore admits at most27 new files',()=>{const tracker=createNineSweepMarkerTracker(observer),before=markerTrackingSnapshot(tracker);expect(()=>applyMarkerSweep(tracker,sweep(1,true,4))).toThrow('bounded detections');expect(markerTrackingSnapshot(tracker)).toEqual(before);for(let i=1;i<=9;i++)applyMarkerSweep(tracker,sweep(i,true,3));expect(markerTrackingSnapshot(tracker).state.nextTrackSequenceByObserver.get(observer)).toBe(27n);});
 it('N9-C: every prefix reconstructs the ninth outcome and preserves the tenth rejection',()=>{const history=Array.from({length:9},(_,i)=>sweep(i+1)),expected=create(observer,history);for(let n=0;n<=9;n++){const m=create(observer,history.slice(0,n));for(const s of history.slice(n))commit(m,begin(m,s));expect(snapshot(m)).toEqual(snapshot(expected));expect(()=>begin(m,sweep(10))).toThrow();}expect(()=>createMarkerTransactionManager(observer,history)).toThrow('bounded prefix');});
 it('N9-D: aborted ninth can retry with the same ordinals and cannot be committed twice',()=>{const m=create(observer,Array.from({length:8},(_,i)=>sweep(i+1))),before=snapshot(m),a=begin(m,sweep(9)),candidate=preview(m,a);abort(m,a);expect(snapshot(m)).toEqual(before);const b=begin(m,sweep(9));expect(preview(m,b)).toEqual(candidate);commit(m,b);expect(()=>commit(m,b)).toThrow();expect(()=>begin(m,sweep(9))).toThrow();});
 it('N9-E: ninth display frame is explicit; the old constructor and missing-time behavior remain intact',()=>{const frames=Array.from({length:9},(_,i)=>({at:BigInt(i+1),x:0n,y:0n,glyph:0n,visible:true,permitted:true}));expect(()=>createPositionDisplaySource(frames)).toThrow();const s=createNineFramePositionDisplaySource(frames);expect(observePositionDisplay(s,9n).kind).toBe('Present');expect(observePositionDisplay(s,10n)).toEqual({kind:'Unavailable',at:10n});expect(()=>createNineFramePositionDisplaySource([...frames,{...frames[0],at:10n}])).toThrow();});
});
