import {describe,it,expect} from 'vitest';
import {createTrialPanelPerception,consumeTrialPanelAndVisual,prepareTrialPanelConsumption,trialPanelPerceptionSnapshot,type VisualEventDetection} from '../campaign3/trialPanelPerception';
const observer='observer/a';
const panel=(at:bigint,present:boolean)=>({observer,observation:at*10n,...(present?{detection:at*10n+2n}:{}),sample:present?{kind:'Present' as const,at,glyph:0,stage:'Motion' as const}:{kind:'Unavailable' as const,at}});
const visual=(at:bigint):VisualEventDetection=>({observer,observation:at*10n+1n,detection:at*10n+2n,at});
describe('panel/visual one event-file owner',()=>{
 it('PVE-A: present panel and visual reuse one actual event detection and file',()=>{const token=createTrialPanelPerception(observer),r=consumeTrialPanelAndVisual(token,panel(1n,true),visual(1n));expect(r.visualEventTransition).toEqual(r.transition);expect(r.context).toEqual(r.visualEventTransition?.perceptualEventReferentId);expect(trialPanelPerceptionSnapshot(token).detections).toEqual([12n]);expect(trialPanelPerceptionSnapshot(token).files.activeEventFiles).toHaveLength(1);});
 it('PVE-B: unavailable panel still permits visual event, without invented context or counter collision',()=>{const token=createTrialPanelPerception(observer),a=consumeTrialPanelAndVisual(token,panel(1n,true),visual(1n)),gap=consumeTrialPanelAndVisual(token,panel(2n,false),visual(2n));expect(gap.context).toBeUndefined();expect(gap.stage).toBeUndefined();expect(gap.transition).toBeUndefined();expect(gap.visualEventTransition?.continuityKind).toBe('NewEventFile');expect(gap.visualEventTransition?.perceptualEventReferentId.observerEventSequence).toBe(1n);expect(gap.ends).toHaveLength(2);expect(trialPanelPerceptionSnapshot(token).files.activeEventFiles).toEqual([]);const b=consumeTrialPanelAndVisual(token,panel(3n,true),visual(3n));expect(a.context?.observerEventSequence).toBe(0n);expect(b.context?.observerEventSequence).toBe(2n);});
 it('PVE-C: no visual observation creates no fallback; consecutive fallbacks never establish trial continuity',()=>{const token=createTrialPanelPerception(observer);expect(consumeTrialPanelAndVisual(token,panel(1n,false),undefined).visualEventTransition).toBeUndefined();const a=consumeTrialPanelAndVisual(token,panel(2n,false),visual(2n)),b=consumeTrialPanelAndVisual(token,panel(3n,false),visual(3n));expect(a.context).toBeUndefined();expect(b.context).toBeUndefined();expect(a.visualEventTransition?.perceptualEventReferentId).not.toEqual(b.visualEventTransition?.perceptualEventReferentId);expect(trialPanelPerceptionSnapshot(token).files.activeEventFiles).toEqual([]);});
 it('PVE-D: wrong observer/time/detection or replay rejects atomically before replacing trial context',()=>{const token=createTrialPanelPerception(observer);consumeTrialPanelAndVisual(token,panel(1n,true),visual(1n));const before=trialPanelPerceptionSnapshot(token),good=visual(2n);for(const bad of [{...good,observer:'foreign'},{...good,at:1n},{...good,detection:99n},{...good,observation:11n},{...good,observation:20n}]){expect(()=>consumeTrialPanelAndVisual(token,panel(2n,true),bad)).toThrow();expect(trialPanelPerceptionSnapshot(token)).toEqual(before);}expect(()=>consumeTrialPanelAndVisual(token,{...panel(2n,false),observation:11n},undefined)).toThrow();expect(trialPanelPerceptionSnapshot(token)).toEqual(before);});
 it('PVE-E: malformed fallback cannot close a valid prior context',()=>{const token=createTrialPanelPerception(observer);consumeTrialPanelAndVisual(token,panel(1n,true),undefined);const before=trialPanelPerceptionSnapshot(token);expect(()=>consumeTrialPanelAndVisual(token,panel(2n,false),{...visual(2n),detection:12n})).toThrow();expect(trialPanelPerceptionSnapshot(token)).toEqual(before);});
 it('PVE-F: returned context cannot mutate the retained perception window',()=>{const token=createTrialPanelPerception(observer),r=consumeTrialPanelAndVisual(token,panel(1n,true),visual(1n)),before=trialPanelPerceptionSnapshot(token);(r.context! as {observerEventSequence:bigint}).observerEventSequence=99n;expect(trialPanelPerceptionSnapshot(token)).toEqual(before);expect(consumeTrialPanelAndVisual(token,panel(2n,true),visual(2n)).context?.observerEventSequence).toBe(0n);});
 it('PVE-G: prepare/close and stale commit cannot publish a different context',()=>{const token=createTrialPanelPerception(observer),before=trialPanelPerceptionSnapshot(token),a=prepareTrialPanelConsumption(token,panel(1n,true)),b=prepareTrialPanelConsumption(token,panel(1n,true));expect(trialPanelPerceptionSnapshot(token)).toEqual(before);a.close();expect(()=>a.commit()).toThrow('STALE_TRANSACTION');b.commit();const committed=trialPanelPerceptionSnapshot(token);expect(()=>b.commit()).toThrow('STALE_TRANSACTION');expect(trialPanelPerceptionSnapshot(token)).toEqual(committed);const c=prepareTrialPanelConsumption(token,panel(2n,true)),d=prepareTrialPanelConsumption(token,panel(3n,false));c.commit();const after=trialPanelPerceptionSnapshot(token);expect(()=>d.commit()).toThrow('STALE_TRANSACTION');expect(trialPanelPerceptionSnapshot(token)).toEqual(after);});
});
