import {describe,it,expect} from 'vitest';
import {applyPerceptualEventTransition,emptyPerceptualEventFileState,assemblePreRecognitionExperience,type PerceptualEventReferentId} from '../semanticBinding/perceptualEventFiles';
import {groupPerceivedTrial as group,groupPerceivedPositionTrial as pair} from '../campaign3/perceivedTrialGrouping';
const observer='observer/a';
const event=()=>applyPerceptualEventTransition(emptyPerceptualEventFileState(),{observerId:observer,currentEventDetectionId:{observerId:observer,eventDetectionOccurrenceId:10n},continuityKind:'NewEventFile',supportingObservationIds:[{observerId:observer,observationId:9n}],occurredAt:0n,transformationVersion:'perceptual-event-files/0.1-candidate'}).transition.perceptualEventReferentId;
const experience=(id:bigint,at:bigint,context:PerceptualEventReferentId)=>assemblePreRecognitionExperience({experienceId:id,observerId:observer,occurredAt:at,perceptualEventReferentIds:[context],perceivedBindings:[],perceptualClassifications:[],perceptualEventClassifications:[],supportingObservationIds:[{observerId:observer,observationId:id+100n}],transformationVersion:'semantic-binding/0.1-candidate'});
const rows=(context=event())=>[{role:'Before' as const,experience:experience(20n,1n,context)},{role:'Motion' as const,experience:experience(5n,2n,context)},{role:'After' as const,experience:experience(1n,3n,context)}];
describe('explicit SEM event-file trial grouping',()=>{
 it('PG-A: actual SEM event-file identity groups roles independently of carrier/ordinal order',()=>{const c=event(),r=rows(c);expect(group(observer,c,r)).toEqual(group(observer,c,[r[2],r[0],r[1]]));expect(group(observer,c,r)).toMatchObject({kind:'Grouped',beforeExperience:20n,motionExperience:5n,afterExperience:1n});});
 it('PG-B: losing context removes grouping despite identical available observations',()=>{const r=rows();expect(group(observer,null,r)).toEqual({kind:'Unavailable',reason:'MissingContext'});expect(group(observer,event(),r).kind).toBe('Grouped');});
 it('PG-C: a different event-file cannot fill a role through proximity or ordinal matching',()=>{const c=event(),r=rows(c);r[2]={...r[2],experience:experience(1n,3n,{...c,observerEventSequence:1n})};expect(group(observer,c,r)).toEqual({kind:'Unavailable',reason:'IncompleteContext'});});
 it('PG-D: ambiguous role is unavailable and wrong observer/duplicate occurrence reject',()=>{const c=event(),r=rows(c);expect(group(observer,c,[...r,{role:'Before',experience:experience(33n,1n,c)}])).toEqual({kind:'Unavailable',reason:'AmbiguousRole'});expect(()=>group('observer/b',c,r)).toThrow();expect(()=>group(observer,c,[...r,r[0]])).toThrow('DUPLICATE');});
 it('PG-E: temporal role constraints are checked but not used to infer missing roles',()=>{const c=event(),r=rows(c);r[2]={...r[2],experience:experience(1n,2n,c)};expect(()=>group(observer,c,r)).toThrow('ORDER');expect(group(observer,c,r.slice(0,2))).toEqual({kind:'Unavailable',reason:'IncompleteContext'});});
});
describe('explicit SEM context with two retained positions',()=>{
 const positioned=(c=event())=>[{role:'Before' as const,experience:experience(20n,1n,c)},{role:'Motion' as const,experience:experience(100n,2n,c)},{role:'Motion' as const,experience:experience(1n,3n,c)},{role:'After' as const,experience:experience(2n,4n,c)}];
 it('PGP-A: actual observed time orders positions independently of carrier and occurrence order',()=>{const c=event(),r=positioned(c),a=pair(observer,c,r);expect(a).toEqual(pair(observer,c,[...r].reverse()));expect(a).toMatchObject({kind:'Grouped',startExperience:100n,endExperience:1n,beforeExperience:20n,afterExperience:2n});});
 it('PGP-B: no pair is inferred from missing or excess role members',()=>{const c=event(),r=positioned(c);expect(pair(observer,c,r.filter((_,i)=>i!==1))).toEqual({kind:'Unavailable',reason:'IncompleteContext'});expect(pair(observer,c,[...r,{role:'Motion',experience:experience(99n,3n,c)}])).toEqual({kind:'Unavailable',reason:'AmbiguousRole'});expect(pair(observer,null,r)).toEqual({kind:'Unavailable',reason:'MissingContext'});});
 it('PGP-C: simultaneous positions, foreign observer and duplicate experience reject',()=>{const c=event(),r=positioned(c);r[2]={...r[2],experience:experience(1n,2n,c)};expect(()=>pair(observer,c,r)).toThrow('ORDER');expect(()=>pair('observer/b',c,r)).toThrow('OBSERVER');expect(()=>pair(observer,c,[...r,r[0]])).toThrow('DUPLICATE');expect(()=>pair('',null,[])).toThrow('OBSERVER');});
});
