import {describe,it,expect} from 'vitest';
import {canonicalEncode} from '../substrate/canonicalEncoding';
import {semanticReferentFromAuthoredContent} from '../substrate/referentOrigin';
import {governedContentDefinitionId} from '../substrate/contentDefinitionId';
import {EventRoleId} from '../semanticBinding/eventBindings';
import {decodeSemanticValue} from '../semanticBinding/semanticCodecs';
import {createPositionSceneSource,materializePositionScene,type PositionSceneItem} from '../campaign3/positionSceneSource';
const item=(name:string,x:bigint):PositionSceneItem=>({marker:semanticReferentFromAuthoredContent(governedContentDefinitionId(name)),role:EventRoleId.Actor,x,y:0n,glyph:x,visible:true,permitted:true,roleMode:'Preserve'});
const run=(items:readonly PositionSceneItem[])=>{let n=0n;const r=materializePositionScene(createPositionSceneSource([{at:1n,items}]),1n,()=>n++);return {...r,allocated:n};};
describe('materialized bounded position scene',()=>{
 it('PSS-A: actual world/binding records precede the safe projection without exposing their identities',()=>{const r=run([item('object/c',2n),item('object/a',0n),item('object/b',1n)]);expect(r.allocated).toBe(4n);expect(canonicalEncode(decodeSemanticValue(canonicalEncode(r.truth)))).toEqual(canonicalEncode(r.truth));expect(r.truth).toMatchObject({kind:'record',schema:{typeId:210n}});expect(Object.keys(r.safe).sort()).toEqual(['at','items']);expect(r.safe.items.map(i=>i.position.x)).toEqual([0n,1n,2n]);for(const i of r.safe.items){expect(Object.keys(i).sort()).toEqual(['glyph','position','role']);expect(i.role).toEqual({kind:'exact',eventRoleId:EventRoleId.Actor});}});
 it('PSS-B: renaming hidden markers or reordering source items cannot reorder safe output',()=>{const a=[item('object/a',2n),item('object/b',0n)],b=[item('object/z',2n),item('object/y',0n)];expect(run(a).safe).toEqual(run([...a].reverse()).safe);expect(run(a).safe).toEqual(run(b).safe);expect(canonicalEncode(run(a).truth)).not.toEqual(canonicalEncode(run(b).truth));});
 it('PSS-C: denied/hidden and unresolved roles do not reveal inaccessible truth',()=>{const a=item('object/a',0n);expect(run([{...a,visible:false}]).safe).toEqual(run([{...a,permitted:false}]).safe);expect(run([{...a,visible:false}]).safe.items).toEqual([]);expect(run([{...a,roleMode:'Unresolved'}]).safe).toEqual(run([{...a,role:EventRoleId.Beneficiary,roleMode:'Unresolved'}]).safe);expect(run([{...a,roleMode:'Unresolved'}]).safe.items[0].role).toEqual({kind:'unresolved'});});
 it('PSS-D: exact finite data and unique markers reject before any runtime allocation',()=>{let getter=false;const a=item('object/a',0n);for(const items of [[a,a],[a,item('object/b',1n),item('object/c',2n),item('object/d',3n)],[{...a,get x(){getter=true;return 0n;}}],[{...a,role:EventRoleId.Action}],[{...a,x:8n}],[{...a,significance:true}]])expect(()=>createPositionSceneSource([{at:1n,items}])).toThrow();expect(getter).toBe(false);expect(()=>createPositionSceneSource(Array.from({length:11},(_,i)=>({at:BigInt(i+1),items:[]})))).toThrow();expect(()=>createPositionSceneSource([{at:1n,items:[]},{at:1n,items:[]}])).toThrow();});
 it('PSS-E: inputs and outputs are detached; the shared allocator may not reuse world identity for a binding',()=>{const a={...item('object/a',0n)},source=createPositionSceneSource([{at:1n,items:[a]}]);a.x=7n;let n=0n;const r=materializePositionScene(source,1n,()=>n++);expect(r.safe.items[0].position.x).toBe(0n);expect(()=>Object.assign(r.safe.items[0].position,{x:7n})).toThrow();expect(()=>materializePositionScene(source,1n,()=>0n)).toThrow('POSITION_SCENE_ALLOCATION');expect(()=>materializePositionScene(source,2n,()=>0n)).toThrow('POSITION_SCENE_DOMAIN');});
 it('PSS-F: identical visible tuples retain their multiplicity without using true identity as a tie-break',()=>{const r=run([item('object/a',0n),item('object/b',0n)]);expect(r.safe.items).toHaveLength(2);expect(r.safe.items[0]).toEqual(r.safe.items[1]);expect(r.allocated).toBe(3n);});
});
