import {describe,it,expect} from 'vitest';
import {createPositionDisplaySource,observePositionDisplay,type PositionDisplayFrame,type PositionDisplaySource} from '../campaign3/positionDisplaySource';
const frame=(at=1n):PositionDisplayFrame=>({at,x:0n,y:0n,glyph:0n,visible:true,permitted:true});
describe('bounded observed position source',()=>{
 it('POS-A: zero position/glyph are present and each output contains one position',()=>{const s=createPositionDisplaySource([frame(),{...frame(2n),x:1n}]);expect(observePositionDisplay(s,1n)).toEqual({kind:'Present',at:1n,position:{x:0n,y:0n},glyph:0n});expect(observePositionDisplay(s,2n)).toEqual({kind:'Present',at:2n,position:{x:1n,y:0n},glyph:0n});});
 it('POS-B: hidden, denied and unscheduled are indistinguishable; no last-frame fallback',()=>{for(const frames of [[{...frame(),visible:false}],[{...frame(),permitted:false}],[]])expect(observePositionDisplay(createPositionDisplaySource(frames),1n)).toEqual({kind:'Unavailable',at:1n});expect(observePositionDisplay(createPositionDisplaySource([frame()]),2n)).toEqual({kind:'Unavailable',at:2n});});
 it('POS-C: finite ordered exact data is required without executing accessors',()=>{let called=false;const executable={...frame(),get x(){called=true;return 0n;}};for(const frames of [[executable],[{...frame(),x:8n}],[{...frame(),stroke:true}],[frame(),frame()],[frame(2n),frame(1n)],new Array(1),Array.from({length:9},(_,i)=>frame(BigInt(i)))])expect(()=>createPositionDisplaySource(frames)).toThrow('POSITION_DISPLAY_SOURCE_DOMAIN');expect(called).toBe(false);});
 it('POS-D: construction and returned projection are detached from the authored object',()=>{const f={...frame()},s=createPositionDisplaySource([f]);f.x=7n;const out=observePositionDisplay(s,1n);if(out.kind!=='Present')throw Error('present');expect(()=>Object.assign(out.position,{x:6n})).toThrow();expect(observePositionDisplay(s,1n)).toEqual(out);expect(out.position.x).toBe(0n);expect(()=>observePositionDisplay({} as PositionDisplaySource,1n)).toThrow();});
 it('POS-E: reads do not consume frames or expose hidden positions',()=>{const a=createPositionDisplaySource([{...frame(),visible:false,x:1n}]),b=createPositionDisplaySource([{...frame(),visible:false,x:7n}]);for(let i=0;i<3;i++)expect(observePositionDisplay(a,1n)).toEqual(observePositionDisplay(b,1n));expect(()=>observePositionDisplay(a,-1n)).toThrow();});
});
