import {describe,it,expect} from 'vitest';
import {createTrialPanelSource,observeTrialPanel,type TrialPanelFrame,type TrialPanelSource} from '../campaign3/trialPanelSource';
const frame=(at=1n):TrialPanelFrame=>({at,glyph:0,stage:'Before',visible:true,permitted:true});
describe('bounded neutral trial panel source',()=>{
 it('TP-A: actual exact frame including zero glyph',()=>{expect(observeTrialPanel(createTrialPanelSource([frame()]),1n)).toEqual({kind:'Present',at:1n,glyph:0,stage:'Before'});});
 it('TP-B: hidden, denied and unscheduled observations release the same absence',()=>{const absent={kind:'Unavailable',at:1n};for(const frames of [[],[{...frame(),visible:false}],[{...frame(),permitted:false}]])expect(observeTrialPanel(createTrialPanelSource(frames),1n)).toEqual(absent);expect(observeTrialPanel(createTrialPanelSource([frame()]),2n)).toEqual({kind:'Unavailable',at:2n});});
 it('TP-C: closed finite plain data domain rejects hidden side fields, getters and bad schedules',()=>{for(const bad of [[{...frame(),outcome:'success'}],[{...frame(),glyph:8}],[{...frame(),at:-1n}],[frame(),frame()],[frame(2n),frame(1n)],Array.from({length:17},(_,i)=>frame(BigInt(i))),Array(1)])expect(()=>createTrialPanelSource(bad as TrialPanelFrame[])).toThrow('TRIAL_PANEL_SOURCE_DOMAIN');let read=false;const evil={...frame()};Object.defineProperty(evil,'glyph',{get(){read=true;return 0;}});expect(()=>createTrialPanelSource([evil])).toThrow();expect(read).toBe(false);});
 it('TP-D: schedule and results detach; forged source tokens reject',()=>{const f={...frame()},s=createTrialPanelSource([f]);f.glyph=7;const first=observeTrialPanel(s,1n);expect(Object.isFrozen(first)).toBe(true);expect(observeTrialPanel(s,1n)).toEqual({kind:'Present',at:1n,glyph:0,stage:'Before'});expect(()=>observeTrialPanel({} as TrialPanelSource,1n)).toThrow();});
 it('TP-E: reads neither advance the source nor reveal private absence flags',()=>{const s=createTrialPanelSource([frame(),{...frame(2n),stage:'After',visible:false}]);const first=observeTrialPanel(s,1n);for(let i=0;i<4;i++){expect(observeTrialPanel(s,2n)).toEqual({kind:'Unavailable',at:2n});expect(observeTrialPanel(s,1n)).toEqual(first);}expect(Reflect.ownKeys(s)).toEqual([]);});
});
