import {describe,it,expect} from 'vitest';
import {createTrialPanelPerception,consumeTrialPanel,trialPanelPerceptionSnapshot} from '../campaign3/trialPanelPerception';
import {createTrialPanelSource,observeTrialPanel,type TrialPanelStage} from '../campaign3/trialPanelSource';
import {assemblePreRecognitionExperience} from '../semanticBinding/perceptualEventFiles';
import {groupPerceivedPositionTrial} from '../campaign3/perceivedTrialGrouping';
const observer='observer/a';
const setup=(stages:readonly (TrialPanelStage|null)[],glyphs:number[]=stages.map(()=>0))=>{const token=createTrialPanelPerception(observer),source=createTrialPanelSource(stages.map((s,i)=>({at:BigInt(i+1),glyph:glyphs[i],stage:s??'Motion',visible:s!==null,permitted:true})));return {token,read:(at:bigint)=>{const sample=observeTrialPanel(source,at);return consumeTrialPanel(token,{observer,observation:at*2n,...(sample.kind==='Present'?{detection:at*2n+1n}:{}),sample});}};};
describe('observed panel event-file perception',()=>{
 it('TC-A: real SEM start, continuation and end share one observer event-file',()=>{const f=setup(['Before','Motion','Motion','After']),results=[1n,2n,3n,4n].map(f.read);expect(results.map(r=>r.transition!.continuityKind)).toEqual(['NewEventFile','ContinuesPriorEventFile','ContinuesPriorEventFile','ContinuesPriorEventFile']);expect(results.every(r=>r.context!.observerEventSequence===0n)).toBe(true);expect(results[3].ends).toHaveLength(1);expect(trialPanelPerceptionSnapshot(f.token).files.activeEventFiles).toEqual([]);});
 it('TC-B: absence breaks continuity; a reappearing glyph cannot recover the old file',()=>{const f=setup(['Before',null,'Motion']);const a=f.read(1n),gap=f.read(2n),b=f.read(3n);expect(gap.context).toBeUndefined();expect(gap.ends).toHaveLength(1);expect(b.context).not.toEqual(a.context);expect(b.transition!.continuityKind).toBe('NewEventFile');});
 it('TC-C: changed glyph and repeated Before produce explicit splits',()=>{for(const f of [setup(['Before','Motion'],[0,1]),setup(['Before','Before'])]){const a=f.read(1n),b=f.read(2n);expect(b.context).not.toEqual(a.context);expect(b.ends).toHaveLength(1);expect(trialPanelPerceptionSnapshot(f.token).files.activeEventFiles).toHaveLength(1);}});
 it('TC-D: foreign, replayed or malformed observations leave state and allocation unchanged',()=>{const f=setup(['Before','Motion']);f.read(1n);const before=trialPanelPerceptionSnapshot(f.token);const good={observer,observation:4n,detection:5n,sample:{kind:'Present' as const,at:2n,glyph:0,stage:'Motion' as const}};for(const bad of [{...good,observer:'observer/b'},{...good,observation:2n},{...good,detection:3n},{...good,sample:{...good.sample,at:1n}},{...good,sample:{...good.sample,glyph:9}}]){expect(()=>consumeTrialPanel(f.token,bad)).toThrow();expect(trialPanelPerceptionSnapshot(f.token)).toEqual(before);}expect(f.read(2n).context!.observerEventSequence).toBe(0n);});
 it('TC-E: missing stage cannot be rebuilt from the intended trial schedule',()=>{const f=setup(['Before',null,'Motion','Motion','After']),rows=[];for(const at of [1n,2n,3n,4n,5n]){const r=f.read(at);if(r.context)rows.push({role:r.stage!,experience:assemblePreRecognitionExperience({experienceId:at,observerId:observer,occurredAt:at,perceptualEventReferentIds:[r.context],perceivedBindings:[],perceptualClassifications:[],perceptualEventClassifications:[],supportingObservationIds:[{observerId:observer,observationId:at*2n}],transformationVersion:'semantic-binding/0.1-candidate'})});}expect(groupPerceivedPositionTrial(observer,rows.at(-1)!.experience.perceptualEventReferentIds[0],rows)).toEqual({kind:'Unavailable',reason:'IncompleteContext'});});
});
