import {it,expect} from 'vitest';
import {createVividRun as create,restoreVividRun as restore,LAWS,type Law} from '../campaign3/vividRecollection';
import {vividCases as cases} from './vividRecollectionFixtures';
async function run(name:keyof ReturnType<typeof cases>='rich',law:Law='PerceptualFidelity'){const r=create(law,cases()[name]);while(await r.step()){}return r;}
it('same recent values, selection and rank distinguish clear from weak reinstatement',async()=>{const a=(await run()).snapshot().rows[1],b=(await run('weak')).snapshot().rows[1];expect(a.selected&&b.selected).toBe(true);expect(a.rank).toBe(b.rank);expect(a.facets.map(x=>x.value)).toEqual(b.facets.map(x=>x.value));expect(a.facets).toHaveLength(3);expect(b.facets).toHaveLength(3);expect(a.band).toBe('Vivid');expect(b.band).toBe('Weak');});
it('false recent recollection can remain clear; hidden truth never repairs published content',async()=>{const a=(await run('falseDisplay')).snapshot().rows[1];expect(a.band).toBe('Vivid');expect(a.facets.every(f=>!f.value)).toBe(true);for(const law of LAWS){expect((await run('rich',law)).observerView()).toEqual((await run('hiddenTruth',law)).observerView());expect((await run('denied',law)).observerView()).toEqual((await run('deniedChanged',law)).observerView());}});
it('recent to fragmentary transition removes actual detail after current publication',async()=>{const s=(await run()).snapshot();expect(s.rows[3].facets).toHaveLength(3);expect(s.rows[4].facets).toHaveLength(1);expect(s.rows[4].band).toBe('Fragmentary');expect(s.imprint!.facets).toHaveLength(1);expect((await run('rich','KeepRich')).snapshot().rows[4].band).toBe('Vivid');});
it('presence and detail-count readouts are discriminated without inventing features',async()=>{expect((await run('weak','DetailCount')).snapshot().rows[1].band).toBe('Vivid');expect((await run('partial','AccessOnly')).snapshot().rows[1].band).toBe('Vivid');expect((await run('partial')).snapshot().rows[1].band).toBe('Fragmentary');expect((await run('empty')).snapshot().rows[1].band).toBe('Empty');});
it('absent cue publishes nothing; unrelated cue can retain baseline selection',async()=>{const r=(await run('noCue','KeepRich')).snapshot();expect(r.rows.every(x=>!x.selected&&x.band==='Unavailable')).toBe(true);expect(r.imprint!.facets).toHaveLength(3);expect(r.presentations).toEqual([]);const other=(await run('otherCue')).snapshot(),rich=(await run()).snapshot();expect(other.rows[1].selected).toBe(true);expect(other.rows.map(x=>x.facets)).toEqual(rich.rows.map(x=>x.facets));});
it('only actual publication settles history; queries do not add lost features',async()=>{const a=(await run()).snapshot(),b=(await run('noQueries')).snapshot();expect(a.presentations).toEqual([2,3,4,5,6]);expect(b.presentations).toEqual([6]);expect(a.imprint).toEqual(b.imprint);expect(a.rows[5].facets).toEqual(b.rows[5].facets);expect(a.rows[0].selected).toBe(false);});
it('all laws reproduce whole component prefixes and one successor',async()=>{for(const law of LAWS){const r=create(law,cases().rich);for(let i=0;i<=6;i++){const q=await restore(law,cases().rich,i,r.save());expect(q.save()).toEqual(r.save());expect(await q.step()).toBe(await r.step());expect(q.save()).toEqual(r.save());}}},60000);
it('fault after consumed publication or before commit rolls back history and deterministic retry',async()=>{for(const fault of ['after-publication','before-commit'] as const){const r=create('PerceptualFidelity',cases().rich);await r.step();const before=r.save();await expect(r.step(fault)).rejects.toThrow('VIVID_INJECTED');expect(r.save()).toEqual(before);const q=await restore('PerceptualFidelity',cases().rich,1,before),pending=r.step();await expect(r.step()).rejects.toThrow('VIVID_CONCURRENT');await pending;await q.step();expect(r.save()).toEqual(q.save());}});
it('strict copied source and full saves reject getters, mutable originals and forgery',async()=>{const f=cases().rich,r=create('PerceptualFidelity',f);f[0].display[0]=false;await r.step();expect(r.snapshot().imprint!.facets[0].value).toBe(true);const bad=cases().rich;Object.defineProperty(bad[0].clarity,'0',{get(){throw Error('GETTER_RAN');}});expect(()=>create('PerceptualFidelity',bad)).toThrow('VIVID_ARRAY');const copy=r.save();copy[copy.length-1]^=1;await expect(restore('PerceptualFidelity',cases().rich,1,copy)).rejects.toThrow('VIVID_SAVE_MISMATCH');await expect(restore('PerceptualFidelity',cases().weak,1,r.save())).rejects.toThrow('VIVID_SAVE_MISMATCH');});
