import {beforeAll,describe,it,expect} from 'vitest';
import receipt from '../../docs/planning/DEFINING_MEMORY_TRAINING_REV1.json';
import {createDefiningAcquisitionPrelude} from '../campaign3/definingAcquisitionPrelude';
import {canonicalEncode as enc,list} from '../substrate/canonicalEncoding';
import {dataRecord as rec,dataField as f,dataItems as items} from '../campaign2/canonicalData';
import {meaningTraining} from '../campaign3/definingMeaning';
const bytes=(s:string)=>Uint8Array.from(s.match(/../g)!.map(x=>parseInt(x,16)));
let run:Awaited<ReturnType<typeof createDefiningAcquisitionPrelude>>;const prefixes:Uint8Array[]=[],events:bigint[]=[],times:bigint[]=[];
const image=()=>{const s=run.runtime.snapshot();return enc(list([s.state.canonicalValue(),list(s.outputs),list(s.committedTrace)]));};
beforeAll(async()=>{run=await createDefiningAcquisitionPrelude();prefixes.push(image());while(true){const settled=await run.runtime.settleNextInstant();if(!settled)break;events.push(...settled.executedEvents.map(e=>e.eventId));times.push(settled.instant);prefixes.push(image());}},240000);
describe('native defining acquisition prelude',()=>{
 it('begins with empty acquired memory and a distinct committed model/run',()=>{expect(run.initialState).toEqual(bytes(receipt.initialState));expect(run.modelIdentity.canonicalBytes).not.toEqual(bytes(receipt.modelIdentity));expect(run.runIdentity.canonicalBytes).not.toEqual(bytes(receipt.runIdentity));});
 it('reproduces actual GA37 acquired state and every observer output',()=>{const expected=receipt.snapshots[0],s=run.runtime.snapshot();expect(s.clock).toBe(37n);expect(enc(s.state.canonicalValue())).toEqual(bytes(expected.state));expect(enc(list(s.outputs))).toEqual(bytes(expected.outputs));});
 it('supplies uncredited evidence with actual supported attribution to the meaning adapter',()=>{const s=run.runtime.snapshot(),t=meaningTraining(enc(s.state.canonicalValue()),enc(list(s.outputs)));expect(t.memory).toHaveLength(16);expect(t.targets).toEqual([{acquisition:35n,unit:'child'}]);expect(t.memory.every(a=>a.units.every(u=>u.outcomeSignificanceDirections.length===0))).toBe(true);});
 it('settles only the committed cutoff calendar with unique event IDs and complete traces',async()=>{const s=run.runtime.snapshot();expect(times.at(-1)).toBe(37n);expect(times.every(t=>t<=37n)).toBe(true);expect(new Set(events).size).toBe(events.length);expect(s.queue).toEqual([]);expect(s.committedTrace).toHaveLength(events.length);expect(await run.runtime.settleNextInstant()).toBeUndefined();});
 it('fresh empty-S0 execution repeats every complete prefix',async()=>{const fresh=await createDefiningAcquisitionPrelude();const next=()=>{const s=fresh.runtime.snapshot();return enc(list([s.state.canonicalValue(),list(s.outputs),list(s.committedTrace)]));};expect(next()).toEqual(prefixes[0]);let i=1;while(await fresh.runtime.settleNextInstant())expect(next()).toEqual(prefixes[i++]);expect(i).toBe(prefixes.length);},240000);
 it('a reached terminal fault rolls back acquired state, trace, queue and allocators and stays Failed',async()=>{const fresh=await createDefiningAcquisitionPrelude(),r=fresh.runtime;await r.settleNextInstant();await r.settleNextInstant();const before=r.snapshot();let hit=false;await expect(r.settleNextInstantForConformance({onBoundary:(b,e)=>{if(b==='after-state-validation'&&e?.phase===140n){hit=true;throw Error('defining prelude fault');}}})).rejects.toThrow('defining prelude fault');expect(hit).toBe(true);const after=r.snapshot();expect(enc(after.state.canonicalValue())).toEqual(enc(before.state.canonicalValue()));expect(after.queue).toEqual(before.queue);expect(after.allocators).toEqual(before.allocators);expect(after.committedTrace).toEqual(before.committedTrace);expect(after.outputs).toEqual(before.outputs);expect(after.status).toBe('Failed');await expect(r.settleNextInstant()).rejects.toThrow();},120000);
});
