/** procrastination-public/0.1-candidate; availability-mediated history with separate belief. */
import {canonicalEncode as enc,list,text,unsigned as u,rational as q,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {commitManifest,createModelIdentity,createRunIdentity} from '../substrate/identity';
import {AuthoritativeState,StateAuthorityRegistry,statePathPatternValue,type StatePath} from '../substrate/state';
import {compileMutationAuthorityRegistry} from '../substrate/mutationAuthority';
import {simInstant} from '../substrate/time';
import {RANDOM_ALGORITHM_VERSION} from '../substrate/random';
import type {ScheduledEvent} from '../substrate/scheduler';
import {semanticReferentFromAuthoredContent} from '../substrate/referentOrigin';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {receivingRecord as old} from './receivingCodecs';
import {copyData} from './beliefModel';
import {multisourceBase} from './multisourceModelRecipe';
import {decodeProcrastination as decode,procrastinationRecord as cr} from './procrastinationCodecs';
import {habitRecord as r} from './habitCodecs';
import {habitSummary as procrastinationSummary} from './habitMath';
export {copyData};
export const PROCRASTINATION_VERSION='procrastination-public/0.1-candidate',sid=(ns:number,name:string)=>typedIdentifier(ns,text(name));
export const OBSERVER=sid(1000,'observer/habit'),CHARACTER=semanticReferentFromAuthoredContent(sid(1038,'content/habit/character'));
export const TASK=old(371,[CHARACTER,semanticReferentFromAuthoredContent(sid(1038,'content/procrastination/work-goal'))]),OPTIONS=['work','defer'].map(n=>old(395,[CHARACTER,sid(1027,'action/procrastination/'+n)]));
export const LEISURE=old(371,[CHARACTER,semanticReferentFromAuthoredContent(sid(1038,'content/procrastination/immediate-goal'))]);
export const STAGES=[['appraise',40],['options',50],['raw',51],['reasons',52],['decision',60],['intent',70],['expression',80],['plan',90],['attempt',100],['execute',110],['observe',120],['history',140],['belief',140],['cache',140],['forecast',140]] as const;
export const eventId=(n:string)=>sid(1001,'event/procrastination/'+n);
export const historyPath:StatePath={rootStateTypeId:821n,fieldId:1n,selectors:[{kind:'mapKey',key:CHARACTER}]},beliefPath:StatePath={...historyPath,rootStateTypeId:823n},cachePath:StatePath={...historyPath,rootStateTypeId:825n};
export const pattern=(p:StatePath)=>({...p,selectors:p.selectors.map(selector=>({kind:'exact' as const,selector}))});
export interface ProcrastinationSettings {candidate:number;law:number;}
export const DEFAULT_SETTINGS:ProcrastinationSettings={candidate:1,law:1};
export const goalPath:StatePath={...historyPath,rootStateTypeId:1357n},workspacePath:StatePath={...historyPath,rootStateTypeId:1359n};
export const forecastPath:StatePath={...historyPath,rootStateTypeId:1372n};
export const stageReads=(n:string,s:ProcrastinationSettings)=>n==='appraise'?[beliefPath,historyPath,goalPath,workspacePath,forecastPath]:n==='history'?[historyPath]:n==='belief'?[beliefPath]:n==='cache'?[goalPath]:n==='forecast'?[forecastPath]:[];
export const stageWrites=(n:string,s:ProcrastinationSettings)=>n==='appraise'?[workspacePath]:n==='history'?[historyPath]:n==='belief'?[beliefPath]:n==='cache'?[goalPath]:n==='forecast'?[forecastPath]:[];
export const owner=(n:string)=>sid(1025,n==='forecast'?'authority/prospective-evidence':n==='appraise'?'authority/procrastination-workspace':n==='cache'?'authority/procrastination-goal':n==='history'?'authority/habit-history':'authority/reward-expectation');
const ownership=(s:ProcrastinationSettings)=>compileMutationAuthorityRegistry([['authority/prospective-evidence',forecastPath,1371n],['authority/habit-history',historyPath,820n],['authority/reward-expectation',beliefPath,822n],['authority/procrastination-goal',goalPath,1356n],['authority/procrastination-workspace',workspacePath,1358n]].map(([authorityName,path,type])=>({authorityName:authorityName as string,ownedLeaves:[{pattern:pattern(path as StatePath),valueGrammar:{kind:'canonical-record' as const,recordTypeId:type as bigint},removalAllowed:false}]})));
export function procrastinationRecipe(settings:Partial<ProcrastinationSettings>={}){const s={...DEFAULT_SETTINGS,...settings};if(![1,2,3,4].includes(s.candidate)||![1,2].includes(s.law))throw Error('PROCRASTINATION_PROFILE');const parameters=cr(1353,[text(PROCRASTINATION_VERSION),u(s.candidate),u(s.law)]),content=cr(1374,[OBSERVER,CHARACTER,TASK,list(OPTIONS),multisourceBase().get('task-reason-dice'),q(1,1),q(0,1),q(0,1),LEISURE,u(6),u(3)]),stages=STAGES.map(([n,phase])=>cr(1354,[eventId(n),u(phase),list(stageReads(n,s).map(p=>statePathPatternValue(pattern(p)))),list(stageWrites(n,s).map(p=>statePathPatternValue(pattern(p)))),owner(n)]));return {parameters:enc(parameters),content:enc(content),registry:enc(list([ownership(s).definitionValue,list(stages)]))};}
export type ProcrastinationSource=ReturnType<typeof procrastinationRecipe>;
export async function compileProcrastinationModel(input:ProcrastinationSource){const source=copyData(input,['parameters','content','registry']),profile=rec(decode(source.parameters),1353n),settings={candidate:Number(uint(f(profile,2n))),law:Number(uint(f(profile,3n)))},recipe=procrastinationRecipe(settings);for(const n of ['parameters','content','registry'] as const)if(key(decode(recipe[n]))!==key(decode(source[n])))throw Error('PROCRASTINATION_EXACT_MODEL');const own=ownership(settings),authority=new StateAuthorityRegistry(own.writableLeaves,own.authorities),content=rec(decode(source.content),1374n),modelIdentity=await createModelIdentity({rulesVersion:PROCRASTINATION_VERSION,contentSchemaVersion:PROCRASTINATION_VERSION,contentManifest:await commitManifest(content),parameterSchemaVersion:PROCRASTINATION_VERSION,parameterSet:await commitManifest(profile),numericProfileVersion:'procrastination-exact-rational/0.1-candidate',randomAlgorithmVersion:RANDOM_ALGORITHM_VERSION,registrySchemaVersion:PROCRASTINATION_VERSION,registryManifest:await commitManifest(decode(source.registry))}),empty=r(820,[list([])]),initial=new AuthoritativeState([{path:historyPath,value:empty},{path:goalPath,value:cr(1356,[false,u(0),true,u(0)])},{path:workspacePath,value:cr(1358,[false,false,false,false])},{path:forecastPath,value:cr(1371,[list([])])}]);
 function validateState(state:AuthoritativeState){decode(enc(state.canonicalValue()));const pk=(p:StatePath)=>key(statePathPatternValue(pattern(p))),allowed=new Set([historyPath,beliefPath,goalPath,workspacePath,forecastPath].map(pk));for(const e of state.entries())if(!allowed.has(pk(e.path)))throw Error('PROCRASTINATION_STATE_PATH');const journal=state.read(historyPath).value;if(!journal)throw Error('PROCRASTINATION_JOURNAL_MISSING');let at=0n;const seen=new Set<string>();for(const v of items(f(rec(journal,820n),1n),'list')){const e=rec(v,819n),t=f(e,2n);if(typeof t==='boolean'||t.kind!=='signed'||t.value<=at||seen.has(key(f(e,1n))))throw Error('PROCRASTINATION_HISTORY_ORDER');at=t.value;seen.add(key(f(e,1n)));}const evidence=items(f(rec(state.read(forecastPath).value!,1371n),1n),'list');let last=0n;const ids=new Set<string>();for(const v of evidence){const e=rec(v,1370n),t=f(e,2n);if(typeof t==='boolean'||t.kind!=='signed'||t.value<=last||ids.has(key(f(e,1n)))||items(f(e,3n),'list').length!==1)throw Error('PROCRASTINATION_EVIDENCE_ORDER');last=t.value;ids.add(key(f(e,1n)));}for(const [p,t] of [[goalPath,1356n],[workspacePath,1358n]] as const)rec(state.read(p).value!,t);}
 return {source,profile,settings,content,modelIdentity,authority,initial,validateState};}
export type ProcrastinationCompiled=Awaited<ReturnType<typeof compileProcrastinationModel>>;
export async function compileProcrastinationInputs(model:ProcrastinationCompiled,initialState:Uint8Array,orderedInputs:Uint8Array,runSeed:Uint8Array){if(key(decode(initialState))!==key(model.initial.canonicalValue()))throw Error('PROCRASTINATION_INITIAL_STATE');const originals=items(decode(orderedInputs),'list');if(originals.length>8)throw Error('PROCRASTINATION_INPUT_LIMIT');let previous=0n,adopted=false,retired=false;const events:ScheduledEvent[]=originals.map((v,i)=>{const original=rec(v,1355n),instruction=uint(f(original,2n)),o=rec(f(original,1n),818n),t=f(o,1n);if(uint(f(o,2n))!==2n)throw Error('PROCRASTINATION_FREE_PROBE_ONLY');if(instruction===1n){if(adopted)throw Error('PROCRASTINATION_READOPTION');adopted=true;}if(instruction===2n){if(!adopted||retired)throw Error('PROCRASTINATION_RETIREMENT');retired=true;}if(typeof t==='boolean'||t.kind!=='signed'||t.value<=previous||t.value>8n)throw Error('PROCRASTINATION_INPUT_TIME');previous=t.value;return {eventId:BigInt(i),eventSequence:BigInt(i),dueAt:simInstant(t.value),phase:40n,eventTypeId:eventId('appraise'),payload:v,dependencies:list([]),causalParentEventIds:[]};});const runIdentity=await createRunIdentity({modelIdentity:model.modelIdentity,initialState:await commitManifest(decode(initialState)),orderedInputSequence:await commitManifest(decode(orderedInputs)),runSeed});return {events,runIdentity,runSeed:runSeed.slice()};}
