import {canonicalEncode as enc,list,set,signed,unsigned as u,type CanonicalValue} from '../substrate/canonicalEncoding';
import {betrayalRecord as r} from '../campaign3/betrayalCodecs';
export const initialState=enc(set([])),seed=new Uint8Array(32).fill(13);
export type Row={target:number;episode:number;worldIntent:boolean;worldFailure:boolean;worldWill:boolean;failureOpportunity:boolean;failure:boolean;intentOpportunity:boolean;intent:boolean;willOpportunity:boolean;will:boolean;link:boolean;partA:boolean;partB:boolean;accessA:boolean;accessB:boolean;cueA:boolean;cueB:boolean;commitmentOpportunity:boolean;commitment:boolean;controlOpportunity:boolean;control:boolean;worldControl:boolean};
const row=(x:Partial<Row>={}):Row=>({target:1,episode:1,worldIntent:true,worldFailure:true,worldWill:true,failureOpportunity:false,failure:true,intentOpportunity:false,intent:true,willOpportunity:false,will:true,link:true,partA:true,partB:true,accessA:true,accessB:true,cueA:true,cueB:true,commitmentOpportunity:false,commitment:true,controlOpportunity:false,control:true,worldControl:true,...x});
export function cases(){
 const probe=()=>row({accessA:false,accessB:false});
 const main=[row({commitmentOpportunity:true,willOpportunity:true}),row({failureOpportunity:true,intentOpportunity:true,controlOpportunity:true}),probe(),row({intentOpportunity:true,intent:false}),probe(),row({target:2,episode:2,commitmentOpportunity:true}),row({willOpportunity:true}),probe()];
 const change=(fn:(r:Row,i:number)=>Row)=>main.map((r,i)=>fn({...r},i)),fourth=(x:Partial<Row>)=>change((r,i)=>i===3?{...r,...x}:r),first=(x:Partial<Row>)=>change((r,i)=>i===0?{...r,...x}:r);
 return {main,noExplanation:fourth({intentOpportunity:false}),constrained:fourth({intentOpportunity:false,controlOpportunity:true,control:false}),deniedExplanation:fourth({accessA:false,accessB:false}),missingLink:fourth({link:false}),foreignEpisode:fourth({episode:2}),foreignTarget:fourth({target:2}),willOnly:fourth({intentOpportunity:false,willOpportunity:true,will:false}),correctionWillFalse:fourth({willOpportunity:true,will:false}),hiddenWorld:change(r=>({...r,worldIntent:false,worldFailure:false,worldWill:false,worldControl:false})),denied:change((r,i)=>i===2?{...r,failureOpportunity:true,failure:false,intentOpportunity:true,intent:false,willOpportunity:true,will:false,commitmentOpportunity:true,commitment:false,controlOpportunity:true,control:false}:r),noA:change((r,i)=>i<6?{...r,accessA:false,cueA:false}:r),noB:change((r,i)=>i<6?{...r,accessB:false,cueB:false}:r),witnessA:change(r=>({...r,partA:false})),unknownIntent:change(r=>({...r,intentOpportunity:false})),unknownControl:change(r=>({...r,controlOpportunity:false})),noFailure:change(r=>({...r,failureOpportunity:false})),success:change(r=>({...r,failure:false})),noCommit:first({commitmentOpportunity:false}),negativeCommit:first({commitment:false}),lateCommit:change((r,i)=>i===0?{...r,commitmentOpportunity:false}:i===3?{...r,commitmentOpportunity:true}:r),sameInstantCommit:change((r,i)=>i===0?{...r,commitmentOpportunity:false}:i===1?{...r,commitmentOpportunity:true}:r),missingCue:change(r=>({...r,cueA:false})),unknown:change(r=>({...r,accessA:false,accessB:false,cueA:false,cueB:false}))};
}
export const ordered=(rows:Row[])=>enc(list(rows.map((x,i)=>r(1265,[signed(i+1),u(x.target),u(x.episode),x.worldIntent,x.worldFailure,x.worldWill,x.failureOpportunity,x.failure,x.intentOpportunity,x.intent,x.willOpportunity,x.will,x.link,x.partA,x.partB,x.accessA,x.accessB,x.cueA,x.cueB,x.commitmentOpportunity,x.commitment,x.controlOpportunity,x.control,x.worldControl]))));
export const records=(xs:readonly CanonicalValue[],type:bigint)=>xs.filter(x=>typeof x!=='boolean'&&x.kind==='record'&&x.schema.typeId===type);
