import {it,expect} from 'vitest';
import {canonicalEncode as enc,list,record,unsigned as u,type CanonicalValue} from '../substrate/canonicalEncoding';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {identityRecipe,taskStages,bioStages,eventId,path,owner,compileIdentityModel,compileIdentityInputs,contextValue} from '../campaign3/identityPublicModel';
import {prepareIdentityModel,createIdentityPublicRun,restoreIdentityPublicRun} from '../campaign3/identityPublicFactory';
import {decodeIdentityPublic as decode,identityPublicRecord as r} from '../campaign3/identityPublicCodecs';
import {createEligibilityRun,eligibilitySummary} from '../campaign3/identityEligibility';
import {createBiologyPublicRun,prepareBiologyModel} from '../campaign3/biologyPublicFactory';
import {biologyRecipe,orderedBytes,initialBytes} from '../campaign3/biologyPublicModel';
import {applyStatePatch} from '../substrate/state';
import {value} from '../campaign3/biologyPublicData';
import {eligibilityInputs} from './identityEligibilityFixtures';
import {taskCase,bioCase,runtime,records,taskSemantic,nativeOutputs} from './identityPublicFixtures';
async function publicRun(c:ReturnType<typeof taskCase>){const run=await createIdentityPublicRun(await prepareIdentityModel(c.source),c);while(await run.settleNextInstant()){}return run;}
it('native task phases preserve all component semantic rows',async()=>{
 const s=await runtime(taskCase()),old=createEligibilityRun('Threshold',6,eligibilityInputs('Meaningful'));while(await s.runtime.settle())await old.step();const expected=items(items(old.snapshot(),'list')[1],'list').map(eligibilitySummary).map(({at,chosen,authorship,probabilities,contribution,strength,executed})=>({at,chosen,authorship,probabilities,contribution,strength,executed}));expect(taskSemantic(s.runtime.snapshot().outputs)).toEqual(expected);
 for(const [type,phase]of [[1431,60],[1432,70],[1433,80],[1439,110],[1434,130],[1437,140]])for(const t of s.runtime.snapshot().trace.map(v=>rec(v,160n)).filter(v=>records(items(f(v,13n),'list'),type).length))expect(f(rec(f(t,4n),130n),3n)).toEqual(u(phase));
},120000);
it('whole observer view excludes failed physical execution through later identity',async()=>{const a=await publicRun(taskCase()),b=await publicRun(taskCase('FailedExecution'));expect(a.observerView()).toEqual(b.observerView());expect(a.snapshot().state).not.toEqual(b.snapshot().state);},120000);
it('typed native biology NoFeedback preserves frozen biology choices and body state',async()=>{const c=bioCase('matched','NoFeedback'),a=await publicRun(c),b=await createBiologyPublicRun(await prepareBiologyModel(biologyRecipe(c.c.law,c.c.config)),{initialState:initialBytes(c.c.config.initial),orderedInputs:orderedBytes(c.c.frames),runSeed:c.runSeed});while(await b.settleNextInstant()){}const old=items(decode(b.snapshot().outputs),'list');expect(records(nativeOutputs(a),1414).map(v=>value(f(v,4n)))).toEqual(records(old,1414).map(v=>value(f(v,4n))));expect(records(nativeOutputs(a),1411).map(v=>value(f(v,3n)))).toEqual(records(old,1411).map(v=>value(f(v,3n))));},120000);
it('biological pleasure/withdrawal alone never mints a protective identity channel',async()=>{for(const law of ['Threshold','Frequency'] as const){const run=await publicRun(bioCase('noGoal',law));const q=records(nativeOutputs(run),1434);expect(q).toHaveLength(12);expect(q.every(v=>uint(f(v,3n))===5n)).toBe(true);}},120000);
it('biological hidden physiology preserves the entire observer view',async()=>{const a=await publicRun(bioCase('hidden')),b=await publicRun(bioCase('hiddenChanged'));expect(a.observerView()).toEqual(b.observerView());expect(a.snapshot().state).not.toEqual(b.snapshot().state);},120000);
it('public restore checks whole native prefixes and tampered provenance',async()=>{const c=taskCase(),run=await createIdentityPublicRun(await prepareIdentityModel(c.source),c);await run.settleNextInstant();const save=run.save();await run.settleNextInstant();const restored=await restoreIdentityPublicRun(c.source,{initialState:c.initialState,orderedInputs:c.orderedInputs,save});await restored.settleNextInstant();expect(restored.save()).toEqual(run.save());const v=rec(decode(save),132n),fields=new Map(v.fields);fields.set(11n,list([]));await expect(restoreIdentityPublicRun(c.source,{initialState:c.initialState,orderedInputs:c.orderedInputs,save:enc(record(v.schema,fields))})).rejects.toThrow();},120000);
for(const family of ['Task','Biological'] as const)for(const stage of [...(family==='Task'?taskStages:bioStages).map(([n])=>n),'commit'])it(family+' rollback at '+stage,async()=>{const s=await runtime(family==='Task'?taskCase():bioCase());const before=s.runtime.snapshot();let reached=false;await expect(s.runtime.settleForConformance({onBoundary(b,e){if(stage==='commit'?b==='before-commit':b==='after-trace-validation'&&e&&key(e.eventTypeId)===key(eventId(family,stage))){reached=true;throw Error('injected');}}})).rejects.toThrow();expect(reached).toBe(true);expect(s.runtime.snapshot()).toEqual(before);},120000);
it('source kind, original record type, actor state and foreign handle admission stay closed',async()=>{const c=taskCase(),run=await publicRun(c),expression=records(nativeOutputs(run),1433)[0],fields=new Map(expression.fields);fields.set(4n,u(2));expect(()=>decode(enc(record(expression.schema,fields)))).toThrow('source kind');await expect(createIdentityPublicRun({} as any,c)).rejects.toThrow('MODEL_HANDLE');await expect(createIdentityPublicRun(await prepareIdentityModel(c.source),{...c,orderedInputs:enc(list([expression]))})).rejects.toThrow();const s=await runtime(c),prior=s.input.state.read(path('Task',1436)).value!;expect(()=>applyStatePatch(s.input.state,{operations:[{kind:'set',path:path('Task',1436),expected:{presence:true,value:prior},newValue:prior}]},owner('Task','execution'),s.model.authority)).toThrow();},120000);
