import {describe,it,expect} from 'vitest';
import {createDevelopmentRun,restoreDevelopmentRun,developmentalGain,type DevelopmentProfile} from '../campaign3/developmentComponent';
import {profile,developmentFrames,simpleFrame} from './developmentFixtures';
const run=async(p=profile,xs=developmentFrames())=>{const r=createDevelopmentRun(p,xs);while(await r.step()){}return r;};
describe('development-component/0.1-candidate',()=>{
 it('derives independent monotone candidate age gains with nonzero mature plasticity',()=>{for(const curve of ['Step','Ramp'] as const){const g=Array.from({length:5},(_,i)=>developmentalGain(curve,i));expect(g[0].numerator/g[0].denominator).toBe(4n);expect(g[4].numerator).toBe(g[4].denominator);for(let i=1;i<5;i++)expect(g[i].compare(g[i-1])).toBeLessThanOrEqual(0);}expect(developmentalGain('Step',2).equals(developmentalGain('Ramp',2))).toBe(false);});
 it('earlier equivalent practice changes actual later execution before its own learning',async()=>{const a=(await run()).rows(),b=(await run(profile,developmentFrames(false))).rows();expect(a[0].executed).toBe(false);expect(b[0].executed).toBe(false);expect(a[1].skillBefore).toBe('1/2');expect(b[1].skillBefore).toBe('1/8');expect(a[1].executed).toBe(true);expect(b[1].executed).toBe(false);expect(a[7].skillAfter).not.toBe(a[7].skillBefore);});
 it('isolates the two developmental routes and preserves original authored evidence',async()=>{const [a,l,w,n]=await Promise.all([run(),run({...profile,learning:false}),run({...profile,formation:false}),run({...profile,learning:false,formation:false})]);const rows=[a,l,w,n].map(x=>x.rows());for(let i=0;i<18;i++){expect(rows[0][i].skillAfter).toBe(rows[2][i].skillAfter);expect(rows[1][i].skillAfter).toBe(rows[3][i].skillAfter);expect(rows[0][i].personalityAfter).toBe(rows[1][i].personalityAfter);expect(rows[2][i].personalityAfter).toBe(rows[3][i].personalityAfter);if(developmentFrames()[i].choice==='Learn'){expect(rows[0][i].expression).toBe(rows[2][i].expression);expect(rows[0][i].authorship).toBe(rows[2][i].authorship);expect(rows[0][i].journal).toBe(rows[2][i].journal);}}});
 it('preserves early formation after age convergence and allows later corrective change',async()=>{const a=(await run()).rows(),b=(await run(profile,developmentFrames(false))).rows();expect(a[6].phase).toBe(4);expect(b[6].phase).toBe(4);expect(a[3].personalityAfter).toBe(a[6].personalityBefore);expect(a[6].personalityBefore).not.toBe(b[6].personalityBefore);expect(a[6].probabilities).not.toEqual(b[6].probabilities);expect(a.slice(7,15).some(r=>r.personalityAfter!==r.personalityBefore)).toBe(true);});
 it('false reports can teach faster, without changing actual competence',async()=>{const frames=[simpleFrame({exercise:true,report:false}),simpleFrame({exercise:true,report:true})],a=(await run(profile,frames)).rows(),b=(await run(profile,frames.map(x=>({...x,phase:4})))).rows();expect(a[1].executed).toBe(false);expect(a[1].beliefAfter).toBe('1/2');expect(b[1].beliefAfter).toBe('1/8');expect(a[1].skillAfter).toBe('0/1');});
 it('distinguishes unknown, known zero, denied evidence and no practice opportunity',async()=>{const xs=[simpleFrame({report:true,practice:true}),simpleFrame({exercise:true,practice:true,permitted:false,report:true}),simpleFrame({exercise:true,report:false}),simpleFrame({exercise:true,report:null})],rs=(await run(profile,xs)).rows();expect(rs[0].beliefAfter).toBeNull();expect(rs[1].beliefAfter).toBeNull();expect(rs[1].skillAfter).toBe('0/1');expect(rs[2].beliefAfter).toBe('0/1');expect(rs[3].support).toBe(1);});
 it.each(['trivial','pressure','force'] as const)('does not grant youth authorship for %s',async control=>{const xs=developmentFrames().map(x=>x.choice==='Learn'?{...x,...(control==='trivial'?{significance:0 as const}:control==='pressure'?{pressure:4 as const}:{choice:'Forced' as const})}:x),rs=(await run(profile,xs)).rows();expect(rs.every(r=>r.personalityAfter==='0/1'&&r.formationEntry===null)).toBe(true);if(control==='force')expect(rs[0].expression).toBeNull();});
 it('saturates skill and still learns with mature gain',async()=>{for(const phase of [0,4]){const rs=(await run(profile,Array.from({length:10},()=>simpleFrame({phase,exercise:true,practice:true})))).rows();expect(rs.at(-1)!.skillAfter).toBe('1/1');expect(rs[0].skillAfter).not.toBe('0/1');}});
 it('restores every component prefix and exact successor without installing saved state',async()=>{const xs=developmentFrames().slice(0,4),r=createDevelopmentRun(profile,xs);for(let i=0;i<=4;i++){const s=r.save(),b=await restoreDevelopmentRun(profile,xs,s);expect(b.save()).toEqual(s);expect(await b.step()).toBe(await r.step());expect(b.save()).toEqual(r.save());}const bad=r.save();bad[bad.length-1]^=1;await expect(restoreDevelopmentRun(profile,xs,bad)).rejects.toThrow();});
 it('guards publication and atomically rolls back before commit',async()=>{const r=createDevelopmentRun(profile,developmentFrames()),before=r.save(),pending=r.step(true);expect(()=>r.save()).toThrow('NOT_QUIESCENT');await expect(r.step()).rejects.toThrow('NOT_QUIESCENT');await expect(pending).rejects.toThrow('INJECTED');expect(r.save()).toEqual(before);expect(await r.step()).toBe(true);});
 it('rejects malformed input without invoking getters and copies originals',async()=>{let calls=0;const p={...profile};Object.defineProperty(p,'learning',{get(){calls++;return true;}});expect(()=>createDevelopmentRun(p,developmentFrames())).toThrow('FIELDS');expect(calls).toBe(0);expect(()=>createDevelopmentRun(profile,[simpleFrame({phase:4}),simpleFrame({phase:0})])).toThrow('INPUT');const xs=developmentFrames(),r=createDevelopmentRun(profile,xs),s=r.save();xs[0].phase=4;expect(r.save()).toEqual(s);});
});
