/** biological-dynamics/0.1-candidate: world authority and explicit sensor projection. */
import {roundEven} from '../substrate/exactMath';
export const BIOLOGY_VERSION='biological-dynamics/0.1-candidate';
export const CHANNELS=['reward','stress','arousal'] as const;
export type Channel=typeof CHANNELS[number];
export const BIOLOGY_LAWS=['Full','NoTolerance','NoDisplacement','NoSensitization','NoRecovery','IndependentAxes','NoSatiation'] as const;
export type BiologyLaw=typeof BIOLOGY_LAWS[number];
export interface ChannelParameters {baseline:number;decay:number;threshold:number;toleranceGain:number;toleranceRecovery:number;sensitizationGain:number;sensitizationRecovery:number;displacementGain:number;displacementRecovery:number;satiationGain:number;satiationRecovery:number;}
export interface Constitution {fuelDrain:number;waterDrain:number;sleepAccumulation:number;sleepRecovery:number;healing:number;clearance:number;nightDrive:number;channels:Record<Channel,ChannelParameters>;network:{from:Channel;to:Channel;weight:number}[];}
export interface Regulator {level:number;displacement:number;satiation:number;tolerance:Record<string,number>;sensitization:Record<string,number>;}
export interface BiologyState {at:number;fuel:number;water:number;sleepDebt:number;damage:number;burden:number;phase:number;channels:Record<Channel,Regulator>;}
export interface Stimulus {channel:Channel;exposure:string;dose:number;direction:1|-1;}
export interface PhysicalInput {fuel:number;water:number;asleep:boolean;injury:number;intoxicant:number;stimuli:Stimulus[];}
export interface SensorPolicy {resolution:number;denied:string[];}
const copy=<T>(v:T):T=>structuredClone(v);
export const lattice=(n:bigint,d=1n)=>Number(roundEven(n,d));
const clamp=(v:number)=>Math.max(0,Math.min(1000,v));
const mul=(a:number,b:number)=>lattice(BigInt(a)*BigInt(b),1000n);
const check=(v:number,max=1000)=>{if(!Number.isSafeInteger(v)||v<0||v>max)throw Error('BIOLOGY_DOMAIN');};
const plain=(v:object)=>{if(!v||Object.getPrototypeOf(v)!==Object.prototype||Object.values(Object.getOwnPropertyDescriptors(v)).some(d=>!('value'in d)))throw Error('BIOLOGY_DATA');};
export function defaultConstitution():Constitution {
 const channel=(baseline:number):ChannelParameters=>({baseline,decay:500,threshold:0,toleranceGain:250,toleranceRecovery:20,sensitizationGain:0,sensitizationRecovery:20,displacementGain:125,displacementRecovery:10,satiationGain:500,satiationRecovery:100});
 return {fuelDrain:20,waterDrain:25,sleepAccumulation:35,sleepRecovery:180,healing:15,clearance:100,nightDrive:100,channels:{reward:channel(300),stress:{...channel(0),displacementGain:0,toleranceGain:0,satiationGain:0},arousal:{...channel(500),displacementGain:0,toleranceGain:0,satiationGain:0}},network:[]};
}
export function validateConstitution(c:Constitution){plain(c);for(const k of ['fuelDrain','waterDrain','sleepAccumulation','sleepRecovery','healing','clearance','nightDrive'] as const)check(c[k]);plain(c.channels);for(const k of CHANNELS){plain(c.channels[k]);for(const n of ['baseline','decay','threshold','toleranceGain','toleranceRecovery','sensitizationGain','sensitizationRecovery','displacementGain','displacementRecovery','satiationGain','satiationRecovery'] as const)check(c.channels[k][n]);}if(!Array.isArray(c.network)||c.network.length>6)throw Error('BIOLOGY_NETWORK');const seen=new Set<string>();for(const e of c.network){plain(e);if(!CHANNELS.includes(e.from)||!CHANNELS.includes(e.to)||e.from===e.to||!Number.isInteger(e.weight)||Math.abs(e.weight)>1000||seen.has(e.from+'/'+e.to))throw Error('BIOLOGY_NETWORK');seen.add(e.from+'/'+e.to);}}
export function initialBiology(c=defaultConstitution()):BiologyState {validateConstitution(c);return {at:0,fuel:800,water:800,sleepDebt:0,damage:0,burden:0,phase:8,channels:Object.fromEntries(CHANNELS.map(k=>[k,{level:c.channels[k].baseline,displacement:0,satiation:0,tolerance:{},sensitization:{}}])) as Record<Channel,Regulator>};}
export const emptyPhysicalInput=():PhysicalInput=>({fuel:0,water:0,asleep:false,injury:0,intoxicant:0,stimuli:[]});
export function validateBiology(s:BiologyState){plain(s);check(s.at,1000000);check(s.phase,23);for(const k of ['fuel','water','sleepDebt','damage','burden'] as const)check(s[k]);plain(s.channels);for(const k of CHANNELS){const r=s.channels[k];plain(r);for(const n of ['level','displacement','satiation'] as const)check(r[n]);for(const n of ['tolerance','sensitization'] as const){plain(r[n]);for(const [e,v] of Object.entries(r[n])){if(!/^[a-z][a-z0-9-]{0,31}$/.test(e)||['constructor','prototype'].includes(e))throw Error('BIOLOGY_EXPOSURE');check(v);if(!v)throw Error('BIOLOGY_CANONICAL_ZERO');}}}}
export function advanceBiology(prior:BiologyState,c:Constitution,input:PhysicalInput,law:BiologyLaw='Full',phase:'whole'|'elapsed'|'consequence'='whole'){
 validateConstitution(c);validateBiology(prior);plain(input);if(!BIOLOGY_LAWS.includes(law)||typeof input.asleep!=='boolean'||!Array.isArray(input.stimuli)||input.stimuli.length>12)throw Error('BIOLOGY_INPUT');for(const k of ['fuel','water','injury','intoxicant'] as const)check(input[k]);
 const seen=new Set<string>();for(const x of input.stimuli){plain(x);if(!CHANNELS.includes(x.channel)||!/^[a-z][a-z0-9-]{0,31}$/.test(x.exposure)||['constructor','prototype'].includes(x.exposure)||![1,-1].includes(x.direction)||seen.has(x.channel+'/'+x.exposure))throw Error('BIOLOGY_STIMULUS');check(x.dose);seen.add(x.channel+'/'+x.exposure);}
 if(!['whole','elapsed','consequence'].includes(phase)||phase==='elapsed'&&(input.fuel||input.water||input.injury||input.intoxicant||input.asleep||input.stimuli.length))throw Error('BIOLOGY_PHASE');
 const elapsed=phase!=='consequence',adapt=phase!=='elapsed',next=copy(prior);if(elapsed){next.at++;next.phase=(prior.phase+1)%24;}next.fuel=clamp(prior.fuel-(elapsed?c.fuelDrain:0)+input.fuel);next.water=clamp(prior.water-(elapsed?c.waterDrain:0)+input.water);next.sleepDebt=clamp(prior.sleepDebt+(input.asleep?-c.sleepRecovery:elapsed?c.sleepAccumulation:0));next.damage=clamp(prior.damage-(elapsed?c.healing:0)+input.injury);next.burden=clamp(prior.burden-(elapsed?c.clearance:0)+input.intoxicant);
 const terms:Record<string,unknown>={};
 for(const k of CHANNELS){
  const p=c.channels[k],r=prior.channels[k],n=next.channels[k],stimuli=input.stimuli.filter(x=>x.channel===k),decay=elapsed?mul(p.baseline-r.level,p.decay):0,network=!elapsed||law==='IndependentAxes'?0:c.network.filter(e=>e.to===k).reduce((v,e)=>v+mul(prior.channels[e.from].level-c.channels[e.from].baseline,e.weight),0);
  const effects=stimuli.map(x=>{const t=law==='NoTolerance'?0:r.tolerance[x.exposure]??0,s=law==='NoSensitization'?0:r.sensitization[x.exposure]??0,sat=law==='NoSatiation'?0:r.satiation,potential=lattice(BigInt(x.dose)*BigInt(1000+s)*BigInt(1000-sat),BigInt(1000+t)*1000n),effective=Math.max(0,potential-p.threshold);return {...x,tolerance:t,sensitization:s,satiation:sat,potential,effective};});
  const beforeClip=r.level+decay+network+effects.reduce((v,e)=>v+e.direction*e.effective,0);n.level=clamp(beforeClip);
  if(adapt)for(const [leaf,gain,recovery] of [['tolerance',p.toleranceGain,p.toleranceRecovery],['sensitization',p.sensitizationGain,p.sensitizationRecovery]] as const){const keys=new Set([...Object.keys(r[leaf]),...stimuli.map(x=>x.exposure)]);for(const e of keys){const dose=stimuli.find(x=>x.exposure===e)?.dose??0,value=clamp((r[leaf][e]??0)+(dose?mul(dose,gain):law==='NoRecovery'?0:-recovery));if(value)n[leaf][e]=value;else delete n[leaf][e];}}
  const dose=stimuli.reduce((v,x)=>v+x.dose,0);if(adapt)n.displacement=law==='NoDisplacement'?0:clamp(r.displacement+(dose?mul(dose,p.displacementGain):law==='NoRecovery'?0:-p.displacementRecovery));n.satiation=clamp(r.satiation-(elapsed?p.satiationRecovery:0)+mul(dose,p.satiationGain));
  terms[k]={decay,network,effects,beforeClip,overflow:beforeClip-n.level,target:clamp(p.baseline+r.displacement)};
 }
 validateBiology(next);return {state:next,terms};
}
export function physicalChallenges(s:BiologyState,c:Constitution){validateBiology(s);validateConstitution(c);const sleepiness=clamp(s.sleepDebt+(s.phase<6?c.nightDrive:0)),withdrawal=Object.fromEntries(CHANNELS.map(k=>[k,Math.max(0,clamp(c.channels[k].baseline+s.channels[k].displacement)-s.channels[k].level)])) as Record<Channel,number>;return {hunger:1000-s.fuel,thirst:1000-s.water,sleepiness,pain:s.damage,intoxication:s.burden,reward:s.channels.reward.level,stress:s.channels.stress.level,arousal:s.channels.arousal.level,withdrawal,control:clamp(lattice(BigInt(sleepiness+s.channels.stress.level+s.burden+Math.abs(s.channels.arousal.level-500)),2n)),execution:clamp(lattice(BigInt(s.damage+s.burden),2n))};}
export function senseBiology(s:BiologyState,c:Constitution,policy:SensorPolicy){plain(policy);if(!Number.isInteger(policy.resolution)||policy.resolution<=0||1000%policy.resolution||!Array.isArray(policy.denied))throw Error('BIOLOGY_SENSOR');const x=physicalChallenges(s,c),flat={hunger:x.hunger,thirst:x.thirst,sleepiness:x.sleepiness,pain:x.pain,intoxication:x.intoxication,reward:x.reward,pleasure:Math.max(0,x.reward-c.channels.reward.baseline),stress:x.stress,arousal:x.arousal,withdrawalReward:x.withdrawal.reward,withdrawalStress:x.withdrawal.stress,withdrawalArousal:x.withdrawal.arousal};if(policy.denied.some(k=>!Object.hasOwn(flat,k))||new Set(policy.denied).size!==policy.denied.length)throw Error('BIOLOGY_SENSOR');return Object.fromEntries(Object.entries(flat).map(([k,v])=>[k,policy.denied.includes(k)?null:Math.floor(v/policy.resolution)*policy.resolution])) as Record<keyof typeof flat,number|null>;}
