/** biology-public/0.1-candidate; safe cognitive operands only. */
import {lattice,senseBiology,type BiologyState,type Constitution,type SensorPolicy,type PhysicalInput} from './biologicalDynamics';
import {ACTIONS,DOMAINS,type Action,type Domain,type BiologicalFrame,type IntegrationLaw,type IntegrationConfig} from './biologicalIntegration';
import type {Ground} from './biologicalChoice';
const clone=<T>(v:T):T=>structuredClone(v),clamp=(v:number)=>Math.max(0,Math.min(1000,v)),mul=(a:number,b:number)=>lattice(BigInt(a)*BigInt(b),1000n);
export function dataOnly(value:unknown,seen=new Set<object>()){if(value===null||typeof value==='string'||typeof value==='boolean')return;if(typeof value==='number'){if(!Number.isFinite(value))throw Error('BIO_INTEGRATION_DATA');return;}if(typeof value!=='object'||seen.has(value))throw Error('BIO_INTEGRATION_DATA');const array=Array.isArray(value);if(Object.getPrototypeOf(value)!==(array?Array.prototype:Object.prototype))throw Error('BIO_INTEGRATION_DATA');seen.add(value);const ds=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(value).some(k=>typeof k!=='string')||Object.values(ds).some(d=>!('value'in d))||array&&Object.keys(value).length!==(value as unknown[]).length)throw Error('BIO_INTEGRATION_DATA');for(const [k,d] of Object.entries(ds))if(!(array&&k==='length'))dataOnly(d.value,seen);seen.delete(value);}
export type View=ReturnType<typeof senseBiology>;
export type Sample={at:number;action:Action;cue:boolean;outcomes:Record<Domain,number|null>};
export function observation(body:BiologyState,c:Constitution,policy:SensorPolicy,law:IntegrationLaw):View {const view=senseBiology(body,c,policy);if(law!=='BaselinePleasure'&&view.pleasure!==null){const gap=Math.max(0,body.channels.reward.level-Math.min(1000,c.channels.reward.baseline+body.channels.reward.displacement));view.pleasure=Math.floor(clamp(gap+(policy.bias?.pleasure??0))/policy.resolution)*policy.resolution;}return view;}
export function experienced(before:View,after:View):Record<Domain,number|null>{const diff=(k:keyof View)=>before[k]===null||after[k]===null?null:Math.max(0,before[k]!-after[k]!);const pain=before.pain===null||after.pain===null?null:Math.max(0,after.pain-before.pain),intox=before.intoxication===null||after.intoxication===null?null:Math.max(0,after.intoxication-before.intoxication);return {pleasure:before.pleasure===null||after.pleasure===null?null:Math.max(0,after.pleasure-before.pleasure),withdrawal:diff('withdrawalReward'),hunger:diff('hunger'),thirst:diff('thirst'),sleep:diff('sleepiness'),pain:diff('pain'),stress:diff('stress'),harm:pain===null||intox===null?null:Math.max(pain,intox)};}
export function estimates(history:Sample[],action:Action,law:IntegrationLaw){return Object.fromEntries(DOMAINS.map(domain=>{const xs=history.filter(s=>s.action===action&&s.outcomes[domain]!==null).map(s=>s.outcomes[domain]!);return [domain,!xs.length?null:law==='Latest'?xs.at(-1)!:lattice(BigInt(xs.reduce((a,b)=>a+b,0)),BigInt(xs.length))];})) as Record<Domain,number|null>;}
export function mergeInput(a:PhysicalInput,b:PhysicalInput):PhysicalInput {const stimuli=clone(a.stimuli);for(const x of b.stimuli){const old=stimuli.find(y=>y.channel===x.channel&&y.exposure===x.exposure);if(old)throw Error('BIO_INTEGRATION_EXPOSURE_COLLISION');stimuli.push(clone(x));}return {fuel:clamp(a.fuel+b.fuel),water:clamp(a.water+b.water),injury:clamp(a.injury+b.injury),intoxicant:clamp(a.intoxicant+b.intoxicant),asleep:a.asleep||b.asleep,stimuli};}

export type Goals={protection:boolean;work:boolean;maintained:boolean};
export type Context=Pick<BiologicalFrame,'available'|'cue'|'practice'|'adoptProtection'|'adoptWork'|'reminder'|'support'|'load'>;
export function context(f:BiologicalFrame):Context{return {available:f.available,cue:f.cue,practice:f.practice,adoptProtection:f.adoptProtection,adoptWork:f.adoptWork,reminder:f.reminder,support:f.support,load:f.load};}
export function maintain(prior:Goals,f:Context):Goals {const protection=prior.protection||f.adoptProtection,work=prior.work||f.adoptWork;return {protection,work,maintained:(protection||work)&&(f.reminder||prior.maintained&&f.support)};}
export function appraise(before:View,f:Context,goals:Goals,history:Sample[],c:Pick<IntegrationConfig,'controlThreshold'|'protectionImportance'|'workImportance'>,law:IntegrationLaw){
const beliefs=Object.fromEntries(ACTIONS.map(a=>[a,estimates(history,a,law)])) as Record<Action,Record<Domain,number|null>>,habit=Object.fromEntries(ACTIONS.map(a=>[a,history.filter(s=>s.action===a&&s.cue===f.cue).reduce((h,s)=>lattice(BigInt(h+((s.outcomes.pleasure??0)>0||(s.outcomes.withdrawal??0)>0?1000:0)),2n),0)])) as Record<Action,number>;const known=[before.sleepiness,before.stress,before.intoxication,before.arousal].every(x=>x!==null),control=known?clamp(1000-lattice(BigInt(before.sleepiness!+before.stress!+before.intoxication!+Math.abs(before.arousal!-500)),2n)-f.load):null,inhibited=law!=='NoControl'&&goals.protection&&goals.maintained&&control!==null&&control>=c.controlThreshold;
   const options=f.available.filter(a=>f.practice?a===f.practice:(!(a==='drug'&&inhibited)&&(a==='work'||a==='withhold'||law==='KnownAccess'||(a==='drug'?habit[a]>=500:habit[a]>=500||DOMAINS.some(d=>(beliefs[a][d]??0)>0)))));
   const grounds:Ground[]=[];const add=(option:Action,domain:string,strength:number)=>{if(strength)grounds.push({option,domain,strength:Math.max(-1000,Math.min(1000,strength))});};
   for(const a of options){if(f.practice){add(a,'practice',1000);continue;}const b=beliefs[a],cueCount=history.filter(s=>s.action===a&&s.cue===f.cue).length,reward=law==='CueHabituation'?lattice(BigInt(b.pleasure??0)*4n,BigInt(4+cueCount)):b.pleasure??0;add(a,'pleasure',reward);
    for(const [domain,pressure] of [['withdrawal',before.withdrawalReward],['hunger',before.hunger],['thirst',before.thirst],['sleep',before.sleepiness],['pain',before.pain],['stress',before.stress]] as const)if(pressure!==null&&!(domain==='withdrawal'&&law==='NoReliefLearning'))add(a,domain,mul(pressure,b[domain]??0));
    if(goals.protection&&goals.maintained){add(a,'protection',-mul(c.protectionImportance,b.harm??0));if(a==='withhold')add(a,'protective-goal',c.protectionImportance);}if(a==='work'&&goals.work&&goals.maintained)add(a,'work-goal',c.workImportance);
   }
   const vulnerability=before.pain===null?null:clamp(500+lattice(BigInt(before.pain),2n)),threat=beliefs.drug.harm===null||vulnerability===null?null:mul(mul(beliefs.drug.harm,c.protectionImportance*(goals.protection?1:0)),vulnerability),distress=before.withdrawalReward===null||before.stress===null||before.pain===null?null:Math.max(before.withdrawalReward,before.stress,before.pain);

return {before,goals,beliefs,habit,control,inhibited,options,grounds,affect:{pleasure:before.pleasure,distress,threat}};
}
export type Appraisal=ReturnType<typeof appraise>;
export function learn(history:Sample[],action:Action|null,receipt:Record<Domain,number|null>|null,at:number,cue:boolean,law:IntegrationLaw){const next=clone(history);if(action&&receipt&&law!=='NoLearning')next.push({at,action,cue,outcomes:{...receipt,...(law==='NoReliefLearning'?{withdrawal:null}:{})}});return next;}
