import {ACTIONS,INTEGRATION_LAWS,type IntegrationConfig,type BiologicalFrame,type IntegrationLaw} from './biologicalIntegration';
import {CHANNELS,BIOLOGY_LAWS,validateBiology,validateConstitution,advanceBiology,emptyPhysicalInput,initialBiology,senseBiology,type BiologyState,type PhysicalInput,type SensorPolicy} from './biologicalDynamics';
import {dataOnly} from './biologyPublicMath';
function keys(v:object,required:readonly string[],optional:readonly string[]=[]){if(!v||Array.isArray(v)||Object.getPrototypeOf(v)!==Object.prototype||Object.keys(v).some(k=>!required.includes(k)&&!optional.includes(k))||required.some(k=>!Object.hasOwn(v,k)))throw Error('BIOLOGY_EXACT_FIELDS');}
const range=(v:number)=>{if(!Number.isInteger(v)||v<0||v>1000)throw Error('BIOLOGY_SCALAR');};
function physical(v:PhysicalInput){keys(v,['fuel','water','asleep','injury','intoxicant','stimuli']);for(const s of v.stimuli)keys(s,['channel','exposure','dose','direction']);}
const senses=['hunger','thirst','sleepiness','pain','intoxication','reward','pleasure','stress','arousal','withdrawalReward','withdrawalStress','withdrawalArousal'];
function sensor(v:SensorPolicy){keys(v,['resolution','denied'],['bias']);if(v.bias)keys(v.bias,[],senses);}
export function admitBody(body:BiologyState){dataOnly(body);keys(body,['at','fuel','water','sleepDebt','damage','burden','phase','channels']);keys(body.channels,CHANNELS);for(const c of Object.values(body.channels))keys(c,['level','displacement','satiation','tolerance','sensitization']);validateBiology(body);}
export function admitConfig(law:IntegrationLaw,c:IntegrationConfig){dataOnly(c);if(!INTEGRATION_LAWS.includes(law)||!BIOLOGY_LAWS.includes(c.worldLaw))throw Error('BIOLOGY_LAW');keys(c,['constitution','initial','worldLaw','catalog','competence','controlThreshold','protectionImportance','workImportance']);keys(c.constitution,['fuelDrain','waterDrain','sleepAccumulation','sleepRecovery','healing','clearance','nightDrive','channels','network']);keys(c.constitution.channels,CHANNELS);for(const p of Object.values(c.constitution.channels))keys(p,['baseline','decay','threshold','toleranceGain','toleranceRecovery','sensitizationGain','sensitizationRecovery','displacementGain','displacementRecovery','satiationGain','satiationRecovery']);for(const edge of c.constitution.network)keys(edge,['from','to','weight']);validateConstitution(c.constitution);admitBody(c.initial);keys(c.catalog,ACTIONS);for(const input of Object.values(c.catalog)){physical(input);advanceBiology(c.initial,c.constitution,input,c.worldLaw);}for(const n of [c.competence,c.controlThreshold,c.protectionImportance,c.workImportance])range(n);}
export function admitFrame(f:BiologicalFrame,c:IntegrationConfig){dataOnly(f);keys(f,['available','cue','practice','adoptProtection','adoptWork','reminder','support','load','interference','sensor','receipt','external'],['consequenceSensor']);physical(f.external);sensor(f.sensor);if(f.consequenceSensor)sensor(f.consequenceSensor);advanceBiology(c.initial,c.constitution,f.external,c.worldLaw);senseBiology(c.initial,c.constitution,f.sensor);if(f.consequenceSensor)senseBiology(c.initial,c.constitution,f.consequenceSensor);}
