/** commit-public/0.1-candidate: registered owners, causal lifecycle and selective witnesses. */
import {canonicalEncode as enc,list,text,unsigned as u,signed,rational as q,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {AuthoritativeState,applyStatePatch,restoreAuthoritativeState,statePathPatternValue,type ActualReadRecord,type StatePatch,type StructuralMutationDiff,type StatePath} from '../substrate/state';
import {DeterministicScheduler,SchedulerContractError,type EventHandlerContext,type EventEmission,type ScheduledEvent,type ConformanceInstrumentation} from '../substrate/scheduler';
import {createCanonicalSave,scheduledEventValue} from '../substrate/persistence';
import {traceRecordValue} from '../substrate/trace';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {ONE,readQ,compileReasonNuclei,appendIdentityContribution} from '../campaign2/cognitiveMath';
import {rawSignalOutput} from '../campaign2/cognitiveTransforms';
import {createCognitiveRandomSession,arbitrationOutput} from '../campaign2/cognitiveArbitration';
import {intentOutput,expressionOutput,qualificationOutput,chosenData} from '../campaign2/cognitiveChoice';
import {receivingRecord as old} from './receivingCodecs';
import {biographyContext} from './longitudinalMath';
import {commitRecord as r,decodeCommit as decode} from './commitCodecs';
import {VERSION,STAGES,OBSERVERS,ACTOR,TASKS,sid,eventId,taskPath,identityPath,personPath,observerIndex,pattern,owner,reads,writes,type CommitCompiled,compileCommitInputs} from './commitModel';
import {commitmentContext,nextInstances} from './commitMath';
export function createCommitRuntime(model:CommitCompiled,input:Awaited<ReturnType<typeof compileCommitInputs>>){
 const originals=new Map(input.events.map(e=>[e.eventId,key(scheduledEventValue(e))])),random=createCognitiveRandomSession(input.runSeed);let active=false,expected=new Map<bigint,string>();const fail=(why:string):never=>{throw new SchedulerContractError('INPUT_NOT_ADMITTED',why);};
 const adapter={clone:(s:AuthoritativeState)=>new AuthoritativeState(s.entries()),validate:model.validateState,canonicalValue:(s:AuthoritativeState)=>s.canonicalValue(),restore:restoreAuthoritativeState,analyticalAnchors:()=>list([]),randomRelevantAuthoritativeIds:()=>list([])};
 async function handler({event,state,allocateRuntimeId}:EventHandlerContext<AuthoritativeState>){
  if(!active)fail('inactive commit transaction');const stage=STAGES.find(([n])=>key(event.eventTypeId)===key(eventId(n)));if(!stage)fail('commit stage');const [name,phase]=stage!;if(event.phase!==BigInt(phase))fail('commit phase');const fingerprint=key(scheduledEventValue(event));if(['source','context','probe-a','probe-b','communication'].includes(name)){if(originals.get(event.eventId)!==fingerprint)fail('commit original');}else{if(expected.get(event.eventId)!==fingerprint)fail('commit generated');expected.delete(event.eventId);}
  const occurrence=(ns=1162)=>typedIdentifier(ns,u(allocateRuntimeId())),paths=reads(name),domain=paths.map(pattern),actualReads:ActualReadRecord[]=[],pk=(p:StatePath)=>key(statePathPatternValue(pattern(p))),read=(p:StatePath)=>{if(!paths.some(x=>pk(x)===pk(p)))return fail('commit read domain');const prior=state.read(p);actualReads.push({accessorId:sid(1028,'accessor/commit/'+name),path:p,presence:prior.presence,value:prior.value,derivedSources:[]});return prior.value;};
  const outputs:CanonicalValue[]=[],emittedEvents:EventEmission[]=[];let nextState=state,patch:StatePatch={operations:[]},diffs:readonly StructuralMutationDiff[]=[],randomDrawRecords:CanonicalValue[]=[],quantizationOperations:CanonicalValue[]=[];
  const emit=(next:string,payload:CanonicalValue)=>emittedEvents.push({dueAt:event.dueAt,phase:BigInt(STAGES.find(([n])=>n===next)![1]),eventTypeId:eventId(next),payload,dependencies:list([])}),write=(changes:{path:StatePath;prior:CanonicalValue|undefined;next:CanonicalValue}[])=>{if(changes.some(c=>!writes(name).some(p=>pk(p)===pk(c.path))))fail('commit write domain');patch={operations:changes.map(c=>({kind:'set' as const,path:c.path,expected:c.prior?{presence:true as const,value:c.prior}:{presence:false as const},newValue:c.next}))};const applied=applyStatePatch(state,patch,owner(name),model.authority);nextState=applied.state;diffs=applied.diffs;};
  if(name==='source'){const v=rec(event.payload,954n);if(uint(f(v,3n))>0n)emit('lifecycle',f(v,3n));}
  else if(name==='context'){const training=f(rec(event.payload,954n),2n)===true;if(training)emit('raw',list([true,biographyContext(event.dueAt,occurrence),old(414,[list([])]),list([])]));else{const instances=[read(taskPath(0)),read(taskPath(1))].filter((v):v is CanonicalValue=>v!==undefined),history=read(identityPath);if(!history)fail('commit earned identity required');emit('raw',list([false,commitmentContext(event.dueAt,occurrence,instances,model.law),history!,list(instances)]));}}
  else if(name==='raw'){const pair=items(event.payload,'list'),result=rawSignalOutput(occurrence(1133),pair[1],pair[0]!==true,readQ(q(1,100)),()=>pair[2]);quantizationOperations=result.quantizationOperations;outputs.push(result.output);emit('reasons',list([pair[0],result.output,pair[2],pair[3]]));}
  else if(name==='reasons'){const pair=items(event.payload,'list'),context=old(408,[occurrence(1134),pair[1],list(compileReasonNuclei(items(f(rec(pair[1],403n),3n),'set'),f(model.content,pair[0]===true?5n:4n)))]);outputs.push(context);if(pair[0]!==true)outputs.push(r(959,[occurrence(),signed(event.dueAt),pair[3],pair[2],pair[1],context]));emit('decision',list([pair[0],context]));}
  else if(name==='decision'){const pair=items(event.payload,'list'),root=typedIdentifier(1135,u(event.dueAt)),out=await arbitrationOutput(root,event.dueAt,pair[1],old(440,[q(1,2),q(1,2)]),random.forResolution(root,pair[1]));outputs.push(out);if(uint(f(rec(f(rec(out,409n),4n),419n),1n))===3n){const data=chosenData(out);randomDrawRecords=items(f(data,9n),'list').map(v=>f(rec(v,422n),5n));const tie=rec(f(data,10n),423n);if(uint(f(tie,1n))===2n)randomDrawRecords.push(f(tie,3n));emit('expression',list([pair[0],out]));}}
  else if(name==='expression'){const pair=items(event.payload,'list'),intent=intentOutput(occurrence(1136),pair[1]),expression=expressionOutput(occurrence(1137),intent);outputs.push(intent,expression);if(pair[0]===true)emit('qualification',expression);}
  else if(name==='qualification'){const out=qualificationOutput(occurrence(1138),event.payload);outputs.push(out);emit('identity',out);}
  else if(name==='identity'){const prior=read(identityPath),history=prior??old(414,[list([])]),qualification=rec(event.payload,429n),result=rec(f(qualification,3n),430n);if(uint(f(result,1n))!==1n)fail('commit training must qualify');const expression=rec(f(qualification,2n),426n),resolution=rec(f(rec(f(expression,2n),425n),2n),409n),contribution=old(413,[f(qualification,1n),f(resolution,1n),signed(event.dueAt),f(result,3n)]),fold=appendIdentityContribution(items(f(rec(history,414n),1n),'list'),contribution,ONE);quantizationOperations=fold.operations;write([{path:identityPath,prior,next:fold.history}]);outputs.push(r(960,[occurrence(),history,fold.history,qualification]));}
  else if(name==='lifecycle'){const priors=[read(taskPath(0)),read(taskPath(1))],before=priors.filter((v):v is CanonicalValue=>v!==undefined),command=Number(uint(event.payload)),after=nextInstances(before,command,model.law);write(after.flatMap(v=>{const i=TASKS.findIndex(t=>key(t)===key(f(rec(v,955n),1n)));if(i<0)return fail('commit foreign instance');return priors[i]&&key(priors[i]!)===key(v)?[]:[{path:taskPath(i),prior:priors[i],next:v}];}));outputs.push(r(957,[occurrence(),u(command),list(before),list(after)]));}
  else if(name.startsWith('probe')){const i=observerIndex(name),claims=TASKS.flatMap((task,j)=>{const prior=read(personPath(i,j));return prior?[r(964,[task,f(rec(prior,967n),1n),f(rec(prior,967n),2n)])]:[];});outputs.push(r(968,[occurrence(),signed(event.dueAt),OBSERVERS[i],list(claims)]));}
  else if(name==='communication'){const original=rec(event.payload,954n),j=Number(uint(f(original,4n)))-1;if(j>=0){const instance=read(taskPath(j)),out=r(961,[occurrence(),signed(event.dueAt),TASKS[j],instance?f(rec(instance,955n),3n):u(0)]);outputs.push(out);for(const recipient of items(f(original,5n),'set'))emit(uint(recipient)===1n?'observe-a':'observe-b',out);}}
  else if(name.startsWith('observe')){const i=observerIndex(name),truth=rec(event.payload,961n),out=r(962,[occurrence(),OBSERVERS[i],signed(event.dueAt),f(truth,3n),f(truth,4n)]);outputs.push(out);emit(i===0?'evidence-a':'evidence-b',out);}
  else if(name.startsWith('evidence')){const i=observerIndex(name),observation=rec(event.payload,962n);if(key(f(observation,2n))!==key(OBSERVERS[i]))fail('commit foreign observation');const out=r(963,[occurrence(),observation]);outputs.push(out);emit(i===0?'update-a':'update-b',out);}
  else{const i=observerIndex(name),evidence=rec(event.payload,963n),observation=rec(f(evidence,2n),962n),j=TASKS.findIndex(t=>key(t)===key(f(observation,4n)));if(j<0||key(f(observation,2n))!==key(OBSERVERS[i]))fail('commit foreign evidence');const prior=read(personPath(i,j)),next=r(967,[f(observation,5n),f(observation,1n)]);write([{path:personPath(i,j),prior,next}]);outputs.push(r(970,[occurrence(),OBSERVERS[i],evidence,next,...(prior?[prior]:[])]));}
  outputs.forEach(v=>decode(enc(v)));return {nextState,outputs,emittedEvents,traceContributions:[],traceFactory:(children:readonly ScheduledEvent[])=>{if(children.length!==emittedEvents.length)fail('commit child count');children.forEach((e,i)=>{if(e.causalParentEventIds.length!==1||e.causalParentEventIds[0]!==event.eventId||key(e.payload)!==key(emittedEvents[i].payload))fail('commit child association');expected.set(e.eventId,key(scheduledEventValue(e)));});return [traceRecordValue({traceSchemaVersion:'trace/0.2-candidate',modelIdentity:model.modelIdentity.value,runIdentity:input.runIdentity.value,event,seamId:sid(1036,'seam/commit/'+name),seamVersion:VERSION,recordKind:event.eventTypeId,subjectIds:[ACTOR],sourceRecordIds:[],registeredReadDomain:domain,actualReadRecords:actualReads,inputProjection:event.payload,outputProjection:list(outputs),randomDrawRecords,quantizationOperations,statePatch:patch,structuralMutationDiffs:diffs,emittedEvents:children,invariantResults:[]})];}};
 }
 const scheduler=new DeterministicScheduler({initialState:new AuthoritativeState([]),stateAdapter:adapter,handlers:new Map(STAGES.map(([n])=>[key(eventId(n)),handler])),initialQueue:input.events,initialAllocators:{nextRuntimeId:0n,nextEventId:BigInt(input.events.length),nextEventSequence:BigInt(input.events.length)},maxSettlementWorkPerSimulationInstant:32n,invariants:[state=>{if(expected.size)fail('commit pending children');model.validateState(state);random.prepareCommit();}]});
 async function settle(instrumentation?:ConformanceInstrumentation){if(active)fail('commit concurrent settlement');if(!scheduler.getPendingQueue().length)return undefined;active=true;expected=new Map();random.begin();try{const result=instrumentation?await scheduler.settleNextInstantForConformance(instrumentation):await scheduler.settleNextInstant();if(result)random.commit();return result;}finally{active=false;expected.clear();random.close();}}
 return {settle:()=>settle(),settleForConformance:(i:ConformanceInstrumentation)=>settle(i),snapshot:()=>({state:scheduler.getState(),clock:scheduler.getClock(),status:scheduler.status,queue:scheduler.getPendingQueue(),allocators:scheduler.getAllocatorState(),trace:scheduler.getCommittedTrace(),outputs:scheduler.getOutputs(),randomAddresses:random.committedAddressKeys()}),save:()=>createCanonicalSave({scheduler,stateAdapter:adapter,modelIdentity:model.modelIdentity,runIdentity:input.runIdentity,continuingRunInputs:list(random.committedAddressKeys().map(text))}),diagnostic:()=>scheduler.failureDiagnostic};
}
