import {canonicalEncode as enc,list,text,unsigned as u,rational as q,type CanonicalValue} from '../substrate/canonicalEncoding';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {workspaceOutput,appraisalOutput,concernOutput,motiveOutput,candidateOutput} from '../campaign2/cognitiveTransforms';
import {ZERO,ONE} from '../campaign2/cognitiveMath';
import {receivingRecord as old} from './receivingCodecs';
import {commitRecord as r,decodeCommit} from './commitCodecs';
import {ACTOR,TASKS,OPTIONS,NEED,OBSERVERS,sid} from './commitModel';
export function commitmentContext(at:bigint,occ:(ns?:number)=>CanonicalValue,instances:readonly CanonicalValue[],law:number){
 const effective=law===2?[NEED]:instances.filter(v=>law===3||uint(f(rec(v,955n),3n))===1n).map(v=>f(rec(v,955n),1n)),tasks=effective.map(task=>({key:task,specId:sid(1027,'definition/commit/task/'+(key(task)===key(NEED)?'need':TASKS.findIndex(t=>key(t)===key(task)))),activeFrom:1n,deadline:17n}));
 const workspace=workspaceOutput(occ(1128),ACTOR,sid(1027,'definition/commit/agenda'),old(378,[sid(1027,'definition/commit/prediction'),u(3),true,false]),tasks,at,{status:()=>old(372,[u(1)]),prediction:()=>undefined}).output,appraisal=appraisalOutput(occ(1129),workspace,tasks.map(t=>({taskKey:t.key,specId:t.specId,minimum:ZERO,maximum:ONE}))),concern=concernOutput(occ(1130),appraisal,old(385,[q(0,1),false])),motive=motiveOutput(occ(1131),concern,old(392,[q(1,10),true]));return candidateOutput(occ(1132),motive,true,()=>({instructionId:sid(1027,'definition/commit/instruction'),actionId:f(rec(OPTIONS[0],395n),2n)}));
}
export function nextInstances(prior:readonly CanonicalValue[],command:number,law:number){const by=new Map(prior.map(v=>[key(f(rec(v,955n),1n)),v])),a=by.get(key(TASKS[0])),b=by.get(key(TASKS[1]));if(command===1){if(a)throw Error('COMMIT_ALREADY_CREATED');by.set(key(TASKS[0]),r(955,[TASKS[0],u(1),u(1),u(0)]));}else if(command===2){if(!a||uint(f(rec(a,955n),3n))!==1n||uint(f(rec(a,955n),2n))!==1n)throw Error('COMMIT_CANCEL_PRECONDITION');by.set(key(TASKS[0]),r(955,[TASKS[0],u(2),u(2),u(1)]));}else if(command===3){if(!a||uint(f(rec(a,955n),3n))!==2n||b)throw Error('COMMIT_RECURRENCE_PRECONDITION');by.set(key(TASKS[law===4?0:1]),law===4?r(955,[TASKS[0],u(3),u(1),u(2)]):r(955,[TASKS[1],u(1),u(1),u(0)]));}else throw Error('COMMIT_COMMAND');return [...by.values()].sort((a,b)=>key(f(rec(a,955n),1n))<key(f(rec(b,955n),1n))?-1:1);}
export function commitObserverView(outputs:readonly CanonicalValue[],i:number){if(i!==0&&i!==1)throw Error('COMMIT_OBSERVER');const view:CanonicalValue[]=[],privateTypes=new Set([403n,408n,409n,425n,426n,429n,957n,959n,960n,961n]);for(const value of outputs){decodeCommit(enc(value));if(typeof value==='boolean'||value.kind!=='record')throw Error('COMMIT_OUTPUT_ROSTER');const type=value.schema.typeId;if(privateTypes.has(type))continue;let observer:CanonicalValue;if(type===968n)observer=f(value,3n);else if(type===962n||type===970n)observer=f(value,2n);else if(type===963n)observer=f(rec(f(value,2n),962n),2n);else throw Error('COMMIT_OUTPUT_ROSTER');if(key(observer)===key(OBSERVERS[i]))view.push(type===968n?list([text('known-commitments'),f(value,2n),observer,f(value,4n)]):value);}return list(view);}
