import {list,map,unsigned as u,signed,type CanonicalValue} from '../substrate/canonicalEncoding';
import {ExactRational as Q} from '../substrate/exactMath';
import {ZERO,ONE,readQ,qValue,compileReasonNuclei,readDistribution,analyzeOptions,absolute,expectation} from '../campaign2/cognitiveMath';
import {RandomRunOracle,randomAddressValue,type RandomAddress} from '../substrate/random';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataIdentity as id,dataUnsigned as uint} from '../campaign2/canonicalData';
import {controlRecord} from './controlCodecs';
import {habitRecord} from './habitCodecs';
const r=(n:number,v:readonly CanonicalValue[]|ReadonlyMap<bigint,CanonicalValue>)=>n>=1017?controlRecord(n,v):habitRecord(n,v);
import {receivingRecord as old} from './receivingCodecs';
import {OPTIONS,TASK,CHARACTER,sid,type ControlSettings,type ControlCompiled} from './controlModel';
export function controlSummary(settings:ControlSettings,journal:CanonicalValue){const xs=items(f(rec(journal,820n),1n),'list'),hs=[false,true].map(cue=>{let h=ZERO;for(const row of xs){const e=rec(row,819n);if(f(e,3n)!==cue||settings.law===3)continue;const positive=f(e,4n)===true;if(settings.law===1)h=h.add(positive?ONE:ZERO).divide(Q.of(2n));else {h=h.add(positive?Q.of(1n,4n):Q.of(-1n,4n));if(h.compare(ONE)>0)h=ONE;if(h.compare(ZERO)<0)h=ZERO;}}return qValue(h);});return r(824,[...hs,u(xs.length)]);}
export function controlOptions(settings:ControlSettings,app:CanonicalValue,occ:CanonicalValue){const a=rec(app,826n),mode=uint(f(a,4n)),b=a.fields.get(6n),positive=!!b&&f(rec(b,822n),1n)===true,h=readQ(f(a,5n)),admitted=settings.candidate===4?f(a,7n)===true:positive||(settings.candidate<3&&h.compare(Q.of(1n,2n))>=0);return r(827,[occ,app,list(mode===1n?[OPTIONS[0]]:mode===3n?[OPTIONS[1]]:admitted?OPTIONS:[OPTIONS[1]])]);}
export function controlRaw(options:CanonicalValue,occ:CanonicalValue){const o=rec(options,827n),a=rec(f(o,2n),826n),b=a.fields.get(6n),positive=uint(f(a,4n))===1n||!!b&&f(rec(b,822n),1n)===true,present=items(f(o,3n),'list').some(x=>key(x)===key(OPTIONS[0]));return r(1017,[occ,options,list(positive&&present?[old(402,[old(401,[OPTIONS[0],TASK,u(1)]),qValue(ONE),old(400,[map([])])])]:[])]);}
export function controlReasons(model:ControlCompiled,raw:CanonicalValue,occ:CanonicalValue){return r(1018,[occ,raw,list(compileReasonNuclei(items(f(rec(raw,1017n),3n),'list'),f(model.content,5n)))]);}
export async function controlDecision(reasons:CanonicalValue,at:bigint,occ:CanonicalValue,seed:Uint8Array){const rs=rec(reasons,1018n),nuclei=items(f(rs,3n),'list'),options=items(f(rec(f(rec(f(rs,2n),1017n),2n),827n),3n),'list'),distributions=options.map(option=>{const n=nuclei.find(n=>key(f(rec(f(rec(n,407n),1n),404n),1n))===key(option)),distribution=n?readDistribution(f(rec(n,407n),7n)):new Map([[0n,ONE]]);return {key:option,distribution,reasonMass:absolute(expectation(distribution))};}),analysis=analyzeOptions(distributions,ONE,ONE),mode={Auto:1,QuietRoll:2,PlayerFacingRoll:3}[analysis.mode as 'Auto'|'QuietRoll'|'PlayerFacingRoll'],oracle=new RandomRunOracle(seed),draws:CanonicalValue[]=[],scores=new Map(options.map(o=>[key(o),0n]));let chosen=analysis.ranked[0].key;
 async function draw(purpose:string,bindings:RandomAddress['subjectBindings'],span:bigint){const d=await oracle.drawBounded({causalRootId:id(occ),purposeId:sid(1042,'purpose/control/'+purpose),subjectBindings:bindings,drawIndex:0n},span);draws.push(old(411,[randomAddressValue(d.localAddress),d.effectiveKey,u(d.result),u(d.span),u(d.limit),d.fallback,list(d.attempts.map(a=>old(410,[u(a.internalCandidateIndex),u(a.candidate),a.rejected])))]));return d.result;}
 const binding=(role:string,v:CanonicalValue)=>({subjectRoleId:sid(1043,'subject/control/'+role),subjectId:id(v)});
 if(mode!==1){for(const value of nuclei){const n=rec(value,407n),nk=rec(f(n,1n),404n),option=rec(f(nk,1n),395n),face=await draw('reason-face',[binding('actor',CHARACTER),binding('action',f(option,2n)),binding('ground',f(nk,3n))],uint(f(n,4n))),standing=f(n,5n),situation=f(n,6n);if(typeof standing==='boolean'||standing.kind!=='signed'||typeof situation==='boolean'||situation.kind!=='signed')throw Error('CONTROL_MODIFIER');scores.set(key(option),(uint(f(nk,4n))===1n?1n:-1n)*(face+1n+standing.value+situation.value));}const top=[...scores.values()].reduce((a,b)=>a>b?a:b),leaders=options.filter(o=>scores.get(key(o))===top).sort((a,b)=>key(a)<key(b)?-1:1);chosen=leaders[0];if(leaders.length>1)chosen=leaders[Number(await draw('tie',[binding('actor',CHARACTER)],BigInt(leaders.length)))];}
 return r(1019,[occ,signed(at),reasons,list(analysis.probabilities.map(p=>old(421,[p.key,qValue(p.probability)]))),u(mode),list(draws),chosen]);}
export function controlObserve(outcome:CanonicalValue,original:CanonicalValue,occ:CanonicalValue){const o=rec(original,818n),out=rec(outcome,1024n),visible=f(o,4n)===true,performed=visible&&f(out,3n)===true,informative=visible&&(performed||uint(f(o,2n))===3n),report=uint(f(o,5n)),reward=report===0n?f(out,4n):report===1n;return r(836,[occ,f(o,1n),f(o,6n),performed,...(informative?[reward]:[])]);}
export function appendControl(prior:CanonicalValue,observation:CanonicalValue){const o=rec(observation,836n),xs=items(f(rec(prior,820n),1n),'list');if(f(o,4n)!==true||!o.fields.has(5n))return {next:prior,applied:false};const entry=r(819,[f(o,1n),f(o,2n),f(o,3n),f(o,5n)]);if(xs.length>=16||xs.some(x=>key(f(rec(x,819n),1n))===key(f(o,1n))))throw Error('CONTROL_HISTORY_BOUND_OR_DUPLICATE');return {next:r(820,[list([...xs,entry])]),applied:true};}

