/** familiar-valence-public/0.1-candidate: authenticated ordinary planning and disjoint owners. */
import {canonicalEncode as enc,list,text,unsigned as u,signed,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {AuthoritativeState,applyStatePatch,restoreAuthoritativeState,statePathPatternValue,type ActualReadRecord,type StatePatch,type StructuralMutationDiff,type StatePath} from '../substrate/state';
import {DeterministicScheduler,SchedulerContractError,type EventHandlerContext,type EventEmission,type ScheduledEvent,type ConformanceInstrumentation} from '../substrate/scheduler';
import {createCanonicalSave,scheduledEventValue} from '../substrate/persistence';
import {traceRecordValue} from '../substrate/trace';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {createCognitiveRandomSession} from '../campaign2/cognitiveArbitration';
import {familiarValenceRecord as r,decodeFamiliarValence as decode} from './familiarValenceCodecs';
import {VERSION,STAGES,HOLDERS,TARGETS,ACTOR,index,sid,eventId,path,pattern,owner,reads,writes,type FamiliarValenceCompiled,compileFamiliarValenceInputs} from './familiarValenceModel';
import {appraise,probe,learn,emptyKnowledge} from './familiarValenceMath';
export function createFamiliarValenceRuntime(model:FamiliarValenceCompiled,input:Awaited<ReturnType<typeof compileFamiliarValenceInputs>>){
 const originals=new Map(input.events.map(e=>[e.eventId,key(scheduledEventValue(e))])),world=new Map(input.events.map(e=>[e.dueAt,rec(e.payload,1236n)])),random=createCognitiveRandomSession(input.runSeed);let active=false,expected=new Map<bigint,string>();const fail=(why:string):never=>{throw new SchedulerContractError('INPUT_NOT_ADMITTED',why);};
 const adapter={clone:(s:AuthoritativeState)=>new AuthoritativeState(s.entries()),validate:model.validateState,canonicalValue:(s:AuthoritativeState)=>s.canonicalValue(),restore:restoreAuthoritativeState,analyticalAnchors:()=>list([]),randomRelevantAuthoritativeIds:()=>list([])};
 async function handler({event,state,allocateRuntimeId}:EventHandlerContext<AuthoritativeState>){
  if(!active)fail('inactive familiarValence transaction');const stage=STAGES.find(([n])=>key(event.eventTypeId)===key(eventId(n)));if(!stage)fail('familiarValence stage');const [name,phase]=stage!;if(event.phase!==BigInt(phase))fail('familiarValence phase');const fingerprint=key(scheduledEventValue(event));if(['source'].includes(name)){if(originals.get(event.eventId)!==fingerprint)fail('familiarValence original');}else{if(expected.get(event.eventId)!==fingerprint)fail('familiarValence generated');expected.delete(event.eventId);}
  const occurrence=(ns=1179)=>typedIdentifier(ns,u(allocateRuntimeId())),paths=reads(name),domain=paths.map(pattern),actualReads:ActualReadRecord[]=[],pk=(p:StatePath)=>key(statePathPatternValue(pattern(p))),read=(p:StatePath)=>{if(!paths.some(x=>pk(x)===pk(p)))return fail('familiarValence read domain');const prior=state.read(p);actualReads.push({accessorId:sid(1028,'accessor/familiarValence/'+name),path:p,presence:prior.presence,value:prior.value,derivedSources:[]});return prior.value;};
  const outputs:CanonicalValue[]=[],emittedEvents:EventEmission[]=[];let nextState=state,patch:StatePatch={operations:[]},diffs:readonly StructuralMutationDiff[]=[],randomDrawRecords:CanonicalValue[]=[],quantizationOperations:CanonicalValue[]=[];
  const emit=(next:string,payload:CanonicalValue)=>emittedEvents.push({dueAt:event.dueAt,phase:BigInt(STAGES.find(([n])=>n===next)![1]),eventTypeId:eventId(next),payload,dependencies:list([])}),write=(changes:{path:StatePath;prior:CanonicalValue|undefined;next:CanonicalValue}[])=>{if(changes.some(c=>!writes(name).some(p=>pk(p)===pk(c.path))))fail('familiarValence write domain');patch={operations:changes.map(c=>({kind:'set' as const,path:c.path,expected:c.prior?{presence:true as const,value:c.prior}:{presence:false as const},newValue:c.next}))};const applied=applyStatePatch(state,patch,owner(name),model.authority);nextState=applied.state;diffs=applied.diffs;};
  let projection=event.payload;
  const source=world.get(event.dueAt)!;
  if(name==='source'){
   occurrence();emit('cue-a',list([]));emit('cue-b',list([]));emit('observe-a',list([]));emit('observe-b',list([]));
  }else if(name.startsWith('cue-')){
   const i=index(name),t=Number(uint(f(source,2n)))-1,access=f(source,BigInt(16+i))===true,a=list(access&&f(source,10n)===true?[f(source,8n)]:[]),b=list(access&&f(source,11n)===true?[f(source,9n)]:[]),out=r(1238,[occurrence(),HOLDERS[i],TARGETS[t],signed(event.dueAt),a,b]);projection=list([TARGETS[t],a,b]);outputs.push(out);emit(i===0?'appraise-a':'appraise-b',out);
  }else if(name.startsWith('appraise-')){
   const i=index(name),cue=rec(event.payload,1238n),t=TARGETS.findIndex(x=>key(x)===key(f(cue,3n))),history=read(path(i,t))??emptyKnowledge(),person=r(1240,[list([0,1].flatMap(j=>items(f(rec(read(path(i,j,true))??emptyKnowledge(true),1240n),1n),'list')).sort((a,b)=>Number((f(rec(a,1237n),4n) as {value:bigint}).value-(f(rec(b,1237n),4n) as {value:bigint}).value)))]);
   if(t<0)fail('unknown target');if(model.law===5)projection=list([cue,f(source,3n),f(source,4n),f(source,5n),f(source,6n)]);const out=appraise(occurrence(),event.dueAt,i,t,history,person,cue,model.law,model.law===5?source:undefined);outputs.push(out);emit(i===0?'probe-a':'probe-b',out);
  }else if(name.startsWith('probe-')){
   for(let k=0;k<1;k++)outputs.push(probe(model,occurrence(),event.payload,index(name),k));
  }else if(name.startsWith('observe-')){
   const i=index(name),t=Number(uint(f(source,2n)))-1,access=f(source,BigInt(14+i))===true,part=access&&f(source,BigInt(12+i))===true,a=list(access&&f(source,10n)===true?[f(source,8n)]:[]),b=list(access&&f(source,11n)===true?[f(source,9n)]:[]),benefit=list(access&&f(source,7n)===true?[f(source,5n)]:[]),harm=list(access&&f(source,7n)===true?[f(source,6n)]:[]);
   projection=list([TARGETS[t],part,a,b,benefit,harm]);const out=r(1237,[occurrence(),HOLDERS[i],TARGETS[t],signed(event.dueAt),part,a,b,benefit,harm]);outputs.push(out);emit(i===0?'history-a':'history-b',out);emit(i===0?'memory-a':'memory-b',out);
  }else if(name.startsWith('history-')||name.startsWith('memory-')){
   const i=index(name),person=name.startsWith('memory'),obs=rec(event.payload,1237n),t=TARGETS.findIndex(x=>key(x)===key(f(obs,3n)));if(t<0)fail('unknown target');const p=path(i,t,person),prior=read(p),before=prior??emptyKnowledge(person),next=learn(before,obs,i,t,person,model.law);if(key(before)!==key(next))write([{path:p,prior,next}]);outputs.push(r(1246,[occurrence(),HOLDERS[i],TARGETS[t],u(person?2:1),before,next]));
  }else fail('familiarValence unknown stage');
  outputs.forEach(v=>decode(enc(v)));return {nextState,outputs,emittedEvents,traceContributions:[],traceFactory:(children:readonly ScheduledEvent[])=>{if(children.length!==emittedEvents.length)fail('familiarValence child count');children.forEach((e,i)=>{if(e.causalParentEventIds.length!==1||e.causalParentEventIds[0]!==event.eventId||key(e.payload)!==key(emittedEvents[i].payload))fail('familiarValence child association');expected.set(e.eventId,key(scheduledEventValue(e)));});return [traceRecordValue({traceSchemaVersion:'trace/0.2-candidate',modelIdentity:model.modelIdentity.value,runIdentity:input.runIdentity.value,event,seamId:sid(1036,'seam/familiarValence/'+name),seamVersion:VERSION,recordKind:event.eventTypeId,subjectIds:[ACTOR],sourceRecordIds:[],registeredReadDomain:domain,actualReadRecords:actualReads,inputProjection:projection,outputProjection:list(outputs),randomDrawRecords,quantizationOperations,statePatch:patch,structuralMutationDiffs:diffs,emittedEvents:children,invariantResults:[]})];}};
 }
 const scheduler=new DeterministicScheduler({initialState:new AuthoritativeState([]),stateAdapter:adapter,handlers:new Map(STAGES.map(([n])=>[key(eventId(n)),handler])),initialQueue:input.events,initialAllocators:{nextRuntimeId:0n,nextEventId:BigInt(input.events.length),nextEventSequence:BigInt(input.events.length)},maxSettlementWorkPerSimulationInstant:32n,invariants:[state=>{if(expected.size)fail('familiarValence pending children');model.validateState(state);random.prepareCommit();}]});
 async function settle(instrumentation?:ConformanceInstrumentation){if(active)fail('familiarValence concurrent settlement');if(!scheduler.getPendingQueue().length)return undefined;active=true;expected=new Map();random.begin();try{const result=instrumentation?await scheduler.settleNextInstantForConformance(instrumentation):await scheduler.settleNextInstant();if(result)random.commit();return result;}finally{active=false;expected.clear();random.close();}}
 return {settle:()=>settle(),settleForConformance:(i:ConformanceInstrumentation)=>settle(i),snapshot:()=>({state:scheduler.getState(),clock:scheduler.getClock(),status:scheduler.status,queue:scheduler.getPendingQueue(),allocators:scheduler.getAllocatorState(),trace:scheduler.getCommittedTrace(),outputs:scheduler.getOutputs(),randomAddresses:random.committedAddressKeys()}),save:()=>createCanonicalSave({scheduler,stateAdapter:adapter,modelIdentity:model.modelIdentity,runIdentity:input.runIdentity,continuingRunInputs:list(random.committedAddressKeys().map(text))}),diagnostic:()=>scheduler.failureDiagnostic};
}
