/** habit-public/0.1-candidate transactional execution and consequence learning. */
import {canonicalEncode as enc,list,unsigned as u,signed,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {AuthoritativeState,applyStatePatch,restoreAuthoritativeState,type ActualReadRecord,type StatePatch,type StructuralMutationDiff,type StatePath} from '../substrate/state';
import {DeterministicScheduler,SchedulerContractError,type EventHandlerContext,type EventEmission,type ScheduledEvent,type ConformanceInstrumentation} from '../substrate/scheduler';
import {createCanonicalSave,scheduledEventValue} from '../substrate/persistence';
import {traceRecordValue} from '../substrate/trace';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataIdentity as id} from '../campaign2/canonicalData';
import {ONE,ZERO,qValue,choiceAlignment} from '../campaign2/cognitiveMath';
import {habitRecord as r,decodeHabit as decode} from './habitCodecs';
import {HABIT_VERSION,STAGES,OBSERVER,CHARACTER,OPTIONS,sid,eventId,historyPath,beliefPath,cachePath,stageReads,stageWrites,owner,pattern,type HabitCompiled,compileHabitInputs} from './habitModel';
import {habitSummary,habitOptions,habitRaw,habitReasons,habitDecision,habitObserve,appendHabit} from './habitMath';
export function createHabitRuntime(model:HabitCompiled,input:Awaited<ReturnType<typeof compileHabitInputs>>){
 const originals=new Map(input.events.map(e=>[e.eventId,key(scheduledEventValue(e))])),physical=new Map(input.events.map(e=>[e.dueAt,e.payload]));let active=false,expected=new Map<bigint,string>();
 const fail=(message:string):never=>{throw new SchedulerContractError('INPUT_NOT_ADMITTED',message);};
 // Cross-leaf cache equality is a committed-instant invariant, not an intermediate patch invariant.
 const adapter={clone:(s:AuthoritativeState)=>new AuthoritativeState(s.entries()),validate:(s:AuthoritativeState)=>{decode(enc(s.canonicalValue()));},canonicalValue:(s:AuthoritativeState)=>s.canonicalValue(),restore:restoreAuthoritativeState,analyticalAnchors:()=>list([]),randomRelevantAuthoritativeIds:()=>list([])};
 async function handler({event,state,allocateRuntimeId}:EventHandlerContext<AuthoritativeState>){
  if(!active)fail('inactive habit transaction');const index=STAGES.findIndex(([n])=>key(event.eventTypeId)===key(eventId(n)));if(index<0)fail('unknown habit stage');const [name,phase]=STAGES[index];if(event.phase!==BigInt(phase))fail('habit phase');const fingerprint=key(scheduledEventValue(event));if(name==='appraise'){if(originals.get(event.eventId)!==fingerprint)fail('habit original association');}else{if(expected.get(event.eventId)!==fingerprint)fail('habit generated association');expected.delete(event.eventId);}
  const occurrence=()=>typedIdentifier(1155,u(allocateRuntimeId())),reads:ActualReadRecord[]=[],paths=stageReads(name,model.settings),domain=paths.map(pattern),pk=(p:StatePath)=>key(list([u(p.rootStateTypeId),u(p.fieldId),...p.selectors.map(s=>s.kind==='mapKey'?s.key:false)]));
  const read=(p:StatePath)=>{if(!paths.some(v=>pk(v)===pk(p)))return fail('habit unregistered read');const prior=state.read(p);reads.push({accessorId:sid(1028,'accessor/habit/'+name),path:p,presence:prior.presence,value:prior.value,derivedSources:[]});return prior.value;};
  const outputs:CanonicalValue[]=[],emittedEvents:EventEmission[]=[];let nextState=state,patch:StatePatch={operations:[]},diffs:readonly StructuralMutationDiff[]=[],randomDrawRecords:CanonicalValue[]=[];
  const write=(p:StatePath,prior:CanonicalValue|undefined,value:CanonicalValue)=>{if(!stageWrites(name,model.settings).some(x=>pk(x)===pk(p)))fail('habit unregistered write');patch={operations:[{kind:'set',path:p,expected:prior?{presence:true,value:prior}:{presence:false},newValue:value}]};const result=applyStatePatch(state,patch,owner(name),model.authority);nextState=result.state;diffs=result.diffs;};
  const emit=(next:string,payload:CanonicalValue)=>emittedEvents.push({dueAt:event.dueAt,phase:BigInt(STAGES.find(([n])=>n===next)![1]),eventTypeId:eventId(next),payload,dependencies:list([])});
  let output:CanonicalValue;
  if(name==='appraise'){const src=rec(event.payload,818n),belief=read(beliefPath),summary=model.settings.candidate===1?habitSummary(model.settings,read(historyPath)!):model.settings.candidate===2?read(cachePath):undefined,fields=new Map<bigint,CanonicalValue>([[1n,occurrence()],[2n,f(src,1n)],[3n,f(src,6n)],[4n,f(src,2n)],[5n,summary?f(rec(summary,824n),f(src,6n)===true?2n:1n):qValue(ZERO)]]);if(belief)fields.set(6n,belief);if(model.settings.candidate===4)fields.set(7n,f(src,3n));output=r(826,fields);}
  else if(name==='options')output=habitOptions(model.settings,event.payload,occurrence());
  else if(name==='raw')output=habitRaw(event.payload,occurrence());
  else if(name==='reasons')output=habitReasons(model,event.payload,occurrence());
  else if(name==='decision'){output=await habitDecision(event.payload,event.dueAt,occurrence(),input.runSeed);randomDrawRecords=[...items(f(rec(output,830n),6n),'list')];}
  else if(name==='intent')output=r(831,[occurrence(),event.payload]);
  else if(name==='expression'){const chosen=f(rec(f(rec(event.payload,831n),2n),830n),7n);output=r(832,[occurrence(),event.payload,list(OPTIONS.map(o=>qValue(choiceAlignment(chosen,new Map(OPTIONS.map(x=>[key(x),key(x)===key(o)?ONE:ZERO]))))))]);}
  else if(name==='plan'){const decision=rec(f(rec(f(rec(event.payload,832n),2n),831n),2n),830n);output=r(833,[occurrence(),event.payload,f(rec(f(decision,7n),395n),2n)]);}
  else if(name==='attempt')output=r(834,[occurrence(),event.payload]);
  else if(name==='execute'){const plan=rec(f(rec(event.payload,834n),2n),833n),src=rec(physical.get(event.dueAt)!,818n),performed=key(f(plan,3n))===key(f(rec(OPTIONS[0],395n),2n));output=r(835,[occurrence(),event.payload,performed,f(src,3n)]);}
  else if(name==='observe'){output=habitObserve(event.payload,physical.get(event.dueAt)!,occurrence());for(const n of ['history','belief','cache'])emit(n,output);}
  else if(name==='history'){const prior=read(historyPath)!,result=appendHabit(prior,event.payload);output=r(837,[occurrence(),event.payload,result.applied,prior,result.next]);if(result.applied)write(historyPath,prior,result.next);}
  else if(name==='belief'){const prior=read(beliefPath),obs=rec(event.payload,836n),value=obs.fields.get(5n),next=value===undefined?prior:r(822,[value,f(obs,1n)]),fields=new Map<bigint,CanonicalValue>([[1n,occurrence()],[2n,event.payload],[3n,value!==undefined]]);if(prior)fields.set(4n,prior);if(next)fields.set(5n,next);output=r(838,fields);if(value!==undefined)write(beliefPath,prior,next!);}
  else {if(model.settings.candidate===2){const journal=read(historyPath)!,prior=read(cachePath)!,next=habitSummary(model.settings,journal);output=r(839,[occurrence(),prior,next]);if(key(prior)!==key(next))write(cachePath,prior,next);}else output=r(839,[occurrence()]);}
  decode(enc(output!));outputs.push(output!);if(index<10)emit(STAGES[index+1][0],output!);
  const safeInput=name==='appraise'?list([f(rec(event.payload,818n),1n),f(rec(event.payload,818n),2n),f(rec(event.payload,818n),6n),...(model.settings.candidate===4?[f(rec(event.payload,818n),3n)]:[])]):event.payload;
  return {nextState,outputs,emittedEvents,traceContributions:[],traceFactory:(children:readonly ScheduledEvent[])=>{if(children.length!==emittedEvents.length)fail('habit child count');children.forEach((e,i)=>{if(e.causalParentEventIds.length!==1||e.causalParentEventIds[0]!==event.eventId||key(e.payload)!==key(emittedEvents[i].payload))fail('habit child binding');expected.set(e.eventId,key(scheduledEventValue(e)));});const sourceRecordIds:ReturnType<typeof id>[]=[];if(name!=='appraise'&&typeof event.payload!=='boolean'&&event.payload.kind==='record')sourceRecordIds.push(id(f(event.payload,1n)));const trace=traceRecordValue({traceSchemaVersion:'trace/0.2-candidate',modelIdentity:model.modelIdentity.value,runIdentity:input.runIdentity.value,event,seamId:sid(1036,'seam/habit/'+name),seamVersion:HABIT_VERSION,recordKind:event.eventTypeId,subjectIds:[OBSERVER,CHARACTER],sourceRecordIds,registeredReadDomain:domain,actualReadRecords:reads,inputProjection:safeInput,outputProjection:list(outputs),randomDrawRecords,quantizationOperations:[],statePatch:patch,structuralMutationDiffs:diffs,emittedEvents:children,invariantResults:[]});decode(enc(trace));return [trace];}};
 }
 const scheduler=new DeterministicScheduler({initialState:model.initial,stateAdapter:adapter,handlers:new Map(STAGES.map(([n])=>[key(eventId(n)),handler])),initialQueue:input.events,initialAllocators:{nextRuntimeId:0n,nextEventId:BigInt(input.events.length),nextEventSequence:BigInt(input.events.length)},maxSettlementWorkPerSimulationInstant:14n,invariants:[state=>{if(expected.size)fail('unconsumed habit children');model.validateState(state);}]});
 async function settle(instrumentation?:ConformanceInstrumentation){if(active)fail('habit concurrent settlement');active=true;expected=new Map();try{return instrumentation?await scheduler.settleNextInstantForConformance(instrumentation):await scheduler.settleNextInstant();}finally{active=false;expected.clear();}}
 return {settle:()=>settle(),settleForConformance:(i:ConformanceInstrumentation)=>settle(i),snapshot:()=>({state:scheduler.getState(),clock:scheduler.getClock(),status:scheduler.status,queue:scheduler.getPendingQueue(),allocators:scheduler.getAllocatorState(),trace:scheduler.getCommittedTrace(),outputs:scheduler.getOutputs()}),save:()=>createCanonicalSave({scheduler,stateAdapter:adapter,modelIdentity:model.modelIdentity,runIdentity:input.runIdentity,continuingRunInputs:list([])}),diagnostic:()=>scheduler.failureDiagnostic};
}

