/** habit-public/0.1-candidate; availability-mediated history with separate belief. */
import {canonicalEncode as enc,list,text,unsigned as u,rational as q,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {commitManifest,createModelIdentity,createRunIdentity} from '../substrate/identity';
import {AuthoritativeState,StateAuthorityRegistry,statePathPatternValue,type StatePath} from '../substrate/state';
import {compileMutationAuthorityRegistry} from '../substrate/mutationAuthority';
import {simInstant} from '../substrate/time';
import {RANDOM_ALGORITHM_VERSION} from '../substrate/random';
import type {ScheduledEvent} from '../substrate/scheduler';
import {semanticReferentFromAuthoredContent} from '../substrate/referentOrigin';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {receivingRecord as old} from './receivingCodecs';
import {copyData} from './beliefModel';
import {multisourceBase} from './multisourceModelRecipe';
import {decodeHabit as decode,habitRecord as r} from './habitCodecs';
import {habitSummary} from './habitMath';
export {copyData};
export const HABIT_VERSION='habit-public/0.1-candidate',sid=(ns:number,name:string)=>typedIdentifier(ns,text(name));
export const OBSERVER=sid(1000,'observer/habit'),CHARACTER=semanticReferentFromAuthoredContent(sid(1038,'content/habit/character'));
export const TASK=old(371,[CHARACTER,semanticReferentFromAuthoredContent(sid(1038,'content/habit/exercise'))]),OPTIONS=['exercise','idle'].map(n=>old(395,[CHARACTER,sid(1027,'action/habit/'+n)]));
export const STAGES=[['appraise',40],['options',50],['raw',51],['reasons',52],['decision',60],['intent',70],['expression',80],['plan',90],['attempt',100],['execute',110],['observe',120],['history',140],['belief',140],['cache',140]] as const;
export const eventId=(n:string)=>sid(1001,'event/habit/'+n);
export const historyPath:StatePath={rootStateTypeId:821n,fieldId:1n,selectors:[{kind:'mapKey',key:CHARACTER}]},beliefPath:StatePath={...historyPath,rootStateTypeId:823n},cachePath:StatePath={...historyPath,rootStateTypeId:825n};
export const pattern=(p:StatePath)=>({...p,selectors:p.selectors.map(selector=>({kind:'exact' as const,selector}))});
export interface HabitSettings {candidate:number;law:number;}
export const DEFAULT_SETTINGS:HabitSettings={candidate:1,law:1};
export const stageReads=(n:string,s:HabitSettings)=>n==='appraise'?[beliefPath,...(s.candidate===1?[historyPath]:s.candidate===2?[cachePath]:[])]:n==='history'?[historyPath]:n==='belief'?[beliefPath]:n==='cache'&&s.candidate===2?[historyPath,cachePath]:[];
export const stageWrites=(n:string,s:HabitSettings)=>n==='history'?[historyPath]:n==='belief'?[beliefPath]:n==='cache'&&s.candidate===2?[cachePath]:[];
export const owner=(n:string)=>sid(1025,n==='history'?'authority/habit-history':n==='cache'?'authority/habit-summary':'authority/reward-expectation');
const ownership=(s:HabitSettings)=>compileMutationAuthorityRegistry([['authority/habit-history',historyPath,820n],['authority/reward-expectation',beliefPath,822n],...(s.candidate===2?[['authority/habit-summary',cachePath,824n]]:[])].map(([authorityName,path,type])=>({authorityName:authorityName as string,ownedLeaves:[{pattern:pattern(path as StatePath),valueGrammar:{kind:'canonical-record' as const,recordTypeId:type as bigint},removalAllowed:false}]})));
export function habitRecipe(settings:Partial<HabitSettings>={}){const s={...DEFAULT_SETTINGS,...settings};if(![1,2,3,4].includes(s.candidate)||![1,2,3].includes(s.law))throw Error('HABIT_PROFILE');const parameters=r(817,[text(HABIT_VERSION),u(s.candidate),u(s.law)]),content=r(840,[OBSERVER,CHARACTER,TASK,list(OPTIONS),multisourceBase().get('task-reason-dice'),q(1,1),q(0,1),q(0,1)]),stages=STAGES.map(([n,phase])=>r(841,[eventId(n),u(phase),list(stageReads(n,s).map(p=>statePathPatternValue(pattern(p)))),list(stageWrites(n,s).map(p=>statePathPatternValue(pattern(p)))),owner(n)]));return {parameters:enc(parameters),content:enc(content),registry:enc(list([ownership(s).definitionValue,list(stages)]))};}
export type HabitSource=ReturnType<typeof habitRecipe>;
export async function compileHabitModel(input:HabitSource){const source=copyData(input,['parameters','content','registry']),profile=rec(decode(source.parameters),817n),settings={candidate:Number(uint(f(profile,2n))),law:Number(uint(f(profile,3n)))},recipe=habitRecipe(settings);for(const n of ['parameters','content','registry'] as const)if(key(decode(recipe[n]))!==key(decode(source[n])))throw Error('HABIT_EXACT_MODEL');const own=ownership(settings),authority=new StateAuthorityRegistry(own.writableLeaves,own.authorities),content=rec(decode(source.content),840n),modelIdentity=await createModelIdentity({rulesVersion:HABIT_VERSION,contentSchemaVersion:HABIT_VERSION,contentManifest:await commitManifest(content),parameterSchemaVersion:HABIT_VERSION,parameterSet:await commitManifest(profile),numericProfileVersion:'habit-exact-rational/0.1-candidate',randomAlgorithmVersion:RANDOM_ALGORITHM_VERSION,registrySchemaVersion:HABIT_VERSION,registryManifest:await commitManifest(decode(source.registry))}),empty=r(820,[list([])]),initial=new AuthoritativeState([{path:historyPath,value:empty},...(settings.candidate===2?[{path:cachePath,value:habitSummary(settings,empty)}]:[])]);
 function validateState(state:AuthoritativeState){decode(enc(state.canonicalValue()));const pk=(p:StatePath)=>key(statePathPatternValue(pattern(p))),allowed=new Set([historyPath,beliefPath,...(settings.candidate===2?[cachePath]:[])].map(pk));for(const e of state.entries())if(!allowed.has(pk(e.path)))throw Error('HABIT_STATE_PATH');const journal=state.read(historyPath).value;if(!journal)throw Error('HABIT_JOURNAL_MISSING');let at=0n;const seen=new Set<string>();for(const v of items(f(rec(journal,820n),1n),'list')){const e=rec(v,819n),t=f(e,2n);if(typeof t==='boolean'||t.kind!=='signed'||t.value<=at||seen.has(key(f(e,1n))))throw Error('HABIT_HISTORY_ORDER');at=t.value;seen.add(key(f(e,1n)));}if(settings.candidate===2&&key(state.read(cachePath).value!)!==key(habitSummary(settings,journal)))throw Error('HABIT_CACHE_FOLD');}
 return {source,profile,settings,content,modelIdentity,authority,initial,validateState};}
export type HabitCompiled=Awaited<ReturnType<typeof compileHabitModel>>;
export async function compileHabitInputs(model:HabitCompiled,initialState:Uint8Array,orderedInputs:Uint8Array,runSeed:Uint8Array){if(key(decode(initialState))!==key(model.initial.canonicalValue()))throw Error('HABIT_INITIAL_STATE');const originals=items(decode(orderedInputs),'list');if(originals.length>16)throw Error('HABIT_INPUT_LIMIT');let previous=0n;const events:ScheduledEvent[]=originals.map((v,i)=>{const o=rec(v,818n),t=f(o,1n);if(typeof t==='boolean'||t.kind!=='signed'||t.value<=previous||t.value>32n)throw Error('HABIT_INPUT_TIME');previous=t.value;return {eventId:BigInt(i),eventSequence:BigInt(i),dueAt:simInstant(t.value),phase:40n,eventTypeId:eventId('appraise'),payload:v,dependencies:list([]),causalParentEventIds:[]};});const runIdentity=await createRunIdentity({modelIdentity:model.modelIdentity,initialState:await commitManifest(decode(initialState)),orderedInputSequence:await commitManifest(decode(orderedInputs)),runSeed});return {events,runIdentity,runSeed:runSeed.slice()};}
