/** hearsay-public/0.1-candidate: authenticated ordinary planning and disjoint owners. */
import {canonicalEncode as enc,list,text,unsigned as u,signed,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {AuthoritativeState,applyStatePatch,restoreAuthoritativeState,statePathPatternValue,type ActualReadRecord,type StatePatch,type StructuralMutationDiff,type StatePath} from '../substrate/state';
import {DeterministicScheduler,SchedulerContractError,type EventHandlerContext,type EventEmission,type ScheduledEvent,type ConformanceInstrumentation} from '../substrate/scheduler';
import {createCanonicalSave,scheduledEventValue} from '../substrate/persistence';
import {traceRecordValue} from '../substrate/trace';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key} from '../campaign2/canonicalData';
import {createCognitiveRandomSession} from '../campaign2/cognitiveArbitration';
import {hearsayRecord as r,decodeHearsay as decode} from './hearsayCodecs';
import {VERSION,STAGES,HOLDERS,TARGET,INCIDENT,ACTOR,index,sid,eventId,path,pattern,owner,reads,writes,type HearsayCompiled,compileHearsayInputs} from './hearsayModel';
import {judgment,speakerBelief,appraise,learn,emptyKnowledge} from './hearsayMath';
export function createHearsayRuntime(model:HearsayCompiled,input:Awaited<ReturnType<typeof compileHearsayInputs>>){
 const originals=new Map(input.events.map(e=>[e.eventId,key(scheduledEventValue(e))])),world=new Map(input.events.map(e=>[e.dueAt,rec(e.payload,1196n)])),random=createCognitiveRandomSession(input.runSeed);let active=false,expected=new Map<bigint,string>();const fail=(why:string):never=>{throw new SchedulerContractError('INPUT_NOT_ADMITTED',why);};
 const adapter={clone:(s:AuthoritativeState)=>new AuthoritativeState(s.entries()),validate:model.validateState,canonicalValue:(s:AuthoritativeState)=>s.canonicalValue(),restore:restoreAuthoritativeState,analyticalAnchors:()=>list([]),randomRelevantAuthoritativeIds:()=>list([])};
 async function handler({event,state,allocateRuntimeId}:EventHandlerContext<AuthoritativeState>){
  if(!active)fail('inactive hearsay transaction');const stage=STAGES.find(([n])=>key(event.eventTypeId)===key(eventId(n)));if(!stage)fail('hearsay stage');const [name,phase]=stage!;if(event.phase!==BigInt(phase))fail('hearsay phase');const fingerprint=key(scheduledEventValue(event));if(['source'].includes(name)){if(originals.get(event.eventId)!==fingerprint)fail('hearsay original');}else{if(expected.get(event.eventId)!==fingerprint)fail('hearsay generated');expected.delete(event.eventId);}
  const occurrence=(ns=1176)=>typedIdentifier(ns,u(allocateRuntimeId())),paths=reads(name),domain=paths.map(pattern),actualReads:ActualReadRecord[]=[],pk=(p:StatePath)=>key(statePathPatternValue(pattern(p))),read=(p:StatePath)=>{if(!paths.some(x=>pk(x)===pk(p)))return fail('hearsay read domain');const prior=state.read(p);actualReads.push({accessorId:sid(1028,'accessor/hearsay/'+name),path:p,presence:prior.presence,value:prior.value,derivedSources:[]});return prior.value;};
  const outputs:CanonicalValue[]=[],emittedEvents:EventEmission[]=[];let nextState=state,patch:StatePatch={operations:[]},diffs:readonly StructuralMutationDiff[]=[],randomDrawRecords:CanonicalValue[]=[],quantizationOperations:CanonicalValue[]=[];
  const emit=(next:string,payload:CanonicalValue)=>emittedEvents.push({dueAt:event.dueAt,phase:BigInt(STAGES.find(([n])=>n===next)![1]),eventTypeId:eventId(next),payload,dependencies:list([])}),write=(changes:{path:StatePath;prior:CanonicalValue|undefined;next:CanonicalValue}[])=>{if(changes.some(c=>!writes(name).some(p=>pk(p)===pk(c.path))))fail('hearsay write domain');patch={operations:changes.map(c=>({kind:'set' as const,path:c.path,expected:c.prior?{presence:true as const,value:c.prior}:{presence:false as const},newValue:c.next}))};const applied=applyStatePatch(state,patch,owner(name),model.authority);nextState=applied.state;diffs=applied.diffs;};
  let projection=event.payload;
  if(name==='source'){
   occurrence();emit('private',list([]));emit('infer-a',list([]));emit('infer-b',list([]));
  }else if(name==='private'){
   const source=world.get(event.dueAt)!,value=list(f(source,5n)===true?[f(source,4n)]:[]),obs=r(1197,[occurrence(),HOLDERS[0],signed(event.dueAt),value]);projection=value;outputs.push(obs);emit('learn-private',obs);
  }else if(name.startsWith('infer-')){
   const i=index(name),knowledge=read(path(i))??emptyKnowledge(),truth=model.law===4?f(world.get(event.dueAt)!,2n)===true:undefined;if(truth!==undefined)projection=list([truth]);const out=judgment(occurrence(),event.dueAt,i,knowledge,model.law,truth);outputs.push(out);emit(i===1?'appraise-a':'appraise-b',out);
  }else if(name.startsWith('appraise-')){
   outputs.push(appraise(occurrence(),event.payload,model.goal));
  }else if(name==='report'){
   const knowledge=read(path(0))??emptyKnowledge(),source=world.get(event.dueAt)!,enabled=f(source,6n)===true,ticket=f(source,7n),assertion=enabled?speakerBelief(knowledge):list([]);projection=list([enabled,ticket]);const out=r(1198,[occurrence(),signed(event.dueAt),HOLDERS[0],ticket,assertion]);outputs.push(out);emit('observe-a',out);
  }else if(name==='observe-a'||name==='observe-b'){
   const i=index(name),source=world.get(event.dueAt)!,pair=i===2?items(event.payload,'list'):undefined,report=rec(pair?pair[0]:event.payload,1198n),direct=list(f(source,BigInt(9+i))===true?[f(source,3n)]:[]),heard=f(source,BigInt(7+i))===true?f(report,5n):list([]);
   projection=list([direct,heard,f(report,3n),f(report,4n)]);const d=r(1199,[occurrence(),HOLDERS[i],signed(event.dueAt),TARGET,INCIDENT,u(1),TARGET,u(0),direct]),h=r(1199,[occurrence(),HOLDERS[i],signed(event.dueAt),TARGET,INCIDENT,u(2),HOLDERS[0],f(report,4n),heard]);outputs.push(d,h);
   if(i===1)emit('observe-b',list([report,list([d,h])]));else{emit('learn-a',pair![1]);emit('learn-b',list([d,h]));}
  }else if(name.startsWith('learn-')){
   const i=index(name),prior=read(path(i)),before=prior??emptyKnowledge(),observations=i===0?[event.payload]:items(event.payload,'list'),next=observations.reduce((p,o)=>learn(p,o,i,model.law),before);if(key(before)!==key(next))write([{path:path(i),prior,next}]);outputs.push(r(1204,[occurrence(),HOLDERS[i],before,next]));if(i===0)emit('report',list([]));
  }else fail('hearsay unknown stage');
  outputs.forEach(v=>decode(enc(v)));return {nextState,outputs,emittedEvents,traceContributions:[],traceFactory:(children:readonly ScheduledEvent[])=>{if(children.length!==emittedEvents.length)fail('hearsay child count');children.forEach((e,i)=>{if(e.causalParentEventIds.length!==1||e.causalParentEventIds[0]!==event.eventId||key(e.payload)!==key(emittedEvents[i].payload))fail('hearsay child association');expected.set(e.eventId,key(scheduledEventValue(e)));});return [traceRecordValue({traceSchemaVersion:'trace/0.2-candidate',modelIdentity:model.modelIdentity.value,runIdentity:input.runIdentity.value,event,seamId:sid(1036,'seam/hearsay/'+name),seamVersion:VERSION,recordKind:event.eventTypeId,subjectIds:[ACTOR],sourceRecordIds:[],registeredReadDomain:domain,actualReadRecords:actualReads,inputProjection:projection,outputProjection:list(outputs),randomDrawRecords,quantizationOperations,statePatch:patch,structuralMutationDiffs:diffs,emittedEvents:children,invariantResults:[]})];}};
 }
 const scheduler=new DeterministicScheduler({initialState:new AuthoritativeState([]),stateAdapter:adapter,handlers:new Map(STAGES.map(([n])=>[key(eventId(n)),handler])),initialQueue:input.events,initialAllocators:{nextRuntimeId:0n,nextEventId:BigInt(input.events.length),nextEventSequence:BigInt(input.events.length)},maxSettlementWorkPerSimulationInstant:32n,invariants:[state=>{if(expected.size)fail('hearsay pending children');model.validateState(state);random.prepareCommit();}]});
 async function settle(instrumentation?:ConformanceInstrumentation){if(active)fail('hearsay concurrent settlement');if(!scheduler.getPendingQueue().length)return undefined;active=true;expected=new Map();random.begin();try{const result=instrumentation?await scheduler.settleNextInstantForConformance(instrumentation):await scheduler.settleNextInstant();if(result)random.commit();return result;}finally{active=false;expected.clear();random.close();}}
 return {settle:()=>settle(),settleForConformance:(i:ConformanceInstrumentation)=>settle(i),snapshot:()=>({state:scheduler.getState(),clock:scheduler.getClock(),status:scheduler.status,queue:scheduler.getPendingQueue(),allocators:scheduler.getAllocatorState(),trace:scheduler.getCommittedTrace(),outputs:scheduler.getOutputs(),randomAddresses:random.committedAddressKeys()}),save:()=>createCanonicalSave({scheduler,stateAdapter:adapter,modelIdentity:model.modelIdentity,runIdentity:input.runIdentity,continuingRunInputs:list(random.committedAddressKeys().map(text))}),diagnostic:()=>scheduler.failureDiagnostic};
}
