/** Trusted scheduler adapter; character transformations receive restricted operands. */
import {canonicalEncode as enc,list,set,unsigned as u,signed,rational as q,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {AuthoritativeState,applyStatePatch,restoreAuthoritativeState,type ActualReadRecord,type StatePatch,type StructuralMutationDiff,type StatePath} from '../substrate/state';
import {DeterministicScheduler,SchedulerContractError,type EventHandlerContext,type EventEmission,type ScheduledEvent,type ConformanceInstrumentation} from '../substrate/scheduler';
import {createCanonicalSave,scheduledEventValue} from '../substrate/persistence';
import {traceRecordValue} from '../substrate/trace';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {ONE,readQ,qValue,compileReasonNuclei,appendIdentityContribution} from '../campaign2/cognitiveMath';
import {rawSignalOutput} from '../campaign2/cognitiveTransforms';
import {arbitrationOutput,createCognitiveRandomSession} from '../campaign2/cognitiveArbitration';
import {intentOutput,expressionOutput,qualificationOutput,chosenData} from '../campaign2/cognitiveChoice';
import {receivingRecord as old} from './receivingCodecs';
import {longitudinalRecord as r,decodeLongitudinal as decode} from './longitudinalCodecs';
import {LONGITUDINAL_VERSION,STAGES,OBSERVER,ACTOR,OPTIONS,sid,eventId,path,familyPath,stageReads,stageWrites,owner,pattern,enabled,type LongitudinalCompiled,compileLongitudinalInputs} from './longitudinalModel';
import {biographyContext,familyValue,identityStrength,evolveSkill,evolveRelationship,episode} from './longitudinalMath';
export function createLongitudinalRuntime(model:LongitudinalCompiled,input:Awaited<ReturnType<typeof compileLongitudinalInputs>>){
 const originals=new Map(input.events.map(e=>[e.eventId,key(scheduledEventValue(e))])),physical=new Map(input.events.map(e=>[e.dueAt,rec(e.payload,864n)])),s=model.settings,random=createCognitiveRandomSession(input.runSeed);let active=false,expected=new Map<bigint,string>(),priorClock=0n;
 const fail=(message:string):never=>{throw new SchedulerContractError('INPUT_NOT_ADMITTED',message);};
 const adapter={clone:(state:AuthoritativeState)=>new AuthoritativeState(state.entries()),validate:model.validateState,canonicalValue:(state:AuthoritativeState)=>state.canonicalValue(),restore:restoreAuthoritativeState,analyticalAnchors:()=>list([]),randomRelevantAuthoritativeIds:()=>list([])};
 async function handler({event,state,allocateRuntimeId}:EventHandlerContext<AuthoritativeState>){
  if(!active)fail('inactive longitudinal transaction');const stage=STAGES.find(([n])=>key(event.eventTypeId)===key(eventId(n)));if(!stage)fail('unknown longitudinal stage');const [name,phase]=stage!;if(event.phase!==BigInt(phase))fail('longitudinal phase');const fingerprint=key(scheduledEventValue(event));if(['probe','bio-context','practice-intent'].includes(name)){if(originals.get(event.eventId)!==fingerprint)fail('longitudinal original association');}else{if(expected.get(event.eventId)!==fingerprint)fail('longitudinal generated association');expected.delete(event.eventId);}
  const occurrence=(ns=1157)=>typedIdentifier(ns,u(allocateRuntimeId())),reads:ActualReadRecord[]=[],paths=stageReads(name,s),domain=paths.map(pattern),pk=(p:StatePath)=>key(list([u(p.rootStateTypeId),u(p.fieldId),...p.selectors.map(v=>v.kind==='mapKey'?v.key:false)]));
  const read=(p:StatePath)=>{if(!paths.some(v=>pk(v)===pk(p)))return fail('longitudinal unregistered read');const prior=state.read(p);reads.push({accessorId:sid(1028,'accessor/longitudinal/'+name),path:p,presence:prior.presence,value:prior.value,derivedSources:[]});return prior.value;};
  const outputs:CanonicalValue[]=[],emittedEvents:EventEmission[]=[];let nextState=state,patch:StatePatch={operations:[]},diffs:readonly StructuralMutationDiff[]=[],randomDrawRecords:CanonicalValue[]=[],quantizationOperations:CanonicalValue[]=[];
  const write=(p:StatePath,prior:CanonicalValue|undefined,next:CanonicalValue)=>{if(!stageWrites(name,s).some(v=>pk(v)===pk(p)))fail('longitudinal unregistered write');patch={operations:[{kind:'set',path:p,expected:prior?{presence:true,value:prior}:{presence:false},newValue:next}]};const result=applyStatePatch(state,patch,owner(name,s),model.authority);nextState=result.state;diffs=result.diffs;};
  const update=(p:StatePath,prior:CanonicalValue,next:CanonicalValue)=>{const changed=key(prior)!==key(next);if(changed)write(p,prior,next);return r(880,[occurrence(),owner(name,s),prior,next,changed]);};
  const wrap=(family:number,v:CanonicalValue)=>s.representation===4?r(874,[u(family),list([v])]):v;
  const emit=(next:string,payload:CanonicalValue)=>emittedEvents.push({dueAt:event.dueAt,phase:BigInt(STAGES.find(([n])=>n===next)![1]),eventTypeId:eventId(next),payload,dependencies:list([])});
  let output:CanonicalValue;
  if(name==='probe'){const cache=new Map(paths.map(p=>[pk(p),read(p)])),value=(family:number)=>familyValue(s,family,cache.get(pk(familyPath(s,family)))!),identity=value(1),skill=value(2),relationship=rec(value(3),851n),person=cache.get(pk(path(870)));output=r(876,[occurrence(),signed(event.dueAt),qValue(identityStrength(identity)),skill,relationship,uint(f(relationship,1n))>=2n&&f(relationship,2n)!==true,f(relationship,2n),...(person?[person]:[])]);}
  else if(name==='bio-context'){output=biographyContext(event.dueAt,occurrence);emit('bio-raw',output);}
  else if(name==='bio-raw'){const history=familyValue(s,1,read(familyPath(s,1))!),result=rawSignalOutput(occurrence(1133),event.payload,s.standing,ONE,()=>history);output=result.output;if(s.revision===2&&s.standing){const raw=rec(output,403n),signals=items(f(raw,3n),'set').map(v=>{const signal=rec(v,402n),source=rec(f(signal,1n),401n);return uint(f(source,3n))===3n&&key(f(source,1n))===key(OPTIONS[1])?old(402,[source,qValue(readQ(f(signal,2n)).multiply(readQ(q(-1,1)))),f(signal,3n)]):v;});output=old(403,[f(raw,1n),f(raw,2n),set(signals),f(raw,4n)]);}quantizationOperations=result.quantizationOperations;emit('bio-reasons',output);}
  else if(name==='bio-reasons'){output=old(408,[occurrence(1134),event.payload,list(compileReasonNuclei(items(f(rec(event.payload,403n),3n),'set'),f(model.content,6n)))]);emit('bio-decision',output);}
  else if(name==='bio-decision'){const root=typedIdentifier(1135,u(event.dueAt));output=await arbitrationOutput(root,event.dueAt,event.payload,old(440,[q(1,2),q(1,2)]),random.forResolution(root,event.payload));const data=chosenData(output);randomDrawRecords=items(f(data,9n),'list').map(v=>f(rec(v,422n),5n));const tie=rec(f(data,10n),423n);if(uint(f(tie,1n))===2n)randomDrawRecords.push(f(tie,3n));emit('bio-expression',output);}
  else if(name==='bio-expression'){const intent=intentOutput(occurrence(1136),event.payload);outputs.push(intent);output=expressionOutput(occurrence(1137),intent);emit('bio-qualification',output);}
  else if(name==='bio-qualification'){output=qualificationOutput(occurrence(1138),event.payload);emit('bio-learn',output);}
  else if(name==='bio-learn'){const p=familyPath(s,1),prior=read(p)!,history=familyValue(s,1,prior),qualification=rec(event.payload,429n),result=rec(f(qualification,3n),430n),kind=uint(f(physical.get(event.dueAt)!,2n));let next=prior;if(kind===1n&&enabled(s,1)&&uint(f(result,1n))===1n){const expression=rec(f(qualification,2n),426n),resolution=rec(f(rec(f(expression,2n),425n),2n),409n),contribution=old(413,[f(qualification,1n),f(resolution,1n),signed(event.dueAt),f(result,3n)]),fold=appendIdentityContribution(items(f(rec(history,414n),1n),'list'),contribution,ONE);next=wrap(1,fold.history);quantizationOperations=fold.operations;}output=update(p,prior,next);}
  else if(name==='practice-intent'){output=r(877,[occurrence(),signed(event.dueAt),uint(f(rec(event.payload,864n),2n))===2n,u(1)]);emit('practice-plan',output);}
  else if(name==='practice-plan'||name==='practice-attempt'){const p=rec(event.payload,877n);output=r(877,[occurrence(),f(p,2n),f(p,3n),u(name==='practice-plan'?2:3)]);emit(name==='practice-plan'?'practice-attempt':'source',output);}
  else if(name==='source'){const original=physical.get(event.dueAt)??fail('missing source'),skill=rec(familyValue(s,2,read(familyPath(s,2))!),784n),effective=readQ(f(skill,1n)).multiply(ONE.subtract(readQ(f(original,7n)))),practiced=f(rec(event.payload,877n),3n)===true;output=r(878,[occurrence(),signed(event.dueAt),f(original,2n),practiced,practiced&&effective.compare(readQ(f(original,8n)))>=0,f(original,3n),f(original,6n),f(original,9n),u(event.dueAt-priorClock)]);emit('observe',list([original,output]));emit('skill',output);}
  else if(name==='observe'){const pair=items(event.payload,'list'),original=rec(pair[0],864n),source=rec(pair[1],878n),kind=uint(f(source,3n)),access=f(original,4n)===true,admitted=access&&(kind===2n&&f(source,4n)===true||kind===3n||kind===4n),display=uint(f(original,5n)),value=display===0n?f(source,kind===2n?5n:6n):display===1n;output=r(879,[occurrence(),f(source,2n),f(source,3n),admitted,admitted&&f(source,7n)===true,...(admitted?[value]:[])]);for(const n of ['relationship','person','memory'])emit(n,output);}
  else if(name==='skill'){const p=familyPath(s,2),prior=read(p)!,value=familyValue(s,2,prior),next=enabled(s,2)?evolveSkill(value,event.payload,s):value;output=update(p,prior,key(value)===key(next)?prior:wrap(2,next));}
  else if(name==='relationship'){const p=familyPath(s,3),prior=read(p)!,o=rec(event.payload,879n);let next=prior;if(s.representation!==3&&enabled(s,3)&&uint(f(o,3n))===3n&&f(o,4n)===true&&f(o,5n)===true){next=s.representation===1?r(866,[list([...items(f(rec(prior,866n),1n),'list'),episode(o)])]):wrap(3,evolveRelationship(familyValue(s,3,prior),f(o,6n)===true,s.law));}output=update(p,prior,next);}
  else if(name==='person'){const p=path(870),prior=read(p),o=rec(event.payload,879n);if(enabled(s,3)&&uint(f(o,3n))===4n&&f(o,4n)===true){const next=r(869,[f(o,6n)]);write(p,prior,next);output=r(880,[occurrence(),owner(name,s),prior??r(866,[list([])]),next,prior===undefined||key(prior)!==key(next)]);}else output=r(880,[occurrence(),owner(name,s),prior??r(866,[list([])]),prior??r(866,[list([])]),false]);}
  else {const p=path(867),prior=read(p)!,o=rec(event.payload,879n),kind=uint(f(o,3n)),xs=items(f(rec(prior,866n),1n),'list').filter(v=>{const t=f(rec(v,865n),2n);return s.retention===2||typeof t!=='boolean'&&t.kind==='signed'&&event.dueAt-t.value<4n;}),admit=f(o,4n)===true&&(kind!==3n||f(o,5n)===true)&&((kind===2n&&enabled(s,2))||([3n,4n].includes(kind)&&enabled(s,3)));output=update(p,prior,r(866,[list([...xs,...(admit?[episode(o)]:[])])]));}
  decode(enc(output!));outputs.push(output!);const safeInput=['probe','bio-context'].includes(name)?list([signed(event.dueAt)]):name==='practice-intent'?list([signed(event.dueAt),f(rec(event.payload,864n),2n)]):name==='bio-learn'?list([event.payload,f(physical.get(event.dueAt)!,2n)]):event.payload;
  return {nextState,outputs,emittedEvents,traceContributions:[],traceFactory:(children:readonly ScheduledEvent[])=>{if(children.length!==emittedEvents.length)fail('longitudinal child count');children.forEach((e,i)=>{if(e.causalParentEventIds.length!==1||e.causalParentEventIds[0]!==event.eventId||key(e.payload)!==key(emittedEvents[i].payload))fail('longitudinal child binding');expected.set(e.eventId,key(scheduledEventValue(e)));});const trace=traceRecordValue({traceSchemaVersion:'trace/0.2-candidate',modelIdentity:model.modelIdentity.value,runIdentity:input.runIdentity.value,event,seamId:sid(1036,'seam/longitudinal/'+name),seamVersion:model.version,recordKind:event.eventTypeId,subjectIds:[OBSERVER,ACTOR],sourceRecordIds:[],registeredReadDomain:domain,actualReadRecords:reads,inputProjection:safeInput,outputProjection:list(outputs),randomDrawRecords,quantizationOperations,statePatch:patch,structuralMutationDiffs:diffs,emittedEvents:children,invariantResults:[]});decode(enc(trace));return [trace];}};
 }
 const scheduler=new DeterministicScheduler({initialState:model.initial,stateAdapter:adapter,handlers:new Map(STAGES.map(([n])=>[key(eventId(n)),handler])),initialQueue:input.events,initialAllocators:{nextRuntimeId:0n,nextEventId:BigInt(input.events.length),nextEventSequence:BigInt(input.events.length)},maxSettlementWorkPerSimulationInstant:17n,invariants:[state=>{if(expected.size)fail('unconsumed longitudinal children');model.validateState(state);random.prepareCommit();}]});
 async function settle(instrumentation?:ConformanceInstrumentation){if(active)fail('concurrent longitudinal settlement');if(!scheduler.getPendingQueue().length)return undefined;priorClock=scheduler.getClock();active=true;expected=new Map();random.begin();try{const result=instrumentation?await scheduler.settleNextInstantForConformance(instrumentation):await scheduler.settleNextInstant();if(result)random.commit();return result;}finally{active=false;expected.clear();random.close();}}
 function view(observer:CanonicalValue){if(key(observer)!==key(OBSERVER))throw Error('LONGITUDINAL_VIEW_OBSERVER');const state=scheduler.getState(),value=(family:number)=>familyValue(s,family,state.read(familyPath(s,family)).value!),person=state.read(path(870)).value,fields=new Map<bigint,CanonicalValue>([[1n,OBSERVER],[2n,qValue(identityStrength(value(1)))],[3n,value(2)],[4n,value(3)],[5n,state.read(path(867)).value!]]);if(person)fields.set(6n,person);if(s.representation===1)fields.set(7n,state.read(path(873)).value!);return enc(r(881,fields));}
 return {settle:()=>settle(),settleForConformance:(i:ConformanceInstrumentation)=>settle(i),view,snapshot:()=>({state:scheduler.getState(),clock:scheduler.getClock(),status:scheduler.status,queue:scheduler.getPendingQueue(),allocators:scheduler.getAllocatorState(),trace:scheduler.getCommittedTrace(),outputs:scheduler.getOutputs()}),save:()=>createCanonicalSave({scheduler,stateAdapter:adapter,modelIdentity:model.modelIdentity,runIdentity:input.runIdentity,continuingRunInputs:list([])}),diagnostic:()=>scheduler.failureDiagnostic};
}


