import {describe,it,expect} from 'vitest';
import {ExactRational as Q} from '../substrate/exactMath';
import {adoptMaintenanceGoal as adopt,settleMaintenanceGoal as settle,readMaintenanceConcern as read} from '../campaign3/bodilyMaintenanceGoal';
const range=(a:number,b:number)=>({lower:Q.of(BigInt(a)),upper:Q.of(BigInt(b))});
const domains=new Map([['signal/alpha',range(0,10)]]);
const goal=()=>({character:'character/a',goal:'goal/maintain',signal:'signal/alpha',desired:range(6,8),adoptedAt:0n,activeFrom:1n,expiresAt:10n});
describe('bodily maintenance goal lifecycle',()=>{
 it('MG-A: independent adopted concern with pending and absent distinguished',()=>{const s=adopt([],goal(),domains);expect(read(s,'character/a','goal/maintain',0n,domains)).toEqual({kind:'Unavailable',reason:'Pending'});expect(read(s,'character/a','goal/maintain',1n,domains).kind).toBe('Active');expect(read(s,'character/b','goal/maintain',1n,domains)).toEqual({kind:'Unavailable',reason:'Absent'});});
 it('MG-B: withdrawal changes future concern without altering old read basis',()=>{const s=adopt([],goal(),domains),old=read(s,'character/a','goal/maintain',2n,domains),next=settle(s,'character/a','goal/maintain',3n,'Withdraw',domains);expect(read(next,'character/a','goal/maintain',4n,domains)).toEqual({kind:'Unavailable',reason:'Withdrawn'});expect(old.kind).toBe('Active');expect(s[0].status).toBe('Open');expect(()=>read(next,'character/a','goal/maintain',2n,domains)).toThrow('HISTORICAL');});
 it('MG-C: expiry is explicit and ordered before assessment at boundary',()=>{const s=adopt([],goal(),domains);expect(()=>read(s,'character/a','goal/maintain',10n,domains)).toThrow('EXPIRY_NOT_SETTLED');const next=settle(s,'character/a','goal/maintain',10n,'Expire',domains);expect(read(next,'character/a','goal/maintain',10n,domains)).toEqual({kind:'Unavailable',reason:'Expired'});expect(()=>settle(s,'character/a','goal/maintain',9n,'Expire',domains)).toThrow();});
 it('MG-D: reads never retire maintenance goal; terminal goals cannot be replayed or replaced',()=>{const s=adopt([],goal(),domains);for(let t=1;t<10;t++)read(s,'character/a','goal/maintain',BigInt(t),domains);expect(s[0].status).toBe('Open');const withdrawn=settle(s,'character/a','goal/maintain',2n,'Withdraw',domains);expect(()=>settle(withdrawn,'character/a','goal/maintain',3n,'Withdraw',domains)).toThrow();expect(()=>adopt(withdrawn,goal(),domains)).toThrow('DUPLICATE');});
 it('MG-E: signal identity is model admitted; raw-source names and out-of-domain criteria reject',()=>{expect(()=>adopt([],{...goal(),signal:'reserve/alpha'},domains)).toThrow('SIGNAL_DOMAIN');expect(()=>adopt([],{...goal(),desired:range(6,11)},domains)).toThrow('OUTSIDE_DOMAIN');expect(()=>adopt([],{...goal(),expiresAt:1n},domains)).toThrow('TIME');});
 it('MG-F: rational criterion and concern snapshots do not alias caller objects',()=>{const g=goal(),s=adopt([],g,domains);Object.assign(g.desired.lower,{numerator:9n});expect(s[0].desired.lower.equals(Q.of(6n))).toBe(true);expect(Object.isFrozen(s[0].desired.lower)).toBe(true);});
});
