import {it,expect} from 'vitest';
import {createCostlyRun as create,restoreCostlyRun as restore,LAWS,type Law} from '../campaign3/costlyReward';
import {costlyCases as cases} from './costlyRewardFixtures';
import {decodeReceiving as decode} from '../campaign3/receivingCodecs';
import {dataRecord as rec,dataField as f,dataItems as items} from '../campaign2/canonicalData';
const value=(s:string)=>decode(Uint8Array.from(s.match(/../g)!.map(x=>parseInt(x,16))));
async function run(name:keyof ReturnType<typeof cases>='main',law:Law='MeanHistory',seed=7){const r=create(law,cases()[name],seed);while(await r.step()){}return r;}
it('acquires separate benefit and harm, then withholds under a maintained protective goal',async()=>{const s=(await run()).snapshot();expect(s.rows[4]).toMatchObject({rewardBelief:'1/1',harmBelief:'1/4',habit:'15/16',goal:true,maintained:true,intent:1});for(const i of [4,5,10,11])expect(s.rows[i]).toMatchObject({intent:1,inhibited:true});expect(s.rows.slice(4).every(r=>r.goal&&r.maintained)).toBe(true);expect(s.rows.slice(6,10).some(r=>items(f(rec(value(r.reasons),408n),3n),'list').length===2)).toBe(true);},60000);
it('whole seed roster distinguishes actual costly persistence from no-load withholding',async()=>{let witness=false;for(let seed=0;seed<8;seed++){const a=(await run('main','MeanHistory',seed)).snapshot(),b=(await run('noLoad','MeanHistory',seed)).snapshot();expect(b.rows.slice(4).every(r=>r.intent===1)).toBe(true);expect(a.rows.slice(4).every(r=>r.goal&&r.maintained)).toBe(true);if(a.world.slice(6,10).filter(r=>r.performedA&&r.reward&&r.harm).length>=2)witness=true;}expect(witness).toBe(true);},120000);
it('withheld feedback changes only later learning, never fabricates negative evidence for B',async()=>{const a=(await run()).snapshot(),b=(await run('withheld')).snapshot();expect(a.rows.slice(0,6)).toEqual(b.rows.slice(0,6));expect(a.rows[6].resolution).toBe(b.rows[6].resolution);expect(b.history).toHaveLength(4);expect(b.rows.slice(4).every(r=>r.harmBelief==='1/4')).toBe(true);expect(a.history.length).toBeGreaterThan(4);expect(a.rows[11].harmBelief).not.toBe('1/4');expect(a.history.every(s=>a.rows[s.at-1].intent===0)).toBe(true);},60000);
it('absence, neutral evidence, cue mismatch and physical availability are distinct',async()=>{for(const name of ['unseen','otherCue','unavailable','noBenefit'] as const){const s=(await run(name)).snapshot();expect(s.rows.slice(4).every(r=>r.intent!==0)).toBe(true);if(name==='unseen')expect(s.rows[4].rewardBelief).toBeNull();if(name==='noBenefit')expect(s.rows[4].rewardBelief).toBe('0/1');if(name==='otherCue')expect(s.rows[4]).toMatchObject({rewardBelief:'1/1',habit:'0/1',availableA:true});if(name==='unavailable')expect(s.rows[4]).toMatchObject({habit:'15/16',availableA:false});}},60000);
it('repetition without harm has no costly-outcome diagnostic; no-goal behavior has no protective conflict',async()=>{const a=(await run('harmless')).snapshot(),b=(await run('noGoal')).snapshot();expect(a.world.filter(r=>r.performedA).length).toBeGreaterThan(4);expect(a.world.every(r=>!r.harm)).toBe(true);expect(a.rows.slice(4).every(r=>r.harmBelief==='0/1')).toBe(true);expect(b.rows.every(r=>!r.goal)).toBe(true);expect(b.rows.slice(4).every(r=>r.values[1]==='0/1')).toBe(true);},60000);
it('whole later safe views follow admitted reports and exclude hidden world differences',async()=>{for(const [a,b] of [['trueReports','falseReports'],['withheld','hiddenDenied']] as const){const x=await run(a),y=await run(b);expect(x.observerView()).toEqual(y.observerView());expect(x.snapshot().world).not.toEqual(y.snapshot().world);}},60000);
it('execution failure differs from chosen reward pursuit and yields only admitted false outcomes',async()=>{const s=(await run('failed')).snapshot();expect(s.rows.slice(4).some(r=>r.intent===0)).toBe(true);expect(s.world.slice(4).every(r=>!r.performedA&&!r.reward&&!r.harm)).toBe(true);expect(s.rows.slice(4).filter(r=>r.receipt).every(r=>!r.receipt!.reward&&!r.receipt!.harm)).toBe(true);},60000);
it('retains learning, access, inhibition and protective-reason comparators',async()=>{const base=(await run()).snapshot(),latest=(await run('main','LatestHistory')).snapshot(),access=(await run('otherCue','BeliefAccess')).snapshot(),control=(await run('main','NoControl')).snapshot(),none=(await run('main','NoLearning')).snapshot(),reward=(await run('main','RewardOnly')).snapshot();expect(latest.rows[4].harmBelief).toBe('1/1');expect(base.rows[4].harmBelief).toBe('1/4');expect(access.rows.slice(6,10).some(r=>r.intent===0)).toBe(true);expect(control.rows.slice(4).every(r=>!r.inhibited)).toBe(true);expect(none.history).toEqual([]);expect(none.rows.slice(4).every(r=>r.intent===-1)).toBe(true);expect(reward.rows.slice(6,10).every(r=>r.intent===0&&r.values[1]==='0/1')).toBe(true);expect(reward.rows[6].harmBelief).toBe('1/4');},60000);
for(const fault of ['after-decision','before-commit'] as const)it(`rolls back contested ${fault}, including random addresses`,async()=>{const inputs=cases().main,a=create('MeanHistory',inputs),b=create('MeanHistory',inputs);for(let i=0;i<6;i++){await a.step();await b.step();}const before=a.save();await expect(a.step(fault)).rejects.toThrow('INJECTED');expect(a.save()).toEqual(before);await a.step();await b.step();expect(a.save()).toEqual(b.save());},60000);
it('validates exact data and binds save to originals, law and seed; snapshots are isolated',async()=>{const input=cases().main,a=create('MeanHistory',input);await a.step();const snapshot=a.snapshot();snapshot.history.length=0;expect(a.snapshot().history).toHaveLength(1);for(const [law,frames,seed] of [['LatestHistory',input,7],['MeanHistory',cases().noLoad,7],['MeanHistory',input,8]] as const)await expect(restore(law,frames,a.save(),seed)).rejects.toThrow('MISMATCH');const malformed=cases().main;Object.defineProperty(malformed[0],'cue',{get(){throw Error('callback');}});expect(()=>create('MeanHistory',malformed)).toThrow('DATA');const late=cases().main;late[6].adopt=true;expect(()=>create('MeanHistory',late)).toThrow('DOMAIN');const edited=a.save();edited[edited.length-1]^=1;await expect(restore('MeanHistory',input,edited)).rejects.toThrow();},60000);
for(const law of LAWS)it(`restores all prefixes and advances exactly: ${law}`,async()=>{const input=cases().main,a=create(law,input),saves=[a.save()];while(await a.step())saves.push(a.save());for(let i=0;i<saves.length;i++){const b=await restore(law,input,saves[i]);expect(b.save()).toEqual(saves[i]);expect(await b.step()).toBe(i<12);expect(b.save()).toEqual(saves[Math.min(i+1,12)]);}},120000);
