import {describe,it,expect} from 'vitest';
import {ExactRational as Q} from '../substrate/exactMath';
import {prepareFocalAttribution as prepare} from '../campaign3/focalAttribution';
import type {UseTrial,AttributionField} from '../campaign3/retainedAttributionUse';
import type {AttributionTrial} from '../campaign3/contrastiveAttribution';
const interval={lower:Q.of(20n),upper:Q.of(21n)},focus={acquisition:812n,unit:'alpha'};
function fixture(missing=false){const trials:UseTrial[]=[true,false,true,false].map((stroke,i)=>({motion:{kind:'Detached',value:[[0,0],[stroke?1:0,0]]},before:{kind:'Retained',address:{acquisition:i===0?812n:i===2?813n:900n,unit:i===0||i===2?'alpha':'gamma'},view:0},after:{kind:'Detached',value:missing&&i===0?null:stroke?{lower:Q.of(30n),upper:Q.of(31n)}:interval}}));return {observer:'observer/a',character:'character/a',now:5n,memory:[812n,813n,900n].map(id=>({id,kind:'EventContinuant' as const,acquiredAt:1n,units:[{key:id===900n?'gamma':'alpha',views:[new Uint8Array([20,21])],useProtection:false}]})),admitted:[focus,{acquisition:813n,unit:'alpha'},{acquisition:900n,unit:'gamma'}],trials};}
const opportunity=()=>({observer:'observer/a',character:'character/a',consequence:'consequence/focal',focal:{...focus}});
const project=<K extends AttributionField>(b:Uint8Array,k:K):AttributionTrial[K]=>{if(k==='motion')throw Error('fixture interval');return {lower:Q.of(BigInt(b[0])),upper:Q.of(BigInt(b[1]))} as AttributionTrial[K];};
describe('supplied-focus actual attribution composition',()=>{
 it('FA-A: supporting same-key and stationary memories earn use, never automatic targethood',()=>{const tx=prepare(fixture(),opportunity(),project),r=tx.finish(tx.evaluate());expect(r.assessment.kind).toBe('Supported');expect(r.consumed).toHaveLength(3);expect(r.memory.every(a=>a.units[0].useProtection)).toBe(true);expect(r.attributedTargets).toEqual([focus]);});
 it('FA-B: unavailable produces no target but preserves actual partial use',()=>{const tx=prepare(fixture(true),opportunity(),project),r=tx.finish(tx.evaluate());expect(r.assessment.kind).toBe('Unavailable');expect(r.attributedTargets).toEqual([]);expect(r.consumed).toEqual([focus]);});
 it('FA-C: focus is captured before evaluation and cannot be replaced by caller mutation',()=>{const op=opportunity(),tx=prepare(fixture(),op,project);op.focal.acquisition=813n;op.consequence='different';const r=tx.finish(tx.evaluate());expect(r.attributedTargets).toEqual([focus]);expect(r.focus.consequence).toBe('consequence/focal');});
 it('FA-D: foreign subject, lost child, same-instant focus and missing consequence reject',()=>{expect(()=>prepare(fixture(),{...opportunity(),character:'foreign'},project)).toThrow('SUBJECT');expect(()=>prepare(fixture(),{...opportunity(),focal:{acquisition:812n,unit:'lost'}},project)).toThrow();const f=fixture();f.memory[0].acquiredAt=5n;expect(()=>prepare(f,opportunity(),project)).toThrow('PRIOR_MEMORY');expect(()=>prepare(fixture(),{...opportunity(),consequence:''},project)).toThrow('CONSEQUENCE');});
 it('FA-E: copied/foreign/replayed tokens cannot produce additional target projections',()=>{const a=prepare(fixture(),opportunity(),project),b=prepare(fixture(),opportunity(),project),token=a.evaluate();expect(()=>b.finish(token)).toThrow('BINDING');expect(()=>a.finish({...token})).toThrow('BINDING');a.finish(token);expect(()=>a.finish(token)).toThrow('BINDING');});
});
