import {describe,it,expect} from 'vitest';
import {ExactRational as Q} from '../substrate/exactMath';
import {canonicalEncode,text,typedIdentifier} from '../substrate/canonicalEncoding';
import {semanticReferentFromAuthoredContent} from '../substrate/referentOrigin';
import {governedContentDefinitionId} from '../substrate/contentDefinitionId';
import {EventRoleId} from '../semanticBinding/eventBindings';
import {preRecognitionSemanticExperienceValue} from '../semanticBinding/semanticEvidenceCodecs';
import {decodeSemanticValue} from '../semanticBinding/semanticCodecs';
import {createLocalReserveSource} from '../campaign3/localReserveSource';
import {createTrialPanelSource} from '../campaign3/trialPanelSource';
import {createPositionSceneSource} from '../campaign3/positionSceneSource';
import {createTrialPanelPerception,consumeTrialPanel,trialPanelPerceptionSnapshot} from '../campaign3/trialPanelPerception';
import {createTenSweepMarkerTransactionManager,committedMarkerSnapshot} from '../campaign3/transactionalMarkerTracking';
import {observeGeneralSourceOpportunity} from '../campaign3/generalSourceOpportunity';
import {selectLocalReserveSignals,consumeInteroceptiveSignals} from '../campaign3/interoceptiveSignalSelection';
import {admitLocalReserveSignalCue} from '../campaign3/bodySignalCue';
import {createWindowMarkerManager,isWindowMarkerManager,windowMarkerSnapshot} from '../campaign3/windowMarkerTransaction';
import {createWindowPanelManager,windowPanelSnapshot} from '../campaign3/windowPanelTransaction';
import type {SourceSamplingRequest} from '../campaign3/requestedSourceSampling';
const observer=typedIdentifier(1000,text('observer/a')),all={bodyChannels:['channel/A'],panel:true,visual:true};
function source(p=true,v=true,b=true,window=false){return {body:createLocalReserveSource(['A','B','C'].map(k=>({key:'local-reserve/'+k,capacity:Q.of(100n),rate:Q.of(0n),amount:Q.of(0n),anchoredAt:0n})),['A','B','C'].map(k=>({channel:'channel/'+k,physical:'local-reserve/'+k,signal:'interoceptive-signal/'+k,width:Q.of(1n),available:b,permitted:true}))),panel:createTrialPanelSource([{at:1n,glyph:0,stage:'Before',visible:p,permitted:true}]),scene:createPositionSceneSource([{at:1n,items:[EventRoleId.Actor,EventRoleId.Target,EventRoleId.Participant].map((role,i)=>({marker:semanticReferentFromAuthoredContent(governedContentDefinitionId('object/'+i)),role,x:BigInt(i),y:0n,glyph:BigInt(i),visible:v,permitted:true,roleMode:'Preserve' as const}))}]),perception:createTrialPanelPerception('observer/a'),tracker:window?createWindowMarkerManager('observer/a'):createTenSweepMarkerTransactionManager('observer/a')};}
const snapshot=(s:ReturnType<typeof source>)=>({event:trialPanelPerceptionSnapshot(s.perception),marker:isWindowMarkerManager(s.tracker)?windowMarkerSnapshot(s.tracker):committedMarkerSnapshot(s.tracker)});
const run=(s:ReturnType<typeof source>,next:()=>bigint,request:SourceSamplingRequest=all,lane:'Current'|'Consequence'='Current')=>observeGeneralSourceOpportunity(request.bodyChannels?s.body:undefined,request.panel?s.panel:undefined,request.visual?s.scene:undefined,s.perception,s.tracker,observer,1n,lane,request,next);
describe('one requested multimodal semantic opportunity',()=>{
 it('GSO-A: all7 requests and8 presence cases in both lanes share exactly one conditional experience',()=>{for(const lane of ['Current','Consequence'] as const)for(let mask=1;mask<8;mask++)for(const p of [false,true])for(const v of [false,true])for(const b of [false,true]){const rb=!!(mask&1),rp=!!(mask&2),rv=!!(mask&4),request={bodyChannels:rb?['channel/A']:null,panel:rp,visual:rv};let n=0n;const r=run(source(p,v,b),()=>n++,request,lane),present=rb&&b||rp&&p||rv&&v,event=rp&&p||rv&&v;
  expect(n).toBe(BigInt((rv?5:0)+(rb?1:0)+(rp?1:0)+(event?1:0)+(rv&&v?6:0)+(present?1:0)));expect(r.opportunityId!==null).toBe(present);expect(r.body!==undefined).toBe(rb);expect(r.panel!==undefined).toBe(rp);expect(r.visual!==undefined).toBe(rv);expect(r.tracks).toHaveLength(rv&&v?3:0);expect(r.context!==undefined).toBe(rp&&p);if(rb)expect(r.body!.staged?.experience.experienceId).toBe(r.staged?.experience.experienceId);
  if(r.staged){expect(r.staged.stagedAtPhase).toBe(lane==='Current'?14n:124n);expect(r.staged.experience.supportingObservationIds).toHaveLength(Number(rb&&b)+Number(rp&&p)+Number(rv&&v));const bytes=canonicalEncode(preRecognitionSemanticExperienceValue(r.staged.experience));expect(canonicalEncode(decodeSemanticValue(bytes))).toEqual(bytes);}
 }});
 it('GSO-B: body encoding capacity zero preserves a current cue and the same shared experience',()=>{let n=0n;const r=run(source(),()=>n++),body=r.body!;expect(consumeInteroceptiveSignals(selectLocalReserveSignals(body,{maxSignals:1,maxViewsPerSignal:1,maxBytesPerSignal:4096,capacity:0}).view).groups).toEqual([]);const cue=admitLocalReserveSignalCue(body,1n,true);expect(cue.cue.kind).toBe('Present');expect(body.opportunityId).toBe(r.staged!.experience.experienceId);expect(r.staged!.experience.perceivedBindings).toHaveLength(3);});
 it('GSO-C: failure at all15 actual allocation slots preserves both owners and retry identities',()=>{let n=0n;const expected=run(source(),()=>n++);expect(n).toBe(15n);for(let failAt=0;failAt<15;failAt++){const s=source(),prior=snapshot(s);let calls=0;expect(()=>run(s,()=>calls===failAt?-1n:BigInt(calls++))).toThrow();expect(snapshot(s)).toEqual(prior);let retry=0n;expect(run(s,()=>retry++)).toEqual(expected);}});
 it('GSO-D: unrequested panel state cannot be cleared to authorize a visual event',()=>{const s=source();consumeTrialPanel(s.perception,{observer:'observer/a',observation:100n,detection:101n,sample:{kind:'Present',at:0n,glyph:0,stage:'Before'}});const prior=snapshot(s);let n=200n;run(s,()=>n++,{bodyChannels:['channel/A'],panel:false,visual:false});expect(snapshot(s)).toEqual(prior);expect(()=>run(s,()=>n++,{bodyChannels:['channel/A'],panel:false,visual:true})).toThrow('UNSAMPLED_ACTIVE_CONTEXT');expect(snapshot(s)).toEqual(prior);});
 it('GSO-E: malformed requests reject before source allocation and never execute request getters',()=>{const s=source();let calls=0,allocated=0;const request={bodyChannels:['channel/A'],panel:true,get visual(){calls++;return true;}};expect(()=>observeGeneralSourceOpportunity(s.body,s.panel,s.scene,s.perception,s.tracker,observer,1n,'Current',request,()=>BigInt(allocated++))).toThrow();expect(calls).toBe(0);expect(allocated).toBe(0);});
 it('GSO-F: available unrequested sources remain unread and allocate no observations or world events',()=>{const s=source(),prior=snapshot(s);let n=0n;const r=observeGeneralSourceOpportunity(s.body,s.panel,s.scene,s.perception,s.tracker,observer,1n,'Current',{bodyChannels:['channel/A'],panel:false,visual:false},()=>n++);expect(n).toBe(2n);expect(r.truth).toBeUndefined();expect(r.visual).toBeUndefined();expect(r.panel).toBeUndefined();expect(snapshot(s)).toEqual(prior);});
 it('GSO-G: a shared experience cannot manufacture a cue for an absent modality',()=>{let n=0n;const absentBody=run(source(false,true,false),()=>n++);expect(absentBody.staged).not.toBeNull();expect(admitLocalReserveSignalCue(absentBody.body!,1n,true).cue).toEqual({kind:'Absent'});expect(consumeInteroceptiveSignals(selectLocalReserveSignals(absentBody.body!,{maxSignals:1,maxViewsPerSignal:1,maxBytesPerSignal:4096,capacity:1}).view).groups).toEqual([]);n=0n;const absentVisual=run(source(false,false,true),()=>n++);expect(absentVisual.staged).not.toBeNull();expect(absentVisual.visual!.detections).toEqual([]);expect(absentVisual.event).toBeUndefined();expect(admitLocalReserveSignalCue(absentVisual.body!,1n,true).cue.kind).toBe('Present');});
 it('GSO-H: retained-window source matches history control across every request/presence/lane',()=>{for(const lane of ['Current','Consequence'] as const)for(let mask=1;mask<8;mask++)for(const p of [false,true])for(const v of [false,true])for(const b of [false,true]){const request={bodyChannels:mask&1?['channel/A']:null,panel:!!(mask&2),visual:!!(mask&4)};let x=0n,y=0n;const bounded=source(p,v,b,true),historical=source(p,v,b);expect(run(bounded,()=>x++,request,lane)).toEqual(run(historical,()=>y++,request,lane));expect(x).toBe(y);const saved=windowMarkerSnapshot(bounded.tracker as ReturnType<typeof createWindowMarkerManager>);expect(saved.window.at).toBe(request.visual?1n:0n);expect(saved.files).toEqual(committedMarkerSnapshot(historical.tracker as ReturnType<typeof createTenSweepMarkerTransactionManager>).state);}});
 it('GSO-I: retained-window owner also rolls back at all15 allocation slots',()=>{let n=0n;const expected=run(source(true,true,true,true),()=>n++);for(let failAt=0;failAt<15;failAt++){const s=source(true,true,true,true),prior=snapshot(s);let calls=0;expect(()=>run(s,()=>calls===failAt?-1n:BigInt(calls++))).toThrow();expect(snapshot(s)).toEqual(prior);let retry=0n;expect(run(s,()=>retry++)).toEqual(expected);}});

 it('GSO-J: both bounded owners preserve complete source outputs and late-failure atomicity',()=>{
  for(const lane of ['Current','Consequence'] as const)for(let mask=1;mask<8;mask++)for(const p of [false,true])for(const v of [false,true])for(const b of [false,true]){const request={bodyChannels:mask&1?['channel/A']:null,panel:!!(mask&2),visual:!!(mask&4)},s=source(p,v,b),tracker=createWindowMarkerManager('observer/a'),perception=createWindowPanelManager('observer/a');let x=0n,y=0n;const r=observeGeneralSourceOpportunity(s.body,s.panel,s.scene,perception,tracker,observer,1n,lane,request,()=>x++);expect(r).toEqual(run(s,()=>y++,request,lane));expect(x).toBe(y);expect(windowPanelSnapshot(perception).files).toEqual(trialPanelPerceptionSnapshot(s.perception).files);}
  for(let failAt=0;failAt<15;failAt++){const s=source(),tracker=createWindowMarkerManager('observer/a'),perception=createWindowPanelManager('observer/a'),before={marker:windowMarkerSnapshot(tracker),panel:windowPanelSnapshot(perception)};let calls=0;expect(()=>observeGeneralSourceOpportunity(s.body,s.panel,s.scene,perception,tracker,observer,1n,'Current',all,()=>calls===failAt?-1n:BigInt(calls++))).toThrow();expect({marker:windowMarkerSnapshot(tracker),panel:windowPanelSnapshot(perception)}).toEqual(before);let x=0n,y=0n;expect(observeGeneralSourceOpportunity(s.body,s.panel,s.scene,perception,tracker,observer,1n,'Current',all,()=>x++)).toEqual(run(source(),()=>y++));}
 });

 it('GSO-K: sampling reserves the one experience before binding allocations or owner preparation',()=>{const s=source(true,true,true,true),prior=snapshot(s);let n=0n;const r=run(s,()=>{if(n===11n)expect(snapshot(s)).toEqual(prior);return n++;});expect(r.staged!.reservation.reservedAtPhase).toBe(10n);expect(r.staged!.experience.experienceId).toBe(11n);expect(r.staged!.experience.perceivedBindings.every(b=>b.perceivedBindingId>r.staged!.experience.experienceId)).toBe(true);expect(n).toBe(15n);});

});
