import {describe,it,expect} from 'vitest';
import {validateGeneralSourceSchedule as validate,type PlannedObservation,type SourceScheduleDomain} from '../campaign3/generalSourceSchedule';
const domain=():SourceScheduleDomain=>({initialClock:0n,horizon:100n,channels:['channel/a'],assessmentDefinitions:['assessment/a'],lifecycleInstants:[1n,70n,100n]});
const entry=(at=2n):PlannedObservation=>({at,lane:'Current',request:{bodyChannels:['channel/a'],panel:false,visual:false},use:{bodySelection:false,visualSelection:false,bodyCue:true,visualCue:false,goalAssessment:null}});
describe('bounded source schedule compilation',()=>{
 it('GSS-A: actual sensing may independently cue, select, do both or do neither',()=>{for(const select of [false,true])for(const cue of [false,true]){const e=entry(),r=validate([{...e,use:{...e.use,bodySelection:select,bodyCue:cue}}],domain());expect(r.qualifiedSelectionSlots).toBe(Number(select));expect(r.observations).toBe(1);} });
 it('GSS-B: both selectors count independently; capacity or future eligibility is not a schedule operand',()=>{const rows=Array.from({length:32},(_,i)=>{const e=entry(BigInt(i+2));return {...e,use:{...e.use,bodySelection:true}};});expect(validate(rows,domain()).qualifiedSelectionSlots).toBe(32);rows[0]={...rows[0],request:{...rows[0].request,visual:true},use:{...rows[0].use,visualSelection:true}};expect(()=>validate(rows,domain())).toThrow('GENERAL_SOURCE_SCHEDULE');});
 it('GSS-C:10 visual and16 panel sweeps are separate from selection counts',()=>{const rows=Array.from({length:16},(_,i)=>{const e=entry(BigInt(i+2));return {...e,request:{...e.request,panel:true,visual:i<10}};});expect(validate(rows,domain())).toMatchObject({visualSweeps:10,panelSweeps:16,qualifiedSelectionSlots:0});expect(()=>validate([...rows,{...entry(18n),request:{...entry().request,panel:true}}],domain())).toThrow();rows[10]={...rows[10],request:{...rows[10].request,visual:true}};expect(()=>validate(rows,domain())).toThrow();});
 it('GSS-D: uses never synthesize an unrequested surface or an unknown channel',()=>{const e=entry();expect(()=>validate([{...e,request:{bodyChannels:null,panel:true,visual:false}}],domain())).toThrow();expect(()=>validate([{...e,use:{...e.use,visualCue:true}}],domain())).toThrow();for(const channels of [[],['unknown'],['channel/a','channel/a']])expect(()=>validate([{...e,request:{...e.request,bodyChannels:channels}}],domain())).toThrow();});
 it('GSS-E: goal assessment is consequence-only with actual body request and no simultaneous lifecycle',()=>{const e=entry(4n),valid={...e,lane:'Consequence' as const,use:{...e.use,goalAssessment:'assessment/a'}};expect(validate([valid],domain()).observations).toBe(1);for(const bad of [{...valid,lane:'Current' as const},{...valid,at:70n},{...valid,use:{...valid.use,goalAssessment:'unknown'}},{...valid,request:{bodyChannels:null,panel:true,visual:false},use:{...valid.use,bodyCue:false}}])expect(()=>validate([bad],domain())).toThrow();});
 it('GSS-F: original times stay strict and within the declared run, including restore prefix time',()=>{for(const rows of [[entry(0n)],[entry(101n)],[entry(2n),entry(2n)],[entry(3n),entry(2n)]])expect(()=>validate(rows,domain())).toThrow();expect(()=>validate([entry(20n)],{...domain(),initialClock:20n,lifecycleInstants:[70n,100n]})).toThrow();});
 it('GSS-G: hostile data cannot execute a getter, and accepted input is detached',()=>{let calls=0;const e=entry();Object.defineProperty(e.use,'bodyCue',{get(){calls++;return true;}});expect(()=>validate([e],domain())).toThrow();expect(calls).toBe(0);const sparse=new Array(1) as PlannedObservation[];expect(()=>validate(sparse,domain())).toThrow();const input=entry(),r=validate([input],domain());(input.request.bodyChannels as string[])[0]='changed';expect(r.entries[0].request.bodyChannels).toEqual(['channel/a']);expect(Object.isFrozen(r.entries[0].use)).toBe(true);});
});
