import {describe,it,expect} from 'vitest';
import {ExactRational as Q} from '../substrate/exactMath';
import {adoptMaintenanceGoal,settleMaintenanceGoal} from '../campaign3/bodilyMaintenanceGoal';
import {assessGoalDistance as assess,satisfactionBoundaryControl,type SignalRelationDomain} from '../campaign3/goalDistanceRelation';
const r=(a:number,b=a)=>({lower:Q.of(BigInt(a)),upper:Q.of(BigInt(b))});
const domains=new Map<string,SignalRelationDomain>([['alpha',{kind:'MetricInterval',bounds:r(0,10)}]]);
const state=(g=r(6,8))=>adoptMaintenanceGoal([],{character:'a',goal:'maintain',signal:'alpha',desired:g,adoptedAt:0n,activeFrom:0n,expiresAt:10n},new Map([['alpha',r(0,10)]]));
const args=(before=r(5),after=r(7),g=r(6,8))=>({state:state(g),character:'a',goal:'maintain',signal:'alpha',now:1n,before,after,domains});
describe('conservative goal distance relation',()=>{
 it('GR-A: equal consequence under different goals changes exact relation',()=>{expect(assess(args())).toMatchObject({kind:'Assessed',relation:'MovingCloser',boundary:'Attainment'});expect(assess(args(r(5),r(7),r(2,4)))).toMatchObject({relation:'MovingFarther',boundary:'NoBoundaryChange'});});
 it('GR-B: overlapping evidence is indeterminate, distinct from missing and known equal',()=>{expect(assess(args(r(3,5),r(4,6)))).toMatchObject({kind:'Assessed',relation:'IndeterminateRelation'});expect(assess({...args(),before:null})).toEqual({kind:'Unavailable',reason:'MissingEvidence'});expect(assess(args(r(6,7),r(7,8)))).toMatchObject({kind:'Assessed',relation:'SameDistance'});expect(assess(args(r(3,5),r(3,5)))).toMatchObject({relation:'IndeterminateRelation'});});
 it('GR-C: equal distance across opposite sides preserves position',()=>{expect(assess(args(r(5),r(9)))).toMatchObject({relation:'SameDistance',beforePosition:'BelowGoal',afterPosition:'AboveGoal',boundary:'NoBoundaryChange'});});
 it('GR-D: inclusive endpoints, ambiguous position and violation remain separate',()=>{expect(assess(args(r(6),r(8)))).toMatchObject({beforePosition:'WithinGoal',afterPosition:'WithinGoal'});expect(assess(args(r(5,7),r(9)))).toMatchObject({beforePosition:'AmbiguousPosition',boundary:'IndeterminateBoundary'});expect(assess(args(r(7),r(9)))).toMatchObject({boundary:'Violation',relation:'MovingFarther'});expect(assess(args(r(4,5),r(5,6)))).toMatchObject({relation:'IndeterminateRelation'});});
 it('GR-E: metric admission and exact signal domain are required',()=>{expect(()=>assess({...args(),domains:new Map([['alpha',{kind:'OrdinalInterval' as const,bounds:r(0,10)}]])})).toThrow('METRIC_REQUIRED');expect(()=>assess(args(r(-1),r(7)))).toThrow('EVIDENCE_DOMAIN');expect(()=>assess(args(r(5,4),r(7)))).toThrow('INTERVAL');});
 it('GR-F: withdrawal affects future assessment without rewriting past basis',()=>{const input=args(),old=assess(input),next=settleMaintenanceGoal(input.state,'a','maintain',2n,'Withdraw',new Map([['alpha',r(0,10)]]));expect(assess({...input,state:next,now:3n})).toEqual({kind:'Unavailable',reason:'Withdrawn'});expect(old).toMatchObject({kind:'Assessed',concern:{status:'Open'}});expect(assess({...input,character:'b'})).toEqual({kind:'Unavailable',reason:'Absent'});});
 it('GR-G: boundary comparator discards outside-range direction without changing source',()=>{const farther=assess(args(r(5),r(7),r(2,4))),closer=assess(args(r(7),r(5),r(2,4)));expect(farther).toMatchObject({relation:'MovingFarther'});expect(closer).toMatchObject({relation:'MovingCloser'});expect(satisfactionBoundaryControl(farther)).toEqual(satisfactionBoundaryControl(closer));});
 it('GR-H: exact range bounds and asserted direction agree with exhaustive half-step witnesses',()=>{let checks=0;for(let l=0;l<=10;l++)for(let u=l;u<=10;u++){const result=assess(args(r(l,u),r(5)));if(result.kind!=='Assessed')throw Error('expected assessment');const points=Array.from({length:(u-l)*2+1},(_,i)=>(l*2+i)/2),distances=points.map(x=>Math.max(6-x,0,x-8));expect(result.before.lower.equals(Q.of(BigInt(Math.min(...distances)*2),2n))).toBe(true);expect(result.before.upper.equals(Q.of(BigInt(Math.max(...distances)*2),2n))).toBe(true);if(result.relation==='MovingCloser')expect(distances.every(d=>1<d)).toBe(true);if(result.relation==='MovingFarther')expect(distances.every(d=>1>d)).toBe(true);checks++;}expect(checks).toBe(66);});
});
