import {it,expect} from 'vitest';
import {canonicalEncode as enc,list,record,unsigned as u,rational as q} from '../substrate/canonicalEncoding';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key} from '../campaign2/canonicalData';
import {applyStatePatch,AuthoritativeState} from '../substrate/state';
import {actor,stages,eventId,path,owner,beliefRecipe,compileBeliefModel,compileBeliefInputs,evidenceValue,evidence} from '../campaign3/identityBeliefPublicModel';
import {decodeIdentityBeliefPublic as decode,identityBeliefPublicRecord as r} from '../campaign3/identityBeliefPublicCodecs';
import {prepareIdentityBeliefModel,createIdentityBeliefPublicRun,restoreIdentityBeliefPublicRun} from '../campaign3/identityBeliefPublicFactory';
import {createIdentityBeliefRun,identityBeliefRows,HOLDERS} from '../campaign3/identityBelief';
import {publicInput,restoreInput,beliefCase,nativeRuntime,nativeRun,outputs,beliefRows,records,taskSemantic} from './identityBeliefPublicFixtures';
async function finished(c=beliefCase()){const run=await nativeRun(c);while(await run.settleNextInstant()){}return run;}
it('native source and each holder update match component; phase50 consumes prior140',async()=>{
 const c=beliefCase(),native=await finished(c),component=createIdentityBeliefRun('Mean',1,c.input);while(await component.step()){}const old=identityBeliefRows(component.snapshot()),rows=beliefRows(outputs(native));
 expect(taskSemantic(outputs(native))).toEqual(old.map(x=>{const {at,chosen,authorship,probabilities,contribution,strength,executed}=x.source;return {at,chosen,authorship,probabilities,contribution,strength,executed};}));
 rows.forEach((row,i)=>{expect(row.observations).toEqual(old[i].observations);expect(row.states.map(s=>s.estimate)).toEqual(old[i].estimates);expect(row.appraisals.map(a=>a.estimate)).toEqual(i?old[i-1].estimates.map(e=>e.value):[null,null,null]);});
 const trace=items(decode(native.snapshot().trace),'list').map(v=>rec(v,160n));for(const [type,phase] of [[1450,50],[1431,60],[1432,70],[1433,80],[1439,110],[1434,130],[1448,130],[1449,140]])for(const t of trace.filter(t=>records(items(f(t,13n),'list'),type).length))expect(f(rec(f(t,4n),130n),3n)).toEqual(u(phase));
 expect(rows[4].appraisals.map(({adverse,affect})=>({adverse,affect}))).toEqual(old[4].appraisals);
},600000);
it('private self and hidden biography preserve complete lawful observer views; Oracle fails',async()=>{
 for(const law of ['Mean','PrivateOracle'] as const){const a=await finished(beliefCase(law)),b=await finished(beliefCase(law,'MissingSelf')),c=await finished(beliefCase(law,'Blind',1)),d=await finished(beliefCase(law,'Blind',6));expect(key(decode(a.observerView('observer-a')))===key(decode(b.observerView('observer-a')))).toBe(law==='Mean');expect(key(decode(c.observerView('observer-a')))===key(decode(d.observerView('observer-a')))).toBe(law==='Mean');}
},600000);
it('goal-only intervention preserves all states and changes next50 appraisal',async()=>{const a=beliefRows(outputs(await finished())),b=beliefRows(outputs(await finished(beliefCase('Mean','GoalFlip'))));expect(a.map(r=>r.states)).toEqual(b.map(r=>r.states));expect(a[4].appraisals[0].adverse).toBe('1/4');expect(b[4].appraisals[0].adverse).toBe('3/4');expect(a.slice(0,4)).toEqual(b.slice(0,4));},600000);
it('failed execution preserves all three complete holder views',async()=>{const a=await finished(),b=await finished(beliefCase('Mean','FailedExecution'));HOLDERS.forEach(h=>expect(a.observerView(h)).toEqual(b.observerView(h)));expect(a.snapshot().state).not.toEqual(b.snapshot().state);},600000);
it('independent mutation authority rejects every foreign holder write',async()=>{const s=await nativeRuntime();for(const h of [1,2,3])for(const other of [1,2,3].filter(x=>x!==h)){const p=path('Task',1447,h),prior=s.input.state.read(p).value!;expect(()=>applyStatePatch(s.input.state,{operations:[{kind:'set',path:p,expected:{presence:true,value:prior},newValue:prior}]},owner('Task','learn'+other),s.model.authority)).toThrow();}const p=path('Task',1447,1),prior=s.input.state.read(p).value!;expect(()=>applyStatePatch(s.input.state,{operations:[{kind:'set',path:p,expected:{presence:true,value:prior},newValue:prior}]},owner('Task','identity'),s.model.authority)).toThrow();},600000);
it('foreign holder, target, proposition and nonintegral polarity are not evidence',()=>{const e=evidenceValue({holder:'self',target:'target',proposition:'positive-task-fidelity',ticket:1,polarity:1});expect(()=>evidence(e,2)).toThrow();for(const [field,v]of [[2n,actor('Biological')],[3n,{kind:'text',value:'other'}],[5n,q(1,2)]] as const){const fs=new Map(e.fields);fs.set(field,v);expect(()=>evidence(record(e.schema,fs),1)).toThrow();}},600000);
it('closed public handles, source registries, input roles, seeds and initial states reject',async()=>{const c=beliefCase(),h=await prepareIdentityBeliefModel(c.source);await expect(createIdentityBeliefPublicRun({} as any,publicInput(c))).rejects.toThrow();await expect(prepareIdentityBeliefModel({...c.source,registry:enc(list([]))})).rejects.toThrow();await expect(createIdentityBeliefPublicRun(h,{...publicInput(c),runSeed:new Uint8Array(32).fill(8)})).rejects.toThrow();await expect(createIdentityBeliefPublicRun(h,{...publicInput(c),initialState:enc(r(1446,[u(1),list([]),list([]),u(0)]))})).rejects.toThrow();const xs=items(decode(c.orderedInputs),'list'),x=rec(xs[0],1444n),fs=new Map(x.fields);fs.set(2n,list([u(2),u(1),u(1)]));await expect(createIdentityBeliefPublicRun(h,{...publicInput(c),orderedInputs:enc(list([record(x.schema,fs),...xs.slice(1)]))})).rejects.toThrow();expect(()=>h && r(1445,[u(1),f(rec(f(rec(xs[0],1444n),1n),1428n),2n),{kind:'text',value:'wrong'},u(1),q(1,1)])).toThrow();},600000);
it('complete native save restores exactly and rejects changed law/input/tampered trace',async()=>{const c=beliefCase(),run=await nativeRun(c);await run.settleNextInstant();const save=run.save();await run.settleNextInstant();const restored=await restoreIdentityBeliefPublicRun(c.source,restoreInput(c,save));await restored.settleNextInstant();expect(restored.save()).toEqual(run.save());await expect(restoreIdentityBeliefPublicRun(beliefRecipe('Latest'),restoreInput(c,save))).rejects.toThrow();await expect(restoreIdentityBeliefPublicRun(c.source,restoreInput(beliefCase('Mean','MissingSelf'),save))).rejects.toThrow();const v=rec(decode(save),132n),fs=new Map(v.fields);fs.set(11n,list([]));await expect(restoreIdentityBeliefPublicRun(c.source,restoreInput(c,enc(record(v.schema,fs))))).rejects.toThrow();},600000);
for(const stage of [...stages.map(([n])=>n),'commit'])it('atomic rollback at '+stage,async()=>{const s=await nativeRuntime(),before=s.runtime.snapshot(),project=(v:typeof before)=>({...v,status:undefined,state:enc(v.state.canonicalValue())});let reached=false;await expect(s.runtime.settleForConformance({onBoundary(b,e){if(stage==='commit'?b==='before-commit':b==='after-trace-validation'&&e&&key(e.eventTypeId)===key(eventId('Task',stage))){reached=true;throw Error('injected');}}})).rejects.toThrow();expect(reached).toBe(true);expect(project(s.runtime.snapshot())).toEqual(project(before));},600000);
it('caller byte mutation cannot change admitted inputs or disclose other views',async()=>{const c=beliefCase(),a=await nativeRun(c),b=await nativeRun();c.orderedInputs.fill(0);c.runSeed.fill(7);c.source.parameters.fill(0);await a.settleNextInstant();await b.settleNextInstant();expect(a.save()).toEqual(b.save());expect(()=>a.observerView('foreign' as any)).toThrow();const bytes=a.snapshot().state;bytes.fill(0);expect(a.snapshot().state).not.toEqual(bytes);},600000);

it('native learning read domains keep lawful holders separate and declare negative access',async()=>{for(const law of ['Mean','StandingAlias','PrivateOracle'] as const){const s=await nativeRuntime(beliefCase(law));await s.runtime.settle();const traces=s.runtime.snapshot().trace.map(v=>rec(v,160n));for(const h of [1,2,3]){const t=traces.find(t=>key(f(rec(f(t,4n),130n),5n))===key(eventId('Task','learn'+h)));if(!t)throw Error('missing learning trace');const count=items(f(t,10n),'list').length;expect(count).toBe(law==='StandingAlias'&&h===1||law==='PrivateOracle'&&h!==1?2:1);}}},600000);

it('validation memo never admits changed invalid source or foreign belief owner',async()=>{const s=await nativeRuntime();s.model.validateState(s.input.state);const entries=s.input.state.entries(),changed=new AuthoritativeState(entries.map(e=>e.path.rootStateTypeId===1441n?{...e,value:r(1446,[u(1),list([]),list([]),u(0)])}:e));expect(()=>s.model.validateState(changed)).toThrow();const other=new AuthoritativeState(entries.map(e=>e.path.rootStateTypeId===1447n?{...e,value:r(1446,[u(3),list([]),list([]),u(0)])}:e));expect(()=>s.model.validateState(other)).toThrow();s.model.validateState(s.input.state);},600000);
