import {it,expect} from 'vitest';
import {canonicalEncode as enc,record,list,unsigned as u,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key} from '../campaign2/canonicalData';
import {longitudinalRecipe,compileLongitudinalModel,compileLongitudinalInputs,OBSERVER,path,eventId} from '../campaign3/longitudinalModel';
import {createLongitudinalRuntime} from '../campaign3/longitudinalRuntime';
import {decodeLongitudinal as decode,longitudinalRecord as r} from '../campaign3/longitudinalCodecs';
import {longitudinalInputs,longitudinalScenario} from './longitudinalFixtures';
async function setup(){const model=await compileLongitudinalModel(longitudinalRecipe()),input=await compileLongitudinalInputs(model,enc(model.initial.canonicalValue()),longitudinalInputs(longitudinalScenario()),new Uint8Array(32));return {model,runtime:createLongitudinalRuntime(model,input)};}
it('closed current view contains no truth, archived histories, outputs, saves or protocol records',async()=>{const {runtime}=await setup();for(let i=0;i<9;i++)await runtime.settle();const v=decode(runtime.view(OBSERVER)),types=new Set<bigint>();function walk(x:CanonicalValue){if(typeof x==='boolean')return;if(x.kind==='record'){types.add(x.schema.typeId);[...x.fields.values()].forEach(walk);}else if(x.kind==='list'||x.kind==='set')x.items.forEach(walk);else if(x.kind==='map')x.entries.forEach(([k,v])=>{walk(k);walk(v);});}walk(v);expect([...types].every(t=>[881n,784n,851n,866n,865n,869n].includes(t))).toBe(true);expect(items(f(rec(f(rec(v,881n),5n),866n),1n),'list')).toHaveLength(0);const state=runtime.snapshot().state;expect(state.read(path(873)).presence).toBe(false);expect(state.entries().map(e=>e.path.rootStateTypeId).sort()).toEqual([867n,868n,870n,871n,872n]);},120000);
it('closed grammar rejects wrong union members, occurrence families and unknown fields',()=>{const episode=r(865,[typedIdentifier(1157,u(0)),{kind:'signed',value:1n},u(3),true]),wrong=new Map(episode.fields);wrong.set(1n,typedIdentifier(1156,u(0)));expect(()=>decode(enc(record(episode.schema,wrong)))).toThrow();const journal=r(866,[list([episode])]);expect(()=>r(874,[u(1),list([journal])])).toThrow();const fields=new Map(episode.fields);fields.set(99n,false);expect(()=>decode(enc(record(episode.schema,fields)))).toThrow();});
it('rollback covers actual identity/RNG change and actual episode deletion at commit',async()=>{for(const prefix of [1,8]){const {runtime}=await setup();for(let i=0;i<prefix;i++)await runtime.settle();const before=runtime.snapshot(),view=runtime.view(OBSERVER);let reached=false;await expect(runtime.settleForConformance({onBoundary(b){if(b==='before-commit'){reached=true;throw Error('longitudinal loss/identity commit fault');}}})).rejects.toThrow();expect(reached).toBe(true);const after=runtime.snapshot();expect(enc(after.state.canonicalValue())).toEqual(enc(before.state.canonicalValue()));for(const k of ['queue','allocators','outputs','trace']as const)expect(after[k]).toEqual(before[k]);expect(runtime.view(OBSERVER)).toEqual(view);}},180000);
