import {describe,it,expect} from 'vitest';
import {createMarkerTracker,applyMarkerSweep,markerTrackingSnapshot,type MarkerSweep,type MarkerTracker} from '../campaign3/observedMarkerTracking';
const sweep=(step:number,glyphs:readonly (number|undefined)[],observerId='observer/a'):MarkerSweep=>({observerId,observationId:BigInt(step*10),occurredAt:BigInt(step),detections:glyphs.map((glyph,i)=>({detectionId:BigInt(step*10+i+1),...(glyph===undefined?{}:{glyph:BigInt(glyph)})}))});
describe('observed-marker-tracking/0.1-candidate',()=>{
 it('OMT-A: unique observed markers continue actual SEM files with both supporting observations',()=>{const t=createMarkerTracker('observer/a'),a=applyMarkerSweep(t,sweep(1,[2,4])),b=applyMarkerSweep(t,sweep(2,[4,2]));expect(b.map(x=>x.perceptualReferentId)).toEqual([a[1].perceptualReferentId,a[0].perceptualReferentId]);expect(b.map(x=>x.continuityKind)).toEqual(['ContinuesPriorTrack','ContinuesPriorTrack']);expect(b[0].supportingObservationIds.map(x=>x.observationId)).toEqual([10n,20n]);expect(markerTrackingSnapshot(t).state.nextTrackSequenceByObserver.get('observer/a')).toBe(2n);});
 it('OMT-B: changing hidden physical owners of the same visible markers cannot correct false tracking',()=>{const execute=(owners:string[])=>{const t=createMarkerTracker('observer/a'),a=applyMarkerSweep(t,sweep(1,[2,4]));const world=owners.map((truthOwner,i)=>({truthOwner,glyph:[2,4][i]}));const b=applyMarkerSweep(t,sweep(2,world.map(x=>x.glyph)));return {a,b};};const stable=execute(['object/a','object/b']),swapped=execute(['object/b','object/a']);expect(swapped).toEqual(stable);expect(swapped.b[0].perceptualReferentId).toEqual(swapped.a[0].perceptualReferentId);});
 it('OMT-C: current or previous collisions never merge two detections',()=>{const t=createMarkerTracker('observer/a');applyMarkerSweep(t,sweep(1,[1]));const many=applyMarkerSweep(t,sweep(2,[1,1]));expect(many.map(x=>x.continuityKind)).toEqual(['NewTrack','NewTrack']);expect(new Set(many.map(x=>x.perceptualReferentId.observerTrackSequence)).size).toBe(2);expect(applyMarkerSweep(t,sweep(3,[1]))[0].continuityKind).toBe('NewTrack');});
 it('OMT-D: missing glyph and empty intervening sweep do not imply continuity or retirement',()=>{const t=createMarkerTracker('observer/a');applyMarkerSweep(t,sweep(1,[1]));expect(applyMarkerSweep(t,sweep(2,[undefined]))[0].continuityKind).toBe('NewTrack');applyMarkerSweep(t,sweep(3,[]));expect(applyMarkerSweep(t,sweep(4,[1]))[0].continuityKind).toBe('NewTrack');expect(markerTrackingSnapshot(t).state.activePerceptualReferentIds).toHaveLength(3);});
 it('OMT-E: observer scope is explicit even for equal marker and ordinal values',()=>{const a=createMarkerTracker('observer/a'),b=createMarkerTracker('observer/b');const x=applyMarkerSweep(a,sweep(1,[0]))[0],y=applyMarkerSweep(b,sweep(1,[0],'observer/b'))[0];expect(x.perceptualReferentId.observerTrackSequence).toBe(y.perceptualReferentId.observerTrackSequence);expect(x.perceptualReferentId).not.toEqual(y.perceptualReferentId);expect(()=>applyMarkerSweep(a,sweep(2,[0],'observer/b'))).toThrow();});
 it('OMT-F: large source-ordinal offsets change no marker matching decisions',()=>{const run=(offset:bigint)=>{const t=createMarkerTracker('observer/a');return [sweep(1,[7,1]),sweep(2,[1,7])].flatMap(s=>applyMarkerSweep(t,{...s,observationId:s.observationId+offset,detections:s.detections.map(d=>({...d,detectionId:d.detectionId+offset}))})).map(x=>({file:x.perceptualReferentId,kind:x.continuityKind}));};expect(run(99999n)).toEqual(run(0n));});
 it('OMT-G: malformed, replayed, forged and executable inputs cannot partially advance state',()=>{const t=createMarkerTracker('observer/a');const original=sweep(1,[1]);const output=applyMarkerSweep(t,original),before=markerTrackingSnapshot(t);for(const bad of [original,{...sweep(2,[1]),truthHandle:1},{...sweep(2,[1,9])},{...sweep(2,[1]),occurredAt:1n},{...sweep(2,[1]),detections:[{detectionId:10n,glyph:1n}]}]){expect(()=>applyMarkerSweep(t,bad)).toThrow();expect(markerTrackingSnapshot(t)).toEqual(before);}let invoked=false;const data=sweep(2,[1]);Object.defineProperty(data,'detections',{get(){invoked=true;return [];}});expect(()=>applyMarkerSweep(t,data)).toThrow();expect(invoked).toBe(false);expect(()=>applyMarkerSweep({} as MarkerTracker,sweep(2,[1]))).toThrow();(output[0].perceptualReferentId as {observerTrackSequence:bigint}).observerTrackSequence=999n;expect(markerTrackingSnapshot(t)).toEqual(before);});
 it('OMT-H: finite horizon and monotonically allocated files with no reuse',()=>{const t=createMarkerTracker('observer/a');for(let s=0;s<8;s++)applyMarkerSweep(t,sweep(s,Array.from({length:8},()=>undefined)));const before=markerTrackingSnapshot(t);expect(before.state.nextTrackSequenceByObserver.get('observer/a')).toBe(64n);expect(()=>applyMarkerSweep(t,sweep(8,[0]))).toThrow();expect(markerTrackingSnapshot(t)).toEqual(before);});
});
