import {describe,it,expect} from 'vitest';
import {selectRecallPartitions as select} from '../campaign3/recallPartitions';
describe('independent ranked recall partitions',()=>{
 it('RP-A: both kinds experience actual slot contention',()=>{expect(select({EventContinuant:[3n,1n,2n],Interoceptive:[6n,4n,5n]},{EventContinuant:1,Interoceptive:2})).toEqual({EventContinuant:[3n],Interoceptive:[6n,4n]});});
 it('RP-B: extra opposite-kind competitors cannot displace fixed results',()=>{const slots={EventContinuant:1,Interoceptive:1};const baseline=select({EventContinuant:[1n,2n],Interoceptive:[3n,4n]},slots);expect(select({EventContinuant:[9n,1n,2n],Interoceptive:[3n,4n]},slots).Interoceptive).toEqual(baseline.Interoceptive);expect(select({EventContinuant:[1n,2n],Interoceptive:[9n,3n,4n]},slots).EventContinuant).toEqual(baseline.EventContinuant);});
 it('RP-C: empty or unused opposite-kind slots are never borrowed',()=>{expect(select({EventContinuant:[],Interoceptive:[1n,2n,3n]},{EventContinuant:3,Interoceptive:1})).toEqual({EventContinuant:[],Interoceptive:[1n]});expect(select({EventContinuant:[1n,2n],Interoceptive:[]},{EventContinuant:0,Interoceptive:3})).toEqual({EventContinuant:[],Interoceptive:[]});});
 it('RP-D: supplied within-kind order is preserved, not replaced by identity order',()=>{expect(select({EventContinuant:[90n,1n],Interoceptive:[5n]},{EventContinuant:2,Interoceptive:1}).EventContinuant).toEqual([90n,1n]);});
 it('RP-E: duplicates within or across acquisition kinds and invalid limits reject',()=>{for(const ranked of [{EventContinuant:[1n,1n],Interoceptive:[]},{EventContinuant:[1n],Interoceptive:[1n]}])expect(()=>select(ranked,{EventContinuant:1,Interoceptive:1})).toThrow('RECALL_PARTITION_IDENTITY');expect(()=>select({EventContinuant:[],Interoceptive:[]},{EventContinuant:33,Interoceptive:1})).toThrow('RECALL_PARTITION_SLOTS');});
 it('RP-F: result has separate typed partitions, is detached and cannot feed scores across them',()=>{const ranked={EventContinuant:[1n],Interoceptive:[2n]},result=select(ranked,{EventContinuant:1,Interoceptive:1});ranked.Interoceptive[0]=3n;expect(result.Interoceptive).toEqual([2n]);expect(Object.isFrozen(result.EventContinuant)).toBe(true);expect(Object.keys(result).sort()).toEqual(['EventContinuant','Interoceptive']);});
});
