import {it,expect} from 'vitest';
import {createSubstitutionRun,restoreSubstitutionRun,OPTIONS,type Law} from '../campaign3/dependenceSubstitutes';
import {reinforcementCases} from './reinforcementFixtures';
import {decodeReceiving} from '../campaign3/receivingCodecs';
import {chosenData} from '../campaign2/cognitiveChoice';
import {dataField as f,dataItems as items,dataRecord as rec,dataKey as key} from '../campaign2/canonicalData';
import {readQ} from '../campaign2/cognitiveMath';
const cases=reinforcementCases();
async function run(name:keyof typeof cases='full',seed=2,law:Law='MeanHistory'){const r=createSubstitutionRun(law,cases[name],seed);while(await r.step()){}return r;}
function probability(hex:string,option:number){const resolution=decodeReceiving(Uint8Array.from(hex.match(/../g)!.map(x=>parseInt(x,16))));const row=items(f(chosenData(resolution),2n),'list').find(v=>key(f(rec(v,421n),1n))===key(OPTIONS[option]))!;return readQ(f(rec(row,421n),2n));}
it('acquired feedback changes next reason probability before further self-selected outcomes',async()=>{const a=(await run()).snapshot(),b=(await run('withheld')).snapshot();expect(a.rows[3].beliefBefore).toEqual(['1/2','1/2']);expect(a.rows[3].resolution).toBe(b.rows[3].resolution);expect(a.rows[3].expression).toBe(b.rows[3].expression);expect(a.rows[3].intent).toBe(0);expect(a.rows[4].beliefBefore[0]).toBe('2/3');expect(probability(a.rows[4].resolution,0).compare(probability(b.rows[4].resolution,0))).toBeGreaterThan(0);expect(a.rows.slice(3).map(r=>r.intent)).toEqual([0,0,0,0,0]);expect(b.rows.slice(3).map(r=>r.intent)).toEqual([0,1,0,0,0]);expect(a.physical).toEqual([6,1]);expect(b.physical).toEqual([5,2]);});
it('complete seed cohort retains both divergence and behavioral equality',async()=>{const changed:number[]=[];for(let seed=0;seed<8;seed++){const a=(await run('full',seed)).snapshot(),b=(await run('withheld',seed)).snapshot();expect(a.rows[3].resolution).toBe(b.rows[3].resolution);expect(b.rows.slice(3).every(r=>r.beliefBefore.join(',')==='1/2,1/2')).toBe(true);if(a.rows.map(r=>r.intent).join(',')!==b.rows.map(r=>r.intent).join(','))changed.push(seed);}expect(changed).toEqual([2,3,4,5,6,7]);},30000);
it('learning affects belief evidence and history through chosen actions, not every opportunity',async()=>{const a=(await run()).snapshot(),b=(await run('withheld')).snapshot();expect(a.belief.map(x=>x.length)).toEqual([7,2]);expect(b.belief.map(x=>x.length)).toEqual([2,2]);expect(a.journal).toHaveLength(7);expect(b.journal).toHaveLength(2);expect(a.rows[7].beliefBefore).toEqual(['5/6','1/2']);});
it('latest report remains a non-accumulating serious comparator',async()=>{const a=(await run('full',2,'LatestHistory')).snapshot(),b=(await run('withheld',2,'LatestHistory')).snapshot();expect(a.rows.slice(3).map(r=>r.intent)).toEqual(b.rows.slice(3).map(r=>r.intent));expect(a.rows.slice(3).every(r=>r.beliefBefore.join(',')==='1/1,1/1')).toBe(true);});
it('no demand, no access or unobserved training prevents the proposed learned loop',async()=>{for(const name of ['noDemand','unavailable','unseenTraining'] as const){const s=(await run(name)).snapshot();expect(s.rows.slice(3).every(r=>r.intent===-1)).toBe(true);}expect((await run('full',2,'NoLearning')).snapshot().belief).toEqual([[],[]]);});
it('visible failure depresses expectation without changing the prior intent',async()=>{const a=(await run()).snapshot(),b=(await run('failure')).snapshot();expect(a.rows[3].expression).toBe(b.rows[3].expression);expect(b.rows[4].beliefBefore[0]).toBe('1/3');});
it('false and missing feedback preserve whole safe views under hidden delivery changes',async()=>{for(const [a,b] of [['falseSuccess','trueSuccess'],['withheld','hiddenFailure']] as const)expect((await run(a)).observerView()).toEqual((await run(b)).observerView());});
it('new feedback fixture restores every prefix and next transition',async()=>{const r=createSubstitutionRun('MeanHistory',cases.full,2),saves=[r.save()];while(await r.step())saves.push(r.save());for(let i=0;i<9;i++){const restored=await restoreSubstitutionRun('MeanHistory',cases.full,saves[i],2);expect(restored.save()).toEqual(saves[i]);expect(await restored.step()).toBe(i<8);expect(restored.save()).toEqual(saves[Math.min(i+1,8)]);}},30000);
