import {describe,it,expect} from 'vitest';
import {ExactRational as Q} from '../substrate/exactMath';
import {assessContrastiveAttribution,type AttributionTrial} from '../campaign3/contrastiveAttribution';
import {prepareRetainedAttributionUse as prepare,type UseTrial,type AttributionField,type AttributionUseResult} from '../campaign3/retainedAttributionUse';
import {retainWithUseProtection,type UseProtectedAcquisition} from '../campaign3/useProtectedRetention';
import {retainByRecency} from '../campaign3/recencyRetention';
const interval={lower:Q.of(20n),upper:Q.of(21n)};
const rows=():AttributionTrial[]=>[true,false,true,false].map(stroke=>({motion:[[0,0],[stroke?1:0,0]],before:interval,after:stroke?{lower:Q.of(30n),upper:Q.of(31n)}:interval}));
const bindings=(rs=rows()):{-readonly [K in keyof UseTrial]:UseTrial[K]}[]=>rs.map(t=>({motion:{kind:'Detached',value:t.motion},before:{kind:'Detached',value:t.before},after:{kind:'Detached',value:t.after}}));
const memory=():UseProtectedAcquisition[]=>[{id:1n,kind:'Interoceptive',acquiredAt:1n,units:[{key:'alpha',views:[new Uint8Array([20,21])],useProtection:false},{key:'sibling',views:[new Uint8Array([20,21])],useProtection:false}]},{id:2n,kind:'Interoceptive',acquiredAt:2n,units:[{key:'beta',views:[new Uint8Array([20,21])],useProtection:false}]}];
const alpha={acquisition:1n,unit:'alpha'},beta={acquisition:2n,unit:'beta'};
// Trusted fixture projection. No public observation schema/role is asserted.
const project=<K extends AttributionField>(bytes:Uint8Array,field:K):AttributionTrial[K]=>{if(field==='motion')throw Error('fixture interval only');return {lower:Q.of(BigInt(bytes[0])),upper:Q.of(BigInt(bytes[1]))} as AttributionTrial[K];};
const setup=(trials=bindings(),mem=memory())=>prepare({memory:mem,now:3n,admitted:[alpha,beta],trials},project);
const referenced=()=>{const b=bindings();b[0].before={kind:'Retained',address:alpha,view:0};return b;};
describe('retained attribution semantic use',()=>{
 it('RU-A: actual retained operand changes later survivor, detached equal operand does not',()=>{const used=setup(referenced()),external=setup();const a=used.finish(used.evaluate()),b=external.finish(external.evaluate());expect(a.assessment).toEqual(b.assessment);expect(a.assessment.kind).toBe('Supported');expect(a.consumed).toEqual([alpha]);expect(b.consumed).toEqual([]);const cap={EventContinuant:0,Interoceptive:1};expect(retainWithUseProtection(a.memory,4n,cap).acquisitions[0].id).toBe(1n);expect(retainWithUseProtection(b.memory,4n,cap).acquisitions[0].id).toBe(2n);expect(retainByRecency(a.memory,4n,cap).acquisitions[0].id).toBe(2n);});
 it('RU-B: early unavailable credits read alpha, not merely bound beta or sibling',()=>{const b=referenced();b[0].after={kind:'Detached',value:null};b[1].before={kind:'Retained',address:beta,view:0};const s=setup(b),r=s.finish(s.evaluate());expect(r.assessment.kind).toBe('Unavailable');expect(r.consumed).toEqual([alpha]);expect(r.memory[0].units.map(u=>u.useProtection)).toEqual([true,false]);expect(r.memory[1].units[0].useProtection).toBe(false);});
 it('RU-C: evaluation alone and close produce no protection; tokens are session-local and one-shot',()=>{const m=memory(),s=setup(referenced(),m),other=setup(referenced()),token=s.evaluate();expect(m.every(a=>a.units.every(u=>!u.useProtection))).toBe(true);expect(()=>other.finish(token)).toThrow('BINDING');expect(()=>s.finish({...token})).toThrow('BINDING');s.finish(token);expect(()=>s.finish(token)).toThrow();const closed=setup(referenced()),t=closed.evaluate();closed.close();expect(()=>closed.finish(t)).toThrow('CLOSED');expect(()=>setup().finish({opaque:'attribution-use-result'} as AttributionUseResult)).toThrow();});
 it('RU-D: read domain, missing view, missing child and same-instant formation reject',()=>{expect(()=>prepare({memory:memory(),now:3n,admitted:[],trials:referenced()},project)).toThrow('READ_DOMAIN');const b=referenced();b[0].before={kind:'Retained',address:alpha,view:1};expect(()=>setup(b)).toThrow('VIEW');const m=memory();m[0]={...m[0],acquiredAt:3n};expect(()=>setup(referenced(),m)).toThrow('PRIOR_MEMORY');expect(()=>setup(referenced(),memory().slice(1))).toThrow();});
 it('RU-E: an earlier missing motion prevents consumption of a bound retained interval',()=>{const b=referenced();b[0].motion={kind:'Detached',value:null};const s=setup(b),r=s.finish(s.evaluate());expect(r.assessment.kind).toBe('Unavailable');expect(r.consumed).toEqual([]);});
 it('RU-F: repeated semantic use of one child yields one address; inputs and bytes are detached',()=>{const b=referenced();b[1].before={kind:'Retained',address:alpha,view:0};const m=memory(),s=setup(b,m);m[0].units[0].views[0][0]=99;const r=s.finish(s.evaluate());expect(r.assessment.kind).toBe('Supported');expect(r.consumed).toEqual([alpha]);expect(r.memory[0].units[0].views[0][0]).toBe(20);});
 it('RU-G: successor preserves verdicts across missing and complete admissible evidence',()=>{for(let i=0;i<4;i++)for(const field of ['motion','before','after'] as const){const r=rows();r[i]={...r[i],[field]:null};const s=setup(bindings(r));expect(s.finish(s.evaluate()).assessment).toEqual(assessContrastiveAttribution(r));}for(const end of [0,1,2,7])for(const low of [0,20,22,30]){const r=rows();r[0]={...r[0],motion:[[0,0],[end,0]],after:{lower:Q.of(BigInt(low)),upper:Q.of(BigInt(low+1))}};const s=setup(bindings(r));expect(s.finish(s.evaluate()).assessment).toEqual(assessContrastiveAttribution(r));}});
 it('RU-H: malformed unread operands reject in validation without earning credit',()=>{const r=rows();r[0]={...r[0],motion:null};r[3]={...r[3],after:{lower:Q.of(50n),upper:Q.of(20n)}};expect(()=>setup(bindings(r))).toThrow('invalid attribution interval');});
 it('RU-I: detached rational objects cannot mutate the validated operation snapshot',()=>{const r=rows(),mutable={lower:Q.of(30n),upper:Q.of(31n)};r[0]={...r[0],after:mutable};const s=setup(bindings(r));Object.assign(mutable.lower,{numerator:0n});expect(s.finish(s.evaluate()).assessment.kind).toBe('Supported');});
});
