import {describe,it,expect} from 'vitest';
import {prepareSignificantFormationSettlement as prepare,type SignificantFormationInput} from '../campaign3/significantFormationSettlement';
import {prepareFormationSettlement} from '../campaign3/formationSettlement';
const fixture=():SignificantFormationInput=>({priorProtocol:{domain:[{source:'source/old',character:'character/a',kind:'EventContinuant'}],successes:[{source:'source/old',character:'character/a',kind:'EventContinuant',acquisition:1n,formedAt:1n,completeLoss:false}]},priorMemory:[{id:1n,kind:'EventContinuant',acquiredAt:1n,units:[{key:'old',views:[new Uint8Array([2,3])],useProtection:true,outcomeSignificanceDirections:['MovingCloser','MovingFarther']}]}],incoming:[{source:'source/new',character:'character/a',kind:'EventContinuant'}],formed:[{source:'source/new',character:'character/a',kind:'EventContinuant',acquisition:2n,formedAt:2n}],freshMemory:[{id:2n,kind:'EventContinuant',acquiredAt:2n,units:[{key:'new',views:[new Uint8Array([4,5])]}]}],now:2n,sourceLimit:3,capacity:{EventContinuant:1,Interoceptive:0}});
describe('significant formation owner/protocol settlement',()=>{
 it('SF-FORM-A: old significant child survives a fresh formation while recency control differs',()=>{const f=fixture(),tx=prepare(f),r=tx.finish(tx.resolveMemory());expect(r.memory).toEqual(f.priorMemory);expect(r.protocol.successes.map(x=>[x.acquisition,x.completeLoss])).toEqual([[1n,false],[2n,true]]);const old=prepareFormationSettlement(f);expect(old.finish(old.resolveMemory()).memory[0].id).toBe(2n);});
 it('SF-FORM-B: later formation preserves all old bytes and metadata; fresh children start uncredited',()=>{const f={...fixture(),capacity:{EventContinuant:2,Interoceptive:0}},tx=prepare(f),r=tx.finish(tx.resolveMemory());expect(r.memory.find(a=>a.id===1n)).toEqual(f.priorMemory[0]);expect(r.memory.find(a=>a.id===2n)!.units[0]).toMatchObject({useProtection:false,outcomeSignificanceDirections:[]});expect(r.protocol.successes.every(s=>!s.completeLoss)).toBe(true);});
 it('SF-FORM-C: source-supplied credit fields cannot enter fresh memory',()=>{for(const extra of [{useProtection:true},{outcomeSignificanceDirections:['MovingCloser']}]){const f=fixture();Object.assign(f.freshMemory[0].units[0],extra);expect(()=>prepare(f)).toThrow('FRESH_CREDIT');}});
 it('SF-FORM-D: zero capacity keeps protocol success and records complete loss',()=>{const f={...fixture(),capacity:{EventContinuant:0,Interoceptive:0}},tx=prepare(f),r=tx.finish(tx.resolveMemory());expect(r.memory).toEqual([]);expect(r.protocol.successes).toHaveLength(2);expect(r.protocol.successes.every(s=>s.completeLoss)).toBe(true);});
 it('SF-FORM-E: input is detached and private result tokens are local and one-shot',()=>{const f=fixture(),tx=prepare(f),other=prepare(f);f.priorMemory[0].units[0].views[0][0]=99;const token=tx.resolveMemory();expect(()=>other.finish(token)).toThrow('RESULT_BINDING');expect(()=>tx.finish({...token})).toThrow('RESULT_BINDING');expect(tx.finish(token).memory[0].units[0].views[0][0]).toBe(2);expect(()=>tx.finish(token)).toThrow('RESULT_BINDING');other.close();expect(()=>other.resolveMemory()).toThrow('CLOSED');const bad=fixture();Object.assign(bad.priorMemory[0],{acquiredAt:0n});expect(()=>prepare(bad)).toThrow('PRIOR_BINDING');});
});
