import {describe,it,expect} from 'vitest';
import {retainSignificanceFirst as retain,retainSharedProtectionTier as shared} from '../campaign3/significanceFirstRetention';
import type {SignificantAcquisition,SignificanceDirection} from '../campaign3/directionalSignificanceState';
const a=(id:bigint,at:bigint,used=false,tags:SignificanceDirection[]=[],kind:'EventContinuant'|'Interoceptive'='EventContinuant'):SignificantAcquisition=>({id,acquiredAt:at,kind,units:[{key:'alpha',views:[new Uint8Array([42])],useProtection:used,outcomeSignificanceDirections:tags}]});
const cap={EventContinuant:1,Interoceptive:0};
describe('significance-first supplied-state retention policy',()=>{
 it('SF-A: significance outranks equal use, unlike the actual shared-tier comparator',()=>{const input=[a(1n,1n,true,['MovingCloser']),a(2n,8n,true)];expect(retain(input,9n,cap).acquisitions[0].id).toBe(1n);expect(shared(input,9n,cap).acquisitions[0].id).toBe(2n);});
 it('SF-B: significance protects independently; use still protects absent significance',()=>{expect(retain([a(1n,1n,false,['MovingFarther']),a(2n,8n)],9n,cap).acquisitions[0].id).toBe(1n);expect(retain([a(1n,1n,true),a(2n,8n)],9n,cap).acquisitions[0].id).toBe(1n);expect(retain([a(1n,1n),a(2n,8n)],9n,cap).acquisitions[0].id).toBe(2n);});
 it('SF-C: significance direction, cardinality and added use confer no bonus within tier',()=>{for(const tags of [['MovingCloser'],['MovingFarther'],['MovingCloser','MovingFarther']] as SignificanceDirection[][])for(const used of [false,true])expect(retain([a(1n,1n,used,tags),a(2n,8n,false,['MovingCloser'])],9n,cap).acquisitions[0].id).toBe(2n);});
 it('SF-D: zero capacity loses all and partitions never borrow',()=>{const input=[a(1n,1n,true,['MovingFarther']),a(2n,1n,true,['MovingCloser'],'Interoceptive')];expect(retain(input,9n,{EventContinuant:0,Interoceptive:0}).acquisitions).toEqual([]);const r=retain(input,9n,cap);expect(r.acquisitions.map(a=>a.id)).toEqual([1n]);expect(r.usage).toEqual({EventContinuant:1,Interoceptive:0});});
 it('SF-E: partial loss preserves survivor content, time and independent metadata',()=>{const input=[{...a(1n,1n,true,['MovingFarther']),units:[...a(1n,1n,true,['MovingFarther']).units,{key:'beta',views:[new Uint8Array([9])],useProtection:false,outcomeSignificanceDirections:[]}]}],before=structuredClone(input),result=retain(input,9n,cap);expect(result.losses).toEqual([{acquisition:1n,unit:'beta'}]);expect(result.acquisitions[0]).toEqual(a(1n,1n,true,['MovingFarther']));expect(input).toEqual(before);});
 it('SF-F: exact ties use canonical address and ignore input order',()=>{const input=[a(812n,1n),a(900n,1n)];expect(retain(input,9n,cap)).toEqual(retain([...input].reverse(),9n,cap));expect(retain(input,9n,cap).acquisitions[0].id).toBe(900n);});
 it('SF-G: fresh protected formation rejects; fresh unprotected formation is admitted',()=>{expect(()=>retain([a(1n,9n,true)],9n,cap)).toThrow('FRESH_PROTECTION');expect(()=>retain([a(1n,9n,false,['MovingCloser'])],9n,cap)).toThrow('FRESH_PROTECTION');expect(retain([a(1n,9n)],9n,cap).acquisitions).toHaveLength(1);});
 it('SF-H: survival does not refresh age and invalid capacity rejects',()=>{const input=[a(1n,1n,true,['MovingCloser'])],once=retain(input,9n,cap);expect(retain(once.acquisitions,10n,cap).acquisitions).toEqual(once.acquisitions);expect(()=>retain(input,9n,{...cap,EventContinuant:0.5})).toThrow('CAPACITY');});
});
