import {describe,it,expect} from 'vitest';
import {createNineSweepMarkerTracker,createTenSweepMarkerTracker,applyMarkerSweep,markerTrackingSnapshot} from '../campaign3/observedMarkerTracking';
import {createTenSweepMarkerTransactionManager as create,beginMarkerTransaction as begin,previewMarkerTransaction as preview,commitMarkerTransaction as commit,abortMarkerTransaction as abort,committedMarkerSnapshot as snapshot} from '../campaign3/transactionalMarkerTracking';
import {createNineFramePositionDisplaySource,createTenFramePositionDisplaySource,observePositionDisplay} from '../campaign3/positionDisplaySource';
const observer='observer/a',sweep=(i:number,count=1)=>({observerId:observer,observationId:BigInt(i*10),occurredAt:BigInt(i),detections:Array.from({length:count},(_,j)=>({detectionId:BigInt(i*10+j+1)}))});
describe('explicit tenth competing-acquisition source',()=>{
 it('N10-A: prior nine bound remains; successor admits tenth and rejects eleventh',()=>{const a=createNineSweepMarkerTracker(observer),b=createTenSweepMarkerTracker(observer);for(let i=1;i<=9;i++)expect(applyMarkerSweep(a,sweep(i))).toEqual(applyMarkerSweep(b,sweep(i)));expect(()=>applyMarkerSweep(a,sweep(10))).toThrow('horizon');expect(applyMarkerSweep(b,sweep(10))).toHaveLength(1);expect(()=>applyMarkerSweep(b,sweep(11))).toThrow('horizon');});
 it('N10-B: three detections per sweep bound the source at30 new files',()=>{const t=createTenSweepMarkerTracker(observer);expect(()=>applyMarkerSweep(t,sweep(1,4))).toThrow('bounded detections');for(let i=1;i<=10;i++)applyMarkerSweep(t,sweep(i,3));expect(markerTrackingSnapshot(t).state.nextTrackSequenceByObserver.get(observer)).toBe(30n);});
 it('N10-C: every prefix reconstructs; aborted tenth retries without a consumed identity',()=>{const history=Array.from({length:10},(_,i)=>sweep(i+1)),expected=snapshot(create(observer,history));for(let n=0;n<=10;n++){const m=create(observer,history.slice(0,n));for(const s of history.slice(n))commit(m,begin(m,s));expect(snapshot(m)).toEqual(expected);}const m=create(observer,history.slice(0,9)),prior=snapshot(m),p=begin(m,history[9]),proposed=preview(m,p);abort(m,p);expect(snapshot(m)).toEqual(prior);const q=begin(m,history[9]);expect(preview(m,q)).toEqual(proposed);commit(m,q);expect(()=>begin(m,sweep(11))).toThrow('horizon');});
 it('N10-D: explicit display successor preserves the old profile and tenth actual position',()=>{const frames=Array.from({length:10},(_,i)=>({at:BigInt(i+1),x:BigInt(i%8),y:0n,glyph:0n,visible:true,permitted:true}));expect(()=>createNineFramePositionDisplaySource(frames)).toThrow();expect(observePositionDisplay(createTenFramePositionDisplaySource(frames),10n)).toEqual({kind:'Present',at:10n,position:{x:1n,y:0n},glyph:0n});expect(()=>createTenFramePositionDisplaySource([...frames,{...frames[0],at:11n}])).toThrow();});
});
