import {describe,it,expect} from 'vitest';
import {applyQualifiedUnitUse as use,retainWithUseProtection as retain,type UseProtectedAcquisition} from '../campaign3/useProtectedRetention';
import {retainByRecency} from '../campaign3/recencyRetention';
import {recallBodyByAcquisitionRecency} from '../campaign3/bodyRecall';
const a=(id:bigint,at:bigint,keys=['alpha'],kind:'Interoceptive'|'EventContinuant'='Interoceptive'):UseProtectedAcquisition=>({id,acquiredAt:at,kind,units:keys.map(key=>({key,views:[new Uint8Array([42])],useProtection:false}))});
const cap={EventContinuant:0,Interoceptive:1};
describe('binary child-local use protection baseline',()=>{
 it('UP-A: old used unit beats new unused while recency-only makes the opposite prediction',()=>{const input=use([a(1n,1n),a(2n,8n)],[{acquisition:1n,unit:'alpha'}],9n);expect(retain(input,10n,cap).acquisitions[0].id).toBe(1n);expect(retainByRecency(input,10n,cap).acquisitions[0].id).toBe(2n);});
 it('UP-B: credit is child-local, repeats do not stack and original time/bytes do not change',()=>{const original=[a(1n,1n,['alpha','beta'])],once=use(original,[{acquisition:1n,unit:'alpha'}],2n),twice=use(once,[{acquisition:1n,unit:'alpha'}],3n);expect(twice).toEqual(once);expect(once[0].units.map(u=>u.useProtection)).toEqual([true,false]);expect(once[0].acquiredAt).toBe(1n);expect(once[0].units[0].views).toEqual(original[0].units[0].views);expect(original[0].units[0].useProtection).toBe(false);});
 it('UP-C: protected demand exceeds capacity and zero capacity still loses everything',()=>{const input=use([a(1n,1n),a(2n,8n)],[{acquisition:1n,unit:'alpha'},{acquisition:2n,unit:'alpha'}],9n);expect(retain(input,10n,cap).acquisitions[0].id).toBe(2n);expect(retain(input,10n,{...cap,Interoceptive:0}).acquisitions).toEqual([]);});
 it('UP-D: later receipt cannot rescue lost unit; new acquisition gets no inherited protection',()=>{const gone=retain(use([a(1n,1n)],[{acquisition:1n,unit:'alpha'}],2n),3n,{...cap,Interoceptive:0}).acquisitions;expect(()=>use(gone,[{acquisition:1n,unit:'alpha'}],4n)).toThrow();expect(a(2n,4n).units[0].useProtection).toBe(false);});
 it('UP-E: ordinary recall does not earn or refresh protection',()=>{const input=[a(1n,1n)];for(let i=2;i<8;i++)recallBodyByAcquisitionRecency(input,{kind:'Present',signals:['alpha']},BigInt(i),1);expect(input[0].units[0].useProtection).toBe(false);expect(input[0].acquiredAt).toBe(1n);});
 it('UP-F: no partition borrowing and protection does not change unit cost',()=>{const input=use([a(1n,1n),a(2n,2n,['event'],'EventContinuant')],[{acquisition:1n,unit:'alpha'},{acquisition:2n,unit:'event'}],3n);const result=retain(input,4n,{EventContinuant:1,Interoceptive:0});expect(result.acquisitions.map(a=>a.id)).toEqual([2n]);expect(result.usage).toEqual({EventContinuant:1,Interoceptive:0});});
 it('UP-G: exact ties preserve canonical child ordering and input order invariance',()=>{const input=[a(2n,1n),a(1n,1n)];expect(retain(input,2n,cap)).toEqual(retain([...input].reverse(),2n,cap));expect(retain(input,2n,cap).acquisitions[0].id).toBe(1n);});
 it('UP-H: forged addresses and invalid state bits/times reject',()=>{expect(()=>use([a(1n,1n)],[{acquisition:1n,unit:'missing'}],2n)).toThrow();expect(()=>retain([a(1n,3n)],2n,cap)).toThrow();const invalid={...a(1n,1n),units:[{key:'alpha',views:[new Uint8Array([42])],useProtection:1 as unknown as boolean}]};expect(()=>retain([invalid],2n,cap)).toThrow();});
});
