/** attention-public-integration/0.1-candidate: finite authoritative stage graph. */
import {canonicalEncode as enc,list,set,unsigned,signed,text,typedIdentifier,rational,type CanonicalValue,type TypedIdentifierValue} from '../substrate/canonicalEncoding';
import {AuthoritativeState,ContractReadProjection,statePathValue,type ActualReadRecord,type StatePatch,type StructuralMutationDiff} from '../substrate/state';
import {DeterministicScheduler,SchedulerContractError,type EventHandlerContext,type ScheduledEvent,type EventEmission,type ConformanceInstrumentation} from '../substrate/scheduler';
import {traceRecordValue} from '../substrate/trace';
import {createCanonicalSave,scheduledEventValue} from '../substrate/persistence';
import {dataField as f,dataRecord as rec,dataItems as items,dataIdentity as id,dataText as str,dataUnsigned as u,dataKey as key} from '../campaign2/canonicalData';
import {decodeStatePattern} from '../campaign2/stateModel';
import {materializeEventBindings,finiteMax,type EventRoleId,type EventRoleEvidence,type EventBinding} from '../semanticBinding/eventBindings';
import {emptyPerceptualContinuantFileState,applyPerceptualTrackTransition} from '../semanticBinding/perceptualContinuantFiles';
import {emptyPerceptualEventFileState,applyPerceptualEventTransition,compilePerceivedBindings,type PerceivedBindingRequest,type PerceivedBindingEvidence,type PreRecognitionSemanticExperience} from '../semanticBinding/perceptualEventFiles';
import {admitObservationLane,freezeAndStageSemanticExperience,validateSuccessfulExperienceSettlement,type ExperienceReservation,type StagedSemanticExperience} from '../semanticBinding/phaseOrdering';
import {perceptualStateEntries} from '../semanticBinding/semanticStateAuthority';
import {perceptualTrackTransitionValue,semanticRecordValue,observerIdValue,currentDetectionIdValue,currentEventDetectionIdValue,perceptualEventReferentIdValue,perceptualReferentIdValue,supportingObservationIdValue} from '../semanticBinding/semanticCodecs';
import {worldEventTruthValue,eventRoleEvidenceValue,perceivedBindingEvidenceValue,preRecognitionSemanticExperienceValue,causalRoleEvidenceValue,characterEvidenceRefValue} from '../semanticBinding/semanticEvidenceCodecs';
import {compileCausalRoleModel,INITIAL_CAUSAL_ROLE_RULE,deriveCausalRoleEvidence,characterEvidenceRefKey,type CausalRoleEvidence,type ObserverSafeEvidenceOccurrence,type CharacterEvidenceRef} from '../semanticBinding/evidenceProvenance';
import {prepareAttentionPool,selectAttention,selectEqualPriorityControl,selectUnlimitedAttentionControl,selectedReferences,consumeSelected,closeSelectedView,type SelectedView} from './attentionSelection';
import {attentionRecord as r,attentionRawRecord as raw,decodeAttention as decode} from './attentionCodecs';
import type {AttentionCompiledModel} from './attentionModel';
import type {AttentionInputs} from './attentionInputs';
import {validateAttentionTrace} from './attentionTrace';
const VERSION='attention-public-integration/0.1-candidate',A='semantic-binding/0.1-candidate#SEM-001A',C='semantic-binding/0.1-candidate#SEM-001C',G='semantic-binding/0.1-candidate#SEM-001G',H='semantic-binding/0.1-candidate#SEM-001H';
const ID=(ns:number,p:string)=>typedIdentifier(ns,text(p)),occ=(ns:number,n:bigint)=>typedIdentifier(ns,unsigned(n)),O=observerIdValue('observer/attention-subject'),observer='observer/attention-subject';
const fail=(why:string):never=>{throw new SchedulerContractError('TRANSITION_OUTPUT_VIOLATION',why);};
const unitKey=(b:PerceivedBindingEvidence)=>key(list([perceptualEventReferentIdValue(b.perceptualEventReferentId),perceptualReferentIdValue(b.perceptualReferentId)]));
export function createAttentionRuntime(model:AttentionCompiledModel,input:AttentionInputs,initial:AuthoritativeState){
 const stages=new Map(Array.from({length:10},(_,i)=>[i+1,rec(model.stage(i+1),541n)])),byEvent=new Map([...stages].map(([n,r])=>[key(f(r,4n)),n]));
 const policy=rec(model.definition('definition/attention-policy'),519n),channel=rec(model.definition('definition/attention-channel'),518n),modes=items(f(channel,2n),'list').map(u),eventSchema=rec(model.definition('definition/attention-event-schema'),248n);
 let live=false,expected=new Map<bigint,string>(),completed=new Set<number>(),reservation:ExperienceReservation|undefined,staged:StagedSemanticExperience|undefined,view:SelectedView|undefined;
 let truth:readonly EventBinding[]=[],observation:CanonicalValue|undefined,eventTransition:CanonicalValue|undefined,requests:PerceivedBindingRequest[]=[],bindings:readonly PerceivedBindingEvidence[]=[],experience:PreRecognitionSemanticExperience|undefined,claims:CausalRoleEvidence[]=[],selection:CanonicalValue|undefined;
 let detections:{ordinal:bigint;role:EventRoleEvidence}[]=[],eventDetection=0n,observationId=0n,selectedCanonical:CanonicalValue|undefined;
 function reset(){live=true;expected=new Map([[0n,key(scheduledEventValue(input.event))]]);completed=new Set();reservation=undefined;staged=undefined;truth=[];observation=undefined;eventTransition=undefined;requests=[];bindings=[];experience=undefined;claims=[];selection=undefined;detections=[];selectedCanonical=undefined;}
 function handler(ctx:EventHandlerContext<AuthoritativeState>){
  const {event,state}=ctx,n=byEvent.get(key(event.eventTypeId));if(!live||n===undefined||expected.get(event.eventId)!==key(scheduledEventValue(event))||completed.has(n))throw new SchedulerContractError('INPUT_NOT_ADMITTED','actual unconsumed parent-bound attention event required');expected.delete(event.eventId);
  const reg=stages.get(n)!,at=event.dueAt,allocated:bigint[]=[],allocate=()=>{const value=ctx.allocateRuntimeId();allocated.push(value);return value;};
  let nextState=state,outputs:CanonicalValue[]=[],patch:StatePatch={operations:[]},diffs:readonly StructuralMutationDiff[]=[],reads:ActualReadRecord[]=[],sources:TypedIdentifierValue[]=[],child:{stage:number;payload:CanonicalValue}|undefined;
  const emit=(stage:number,payload:CanonicalValue)=>{child={stage,payload};};
  if(n===1){const scene=rec(input.scene,516n),refs=items(f(scene,1n),'list'),roles=items(f(scene,2n),'list');const world=allocate();truth=materializeEventBindings({eventTypeId:str(id(f(eventSchema,1n)).payload),roleCardinalityRules:items(f(eventSchema,2n),'list').map(v=>({eventRoleId:str(id(f(rec(v,246n),1n)).payload) as EventRoleId,minOccurrences:0,maxOccurrences:finiteMax(3)})),bindingSchemaVersion:VERSION},refs.map((ref,i)=>({eventRoleId:str(id(roles[i]).payload) as EventRoleId,semanticReferent:{semanticReferentId:key(ref),domainTags:['entity','usable-entity']}})),allocate).bindings;
   const value=worldEventTruthValue({worldEventOrdinal:world,eventTypeId:str(id(f(eventSchema,1n)).payload),occurredAt:at,bindings:truth});outputs=[value];emit(2,value);
  }else if(n===2){sources=[id(f(rec(event.payload,210n),1n))];observationId=allocate();const refs=items(f(rec(input.scene,516n),1n),'list');detections=[];
   if(modes.some(m=>m!==1n)){eventDetection=allocate();for(let i=0;i<3;i++)if(modes[i]!==1n){const binding=truth.find(b=>b.semanticReferent.semanticReferentId===key(refs[i]))??fail('port truth binding');detections.push({ordinal:allocate(),role:modes[i]===2n?{kind:'exact',eventRoleId:binding.eventRoleId}:{kind:'unresolved'}});}}
   reservation=admitObservationLane({observerId:observer,lane:'Current',dueAt:at,emitsCharacterAccessibleEvidence:detections.length>0},allocate).reservation;
   observation=detections.length?r('AttentionRoleObservation',[occ(1115,observationId),O,signed(at),currentEventDetectionIdValue(observer,eventDetection),list(detections.map(d=>r('ObservedRoleDetection',[currentDetectionIdValue(observer,d.ordinal),eventRoleEvidenceValue(d.role)]))),text(VERSION)]):r('AttentionNoDetectionObservation',[occ(1115,observationId),O,signed(at),text(VERSION)]);outputs=[observation];emit(detections.length?3:9,r(detections.length?'AttentionTrackingInput':'AttentionEmptySelectionInput',[observation]));
  }else if(n===3){sources=[occ(1115,observationId)];let tracks=emptyPerceptualContinuantFileState();const ev=applyPerceptualEventTransition(emptyPerceptualEventFileState(),{observerId:observer,currentEventDetectionId:{observerId:observer,eventDetectionOccurrenceId:eventDetection},continuityKind:'NewEventFile',supportingObservationIds:[{observerId:observer,observationId}],occurredAt:at,transformationVersion:C});
   eventTransition=semanticRecordValue('PerceptualEventTransition',{ObserverId:O,PerceptualEventReferentId:perceptualEventReferentIdValue(ev.transition.perceptualEventReferentId),CurrentEventDetectionId:currentEventDetectionIdValue(observer,eventDetection),ContinuityKind:unsigned(1),SupportingObservationIds:set([supportingObservationIdValue(observer,observationId)]),OccurredAt:unsigned(at),TransformationVersion:text(C)});
   const trackValues:CanonicalValue[]=[];requests=detections.map(d=>{const next=applyPerceptualTrackTransition(tracks,{observerId:observer,currentDetectionId:{observerId:observer,detectionOccurrenceId:d.ordinal},continuityKind:'NewTrack',supportingObservationIds:[{observerId:observer,observationId}],occurredAt:at,transformationVersion:A});tracks=next.state;trackValues.push(perceptualTrackTransitionValue({observerId:observer,perceptualReferentId:next.transition.perceptualReferentId,detectionOrdinal:d.ordinal,continuityKind:'NewTrack',supportingObservationOrdinals:[observationId],occurredAt:at,transformationVersion:A}));return {observerId:observer,perceptualEventReferentId:ev.transition.perceptualEventReferentId,perceptualReferentId:next.transition.perceptualReferentId,eventRoleEvidence:d.role,supportingObservationIds:[{observerId:observer,observationId}],occurredAt:at,transformationVersion:C};});
   const entries=[...perceptualStateEntries(tracks,ev.state)].sort((a,b)=>key(statePathValue(a.path)).localeCompare(key(statePathValue(b.path))));
   const domain=items(f(reg,11n),'set').map(decodeStatePattern);patch={operations:entries.map(e=>{const suffix=e.path.rootStateTypeId===241n?(e.path.fieldId===1n?'continuant-counter':'continuant-active'):(e.path.fieldId===1n?'event-counter':'event-active'),projection=new ContractReadProjection(state,domain,{value:{kind:'direct',accessorId:ID(1028,'accessor/attention-'+suffix),path:e.path}});projection.read('value');const rs=projection.actualReadRecords();reads.push(...rs);if(rs[0].presence)fail('first source tracking path already present');return {kind:'set' as const,path:e.path,expected:{presence:false as const},newValue:e.value};})};
   const applied=model.state.applyPatch(state,patch,ID(1025,'authority/perception'));nextState=applied.state;diffs=applied.diffs;outputs=[eventTransition,...trackValues];emit(4,r('AttentionBindingInput',[observation!,eventTransition,list(trackValues)]));
  }else if(n===4){sources=[occ(1115,observationId)];const first=allocate(),batch=compilePerceivedBindings(requests,first);for(let i=1;i<batch.bindings.length;i++)allocate();bindings=batch.bindings;outputs=bindings.map(perceivedBindingEvidenceValue);emit(5,r('AttentionClassificationInput',[observation!,eventTransition!,list(outputs)]));
  }else if(n===5){sources=[occ(1115,observationId)];emit(6,r('AttentionFreezeInput',[observation!,eventTransition!,list(bindings.map(perceivedBindingEvidenceValue))]));
  }else if(n===6){sources=[occ(1115,observationId)];if(!reservation)fail('no actual experience reservation');const value:PreRecognitionSemanticExperience={experienceId:reservation!.experienceId,observerId:observer,occurredAt:at,perceptualEventReferentIds:[requests[0].perceptualEventReferentId],perceivedBindings:bindings,perceptualClassifications:[],perceptualEventClassifications:[],supportingObservationIds:[{observerId:observer,observationId}],transformationVersion:H};staged=freezeAndStageSemanticExperience(reservation!,value,event.phase);experience=staged.experience;outputs=[preRecognitionSemanticExperienceValue(experience)];emit(7,r('AttentionRoleBatchInput',[outputs[0]]));
  }else if(n===7){sources=[occ(1106,experience!.experienceId)];const indexes:ObserverSafeEvidenceOccurrence[]=bindings.map(b=>({ref:{kind:'perceived-binding',perceivedBindingId:b.perceivedBindingId},observerId:observer,occurredAt:at,recordSchemaVersion:'perceived-binding/0.1-candidate',producingEpistemicSeamVersion:C,scope:{experienceId:experience!.experienceId,carrier:{kind:'continuant-in-event',perceptualEventReferentId:b.perceptualEventReferentId,perceptualReferentId:b.perceptualReferentId}}}));indexes.sort((a,b)=>characterEvidenceRefKey(a.ref).localeCompare(characterEvidenceRefKey(b.ref)));claims=[];
   for(const b of [...bindings].sort((a,b)=>unitKey(a).localeCompare(unitKey(b)))){const derived=deriveCausalRoleEvidence(compileCausalRoleModel('attention-source',[INITIAL_CAUSAL_ROLE_RULE]),{experience:experience!,perceptualEventReferentId:b.perceptualEventReferentId,perceptualReferentId:b.perceptualReferentId,evidenceOccurrences:indexes,readDomain:{transitionKindId:'transition/derive-character-causal-role',permittedEvidenceSchemas:[{refKind:'perceived-binding',recordSchemaVersion:'perceived-binding/0.1-candidate',producingEpistemicSeamVersion:C}],temporalScope:'SameExperience'},transformationVersion:G},0n);for(const c of derived.evidence)claims.push({...c,causalRoleEvidenceId:allocate()});}
   outputs=claims.map(causalRoleEvidenceValue);emit(8,r('AttentionPositiveSelectionInput',[preRecognitionSemanticExperienceValue(experience!),list(outputs)]));
  }else if(n===8||n===9){sources=n===8?[occ(1106,experience!.experienceId),...claims.map(c=>occ(1111,c.causalRoleEvidenceId))]:[occ(1115,observationId)];const selectionId=occ(1143,allocate()),rows:CanonicalValue[]=[],selectedUnits:CanonicalValue[]=[];
   if(n===8){const pool=prepareAttentionPool(experience!,claims),algorithm=u(f(policy,1n)),capacity=Number(u(f(policy,2n))),result=(algorithm===1n?selectAttention:algorithm===2n?selectEqualPriorityControl:selectUnlimitedAttentionControl)(pool,capacity);view=result.view;
    for(const row of result.audit){const b=bindings.find(b=>unitKey(b)===row.key)!,cs=claims.filter(c=>c.perceptualReferentId.observerTrackSequence===b.perceptualReferentId.observerTrackSequence),unit=r('AttentionUnitKey',[perceptualEventReferentIdValue(b.perceptualEventReferentId),perceptualReferentIdValue(b.perceptualReferentId)]),reason=row.exclusion==='MissingRole'?2:row.exclusion==='MultipleRoles'?3:row.exclusion==='UnsupportedRole'?4:1;
     rows.push(raw('AttentionAuditRow',new Map<bigint,CanonicalValue>([[1n,unit],[2n,set(row.roles.map(role=>ID(1019,role)))],[3n,unsigned(reason)],...(row.numerator!==undefined?[[4n,rational(row.numerator,row.denominator!)] as [bigint,CanonicalValue]]:[]),[5n,row.selected],[6n,set([{kind:'perceived-binding' as const,perceivedBindingId:b.perceivedBindingId},...cs.map(c=>({kind:'causal-role' as const,causalRoleEvidenceId:c.causalRoleEvidenceId}))].map(characterEvidenceRefValue))]])));
    }
    for(const ref of selectedReferences(view).filter(ref=>ref.kind==='perceived-binding')){if(ref.kind!=='perceived-binding')continue;const b=bindings.find(b=>b.perceivedBindingId===ref.perceivedBindingId)!,cs=claims.filter(c=>c.perceptualReferentId.observerTrackSequence===b.perceptualReferentId.observerTrackSequence);selectedUnits.push(r('SelectedAttentionUnit',[r('AttentionUnitKey',[perceptualEventReferentIdValue(b.perceptualEventReferentId),perceptualReferentIdValue(b.perceptualReferentId)]),list([perceivedBindingEvidenceValue(b)]),list(cs.map(causalRoleEvidenceValue))]));}
   }
   const source=raw('AttentionSelectionSource',new Map<bigint,CanonicalValue>(n===8?[[1n,unsigned(1)],[2n,occ(1106,experience!.experienceId)]]:[[1n,unsigned(2)],[3n,occ(1115,observationId)]]));selection=r('AttentionSelectionAudit',[selectionId,O,signed(at),source,policy,list(rows),text(VERSION)]);outputs=[selection];selectedCanonical=r('SelectedEvidenceView',[selectionId,O,signed(at),list(selectedUnits)]);emit(10,selectedCanonical);
  }else if(n===10){sources=[id(f(rec(event.payload,534n),1n))];if(!selection||!selectedCanonical)fail('selection completion missing');const refs:CharacterEvidenceRef[]=view?[...selectedReferences(view)].sort((a,b)=>characterEvidenceRefKey(a).localeCompare(characterEvidenceRefKey(b))):[],values=view?consumeSelected(view,refs).map(decode):[];view=undefined;
   const expectedValues=items(f(rec(event.payload,534n),4n),'list').flatMap(unit=>[...items(f(rec(unit,533n),2n),'list'),...items(f(rec(unit,533n),3n),'list')]);if(values.length!==expectedValues.length||new Set(values.map(key)).size!==values.length||values.some(v=>!expectedValues.some(e=>key(e)===key(v))))fail('selected read ledger incomplete');
   outputs=[r('AttentionProcessingReceipt',[occ(1144,allocate()),sources[0],O,signed(at),list(values.map(v=>{const isBinding=rec(v,(v as {schema:{typeId:bigint}}).schema.typeId).schema.typeId===224n;return raw('AttentionReadValue',new Map<bigint,CanonicalValue>([[1n,unsigned(isBinding?1:2)],[isBinding?2n:3n,v]]));})),text(VERSION)])];
  }
  const count=detections.length,q=claims.length,allocationCount=n===1?4:n===2?count?count+3:1:n===4?count:n===7?q:n>=8?1:0;
  if(allocated.length!==allocationCount)fail('exact runtime allocation budget');if(n!==3&&key(state.canonicalValue())!==key(nextState.canonicalValue()))throw new SchedulerContractError('TRANSITION_WRITE_SCOPE_VIOLATION','nontracking write');
  const allowed=items(f(reg,8n),'list');for(const o of outputs){const type=rec(o,(o as {schema:{typeId:bigint}}).schema.typeId).schema.typeId;if(!allowed.some(v=>u(f(rec(f(rec(v,539n),1n),254n),1n))===type))fail('output schema not registered');model.content.validateRecordRoles(enc(o));}
  const expectedOutputs=n===1||n===2||n===6||n>=8?1:n===3?1+count:n===4?count:n===7?q:0;if(outputs.length!==expectedOutputs)fail('output batch closure');
  // Extract identities through the committed occurrence table; never infer freshness
  // merely from the number of allocations or from a correctly typed namespace.
  const ordinal=(value:CanonicalValue)=>u(id(model.occurrences.extract(enc(value))).payload);
  let fresh:CanonicalValue[]=[];
  if(n===1)fresh=[outputs[0],...items(f(rec(outputs[0],210n),4n),'set')];
  else if(n===2){fresh=[outputs[0]];if(count){const o=rec(outputs[0],521n);fresh.push(f(o,4n),...items(f(o,5n),'list').map(d=>f(rec(d,520n),1n)));}}
  else if(n===4||n===7||n>=8)fresh=outputs;
  const expectedFresh=n===2&&count?allocated.slice(0,-1):allocated;
  if(key(list(fresh.map(ordinal).sort((a,b)=>a<b?-1:a>b?1:0).map(unsigned)))!==key(list(expectedFresh.map(unsigned))))fail('output identity differs from allocated slot');
  if(n===6&&ordinal(outputs[0])!==reservation!.experienceId)fail('experience differs from reserved slot');
  const emissions:EventEmission[]=child?[{dueAt:at,phase:u(f(stages.get(child.stage)!,5n)),eventTypeId:id(f(stages.get(child.stage)!,4n)),payload:child.payload,dependencies:list([])}]:[];
  completed.add(n);
  return {nextState,outputs,emittedEvents:emissions,traceContributions:[],traceFactory:(children:readonly ScheduledEvent[])=>{for(const child of children)expected.set(child.eventId,key(scheduledEventValue(child)));const trace=traceRecordValue({traceSchemaVersion:'trace/0.2-candidate',modelIdentity:model.modelIdentity.value,runIdentity:input.runIdentity.value,event,seamId:id(f(reg,2n)),seamVersion:VERSION,recordKind:event.eventTypeId,subjectIds:n===1?[]:[O],sourceRecordIds:sources,registeredReadDomain:items(f(reg,10n),'set').map(v=>decodeStatePattern(f(rec(v,540n),2n))),actualReadRecords:reads,inputProjection:event.payload,outputProjection:list(outputs),randomDrawRecords:[],quantizationOperations:[],statePatch:patch,structuralMutationDiffs:diffs,emittedEvents:children,invariantResults:[]});validateAttentionTrace(model,input.runIdentity.value,{stage:n,event,state,outputs,children,nextState},trace);return [trace];}};
 }
 const adapter={clone:(s:AuthoritativeState)=>new AuthoritativeState(s.entries()),validate:(s:AuthoritativeState)=>model.validateState(s),canonicalValue:(s:AuthoritativeState)=>s.canonicalValue(),restore:(v:CanonicalValue)=>model.state.restoreState(enc(v)),analyticalAnchors:()=>list([]),randomRelevantAuthoritativeIds:()=>list([])};
 const scheduler=new DeterministicScheduler({initialState:initial,stateAdapter:adapter,handlers:new Map([...byEvent].map(([k])=>[k,handler])),initialQueue:[input.event],initialAllocators:{nextRuntimeId:0n,nextEventId:1n,nextEventSequence:1n},maxSettlementWorkPerSimulationInstant:model.work,invariants:[()=>{validateSuccessfulExperienceSettlement(reservation?[reservation]:[],staged?[staged]:[]);if(expected.size||!completed.has(10)||completed.size!==(detections.length?9:4))fail('complete branch required');}]});
 async function settle(instrumentation?:ConformanceInstrumentation){if(!scheduler.getPendingQueue().length)return undefined;reset();try{return instrumentation?await scheduler.settleNextInstantForConformance(instrumentation):await scheduler.settleNextInstant();}finally{if(view)closeSelectedView(view);view=undefined;live=false;expected.clear();truth=[];bindings=[];claims=[];experience=undefined;reservation=undefined;staged=undefined;observation=undefined;eventTransition=undefined;requests=[];selection=undefined;selectedCanonical=undefined;detections=[];eventDetection=0n;observationId=0n;}}
 return Object.freeze({settleNextInstant:()=>settle(),settleNextInstantForConformance:(x:ConformanceInstrumentation)=>settle(x),snapshot:()=>({clock:scheduler.getClock(),status:scheduler.status,state:scheduler.getState(),outputs:scheduler.getOutputs(),trace:scheduler.getCommittedTrace(),allocators:scheduler.getAllocatorState(),queue:scheduler.getPendingQueue()}),save:()=>createCanonicalSave({scheduler,stateAdapter:adapter,modelIdentity:model.modelIdentity,runIdentity:input.runIdentity,continuingRunInputs:list([])}),diagnostic:()=>scheduler.failureDiagnostic});
}
