/** commit-public/0.1-candidate: exact lifecycle, fixed earned identity and observer owners. */
import {canonicalEncode as enc,list,set,text,unsigned as u,rational as q,type CanonicalValue} from '../substrate/canonicalEncoding';
import {commitManifest,createModelIdentity,createRunIdentity} from '../substrate/identity';
import {AuthoritativeState,StateAuthorityRegistry,statePathPatternValue,type StatePath} from '../substrate/state';
import {compileMutationAuthorityRegistry} from '../substrate/mutationAuthority';
import {simInstant} from '../substrate/time';
import {RANDOM_ALGORITHM_VERSION} from '../substrate/random';
import type {ScheduledEvent} from '../substrate/scheduler';
import {semanticReferentFromAuthoredContent} from '../substrate/referentOrigin';
import {validateIdentityHistory} from '../campaign2/cognitiveMath';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {receivingRecord as old} from './receivingCodecs';
import {ACTOR,TASKS,OPTIONS,sid} from './longitudinalModel';
import {copyData} from './beliefModel';
import {commitRecord as r,decodeCommit as decode} from './commitCodecs';
export {ACTOR,TASKS,OPTIONS,sid,copyData};
export const VERSION='commit-public/0.1-candidate',OBSERVERS=['a','b'].map(n=>sid(1000,'observer/commit/'+n)),NEED=old(371,[ACTOR,semanticReferentFromAuthoredContent(sid(1038,'content/commit/core-need'))]);
export const STAGES=[['source',30],['context',40],['probe-a',40],['probe-b',40],['raw',51],['reasons',52],['decision',60],['expression',80],['communication',110],['observe-a',120],['observe-b',120],['qualification',130],['evidence-a',130],['evidence-b',130],['identity',140],['lifecycle',140],['update-a',140],['update-b',140]] as const;
export const eventId=(n:string)=>sid(1001,'event/commit/'+n),pattern=(p:StatePath)=>({...p,selectors:p.selectors.map(selector=>({kind:'exact' as const,selector}))});
export const taskPath=(i:number):StatePath=>({rootStateTypeId:956n,fieldId:1n,selectors:[{kind:'mapKey',key:TASKS[i]}]}),identityPath:StatePath={rootStateTypeId:958n,fieldId:1n,selectors:[{kind:'mapKey',key:ACTOR}]},personPath=(i:number,j:number):StatePath=>({rootStateTypeId:965n,fieldId:1n,selectors:[{kind:'mapKey',key:r(966,[OBSERVERS[i],TASKS[j]])}]});
export const observerIndex=(n:string)=>n.endsWith('-a')?0:1;
export const owner=(n:string)=>sid(1025,n==='lifecycle'?'authority/commit-lifecycle':n==='identity'?'authority/commit-identity':`authority/commit-observer-${observerIndex(n)}`);
export const reads=(n:string):StatePath[]=>n==='context'?[taskPath(0),taskPath(1),identityPath]:n==='lifecycle'||n==='communication'?[taskPath(0),taskPath(1)]:n==='identity'?[identityPath]:n.startsWith('probe')||n.startsWith('update')?[personPath(observerIndex(n),0),personPath(observerIndex(n),1)]:[];
export const writes=(n:string):StatePath[]=>n==='lifecycle'?[taskPath(0),taskPath(1)]:n==='identity'?[identityPath]:n.startsWith('update')?[personPath(observerIndex(n),0),personPath(observerIndex(n),1)]:[];
const ownership=()=>compileMutationAuthorityRegistry(['lifecycle','identity','update-a','update-b'].map(n=>({authorityName:(owner(n).payload as {value:string}).value,ownedLeaves:writes(n).map(p=>({pattern:pattern(p),valueGrammar:{kind:'canonical-record' as const,recordTypeId:n==='lifecycle'?955n:n==='identity'?414n:967n},removalAllowed:false}))})));
export function commitRecipe(law=1){if(![1,2,3,4].includes(law))throw Error('COMMIT_PROFILE');const bands=old(438,[1,2,3,4,5].map(n=>q(n,5))),modifier=(unit:number)=>old(439,[q(1,unit),u(3)]),dice=(unit:number)=>old(437,[bands,q(0,1),modifier(unit),modifier(unit)]),parameters=r(952,[text(VERSION),u(law)]),content=r(953,[ACTOR,list(OBSERVERS),list([...TASKS,NEED]),dice(10),dice(4)]),stages=STAGES.map(([n,phase])=>r(969,[eventId(n),u(phase),list(reads(n).map(p=>statePathPatternValue(pattern(p)))),list(writes(n).map(p=>statePathPatternValue(pattern(p)))),owner(n)]));return {parameters:enc(parameters),content:enc(content),registry:enc(list([ownership().definitionValue,list(stages)]))};}
export type CommitSource=ReturnType<typeof commitRecipe>;
export async function compileCommitModel(input:CommitSource){const source=copyData(input,['parameters','content','registry']),profile=rec(decode(source.parameters),952n),law=Number(uint(f(profile,2n))),recipe=commitRecipe(law);for(const n of ['parameters','content','registry'] as const)if(key(decode(source[n]))!==key(decode(recipe[n])))throw Error('COMMIT_EXACT_MODEL');const own=ownership(),authority=new StateAuthorityRegistry(own.writableLeaves,own.authorities),content=rec(decode(source.content),953n);
 const modelIdentity=await createModelIdentity({rulesVersion:VERSION,contentSchemaVersion:VERSION,contentManifest:await commitManifest(content),parameterSchemaVersion:VERSION,parameterSet:await commitManifest(profile),numericProfileVersion:'commit-exact-with-identity-lattice/0.1-candidate',randomAlgorithmVersion:RANDOM_ALGORITHM_VERSION,registrySchemaVersion:VERSION,registryManifest:await commitManifest(decode(source.registry))});
 function validateState(state:AuthoritativeState){decode(enc(state.canonicalValue()));const allowed=[taskPath(0),taskPath(1),identityPath,...[0,1].flatMap(i=>[personPath(i,0),personPath(i,1)])].map(p=>key(statePathPatternValue(pattern(p))));for(const e of state.entries()){if(!allowed.includes(key(statePathPatternValue(pattern(e.path)))))throw Error('COMMIT_STATE_PATH');if(e.path.rootStateTypeId===958n)validateIdentityHistory(items(f(rec(e.value,414n),1n),'list'));else if(e.path.rootStateTypeId===956n){const v=rec(e.value,955n),version=uint(f(v,2n)),status=uint(f(v,3n)),cause=uint(f(v,4n));if(key(f(v,1n))!==key(e.path.selectors[0].kind==='mapKey'?e.path.selectors[0].key:false)||!(version===1n&&status===1n&&cause===0n||version===2n&&status===2n&&cause===1n||law===4&&version===3n&&status===1n&&cause===2n))throw Error('COMMIT_INSTANCE');}else rec(e.value,967n);}}
 return {source,content,law,modelIdentity,authority,validateState};}
export type CommitCompiled=Awaited<ReturnType<typeof compileCommitModel>>;
export async function compileCommitInputs(model:CommitCompiled,initialState:Uint8Array,orderedInputs:Uint8Array,runSeed:Uint8Array){if(key(decode(initialState))!==key(set([])))throw Error('COMMIT_INITIAL_STATE');const originals=items(decode(orderedInputs),'list');if(!originals.length||originals.length>8)throw Error('COMMIT_INPUT_LIMIT');let last=0n;const events:ScheduledEvent[]=[];
 originals.forEach((value,i)=>{const v=rec(value,954n),at=f(v,1n),training=f(v,2n)===true;if(typeof at==='boolean'||at.kind!=='signed'||at.value<=last||at.value>16n)throw Error('COMMIT_TIME');last=at.value;if(training!==(i===0)||training&&(uint(f(v,3n))!==0n||uint(f(v,4n))!==0n||items(f(v,5n),'set').length))throw Error('COMMIT_TRAINING');for(const n of ['source','context','probe-a','probe-b','communication'])events.push({eventId:BigInt(events.length),eventSequence:BigInt(events.length),dueAt:simInstant(at.value),phase:BigInt(STAGES.find(([name])=>name===n)![1]),eventTypeId:eventId(n),payload:value,dependencies:list([]),causalParentEventIds:[]});});
 const runIdentity=await createRunIdentity({modelIdentity:model.modelIdentity,initialState:await commitManifest(decode(initialState)),orderedInputSequence:await commitManifest(decode(orderedInputs)),runSeed});return {events,runIdentity,runSeed:runSeed.slice()};}
