/** development-component/0.1-candidate; no native runtime admission. */
import {canonicalEncode as enc,canonicalDecode,RecordSchemaRegistry,list,unsigned as u,type CanonicalValue} from '../substrate/canonicalEncoding';
import {ExactRational as Q} from '../substrate/exactMath';
import {ZERO,ONE,readQ} from '../campaign2/cognitiveMath';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {chosenData} from '../campaign2/cognitiveChoice';
import {data,value} from './biologyPublicData';
import {identityPublicRecord as r,identityPublicSupportedSchemas} from './identityPublicCodecs';
import {appendQualification} from './identityPublicMath';
import {contextValue} from './identityPublicModel';
import {dispositionDecision} from './dispositionAdaptation';
import {OPTIONS} from './longitudinalModel';
export const DEVELOPMENT_VERSION='development-component/0.1-candidate';
export interface DevelopmentProfile {curve:'Step'|'Ramp';learning:boolean;formation:boolean;constitution:-1|0|1;}
export interface DevelopmentFrame {phase:number;exercise:boolean;practice:boolean;permitted:boolean;difficulty:number;report:boolean|null;choice:'Learn'|'Probe'|'None'|'Forced';significance:0|4;pressure:0|4;setting:'Work'|'Home';seed:number;}
const registry=new RecordSchemaRegistry(identityPublicSupportedSchemas()),decode=(b:Uint8Array)=>canonicalDecode(b,registry),str=(x:Q)=>`${x.numerator}/${x.denominator}`,min=(a:Q,b:Q)=>a.compare(b)<0?a:b,clamp=(x:Q)=>x.compare(Q.of(1n,2n))>0?Q.of(1n,2n):x.compare(Q.of(-1n,2n))<0?Q.of(-1n,2n):x;
function fields(x:unknown,names:string[]){if(!x||Object.getPrototypeOf(x)!==Object.prototype)throw Error('DEVELOPMENT_FIELDS');const ds=Object.getOwnPropertyDescriptors(x);if(Reflect.ownKeys(ds).length!==names.length||names.some(n=>!ds[n]||!('value'in ds[n])))throw Error('DEVELOPMENT_FIELDS');}
export function checkedDevelopment(profile:DevelopmentProfile,originals:readonly DevelopmentFrame[]){
 fields(profile,['curve','learning','formation','constitution']);if(!['Step','Ramp'].includes(profile.curve)||typeof profile.learning!=='boolean'||typeof profile.formation!=='boolean'||![-1,0,1].includes(profile.constitution))throw Error('DEVELOPMENT_PROFILE');
 if(!Array.isArray(originals)||originals.length<1||originals.length>24||Reflect.ownKeys(originals).length!==originals.length+1)throw Error('DEVELOPMENT_HORIZON');let last=0;
 const frames=Array.from({length:originals.length},(_,i)=>{const descriptor=Object.getOwnPropertyDescriptor(originals,String(i));if(!descriptor||!('value'in descriptor))throw Error('DEVELOPMENT_ARRAY');const x=descriptor.value as DevelopmentFrame;fields(x,['phase','exercise','practice','permitted','difficulty','report','choice','significance','pressure','setting','seed']);if(!Number.isInteger(x.phase)||x.phase<last||x.phase>4||!Number.isInteger(x.difficulty)||x.difficulty<0||x.difficulty>8||![x.exercise,x.practice,x.permitted].every(v=>typeof v==='boolean')||!(x.report===null||typeof x.report==='boolean')||!['Learn','Probe','None','Forced'].includes(x.choice)||![0,4].includes(x.significance)||![0,4].includes(x.pressure)||!['Work','Home'].includes(x.setting)||!Number.isInteger(x.seed)||x.seed<0||x.seed>255)throw Error('DEVELOPMENT_INPUT');last=x.phase;return {...x};});return {profile:{...profile},frames};
}
export function developmentalGain(curve:DevelopmentProfile['curve'],phase:number){if(!Number.isInteger(phase)||phase<0||phase>4||!['Step','Ramp'].includes(curve))throw Error('DEVELOPMENT_PHASE');return curve==='Step'?Q.of(phase<2?4n:1n):ONE.add(Q.of(BigInt(3*(4-phase)),4n));}
export interface FormationEntry {at:number;phase:number;contribution:string;gain:string;delta:string;}
export interface DevelopmentRow {at:number;phase:number;learningGain:string;formationGain:string;skillBefore:string;skillAfter:string;attempted:boolean;executed:boolean;practiced:boolean;admittedReport:boolean|null;beliefBefore:string|null;beliefAfter:string|null;support:number;personalityBefore:string;personalityAfter:string;chosen:string|null;probabilities:string[];authorship:string|null;contribution:string;expression:string|null;journal:string;formationEntry:FormationEntry|null;forcedExecuted:boolean;}
export function createDevelopmentRun(inputProfile:DevelopmentProfile,originals:readonly DevelopmentFrame[]){
 const {profile,frames}=checkedDevelopment(inputProfile,originals),commitment=data({version:DEVELOPMENT_VERSION,profile,frames});let at=0,busy=false,phase=frames[0].phase,skill=ZERO,belief:Q|null=null,support=0,personality=ZERO,journal:CanonicalValue=r(1435,[list([])]),formation:FormationEntry[]=[],rows:DevelopmentRow[]=[],bundles:CanonicalValue[]=[];
 const ready=()=>{if(busy)throw Error('DEVELOPMENT_NOT_QUIESCENT');};const save=()=>enc(list([commitment,u(at),data({phase,skill:str(skill),belief:belief?str(belief):null,support,personality:str(personality),formation,rows}),journal,list(bundles)]));
 return Object.freeze({async step(failBeforeCommit=false){ready();if(at===frames.length)return false;busy=true;try{
  const x=frames[at],next=at+1,g=developmentalGain(profile.curve,x.phase),lg=profile.learning?g:ONE,fg=profile.formation?g:ONE,attempted=x.exercise,engaged=attempted&&x.permitted,executed=engaged&&skill.compare(Q.of(BigInt(x.difficulty),8n))>=0,practiced=engaged&&x.practice,report=engaged?x.report:null;
  const afterSkill=practiced?min(ONE,skill.add(lg.divide(Q.of(8n)))):skill,afterBelief=report===null?belief:belief===null?(report?ONE:ZERO):belief.add((report?ONE:ZERO).subtract(belief).multiply(lg.divide(Q.of(8n)))),afterSupport=support+(report===null?0:1);
  const training=x.choice==='Learn',ctx=contextValue({setting:x.setting,significance:x.significance,pressure:x.pressure,instructed:false,movement:'Chosen',permitted:true},training),d=x.choice==='Learn'||x.choice==='Probe'?await dispositionDecision(next,x.seed,ctx,journal,{law:'Plastic',constitution:profile.constitution},training?ZERO:personality,training):undefined;
  const afterJournal=d?appendQualification(journal,d.qualification):journal,c=d?readQ(f(rec(d.qualification,1434n),4n)):ZERO,afterPersonality=training?clamp(personality.add(c.multiply(fg).divide(Q.of(4n)))):personality,entry=training&&!c.equals(ZERO)?{at:next,phase:x.phase,contribution:str(c),gain:str(fg),delta:str(afterPersonality.subtract(personality))}:null;
  const choice=d?chosenData(f(rec(d.decision,1431n),3n)):undefined,row:DevelopmentRow={at:next,phase:x.phase,learningGain:str(lg),formationGain:str(fg),skillBefore:str(skill),skillAfter:str(afterSkill),attempted,executed,practiced,admittedReport:report,beliefBefore:belief?str(belief):null,beliefAfter:afterBelief?str(afterBelief):null,support:afterSupport,personalityBefore:str(personality),personalityAfter:str(afterPersonality),chosen:choice?(key(f(choice,1n))===key(OPTIONS[0])?'A':'B'):null,probabilities:choice?items(f(choice,2n),'list').map(v=>str(readQ(f(rec(v,421n),2n)))):[],authorship:choice?str(readQ(f(choice,7n))):null,contribution:str(c),expression:d?key(d.expression):null,journal:key(afterJournal),formationEntry:entry,forcedExecuted:x.choice==='Forced'&&x.permitted};
  const bundle=d?list([d.reasons,d.decision,d.intent,d.expression,d.qualification]):list([]);decode(enc(bundle));data(row);if(failBeforeCommit)throw Error('DEVELOPMENT_INJECTED');at=next;phase=x.phase;skill=afterSkill;belief=afterBelief;support=afterSupport;personality=afterPersonality;journal=afterJournal;if(entry)formation=[...formation,entry];rows=[...rows,row];bundles=[...bundles,bundle];return true;
 }finally{busy=false;}},save(){ready();return save();},snapshot(){ready();return decode(save());},rows(){ready();return value<DevelopmentRow[]>(data(rows));}});
}
export async function restoreDevelopmentRun(profile:DevelopmentProfile,frames:readonly DevelopmentFrame[],bytes:Uint8Array){const copy=bytes.slice(),xs=items(decode(copy),'list');if(xs.length!==5)throw Error('DEVELOPMENT_SAVE');const count=uint(xs[1]);if(count>BigInt(frames.length))throw Error('DEVELOPMENT_PREFIX');const run=createDevelopmentRun(profile,frames);for(let i=0n;i<count;i++)await run.step();if(key(decode(run.save()))!==key(decode(copy)))throw Error('DEVELOPMENT_RESTORE');return run;}
