/** longitudinal-public/0.1-candidate: one timeline and separate learned-state owners. */
import {canonicalEncode as enc,list,text,unsigned as u,rational as q,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {commitManifest,createModelIdentity,createRunIdentity} from '../substrate/identity';
import {AuthoritativeState,StateAuthorityRegistry,statePathPatternValue,type StatePath} from '../substrate/state';
import {compileMutationAuthorityRegistry} from '../substrate/mutationAuthority';
import {simInstant} from '../substrate/time';
import {RANDOM_ALGORITHM_VERSION} from '../substrate/random';
import type {ScheduledEvent} from '../substrate/scheduler';
import {semanticReferentFromAuthoredContent} from '../substrate/referentOrigin';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {validateIdentityHistory} from '../campaign2/cognitiveMath';
import {receivingRecord as old} from './receivingCodecs';
import {skillRecord} from './skillCodecs';
import {relationshipRecord} from './relationshipCodecs';
import {copyData} from './beliefModel';
import {multisourceBase} from './multisourceModelRecipe';
import {decodeLongitudinal as decode,longitudinalRecord as r} from './longitudinalCodecs';
export {copyData};
export const LONGITUDINAL_VERSION='longitudinal-public/0.2-candidate',sid=(ns:number,name:string)=>typedIdentifier(ns,text(name));
const semantic=(name:string)=>semanticReferentFromAuthoredContent(sid(1038,'content/longitudinal/'+name));
export const OBSERVER=sid(1000,'observer/longitudinal'),ACTOR=semantic('actor'),TARGET=semantic('target'),TASKS=['a','b'].map(n=>old(371,[ACTOR,semantic('task/'+n)])),OPTIONS=['a','b'].map(n=>old(395,[ACTOR,sid(1027,'action/longitudinal/'+n)]));
export const STAGES=[['probe',40],['bio-context',40],['bio-raw',51],['bio-reasons',52],['bio-decision',60],['practice-intent',70],['bio-expression',80],['practice-plan',90],['practice-attempt',100],['source',110],['observe',120],['bio-qualification',130],['bio-learn',140],['skill',140],['relationship',140],['person',140],['memory',140]] as const;
export const eventId=(n:string)=>sid(1001,'event/longitudinal/'+n),path=(root:number):StatePath=>({rootStateTypeId:BigInt(root),fieldId:1n,selectors:[{kind:'mapKey',key:ACTOR}]}),pattern=(p:StatePath)=>({...p,selectors:p.selectors.map(selector=>({kind:'exact' as const,selector}))});
export interface LongitudinalSettings {representation:number;family:number;retention:number;rust:number;law:number;standing:boolean;revision?:number;}
export const DEFAULT_SETTINGS:LongitudinalSettings={representation:2,family:0,retention:1,rust:0,law:1,standing:true,revision:2};
export const enabled=(s:LongitudinalSettings,family:number)=>s.family===0||s.family===family;
export const emptyIdentity=()=>old(414,[list([])]),emptySkill=()=>skillRecord(784,[q(0,1),u(0)]),emptyRelationship=()=>relationshipRecord(851,[u(0),false]),emptyJournal=()=>r(866,[list([])]);
export const familyPath=(s:LongitudinalSettings,family:number)=>path(s.representation===4?875:family===1?872:family===2?871:s.representation===1?873:s.representation===3?867:868);
export function stageReads(n:string,s:LongitudinalSettings):StatePath[]{const roots=n==='probe'?[familyPath(s,1),familyPath(s,2),familyPath(s,3),path(870)]:n==='bio-raw'?[familyPath(s,1)]:n==='bio-learn'?[familyPath(s,1)]:n==='source'||n==='skill'?[familyPath(s,2)]:n==='relationship'?[familyPath(s,3)]:n==='person'?[path(870)]:n==='memory'?[path(867)]:[];return roots.filter((p,i,a)=>a.findIndex(v=>v.rootStateTypeId===p.rootStateTypeId)===i);}
export function stageWrites(n:string,s:LongitudinalSettings):StatePath[]{return n==='bio-learn'?[familyPath(s,1)]:n==='skill'?[familyPath(s,2)]:n==='relationship'&&s.representation!==3?[familyPath(s,3)]:n==='person'?[path(870)]:n==='memory'?[path(867)]:[];}
export const owner=(n:string,s:LongitudinalSettings)=>sid(1025,s.representation===4&&['bio-learn','skill','relationship'].includes(n)?'authority/longitudinal-shared':n==='bio-learn'?'authority/longitudinal-identity':n==='skill'?'authority/longitudinal-skill':n==='relationship'?'authority/longitudinal-relationship':n==='person'?'authority/longitudinal-person':'authority/longitudinal-memory');
function ownership(s:LongitudinalSettings){const rows=['bio-learn','skill','relationship','person','memory'],groups=new Map<string,{authorityName:string;ownedLeaves:{pattern:ReturnType<typeof pattern>;valueGrammar:{kind:'canonical-record';recordTypeId:bigint};removalAllowed:false}[]}>();for(const n of rows){const name=(owner(n,s) as Extract<CanonicalValue,{kind:'typedIdentifier'}>).payload as Extract<CanonicalValue,{kind:'text'}>;const g=groups.get(name.value)??{authorityName:name.value,ownedLeaves:[]};for(const p of stageWrites(n,s)){if(!g.ownedLeaves.some(v=>v.pattern.rootStateTypeId===p.rootStateTypeId))g.ownedLeaves.push({pattern:pattern(p),valueGrammar:{kind:'canonical-record',recordTypeId:({867:866,868:851,870:869,871:784,872:414,873:866,875:874} as Record<number,number>)[Number(p.rootStateTypeId)] as unknown as bigint},removalAllowed:false});}groups.set(name.value,g);}return compileMutationAuthorityRegistry([...groups.values()].filter(g=>g.ownedLeaves.length).map(g=>({...g,ownedLeaves:g.ownedLeaves.map(v=>({...v,valueGrammar:{...v.valueGrammar,recordTypeId:BigInt(v.valueGrammar.recordTypeId)}}))})));}
export function longitudinalRecipe(settings:Partial<LongitudinalSettings>={}){const s={...DEFAULT_SETTINGS,...settings};if(![1,2].includes(s.revision!)||![1,2,3,4].includes(s.representation)||![0,1,2,3,4].includes(s.family)||![1,2].includes(s.retention)||![0,1].includes(s.rust)||![1,2].includes(s.law)||typeof s.standing!=='boolean')throw Error('LONGITUDINAL_PROFILE');const base=rec(multisourceBase().get('task-reason-dice'),437n),dice=old(437,[f(base,1n),q(0,1),old(439,[q(1,s.revision===1?4:16),u(3)]),old(439,[q(1,4),u(3)])]),parameters=r(863,[text(s.revision===1?'longitudinal-public/0.1-candidate':LONGITUDINAL_VERSION),u(s.representation),u(s.family),u(s.retention),u(s.rust),u(s.law),s.standing]),content=r(883,[OBSERVER,ACTOR,TARGET,list(TASKS),list(OPTIONS),dice,q(1,1),u(4)]),stages=STAGES.map(([n,phase])=>r(882,[eventId(n),u(phase),list(stageReads(n,s).map(p=>statePathPatternValue(pattern(p)))),list(stageWrites(n,s).map(p=>statePathPatternValue(pattern(p)))),owner(n,s)]));return {parameters:enc(parameters),content:enc(content),registry:enc(list([ownership(s).definitionValue,list(stages)]))};}
export type LongitudinalSource=ReturnType<typeof longitudinalRecipe>;
export async function compileLongitudinalModel(input:LongitudinalSource){const source=copyData(input,['parameters','content','registry']),profile=rec(decode(source.parameters),863n),versionValue=f(profile,1n),version=typeof versionValue!=='boolean'&&versionValue.kind==='text'?versionValue.value:'',settings:LongitudinalSettings={revision:version==='longitudinal-public/0.1-candidate'?1:version===LONGITUDINAL_VERSION?2:0,representation:Number(uint(f(profile,2n))),family:Number(uint(f(profile,3n))),retention:Number(uint(f(profile,4n))),rust:Number(uint(f(profile,5n))),law:Number(uint(f(profile,6n))),standing:f(profile,7n)===true},recipe=longitudinalRecipe(settings);for(const n of ['parameters','content','registry'] as const)if(key(decode(recipe[n]))!==key(decode(source[n])))throw Error('LONGITUDINAL_EXACT_MODEL');const own=ownership(settings),authority=new StateAuthorityRegistry(own.writableLeaves,own.authorities),content=rec(decode(source.content),883n),modelIdentity=await createModelIdentity({rulesVersion:version,contentSchemaVersion:version,contentManifest:await commitManifest(content),parameterSchemaVersion:version,parameterSet:await commitManifest(profile),numericProfileVersion:'longitudinal-exact/0.1-candidate',randomAlgorithmVersion:RANDOM_ALGORITHM_VERSION,registrySchemaVersion:version,registryManifest:await commitManifest(decode(source.registry))});
 const initial=new AuthoritativeState([{path:path(867),value:emptyJournal()},...(settings.representation===4?[{path:path(875),value:r(874,[u(0),list([])])}]:[{path:path(872),value:emptyIdentity()},{path:path(871),value:emptySkill()},...(settings.representation===3?[]:[{path:familyPath(settings,3),value:settings.representation===1?emptyJournal():emptyRelationship()}])])]);
 function validateState(state:AuthoritativeState){decode(enc(state.canonicalValue()));const allowed=[...initial.entries().map(e=>key(statePathPatternValue(pattern(e.path)))),key(statePathPatternValue(pattern(path(870))))];for(const e of state.entries()){if(!allowed.includes(key(statePathPatternValue(pattern(e.path)))))throw Error('LONGITUDINAL_STATE_PATH');const v=e.value;if(typeof v==='boolean'||v.kind!=='record')throw Error('LONGITUDINAL_STATE_VALUE');if(v.schema.typeId===414n)validateIdentityHistory(items(f(v,1n),'list'));if(v.schema.typeId===866n){let last=0n;const ids=new Set<string>();for(const row of items(f(v,1n),'list')){const t=f(rec(row,865n),2n);if(typeof t==='boolean'||t.kind!=='signed'||t.value<=last||ids.has(key(f(rec(row,865n),1n))))throw Error('LONGITUDINAL_EPISODE_ORDER');last=t.value;ids.add(key(f(rec(row,865n),1n)));}}if(v.schema.typeId===874n){const tag=Number(uint(f(v,1n))),xs=items(f(v,2n),'list');if(tag===0?xs.length!==0:xs.length!==1||(xs[0] as Extract<CanonicalValue,{kind:'record'}>).schema.typeId!==BigInt([0,414,784,851][tag]))throw Error('LONGITUDINAL_SHARED_TAG');}}for(const e of initial.entries())if(!state.read(e.path).presence)throw Error('LONGITUDINAL_MISSING_STATE');}
 return {source,profile,settings,version,content,modelIdentity,authority,initial,validateState};}
export type LongitudinalCompiled=Awaited<ReturnType<typeof compileLongitudinalModel>>;
export async function compileLongitudinalInputs(model:LongitudinalCompiled,initialState:Uint8Array,orderedInputs:Uint8Array,runSeed:Uint8Array){if(key(decode(initialState))!==key(model.initial.canonicalValue()))throw Error('LONGITUDINAL_INITIAL_STATE');const originals=items(decode(orderedInputs),'list');if(originals.length>16)throw Error('LONGITUDINAL_INPUT_LIMIT');let previous=0n;const events:ScheduledEvent[]=[];for(const v of originals){const o=rec(v,864n),at=f(o,1n);if(typeof at==='boolean'||at.kind!=='signed'||at.value<=previous||at.value>64n)throw Error('LONGITUDINAL_INPUT_TIME');previous=at.value;for(const n of ['probe','bio-context','practice-intent'])events.push({eventId:BigInt(events.length),eventSequence:BigInt(events.length),dueAt:simInstant(at.value),phase:BigInt(STAGES.find(([s])=>s===n)![1]),eventTypeId:eventId(n),payload:v,dependencies:list([]),causalParentEventIds:[]});}const runIdentity=await createRunIdentity({modelIdentity:model.modelIdentity,initialState:await commitManifest(decode(initialState)),orderedInputSequence:await commitManifest(decode(orderedInputs)),runSeed});return {events,runIdentity,runSeed:runSeed.slice(),originals};}


