/** recollection-public/0.1-candidate: authenticated ordinary planning and disjoint owners. */
import {canonicalEncode as enc,list,text,unsigned as u,signed,rational as q,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {AuthoritativeState,applyStatePatch,restoreAuthoritativeState,statePathPatternValue,type ActualReadRecord,type StatePatch,type StructuralMutationDiff,type StatePath} from '../substrate/state';
import {DeterministicScheduler,SchedulerContractError,type EventHandlerContext,type EventEmission,type ScheduledEvent,type ConformanceInstrumentation} from '../substrate/scheduler';
import {createCanonicalSave,scheduledEventValue} from '../substrate/persistence';
import {traceRecordValue} from '../substrate/trace';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {createCognitiveRandomSession} from '../campaign2/cognitiveArbitration';
import {recollectionRecord as r,decodeRecollection as decode} from './recollectionCodecs';
import {VERSION,STAGES,OBSERVER,ACTOR,sid,eventId,path,pattern,owner,reads,writes,type RecollectionCompiled,compileRecollectionInputs} from './recollectionModel';
import {recollect,consolidate,emptyMemory,emptySummary} from './recollectionMath';
const instantValue=(v:CanonicalValue)=>{if(typeof v==='boolean'||v.kind!=='signed')throw Error('RECOLLECTION_TIME');return v.value;};
export function createRecollectionRuntime(model:RecollectionCompiled,input:Awaited<ReturnType<typeof compileRecollectionInputs>>){
 const originals=new Map(input.events.map(e=>[e.eventId,key(scheduledEventValue(e))])),world=new Map(input.events.map(e=>[e.dueAt,rec(e.payload,1041n)])),random=createCognitiveRandomSession(input.runSeed);let active=false,expected=new Map<bigint,string>();const fail=(why:string):never=>{throw new SchedulerContractError('INPUT_NOT_ADMITTED',why);};
 const adapter={clone:(s:AuthoritativeState)=>new AuthoritativeState(s.entries()),validate:model.validateState,canonicalValue:(s:AuthoritativeState)=>s.canonicalValue(),restore:restoreAuthoritativeState,analyticalAnchors:()=>list([]),randomRelevantAuthoritativeIds:()=>list([])};
 async function handler({event,state,allocateRuntimeId}:EventHandlerContext<AuthoritativeState>){
  if(!active)fail('inactive recollection transaction');const stage=STAGES.find(([n])=>key(event.eventTypeId)===key(eventId(n)));if(!stage)fail('recollection stage');const [name,phase]=stage!;if(event.phase!==BigInt(phase))fail('recollection phase');const fingerprint=key(scheduledEventValue(event));if(['recall'].includes(name)){if(originals.get(event.eventId)!==fingerprint)fail('recollection original');}else{if(expected.get(event.eventId)!==fingerprint)fail('recollection generated');expected.delete(event.eventId);}
  const occurrence=(ns=1166)=>typedIdentifier(ns,u(allocateRuntimeId())),paths=reads(name),domain=paths.map(pattern),actualReads:ActualReadRecord[]=[],pk=(p:StatePath)=>key(statePathPatternValue(pattern(p))),read=(p:StatePath)=>{if(!paths.some(x=>pk(x)===pk(p)))return fail('recollection read domain');const prior=state.read(p);actualReads.push({accessorId:sid(1028,'accessor/recollection/'+name),path:p,presence:prior.presence,value:prior.value,derivedSources:[]});return prior.value;};
  const outputs:CanonicalValue[]=[],emittedEvents:EventEmission[]=[];let nextState=state,patch:StatePatch={operations:[]},diffs:readonly StructuralMutationDiff[]=[],randomDrawRecords:CanonicalValue[]=[],quantizationOperations:CanonicalValue[]=[];
  const emit=(next:string,payload:CanonicalValue)=>emittedEvents.push({dueAt:event.dueAt,phase:BigInt(STAGES.find(([n])=>n===next)![1]),eventTypeId:eventId(next),payload,dependencies:list([])}),write=(changes:{path:StatePath;prior:CanonicalValue|undefined;next:CanonicalValue}[])=>{if(changes.some(c=>!writes(name).some(p=>pk(p)===pk(c.path))))fail('recollection write domain');patch={operations:changes.map(c=>({kind:'set' as const,path:c.path,expected:c.prior?{presence:true as const,value:c.prior}:{presence:false as const},newValue:c.next}))};const applied=applyStatePatch(state,patch,owner(name),model.authority);nextState=applied.state;diffs=applied.diffs;};
  if(name==='recall'){
   const source=world.get(event.dueAt)!,query=uint(f(source,9n));
   // This branch is an explicit violating oracle comparator. Baseline never reads it.
   const truth=model.law===4?[...world.values()].find(o=>uint(f(o,2n))===1n&&uint(f(o,3n))===query&&instantValue(f(o,1n))<event.dueAt):undefined;
   const out=recollect(read(path(1045))??emptyMemory(),read(path(1048))??emptySummary(),model.law,event.dueAt,query,occurrence(),truth?f(truth,5n)===true:undefined);outputs.push(out);emit('source',out);
  }else if(name==='source'){
   const source=world.get(event.dueAt)!;outputs.push(r(1052,[occurrence(),signed(event.dueAt),f(source,3n),f(source,5n)]));emit('observe',event.payload);
  }else if(name==='observe'){
   const source=world.get(event.dueAt)!,visible=uint(f(source,2n))===1n&&f(source,7n)===true,obs=r(1042,[occurrence(),OBSERVER,signed(event.dueAt),visible?f(source,3n):u(0),visible?f(source,4n):u(0),list(visible&&f(source,8n)===true?[f(source,6n)]:[])]);outputs.push(obs);emit('consolidate',list([obs,event.payload]));
  }else if(name==='consolidate'){
   const pair=items(event.payload,'list'),pm=read(path(1045)),ps=read(path(1048)),memory=pm??emptyMemory(),summary=ps??emptySummary(),next=consolidate(memory,summary,pair[0],pair[1],model.law,event.dueAt);
   const changes=[];if(key(next.memory)!==key(memory))changes.push({path:path(1045),prior:pm,next:next.memory});if(key(next.summary)!==key(summary))changes.push({path:path(1048),prior:ps,next:next.summary});if(changes.length)write(changes);
   outputs.push(r(1050,[occurrence(),memory,next.memory]),r(1051,[occurrence(),summary,next.summary]));
  }else fail('recollection unknown stage');
  outputs.forEach(v=>decode(enc(v)));return {nextState,outputs,emittedEvents,traceContributions:[],traceFactory:(children:readonly ScheduledEvent[])=>{if(children.length!==emittedEvents.length)fail('recollection child count');children.forEach((e,i)=>{if(e.causalParentEventIds.length!==1||e.causalParentEventIds[0]!==event.eventId||key(e.payload)!==key(emittedEvents[i].payload))fail('recollection child association');expected.set(e.eventId,key(scheduledEventValue(e)));});return [traceRecordValue({traceSchemaVersion:'trace/0.2-candidate',modelIdentity:model.modelIdentity.value,runIdentity:input.runIdentity.value,event,seamId:sid(1036,'seam/recollection/'+name),seamVersion:VERSION,recordKind:event.eventTypeId,subjectIds:[ACTOR],sourceRecordIds:[],registeredReadDomain:domain,actualReadRecords:actualReads,inputProjection:event.payload,outputProjection:list(outputs),randomDrawRecords,quantizationOperations,statePatch:patch,structuralMutationDiffs:diffs,emittedEvents:children,invariantResults:[]})];}};
 }
 const scheduler=new DeterministicScheduler({initialState:new AuthoritativeState([]),stateAdapter:adapter,handlers:new Map(STAGES.map(([n])=>[key(eventId(n)),handler])),initialQueue:input.events,initialAllocators:{nextRuntimeId:0n,nextEventId:BigInt(input.events.length),nextEventSequence:BigInt(input.events.length)},maxSettlementWorkPerSimulationInstant:32n,invariants:[state=>{if(expected.size)fail('recollection pending children');model.validateState(state);random.prepareCommit();}]});
 async function settle(instrumentation?:ConformanceInstrumentation){if(active)fail('recollection concurrent settlement');if(!scheduler.getPendingQueue().length)return undefined;active=true;expected=new Map();random.begin();try{const result=instrumentation?await scheduler.settleNextInstantForConformance(instrumentation):await scheduler.settleNextInstant();if(result)random.commit();return result;}finally{active=false;expected.clear();random.close();}}
 return {settle:()=>settle(),settleForConformance:(i:ConformanceInstrumentation)=>settle(i),snapshot:()=>({state:scheduler.getState(),clock:scheduler.getClock(),status:scheduler.status,queue:scheduler.getPendingQueue(),allocators:scheduler.getAllocatorState(),trace:scheduler.getCommittedTrace(),outputs:scheduler.getOutputs(),randomAddresses:random.committedAddressKeys()}),save:()=>createCanonicalSave({scheduler,stateAdapter:adapter,modelIdentity:model.modelIdentity,runIdentity:input.runIdentity,continuingRunInputs:list(random.committedAddressKeys().map(text))}),diagnostic:()=>scheduler.failureDiagnostic};
}
