/** Relationship 0.1/0.2: independent directional learning and response probes. */
import {canonicalEncode as enc,list,unsigned as u,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {AuthoritativeState,applyStatePatch,restoreAuthoritativeState,type ActualReadRecord,type StatePatch,type StructuralMutationDiff,type StatePath} from '../substrate/state';
import {DeterministicScheduler,SchedulerContractError,type EventHandlerContext,type EventEmission,type ScheduledEvent,type ConformanceInstrumentation} from '../substrate/scheduler';
import {createCanonicalSave,scheduledEventValue} from '../substrate/persistence';
import {traceRecordValue} from '../substrate/trace';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataIdentity as id} from '../campaign2/canonicalData';
import {relationshipRecord as r,decodeRelationship as decode} from './relationshipCodecs';
import {RELATIONSHIP_VERSION,STAGES,OBSERVERS,CHARACTERS,TARGETS,sid,eventId,observerIndex,historyPath,personPath,cachePath,stageReads,stageWrites,owner,pattern,type RelationshipCompiled,compileRelationshipInputs} from './relationshipModel';
import {relationshipSummary,relationshipObserve,appendRelationship,relationshipAppraisal,relationshipRaw,relationshipReasons,relationshipResponse} from './relationshipMath';
export function createRelationshipRuntime(model:RelationshipCompiled,input:Awaited<ReturnType<typeof compileRelationshipInputs>>){
 const originals=new Map(input.events.map(e=>[e.eventId,key(scheduledEventValue(e))]));let active=false,expected=new Map<bigint,string>();
 const fail=(message:string):never=>{throw new SchedulerContractError('INPUT_NOT_ADMITTED',message);};
 const adapter={clone:(s:AuthoritativeState)=>new AuthoritativeState(s.entries()),validate:(s:AuthoritativeState)=>{decode(enc(s.canonicalValue()));},canonicalValue:(s:AuthoritativeState)=>s.canonicalValue(),restore:restoreAuthoritativeState,analyticalAnchors:()=>list([]),randomRelevantAuthoritativeIds:()=>list([])};
 async function handler({event,state,allocateRuntimeId}:EventHandlerContext<AuthoritativeState>){
  if(!active)fail('inactive relationship transaction');const stage=STAGES.find(([n])=>key(event.eventTypeId)===key(eventId(n)));if(!stage)fail('unknown relationship stage');const [name,phase]=stage!;if(event.phase!==BigInt(phase))fail('relationship phase');const i=observerIndex(name),suffix=i===0?'-a':'-b',fingerprint=key(scheduledEventValue(event));if(name==='source'||name.startsWith('appraise')){if(originals.get(event.eventId)!==fingerprint)fail('relationship original association');}else{if(expected.get(event.eventId)!==fingerprint)fail('relationship generated association');expected.delete(event.eventId);}
  const occurrence=()=>typedIdentifier(1156,u(allocateRuntimeId())),reads:ActualReadRecord[]=[],paths=stageReads(name,model.settings),domain=paths.map(pattern),pk=(p:StatePath)=>key(list([u(p.rootStateTypeId),u(p.fieldId),...p.selectors.map(s=>s.kind==='mapKey'?s.key:false)]));
  const read=(p:StatePath)=>{if(!paths.some(v=>pk(v)===pk(p)))return fail('relationship unregistered read');const prior=state.read(p);reads.push({accessorId:sid(1028,'accessor/relationship/'+name),path:p,presence:prior.presence,value:prior.value,derivedSources:[]});return prior.value;};
  const outputs:CanonicalValue[]=[],emittedEvents:EventEmission[]=[];let nextState=state,patch:StatePatch={operations:[]},diffs:readonly StructuralMutationDiff[]=[],randomDrawRecords:CanonicalValue[]=[];
  const write=(changes:readonly {path:StatePath;prior:CanonicalValue|undefined;next:CanonicalValue}[])=>{if(changes.some(c=>!stageWrites(name,model.settings).some(p=>pk(p)===pk(c.path))))fail('relationship unregistered write');patch={operations:changes.map(c=>({kind:'set' as const,path:c.path,expected:c.prior?{presence:true as const,value:c.prior}:{presence:false as const},newValue:c.next}))};const result=applyStatePatch(state,patch,owner(name),model.authority);nextState=result.state;diffs=result.diffs;};
  const emit=(next:string,payload:CanonicalValue)=>emittedEvents.push({dueAt:event.dueAt,phase:BigInt(STAGES.find(([n])=>n===next)![1]),eventTypeId:eventId(next),payload,dependencies:list([])});
  let output:CanonicalValue;
  if(name.startsWith('appraise')){const person=read(personPath(i)),summary=model.settings.candidate===2?read(cachePath(i))!:model.settings.candidate===3?r(851,[u(0),false]):relationshipSummary(model.settings,read(historyPath(i))!);output=relationshipAppraisal(i,event.payload,summary,person,occurrence(),model.settings);emit('raw'+suffix,output);}
  else if(name.startsWith('raw')){output=relationshipRaw(i,event.payload,occurrence());emit('reasons'+suffix,output);}
  else if(name.startsWith('reasons')){output=relationshipReasons(model,event.payload,occurrence());emit('response'+suffix,output);}
  else if(name.startsWith('response')){output=await relationshipResponse(i,event.payload,event.dueAt,occurrence(),input.runSeed);randomDrawRecords=[...items(f(rec(output,856n),8n),'list')];}
  else if(name==='source'){const original=rec(event.payload,843n);output=r(844,[occurrence(),f(original,1n),f(original,2n),f(original,3n)]);for(const n of model.settings.reverse?['b','a']:['a','b'])emit('observe-'+n,list([original,output]));}
  else if(name.startsWith('observe')){const pair=items(event.payload,'list');output=relationshipObserve(i,pair[0],pair[1],occurrence());for(const n of ['history','person','cache'])emit(n+suffix,output);}
  else {const observation=rec(event.payload,845n);if(key(f(observation,2n))!==key(OBSERVERS[i])||key(f(observation,3n))!==key(TARGETS[i]))fail('relationship foreign observation');
   if(name.startsWith('history')){const prior=read(historyPath(i))!,other=model.settings.candidate===4?read(historyPath(1-i)):undefined,result=appendRelationship(prior,observation);output=r(857,[occurrence(),observation,result.applied,prior,result.next]);if(result.applied)write([{path:historyPath(i),prior,next:result.next},...(model.settings.candidate===4?[{path:historyPath(1-i),prior:other,next:result.next}]:[])]);}
   else if(name.startsWith('person')){const prior=read(personPath(i)),value=observation.fields.get(8n),next=value===undefined?prior:r(849,[value,f(observation,1n)]),fields=new Map<bigint,CanonicalValue>([[1n,occurrence()],[2n,observation],[3n,value!==undefined]]);if(prior)fields.set(4n,prior);if(next)fields.set(5n,next);output=r(858,fields);if(value!==undefined)write([{path:personPath(i),prior,next:next!}]);}
   else {if(model.settings.candidate===2){const journal=read(historyPath(i))!,prior=read(cachePath(i))!,next=relationshipSummary(model.settings,journal);output=r(859,[occurrence(),OBSERVERS[i],prior,next]);if(key(prior)!==key(next))write([{path:cachePath(i),prior,next}]);}else output=r(859,[occurrence(),OBSERVERS[i]]);}
  }
  decode(enc(output!));outputs.push(output!);const safeInput=name.startsWith('appraise')?list([f(rec(event.payload,843n),1n),f(rec(event.payload,843n),BigInt(i+8)),...(model.settings.candidate===5?[f(rec(event.payload,843n),2n),f(rec(event.payload,843n),3n)]:[])]):event.payload;
  return {nextState,outputs,emittedEvents,traceContributions:[],traceFactory:(children:readonly ScheduledEvent[])=>{if(children.length!==emittedEvents.length)fail('relationship child count');children.forEach((e,j)=>{if(e.causalParentEventIds.length!==1||e.causalParentEventIds[0]!==event.eventId||key(e.payload)!==key(emittedEvents[j].payload))fail('relationship child binding');expected.set(e.eventId,key(scheduledEventValue(e)));});const sourceRecordIds:ReturnType<typeof id>[]=[];if(name!=='source'&&!name.startsWith('appraise')&&typeof event.payload!=='boolean'&&event.payload.kind==='record')sourceRecordIds.push(id(f(event.payload,1n)));const trace=traceRecordValue({traceSchemaVersion:'trace/0.2-candidate',modelIdentity:model.modelIdentity.value,runIdentity:input.runIdentity.value,event,seamId:sid(1036,'seam/relationship/'+name),seamVersion:model.version,recordKind:event.eventTypeId,subjectIds:name==='source'?[]:[OBSERVERS[i],CHARACTERS[i]],sourceRecordIds,registeredReadDomain:domain,actualReadRecords:reads,inputProjection:safeInput,outputProjection:list(outputs),randomDrawRecords,quantizationOperations:[],statePatch:patch,structuralMutationDiffs:diffs,emittedEvents:children,invariantResults:[]});decode(enc(trace));return [trace];}};
 }
 const scheduler=new DeterministicScheduler({initialState:model.initial,stateAdapter:adapter,handlers:new Map(STAGES.map(([n])=>[key(eventId(n)),handler])),initialQueue:input.events,initialAllocators:{nextRuntimeId:0n,nextEventId:BigInt(input.events.length),nextEventSequence:BigInt(input.events.length)},maxSettlementWorkPerSimulationInstant:17n,invariants:[state=>{if(expected.size)fail('unconsumed relationship children');model.validateState(state);}]});
 async function settle(instrumentation?:ConformanceInstrumentation){if(active)fail('relationship concurrent settlement');active=true;expected=new Map();try{return instrumentation?await scheduler.settleNextInstantForConformance(instrumentation):await scheduler.settleNextInstant();}finally{active=false;expected.clear();}}
 function view(observer:CanonicalValue){const i=OBSERVERS.findIndex(o=>key(o)===key(observer));if(i<0)throw Error('RELATIONSHIP_VIEW_OBSERVER');const outputs=scheduler.getOutputs(),own=(v:CanonicalValue,t:bigint,field:bigint)=>typeof v!=='boolean'&&v.kind==='record'&&v.schema.typeId===t&&key(f(v,field))===key(observer),observations=outputs.filter(v=>own(v,845n,2n)&&f(rec(v,845n),5n)===true),apps=outputs.filter(v=>own(v,853n,3n)),responses=outputs.filter(v=>own(v,856n,3n)),state=scheduler.getState(),person=state.read(personPath(i)).value;return enc(r(860,[observer,TARGETS[i],list(observations),list(apps),list(responses),state.read(historyPath(i)).value!,...(person?[person]:[])]));}
 return {settle:()=>settle(),settleForConformance:(i:ConformanceInstrumentation)=>settle(i),view,snapshot:()=>({state:scheduler.getState(),clock:scheduler.getClock(),status:scheduler.status,queue:scheduler.getPendingQueue(),allocators:scheduler.getAllocatorState(),trace:scheduler.getCommittedTrace(),outputs:scheduler.getOutputs()}),save:()=>createCanonicalSave({scheduler,stateAdapter:adapter,modelIdentity:model.modelIdentity,runIdentity:input.runIdentity,continuingRunInputs:list([])}),diagnostic:()=>scheduler.failureDiagnostic};
}

