import {list,map,unsigned as u,signed,type CanonicalValue} from '../substrate/canonicalEncoding';
import {ZERO,ONE,qValue,compileReasonNuclei,readDistribution,analyzeOptions,absolute,expectation} from '../campaign2/cognitiveMath';
import {RandomRunOracle,randomAddressValue,type RandomAddress} from '../substrate/random';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataIdentity as id,dataUnsigned as uint} from '../campaign2/canonicalData';
import {relationshipRecord as r} from './relationshipCodecs';
import {receivingRecord as old} from './receivingCodecs';
import {OPTIONS,TASKS,OBSERVERS,TARGETS,CHARACTERS,sid,type RelationshipSettings,type RelationshipCompiled} from './relationshipModel';
export function relationshipSummary(s:RelationshipSettings,journal:CanonicalValue){let count=0n,rupture=false;for(const row of items(f(rec(journal,847n),1n),'list')){const kind=uint(f(rec(row,846n),3n));if(kind===1n){count++;if(s.law===2)rupture=false;}else rupture=true;}return r(851,[u(count),rupture]);}
export function relationshipObserve(i:number,original:CanonicalValue,truth:CanonicalValue,occ:CanonicalValue){const o=rec(original,843n),t=rec(truth,844n),allowed=f(o,BigInt(i+4))===true,display=uint(f(o,6n)),claim=uint(f(o,7n)),participant=allowed&&(uint(f(t,4n))&BigInt(1<<i))!==0n;return r(845,[occ,OBSERVERS[i],TARGETS[i],f(o,1n),allowed,participant,allowed?(display===0n?f(t,3n):u(display)):u(0),...(allowed&&claim!==0n?[claim===1n]:[])]);}
export function appendRelationship(prior:CanonicalValue,observation:CanonicalValue){const o=rec(observation,845n),kind=uint(f(o,7n)),xs=items(f(rec(prior,847n),1n),'list');if(f(o,5n)!==true||f(o,6n)!==true||![1n,2n].includes(kind))return {next:prior,applied:false};if(xs.length>=12||xs.some(x=>key(f(rec(x,846n),1n))===key(f(o,1n))))throw Error('RELATIONSHIP_HISTORY_BOUND_OR_DUPLICATE');return {next:r(847,[list([...xs,r(846,[f(o,1n),f(o,4n),u(kind)])])]),applied:true};}
export function relationshipAppraisal(i:number,original:CanonicalValue,summary:CanonicalValue,person:CanonicalValue|undefined,occ:CanonicalValue,s:RelationshipSettings){const o=rec(original,843n),fold=rec(summary,851n),count=uint(f(fold,1n)),contact=f(o,BigInt(i+8))===true,rupture=f(fold,2n)===true||s.candidate===5&&uint(f(o,2n))===2n&&(uint(f(o,3n))&BigInt(1<<i))!==0n;return r(853,[occ,f(o,1n),OBSERVERS[i],TARGETS[i],contact,r(851,[u(count),rupture]),count>=2n&&!rupture,rupture,count>=2n&&!contact,...(person?[person]:[])]);}
export function relationshipRaw(i:number,app:CanonicalValue,occ:CanonicalValue){const a=rec(app,853n),signals:CanonicalValue[]=[],empty=old(400,[map([])]),signal=(option:number,role:number,strength:CanonicalValue)=>old(402,[old(401,[OPTIONS[i][option],TASKS[i][option],u(role)]),strength,empty]);signals.push(signal(1,1,qValue(ONE)));if(f(a,5n)===true){signals.push(signal(0,1,qValue(ONE)));const person=a.fields.get(10n);if(person)signals.push(signal(0,2,qValue(f(rec(person,849n),1n)===true?ONE:ZERO.subtract(ONE))));if(f(a,7n)===true||f(a,8n)===true)signals.push(signal(0,3,qValue(f(a,8n)===true?ZERO.subtract(ONE):ONE)));}return r(854,[occ,app,list(signals)]);}
export function relationshipReasons(model:RelationshipCompiled,raw:CanonicalValue,occ:CanonicalValue){return r(855,[occ,raw,list(compileReasonNuclei(items(f(rec(raw,854n),3n),'list'),f(model.content,6n)))]);}
export async function relationshipResponse(i:number,reasons:CanonicalValue,at:bigint,occ:CanonicalValue,seed:Uint8Array){const rs=rec(reasons,855n),a=rec(f(rec(f(rs,2n),854n),2n),853n),options=f(a,5n)===true?OPTIONS[i]:[OPTIONS[i][1]],nuclei=items(f(rs,3n),'list'),distributions=options.map(option=>{const n=nuclei.find(n=>key(f(rec(f(rec(n,407n),1n),404n),1n))===key(option)),distribution=n?readDistribution(f(rec(n,407n),7n)):new Map([[0n,ONE]]);return {key:option,distribution,reasonMass:absolute(expectation(distribution))};}),analysis=analyzeOptions(distributions,ONE,ONE),mode={Auto:1,QuietRoll:2,PlayerFacingRoll:3}[analysis.mode as 'Auto'|'QuietRoll'|'PlayerFacingRoll'],oracle=new RandomRunOracle(seed),draws:CanonicalValue[]=[],scores=new Map(options.map(o=>[key(o),0n]));let chosen=analysis.ranked[0].key;
 // Stable probe addresses are observer + authored instant, not sibling-dependent allocation IDs.
 const root=sid(1038,'content/relationship/probe/'+i+'/'+at),binding=(role:string,v:CanonicalValue)=>({subjectRoleId:sid(1043,'subject/relationship/'+role),subjectId:id(v)});
 async function draw(purpose:string,bindings:RandomAddress['subjectBindings'],span:bigint){const d=await oracle.drawBounded({causalRootId:id(root),purposeId:sid(1042,'purpose/relationship/'+purpose),subjectBindings:bindings,drawIndex:0n},span);draws.push(old(411,[randomAddressValue(d.localAddress),d.effectiveKey,u(d.result),u(d.span),u(d.limit),d.fallback,list(d.attempts.map(a=>old(410,[u(a.internalCandidateIndex),u(a.candidate),a.rejected])))]));return d.result;}
 if(mode!==1){for(const value of nuclei){const n=rec(value,407n),nk=rec(f(n,1n),404n),option=rec(f(nk,1n),395n),face=await draw('reason-face',[binding('actor',CHARACTERS[i]),binding('action',f(option,2n)),binding('ground',f(nk,3n))],uint(f(n,4n))),standing=f(n,5n),situation=f(n,6n);if(typeof standing==='boolean'||standing.kind!=='signed'||typeof situation==='boolean'||situation.kind!=='signed')throw Error('RELATIONSHIP_MODIFIER');scores.set(key(option),(uint(f(nk,4n))===1n?1n:-1n)*(face+1n+standing.value+situation.value));}const top=[...scores.values()].reduce((a,b)=>a>b?a:b),leaders=options.filter(o=>scores.get(key(o))===top).sort((a,b)=>key(a)<key(b)?-1:1);chosen=leaders[0];if(leaders.length>1)chosen=leaders[Number(await draw('tie',[binding('actor',CHARACTERS[i])],BigInt(leaders.length)))];}
 return r(856,[occ,signed(at),OBSERVERS[i],TARGETS[i],reasons,list(analysis.probabilities.map(p=>old(421,[p.key,qValue(p.probability)]))),u(mode),list(draws),chosen]);}

