/** relationship-public/0.2-candidate, retaining the failed 0.1 cohort for replay. */
import {canonicalEncode as enc,list,text,unsigned as u,rational as q,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {commitManifest,createModelIdentity,createRunIdentity} from '../substrate/identity';
import {AuthoritativeState,StateAuthorityRegistry,statePathPatternValue,type StatePath} from '../substrate/state';
import {compileMutationAuthorityRegistry} from '../substrate/mutationAuthority';
import {simInstant} from '../substrate/time';
import {RANDOM_ALGORITHM_VERSION} from '../substrate/random';
import type {ScheduledEvent} from '../substrate/scheduler';
import {semanticReferentFromAuthoredContent} from '../substrate/referentOrigin';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataUnsigned as uint} from '../campaign2/canonicalData';
import {receivingRecord as old} from './receivingCodecs';
import {socialRecord} from './socialCodecs';
import {copyData} from './beliefModel';
import {multisourceBase} from './multisourceModelRecipe';
import {decodeRelationship as decode,relationshipRecord as r} from './relationshipCodecs';
import {relationshipSummary} from './relationshipMath';
export {copyData};
export const RELATIONSHIP_VERSION='relationship-public/0.2-candidate',sid=(ns:number,name:string)=>typedIdentifier(ns,text(name));
const semantic=(name:string)=>semanticReferentFromAuthoredContent(sid(1038,'content/relationship/'+name));
export const OBSERVERS=['a','b'].map(n=>sid(1000,'observer/relationship/'+n)),CHARACTERS=['a','b'].map(semantic),TARGETS=['a/target','b/target'].map(semantic);
export const TASKS=CHARACTERS.map((c,i)=>['contact','activity'].map(n=>old(371,[c,semantic(i+'/'+n)]))),OPTIONS=CHARACTERS.map(c=>['contact','activity'].map(n=>old(395,[c,sid(1027,'action/relationship/'+n)])));
export const STAGES=[['appraise-a',40],['appraise-b',40],['raw-a',51],['raw-b',51],['reasons-a',52],['reasons-b',52],['response-a',60],['response-b',60],['source',110],['observe-a',120],['observe-b',120],['history-a',140],['history-b',140],['person-a',140],['person-b',140],['cache-a',140],['cache-b',140]] as const;
export const eventId=(n:string)=>sid(1001,'event/relationship/'+n),observerIndex=(n:string)=>n.endsWith('-a')?0:1;
export const historyPath=(i:number):StatePath=>({rootStateTypeId:848n,fieldId:1n,selectors:[{kind:'mapKey',key:socialRecord(808,[CHARACTERS[i],TARGETS[i]])}]}),personPath=(i:number):StatePath=>({...historyPath(i),rootStateTypeId:850n}),cachePath=(i:number):StatePath=>({...historyPath(i),rootStateTypeId:852n});
export const pattern=(p:StatePath)=>({...p,selectors:p.selectors.map(selector=>({kind:'exact' as const,selector}))});
export interface RelationshipSettings {candidate:number;law:number;reverse:boolean;revision?:number;}
export const DEFAULT_SETTINGS:RelationshipSettings={candidate:1,law:1,reverse:false,revision:2};
export function stageReads(n:string,s:RelationshipSettings){const i=observerIndex(n);return n.startsWith('appraise')?[personPath(i),...(s.candidate===2?[cachePath(i)]:s.candidate!==3?[historyPath(i)]:[])]:n.startsWith('history')?[historyPath(i),...(s.candidate===4?[historyPath(1-i)]:[])]:n.startsWith('person')?[personPath(i)]:n.startsWith('cache')&&s.candidate===2?[historyPath(i),cachePath(i)]:[];}
export function stageWrites(n:string,s:RelationshipSettings){const i=observerIndex(n);return n.startsWith('history')?[historyPath(i),...(s.candidate===4?[historyPath(1-i)]:[])]:n.startsWith('person')?[personPath(i)]:n.startsWith('cache')&&s.candidate===2?[cachePath(i)]:[];}
export const owner=(n:string)=>sid(1025,n.startsWith('history')?'authority/relationship-history':n.startsWith('cache')?'authority/relationship-summary':'authority/person-model');
const ownership=(s:RelationshipSettings)=>compileMutationAuthorityRegistry([['authority/relationship-history',historyPath,847n],['authority/person-model',personPath,849n],...(s.candidate===2?[['authority/relationship-summary',cachePath,851n]]:[])].map(([authorityName,path,type])=>({authorityName:authorityName as string,ownedLeaves:[0,1].map(i=>({pattern:pattern((path as typeof historyPath)(i)),valueGrammar:{kind:'canonical-record' as const,recordTypeId:type as bigint},removalAllowed:false}))})));
export function relationshipRecipe(settings:Partial<RelationshipSettings>={}){const s={...DEFAULT_SETTINGS,...settings};if(![1,2].includes(s.revision!)||![1,2,3,4,5].includes(s.candidate)||![1,2].includes(s.law)||typeof s.reverse!=='boolean')throw Error('RELATIONSHIP_PROFILE');const version=s.revision===1?'relationship-public/0.1-candidate':RELATIONSHIP_VERSION,baseDice=rec(multisourceBase().get('task-reason-dice'),437n),dice=s.revision===1?baseDice:old(437,[f(baseDice,1n),q(0,1),old(439,[q(1,4),u(3)]),old(439,[q(1,4),u(3)])]),parameters=r(842,[text(version),u(s.candidate),u(s.law),s.reverse]),content=r(861,[list(OBSERVERS),list(CHARACTERS),list(TARGETS),list(TASKS.flat()),list(OPTIONS.flat()),dice,q(0,1),q(0,1),q(1,1),list([0,1].flatMap(i=>Array.from({length:24},(_,t)=>sid(1038,'content/relationship/probe/'+i+'/'+(t+1)))))]),stages=STAGES.map(([n,phase])=>r(862,[eventId(n),u(phase),list(stageReads(n,s).map(p=>statePathPatternValue(pattern(p)))),list(stageWrites(n,s).map(p=>statePathPatternValue(pattern(p)))),owner(n)]));return {parameters:enc(parameters),content:enc(content),registry:enc(list([ownership(s).definitionValue,list(stages)]))};}
export type RelationshipSource=ReturnType<typeof relationshipRecipe>;
export async function compileRelationshipModel(input:RelationshipSource){const source=copyData(input,['parameters','content','registry']),profile=rec(decode(source.parameters),842n),versionValue=f(profile,1n),version=typeof versionValue!=='boolean'&&versionValue.kind==='text'?versionValue.value:'',settings={revision:version==='relationship-public/0.1-candidate'?1:version===RELATIONSHIP_VERSION?2:0,candidate:Number(uint(f(profile,2n))),law:Number(uint(f(profile,3n))),reverse:f(profile,4n)===true},recipe=relationshipRecipe(settings);for(const n of ['parameters','content','registry'] as const)if(key(decode(recipe[n]))!==key(decode(source[n])))throw Error('RELATIONSHIP_EXACT_MODEL');const own=ownership(settings),authority=new StateAuthorityRegistry(own.writableLeaves,own.authorities),content=rec(decode(source.content),861n),modelIdentity=await createModelIdentity({rulesVersion:version,contentSchemaVersion:version,contentManifest:await commitManifest(content),parameterSchemaVersion:version,parameterSet:await commitManifest(profile),numericProfileVersion:'relationship-exact/0.1-candidate',randomAlgorithmVersion:RANDOM_ALGORITHM_VERSION,registrySchemaVersion:version,registryManifest:await commitManifest(decode(source.registry))}),empty=r(847,[list([])]),initial=new AuthoritativeState([0,1].flatMap(i=>[{path:historyPath(i),value:empty},...(settings.candidate===2?[{path:cachePath(i),value:relationshipSummary(settings,empty)}]:[])]));
 function validateState(state:AuthoritativeState){decode(enc(state.canonicalValue()));const pk=(p:StatePath)=>key(statePathPatternValue(pattern(p))),allowed=new Set([0,1].flatMap(i=>[historyPath(i),personPath(i),...(settings.candidate===2?[cachePath(i)]:[])]).map(pk));for(const e of state.entries())if(!allowed.has(pk(e.path)))throw Error('RELATIONSHIP_STATE_PATH');for(const i of [0,1]){const journal=state.read(historyPath(i)).value;if(!journal)throw Error('RELATIONSHIP_JOURNAL_MISSING');let at=0n;const seen=new Set<string>();for(const v of items(f(rec(journal,847n),1n),'list')){const e=rec(v,846n),t=f(e,2n);if(typeof t==='boolean'||t.kind!=='signed'||t.value<=at||seen.has(key(f(e,1n))))throw Error('RELATIONSHIP_HISTORY_ORDER');at=t.value;seen.add(key(f(e,1n)));}if(settings.candidate===2&&key(state.read(cachePath(i)).value!)!==key(relationshipSummary(settings,journal)))throw Error('RELATIONSHIP_CACHE_FOLD');}}
 return {source,profile,settings,version,content,modelIdentity,authority,initial,validateState};}
export type RelationshipCompiled=Awaited<ReturnType<typeof compileRelationshipModel>>;
export async function compileRelationshipInputs(model:RelationshipCompiled,initialState:Uint8Array,orderedInputs:Uint8Array,runSeed:Uint8Array){if(key(decode(initialState))!==key(model.initial.canonicalValue()))throw Error('RELATIONSHIP_INITIAL_STATE');const originals=items(decode(orderedInputs),'list');if(originals.length>12)throw Error('RELATIONSHIP_INPUT_LIMIT');let previous=0n;const events:ScheduledEvent[]=[];for(const v of originals){const o=rec(v,843n),t=f(o,1n);if(typeof t==='boolean'||t.kind!=='signed'||t.value<=previous||t.value>24n)throw Error('RELATIONSHIP_INPUT_TIME');previous=t.value;for(const n of [...(model.settings.reverse?['appraise-b','appraise-a']:['appraise-a','appraise-b']),'source'])events.push({eventId:BigInt(events.length),eventSequence:BigInt(events.length),dueAt:simInstant(t.value),phase:n==='source'?110n:40n,eventTypeId:eventId(n),payload:v,dependencies:list([]),causalParentEventIds:[]});}const runIdentity=await createRunIdentity({modelIdentity:model.modelIdentity,initialState:await commitManifest(decode(initialState)),orderedInputSequence:await commitManifest(decode(orderedInputs)),runSeed});return {events,runIdentity,runSeed:runSeed.slice()};}


