/** social-public/0.1-candidate: transactional, observer-isolated fan-out. */
import {canonicalEncode as enc,list,unsigned as u,typedIdentifier,type CanonicalValue} from '../substrate/canonicalEncoding';
import {AuthoritativeState,applyStatePatch,restoreAuthoritativeState,type ActualReadRecord,type StatePatch,type StructuralMutationDiff,type StatePath} from '../substrate/state';
import {DeterministicScheduler,SchedulerContractError,type EventHandlerContext,type EventEmission,type ScheduledEvent,type ConformanceInstrumentation} from '../substrate/scheduler';
import {createCanonicalSave,scheduledEventValue} from '../substrate/persistence';
import {traceRecordValue} from '../substrate/trace';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key,dataIdentity as id,dataUnsigned as uint} from '../campaign2/canonicalData';
import {socialRecord as r,decodeSocial as decode} from './socialCodecs';
import {SOCIAL_VERSION,STAGES,OBSERVERS,CHARACTERS,TARGETS,TARGET,sid,eventId,observerIndex,personPath,taskPath,stageReads,stageWrites,owner,pattern,displayedClaim,type SocialCompiled,compileSocialInputs} from './socialModel';
import {socialProbe,socialObserve,socialEvidence,updateSocial} from './socialMath';
export function createSocialRuntime(model:SocialCompiled,input:Awaited<ReturnType<typeof compileSocialInputs>>){
 const originals=new Map(input.events.map(e=>[e.eventId,key(scheduledEventValue(e))]));let active=false,expected=new Map<bigint,string>();
 const fail=(message:string):never=>{throw new SchedulerContractError('INPUT_NOT_ADMITTED',message);};
 const adapter={clone:(s:AuthoritativeState)=>new AuthoritativeState(s.entries()),validate:model.validateState,canonicalValue:(s:AuthoritativeState)=>s.canonicalValue(),restore:restoreAuthoritativeState,analyticalAnchors:()=>list([]),randomRelevantAuthoritativeIds:()=>list([])};
 async function handler({event,state,allocateRuntimeId}:EventHandlerContext<AuthoritativeState>){
  if(!active)fail('inactive social transaction');const stage=STAGES.find(([n])=>key(event.eventTypeId)===key(eventId(n)));if(!stage)fail('unknown social stage');const [name,phase]=stage!;if(event.phase!==BigInt(phase))fail('social phase');
  const fingerprint=key(scheduledEventValue(event));if(name==='source'||name.startsWith('probe')){if(originals.get(event.eventId)!==fingerprint)fail('social original association');}else{if(expected.get(event.eventId)!==fingerprint)fail('social generated association');expected.delete(event.eventId);}
  const occurrence=()=>typedIdentifier(1154,u(allocateRuntimeId())),reads:ActualReadRecord[]=[],paths=stageReads(name,model.settings),domain=paths.map(pattern),i=observerIndex(name),pk=(p:StatePath)=>key(list([u(p.rootStateTypeId),u(p.fieldId),...p.selectors.map(s=>s.kind==='mapKey'?s.key:false)]));
  const read=(p:StatePath)=>{if(!paths.some(v=>pk(v)===pk(p)))return fail('social unregistered read');const prior=state.read(p);reads.push({accessorId:sid(1028,'accessor/social/'+name),path:p,presence:prior.presence,value:prior.value,derivedSources:[]});return prior.value;};
  const outputs:CanonicalValue[]=[],emittedEvents:EventEmission[]=[];let nextState=state,patch:StatePatch={operations:[]},diffs:readonly StructuralMutationDiff[]=[];
  const write=(changes:readonly {path:StatePath;prior:CanonicalValue|undefined;next:CanonicalValue}[])=>{if(changes.some(c=>!stageWrites(name,model.settings).some(p=>pk(p)===pk(c.path))))fail('social unregistered write');patch={operations:changes.map(c=>({kind:'set' as const,path:c.path,expected:c.prior?{presence:true as const,value:c.prior}:{presence:false as const},newValue:c.next}))};const result=applyStatePatch(state,patch,owner,model.authority);nextState=result.state;diffs=result.diffs;};
  const emit=(next:string,payload:CanonicalValue)=>emittedEvents.push({dueAt:event.dueAt,phase:BigInt(STAGES.find(([n])=>n===next)![1]),eventTypeId:eventId(next),payload,dependencies:list([])});
  let output:CanonicalValue;
  if(name.startsWith('probe')){const prior=read(personPath(i)),privateControl=model.settings.control===3?!!read(taskPath):undefined;output=socialProbe(i,event.dueAt,prior,occurrence(),privateControl);}
  else if(name==='source'){const committed=!!read(taskPath),original=rec(event.payload,804n),claim=displayedClaim(uint(f(original,3n)),committed);output=r(805,[occurrence(),f(original,1n),committed,f(original,7n),...(claim===undefined?[]:[claim])]);for(const n of model.settings.reverse?['b','a']:['a','b'])emit('observe-'+n,list([original,output]));}
  else if(name.startsWith('observe')){const pair=items(event.payload,'list');output=socialObserve(i,pair[0],pair[1],occurrence());emit(i===0?'evidence-a':'evidence-b',output);}
  else if(name.startsWith('evidence')){const observation=rec(event.payload,807n);if(key(f(observation,2n))!==key(OBSERVERS[i])||key(f(observation,3n))!==key(TARGETS[i]))fail('social foreign observation');output=socialEvidence(observation,occurrence());emit(i===0?'update-a':'update-b',output);}
  else {const evidence=rec(event.payload,812n),observation=rec(f(evidence,2n),807n);if(key(f(observation,2n))!==key(OBSERVERS[i])||key(f(observation,3n))!==key(TARGETS[i]))fail('social foreign evidence');const prior=read(personPath(i)),other=model.settings.control===2?read(personPath(1-i)):undefined,result=updateSocial(model.settings,prior,evidence),fields=new Map<bigint,CanonicalValue>([[1n,occurrence()],[2n,OBSERVERS[i]],[3n,evidence],[4n,result.applied]]);if(prior)fields.set(5n,prior);if(result.next)fields.set(6n,result.next);output=r(813,fields);if(result.applied)write([{path:personPath(i),prior,next:result.next!},...(model.settings.control===2?[{path:personPath(1-i),prior:other,next:result.next!}]:[])]);}
  decode(enc(output!));outputs.push(output!);
  return {nextState,outputs,emittedEvents,traceContributions:[],traceFactory:(children:readonly ScheduledEvent[])=>{
   if(children.length!==emittedEvents.length)fail('social child count');children.forEach((e,j)=>{if(e.causalParentEventIds.length!==1||e.causalParentEventIds[0]!==event.eventId||key(e.payload)!==key(emittedEvents[j].payload))fail('social child binding');expected.set(e.eventId,key(scheduledEventValue(e)));});
   const sourceRecordIds:ReturnType<typeof id>[]=[];if(name.startsWith('evidence')||name.startsWith('update'))sourceRecordIds.push(id(f(rec(event.payload,name.startsWith('evidence')?807n:812n),1n)));
   const trace=traceRecordValue({traceSchemaVersion:'trace/0.2-candidate',modelIdentity:model.modelIdentity.value,runIdentity:input.runIdentity.value,event,seamId:sid(1036,'seam/social/'+name),seamVersion:SOCIAL_VERSION,recordKind:event.eventTypeId,subjectIds:name==='source'?[TARGET]:[OBSERVERS[i],CHARACTERS[i]],sourceRecordIds,registeredReadDomain:domain,actualReadRecords:reads,inputProjection:event.payload,outputProjection:list(outputs),randomDrawRecords:[],quantizationOperations:[],statePatch:patch,structuralMutationDiffs:diffs,emittedEvents:children,invariantResults:[]});decode(enc(trace));return [trace];
  }};
 }
 const scheduler=new DeterministicScheduler<AuthoritativeState>({initialState:model.initial,stateAdapter:adapter,handlers:new Map(STAGES.map(([n])=>[key(eventId(n)),handler])),initialQueue:input.events,initialAllocators:{nextRuntimeId:0n,nextEventId:BigInt(input.events.length),nextEventSequence:BigInt(input.events.length)},maxSettlementWorkPerSimulationInstant:9n,invariants:[state=>{if(expected.size)fail('unconsumed social children');model.validateState(state);}]});
 async function settle(instrumentation?:ConformanceInstrumentation){if(active)fail('social concurrent settlement');active=true;expected=new Map();try{return instrumentation?await scheduler.settleNextInstantForConformance(instrumentation):await scheduler.settleNextInstant();}finally{active=false;expected.clear();}}
 function view(observer:CanonicalValue){const index=OBSERVERS.findIndex(o=>key(o)===key(observer));if(index<0)throw Error('SOCIAL_VIEW_OBSERVER');const outputs=scheduler.getOutputs(),own=(v:CanonicalValue,t:bigint,field:bigint)=>typeof v!=='boolean'&&v.kind==='record'&&v.schema.typeId===t&&key(f(v,field))===key(observer),observations=outputs.filter(v=>own(v,807n,2n)&&f(rec(v,807n),7n)===true),probes=outputs.filter(v=>own(v,811n,3n)),belief=scheduler.getState().read(personPath(index)).value;return enc(r(814,[observer,TARGETS[index],list(observations),list(probes),...(belief?[belief]:[])]));}
 return {settle:()=>settle(),settleForConformance:(i:ConformanceInstrumentation)=>settle(i),view,snapshot:()=>({state:scheduler.getState(),clock:scheduler.getClock(),status:scheduler.status,queue:scheduler.getPendingQueue(),allocators:scheduler.getAllocatorState(),trace:scheduler.getCommittedTrace(),outputs:scheduler.getOutputs()}),save:()=>createCanonicalSave({scheduler,stateAdapter:adapter,modelIdentity:model.modelIdentity,runIdentity:input.runIdentity,continuingRunInputs:list([])}),diagnostic:()=>scheduler.failureDiagnostic};
}
