import {canonicalEncode as enc,list,text,type CanonicalValue} from '../substrate/canonicalEncoding';
import {AuthoritativeState,applyStatePatch,restoreAuthoritativeState,statePathPatternValue,type ActualReadRecord,type StatePatch,type StructuralMutationDiff} from '../substrate/state';
import {DeterministicScheduler,SchedulerContractError,type EventHandlerContext,type EventEmission,type ScheduledEvent,type ConformanceInstrumentation} from '../substrate/scheduler';
import {createCanonicalSave,scheduledEventValue} from '../substrate/persistence';
import {traceRecordValue} from '../substrate/trace';
import {dataRecord as rec,dataField as f,dataItems as items,dataKey as key} from '../campaign2/canonicalData';
import {valuesPublicRecord as r} from './valuesPublicCodecs';
import {VERSION,actor,sid,eventId,path,pattern,owner,reads,writes,stages,historyOwner,historyValue,projectionValue,receiptData,type ValuesCompiled,compileValuesInputs} from './valuesPublicModel';
import {valuesNativeReasons,valuesNativeChoice} from './valuesPublicMath';
import {guardPublicWrapperSettlement} from './publicWrapperQuiescence';
export function createValuesPublicRuntime(model:ValuesCompiled,input:Awaited<ReturnType<typeof compileValuesInputs>>){
 let active=false,expected=new Map<bigint,string>(),pending:string[]=[],committed:string[]=[];
 const originals=new Map(input.events.map(e=>[e.eventId,key(scheduledEventValue(e))])),fail=(s:string):never=>{throw new SchedulerContractError('INPUT_NOT_ADMITTED',s);};
 const adapter={clone:(s:AuthoritativeState)=>new AuthoritativeState(s.entries()),validate:model.validateState,canonicalValue:(s:AuthoritativeState)=>s.canonicalValue(),restore:restoreAuthoritativeState,analyticalAnchors:()=>list([]),randomRelevantAuthoritativeIds:()=>list([])};
 async function handler({event,state,allocateRuntimeId}:EventHandlerContext<AuthoritativeState>){
  if(!active)fail('inactive Values transaction');const stage=stages.find(([n])=>key(eventId(n))===key(event.eventTypeId));if(!stage||event.phase!==BigInt(stage[1]))fail('Values phase');const name=stage![0],fingerprint=key(scheduledEventValue(event));
  if(name==='source'){if(originals.get(event.eventId)!==fingerprint)fail('Values original');}else{if(expected.get(event.eventId)!==fingerprint)fail('Values child');expected.delete(event.eventId);}
  allocateRuntimeId();const domain=reads(model.law,name),actualReadRecords:ActualReadRecord[]=[],outputs:CanonicalValue[]=[],emittedEvents:EventEmission[]=[];let nextState=state,patch:StatePatch={operations:[]},diffs:readonly StructuralMutationDiff[]=[];
  const read=(root:number)=>{if(!domain.some(p=>p.rootStateTypeId===BigInt(root)))fail('Values read');const p=path(root),v=state.read(p);actualReadRecords.push({accessorId:sid(1028,'accessor/values/'+name),path:p,presence:v.presence,value:v.value,derivedSources:[]});if(!v.presence)fail('Values missing state');return v.value!;};
  const emit=(n:string,payload:CanonicalValue)=>emittedEvents.push({dueAt:event.dueAt,phase:BigInt(stages.find(([s])=>s===n)![1]),eventTypeId:eventId(n),payload,dependencies:list([])});
  if(name==='source'){const x=rec(event.payload,1512n);emit('reasons',f(x,3n));emit('consolidate',f(x,2n));}
  else if(name==='reasons'){const h=read(1516),o=historyOwner(model.law,h),view=model.law==='Refold'?projectionValue(o.view(Number(event.dueAt))):read(1517),probes=items(event.payload,'list');const result=probes.length?valuesNativeReasons(probes[0],view):undefined;if(result)outputs.push(result);emit('choice',list(result?[result]:[]));}
  else if(name==='choice'){const operands=items(event.payload,'list');if(operands.length){const result=await valuesNativeChoice(operands[0]);outputs.push(result.output);pending.push(...result.addresses);}}
  else {const h=read(1516),o=historyOwner(model.law,h),before=model.law==='Refold'?projectionValue(o.view(65)):read(1517),rs=items(event.payload,'list');if(rs.length)o.admit(receiptData(rs[0]));const after=projectionValue(o.view(65)),values=[historyValue(o),after];
   patch={operations:writes(model.law,name).map((p,i)=>{const prior=state.read(p);return {kind:'set' as const,path:p,expected:{presence:true as const,value:prior.value!},newValue:values[i]};})};const applied=applyStatePatch(state,patch,owner,model.authority);nextState=applied.state;diffs=applied.diffs;outputs.push(r(1518,[before,after]));}
  return {nextState,outputs,emittedEvents,traceContributions:[],traceFactory:(children:readonly ScheduledEvent[])=>{if(children.length!==emittedEvents.length)fail('Values child count');children.forEach((e,i)=>{if(e.causalParentEventIds.length!==1||e.causalParentEventIds[0]!==event.eventId||key(e.payload)!==key(emittedEvents[i].payload))fail('Values parent');expected.set(e.eventId,key(scheduledEventValue(e)));});return [traceRecordValue({traceSchemaVersion:'trace/0.2-candidate',modelIdentity:model.modelIdentity.value,runIdentity:input.runIdentity.value,event,seamId:sid(1036,'seam/values/'+name),seamVersion:VERSION,recordKind:event.eventTypeId,subjectIds:[actor],sourceRecordIds:[],registeredReadDomain:domain.map(pattern),actualReadRecords,inputProjection:event.payload,outputProjection:list(outputs),randomDrawRecords:[],quantizationOperations:[],statePatch:patch,structuralMutationDiffs:diffs,emittedEvents:children,invariantResults:[]})];}};
 }
 const scheduler=new DeterministicScheduler({initialState:input.state,stateAdapter:adapter,handlers:new Map(stages.map(([n])=>[key(eventId(n)),handler])),initialQueue:input.events,initialAllocators:{nextRuntimeId:0n,nextEventId:BigInt(input.events.length),nextEventSequence:BigInt(input.events.length)},maxSettlementWorkPerSimulationInstant:16n,invariants:[state=>{if(expected.size)fail('Values pending');model.validateState(state);}]});
 async function settle(instrumentation?:ConformanceInstrumentation){if(active)fail('Values concurrent');if(!scheduler.getPendingQueue().length)return undefined;active=true;expected=new Map();pending=[];try{const result=instrumentation?await scheduler.settleNextInstantForConformance(instrumentation):await scheduler.settleNextInstant();if(result)committed.push(...pending);return result;}finally{active=false;expected.clear();pending=[];}}
 return guardPublicWrapperSettlement({settle:()=>settle(),settleForConformance:(i:ConformanceInstrumentation)=>settle(i),snapshot:()=>({state:scheduler.getState(),clock:scheduler.getClock(),status:scheduler.status,queue:scheduler.getPendingQueue(),allocators:scheduler.getAllocatorState(),trace:scheduler.getCommittedTrace(),outputs:scheduler.getOutputs(),randomAddresses:committed.slice()}),save:()=>createCanonicalSave({scheduler,stateAdapter:adapter,modelIdentity:model.modelIdentity,runIdentity:input.runIdentity,continuingRunInputs:list(committed.map(text))}),diagnostic:()=>scheduler.failureDiagnostic});
}
