import {it,expect} from 'vitest';
import {createSubstitutionRun,restoreSubstitutionRun,LAWS,type Law} from '../campaign3/dependenceSubstitutes';
import {substitutionCases} from './substitutionFixtures';
const cases=substitutionCases();
async function run(name:keyof typeof cases='diversified',law:Law='LatestHistory'){const r=createSubstitutionRun(law,cases[name]);while(await r.step()){}return r;}
it('same total successful practice yields dependence on one known satisfier or actual substitution',async()=>{
 const a=(await run('concentrated')).snapshot(),b=(await run()).snapshot();
 expect(a.world[3].physical.reduce((n,v)=>n+v)).toBe(4);expect(b.world[3].physical.reduce((n,v)=>n+v)).toBe(4);
 expect(a.rows.slice(5).map(r=>r.intent)).toEqual([2,2,2]);expect(b.rows.slice(5).map(r=>r.intent)).toEqual([1,1,1]);
 expect(a.unserved).toBe(3);expect(b.unserved).toBe(0);expect(b.physical).toEqual([2,5]);
});
it('expectation-only explains primary substitution without proving habit necessary',async()=>{expect((await run('diversified','ExpectationOnly')).snapshot().rows.map(r=>r.intent)).toEqual((await run()).snapshot().rows.map(r=>r.intent));});
it('retains equal corrected expectations with different acquired repertoires',async()=>{
 const a=(await run('correctedConcentrated')).snapshot().rows[5],b=(await run('correctedDiversified')).snapshot().rows[5],n=(await run('correctedDiversified','ExpectationOnly')).snapshot().rows[5];
 expect(a.beliefBefore).toEqual(['0/1','0/1']);expect(b.beliefBefore).toEqual(a.beliefBefore);expect(a.admitted).toEqual([true,false]);expect(b.admitted).toEqual([true,true]);expect(n.admitted).toEqual([false,false]);expect(a.resolution).not.toBe(b.resolution);
});
it('informationally learned substitute differs from history-only gate',async()=>{expect((await run('knownAlternative')).snapshot().rows[5].intent).toBe(1);expect((await run('knownAlternative','HistoryOnly')).snapshot().rows[5].intent).toBe(2);});
it('unknown and observed failure stay different despite identical idle behavior',async()=>{const a=(await run('concentrated')).snapshot().rows[5],b=(await run('knownFailure')).snapshot().rows[5];expect(a.beliefBefore[1]).toBe(null);expect(b.beliefBefore[1]).toBe('0/1');expect(a.intent).toBe(b.intent);});
it('availability, demand and cue do not silently delete acquired history',async()=>{for(const name of ['unavailable','noDemand','otherCue'] as const){const s=(await run(name)).snapshot();expect(s.rows.slice(5).every(r=>r.intent===2)).toBe(true);expect(s.journal).toHaveLength(4);}expect((await run('restoredA')).snapshot().rows[7].intent).toBe(0);});
it('accumulation and latest report retain different contradiction responses',async()=>{const a=(await run('correctedConcentrated')).snapshot().rows[5],b=(await run('correctedConcentrated','MeanHistory')).snapshot().rows[5];expect(a.beliefBefore[0]).toBe('0/1');expect(b.beliefBefore[0]).toBe('4/5');expect(a.values).not.toEqual(b.values);});
it('actual unseen practice and available evidence without learning do not manufacture knowledge',async()=>{for(const r of [await run('unseenTraining'),await run('diversified','NoLearning')]){const s=r.snapshot();expect(s.journal).toHaveLength(0);expect(s.rows[5].beliefBefore).toEqual([null,null]);expect(s.world[3].physical.reduce((n,v)=>n+v)).toBe(4);}});
it('failed delivery preserves prior expression and later admitted failure can revise expectation',async()=>{const a=(await run()).snapshot(),b=(await run('failure')).snapshot();expect(a.rows[5].expression).toBe(b.rows[5].expression);expect(b.rows[5].receipt).toBe(false);expect(b.rows[6].beliefBefore[1]).toBe('0/1');expect(b.rows[6].admitted[1]).toBe(false);});
it('whole later safe views ignore hidden outcomes and denied information',async()=>{for(const [a,b] of [['diversified','falseTraining'],['deniedFeedback','hiddenBlocked'],['falseSuccess','trueSuccess'],['deniedInfo','absentInfo']] as const)expect((await run(a)).observerView()).toEqual((await run(b)).observerView());});
it('actual balanced two-satisfier contest uses inherited addressed draws',async()=>{expect((await run('bothAvailable')).snapshot().addresses.length).toBeGreaterThan(0);});
for(const fault of ['after-decision','before-commit'] as const)it('rolls back '+fault+' and retries exactly',async()=>{const a=createSubstitutionRun('LatestHistory',cases.bothAvailable),b=createSubstitutionRun('LatestHistory',cases.bothAvailable);for(let i=0;i<5;i++){await a.step();await b.step();}const saved=a.save();await expect(a.step(fault)).rejects.toThrow('INJECTED');expect(a.save()).toEqual(saved);await a.step();await b.step();expect(a.save()).toEqual(b.save());});
it('every candidate restores each prefix and continues exactly',async()=>{for(const law of LAWS){const r=createSubstitutionRun(law,cases.bothAvailable),saves=[r.save()];while(await r.step())saves.push(r.save());for(let i=0;i<9;i++){const restored=await restoreSubstitutionRun(law,cases.bothAvailable,saves[i]);expect(restored.save()).toEqual(saves[i]);expect(await restored.step()).toBe(i<8);expect(restored.save()).toEqual(saves[Math.min(i+1,8)]);}}},30000);
it('rejects malformed data, changed originals, wrong seed and edited saves',async()=>{expect(()=>createSubstitutionRun('LatestHistory',cases.diversified.slice(1))).toThrow();const getter=structuredClone(cases.diversified);Object.defineProperty(getter[0],'mode',{get(){throw Error('getter invoked');}});expect(()=>createSubstitutionRun('LatestHistory',getter)).toThrow('DATA');const bad=structuredClone(cases.diversified);bad[0].infoA=1;expect(()=>createSubstitutionRun('LatestHistory',bad)).toThrow('INFO_MODE');const r=await run();await expect(restoreSubstitutionRun('LatestHistory',cases.concentrated,r.save())).rejects.toThrow();await expect(restoreSubstitutionRun('LatestHistory',cases.diversified,r.save(),8)).rejects.toThrow();const edited=r.save();edited[edited.length-1]^=1;await expect(restoreSubstitutionRun('LatestHistory',cases.diversified,edited)).rejects.toThrow();});
